### ISSUE TITLE
4.x Upgrade Error

### ISSUE THREAD

**Issue by kunz07** [crate/crate#10004]
**CrateDB version**:
4.1.4

**Environment description**:
- JVM version: java -version 
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

- Kernel: uname -a
Linux chiphub 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Distribution: cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 - Number of nodes; Please mention special master/data/client node configuration
Single node configuration

**Problem description**:
Hi,
    Recently I upgraded my crate version from **3.3.4** to **4.1.4** using the following procedure
1. COPY `tables` TO DIRECTORY `dir`
2. Delete all existing tables
3. Upgraded crate using `sudo apt install crate`
4. Recreate tables
5. Restored data using COPY `tables` from `dir`

The upgrade went smoothly without any hassles
But since then, I have this error at regular intervals -

```
May 26 21:28:01 chiphub crate[1442]: [2020-05-26T21:28:01,977][ERROR][i.c.s.TableStatsService  ] [Tête de l'Hivernet] Error running periodic ANALYZE
May 26 21:28:01 chiphub crate[1442]: java.util.concurrent.CompletionException: RemoteTransportException[[Tête de l'Hivernet][127.0.0.1:4300][internal:crate:sql/analyze/fetch_sampl
May 26 21:28:01 chiphub crate[1442]:         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
May 26 21:28:01 chiphub crate[1442]:         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
May 26 21:28:01 chiphub crate[1442]:         at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
May 26 21:28:01 chiphub crate[1442]:         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
May 26 21:28:01 chiphub crate[1442]:         at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
May 26 21:28:01 chiphub crate[1442]:         at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:53) ~[crate-app.jar:4.1.4]
May 26 21:28:01 chiphub crate[1442]:         at io.crate.execution.support.MultiActionListener.countdown(MultiActionListener.java:86) ~[crate-app.jar:4.1.4]
May 26 21:28:01 chiphub crate[1442]:         at io.crate.execution.support.MultiActionListener.onFailure(MultiActionListener.java:77) ~[crate-app.jar:4.1.4]
May 26 21:28:01 chiphub crate[1442]:         at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:62) ~[crate-app.jar:4.1.4
May 26 21:28:01 chiphub crate[1442]:         at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1085) ~[crate-app.
May 26 21:28:01 chiphub crate[1442]:         at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1202) ~[crate-app.jar:4.1
May 26 21:28:01 chiphub crate[1442]:         at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1176) ~[crate-app.jar:4.1.4]
May 26 21:28:01 chiphub crate[1442]:         at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:673) [crate-app.jar:4.1.4]
May 26 21:28:01 chiphub crate[1442]:         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:679) [crate-a
May 26 21:28:02 chiphub crate[1442]:         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
May 26 21:28:02 chiphub crate[1442]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
May 26 21:28:02 chiphub crate[1442]:         at java.lang.Thread.run(Thread.java:834) [?:?]
May 26 21:28:02 chiphub crate[1442]: Caused by: org.elasticsearch.transport.RemoteTransportException: [Tête de l'Hivernet][127.0.0.1:4300][internal:crate:sql/analyze/fetch_samples
May 26 21:28:02 chiphub crate[1442]: Caused by: io.crate.exceptions.GroupByOnArrayUnsupportedException: Column "conf.conf.threshold.category" has a value that is an array. Group b
May 26 21:28:02 chiphub crate[1442]:         at io.crate.expression.reference.doc.lucene.BytesRefColumnReference.setNextDocId(BytesRefColumnReference.java:56) ~[crate-app.jar:4.1.
May 26 21:28:02 chiphub crate[1442]:         at io.crate.statistics.ReservoirSampler$DocIdToRow.apply(ReservoirSampler.java:241) ~[crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at io.crate.statistics.ReservoirSampler.lambda$getSamples$0(ReservoirSampler.java:208) ~[crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at io.crate.common.collections.Lists2.map(Lists2.java:94) ~[crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at io.crate.statistics.ReservoirSampler.getSamples(ReservoirSampler.java:205) ~[crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at io.crate.statistics.ReservoirSampler.getSamples(ReservoirSampler.java:118) ~[crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at io.crate.statistics.TransportAnalyzeAction.lambda$new$1(TransportAnalyzeAction.java:112) ~[crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at io.crate.execution.support.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:48) [crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) ~[crate-app.jar:4.1.4]
May 26 21:28:02 chiphub crate[1442]:         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.
May 26 21:28:02 chiphub crate[1442]:         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.1.4]
```
The crate service itself seems unaffected and is running fine.
Any help in rectifying this error would be much appreciated.
Thanks in advance :)

Regards,
Kunal

**Comment by mfussenegger** [comment]
Thank you for the detailed report.

CrateDB is refreshing statistics about the tables in the cluster periodically. Based on the log entries, the error is caused by this operation. It tries to read `conf.conf.threshold.category` because it expects it to have only a single value, but it appears to have multiple values - so it is either an array or maybe an analyzed column?

Could you post the schema of the table with that column?

**Comment by kunz07** [comment]
Hi, thanks for the quick response!

Here is schema of the offending table

```
CREATE TABLE IF NOT EXISTS "doc"."ntfc_data" (
    "conf" OBJECT(DYNAMIC) AS (
        "channel" ARRAY(TEXT),
        "m_id" ARRAY(TEXT),
        "name" TEXT,
        "ntfc" TEXT,
        "status" TEXT,
        "conf" OBJECT(DYNAMIC) AS (
            "freq" TEXT,
            "notify_prod_start" BOOLEAN,
            "threshold" ARRAY(OBJECT(DYNAMIC) AS (
                "category" TEXT,
                "dur-unit" TEXT,
                "metric" TEXT,
                "operator" TEXT,
                "value" TEXT
                )),
            "user_ids" ARRAY(TEXT)
            )
        ),
    "created_ts" TIMESTAMP WITH TIME ZONE,
    "m_id" ARRAY(TEXT),
    "n_id" INTEGER,
    "n_name" TEXT,
    "n_type" TEXT,
    "status" TEXT,
    "update_by" TEXT,
    "update_ts" TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY ("n_id")
);
```

The `threshold` column consists of data points as such:
    

> 1. [{"category": "all", "dur-unit": "minutes", "metric": "number", "operator": ">", "value": "2"}]
>
> 2. [{"category": "all", "dur-unit": "minutes", "metric": "%", "operator": ">", "value": "0"}, {"category": "all", "dur-unit": "minutes", "metric": "number", "operator": ">", "value": "10"}, {"category": "black_dots", "dur-unit": "minutes", "metric": "%", "operator": ">", "value": "5"}]

In case the data in the table is a single element array as in 1, then the `ANALYZE` does not throw an error, but in case of 2 it throws an error

I have disabled the periodic refresh temporarily as suggested using `set global stats.service.interval = 0;`
