### ISSUE TITLE
Analyze statement failed on table with array[int] columns

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10045]
**CrateDB version**: 4.1.5 

**Problem description**:
`ANALYZE` statement fails with error `ERROR: NotSerializableExceptionWrapper: group_by_on_array_unsupported_exception: Column "working_hours.work_from" has a value that is an array. Group by doesn't work on Arrays`

In server logs:
```
[2020-06-04T13:14:44,038][ERROR][i.c.s.TableStatsService  ] [crate00] Error running periodic ANALYZE
java.util.concurrent.CompletionException: RemoteTransportException[[crate00][10.12.43.42:4300][internal:crate:sql/analyze/fetch_samples]]; nested: GroupByOnArrayUnsupportedException[Column "working_hours.work_from" has a value that is an array
. Group by doesn't work on Arrays];
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
        at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:53) ~[crate-app.jar:4.1.5]
        at io.crate.execution.support.MultiActionListener.countdown(MultiActionListener.java:86) ~[crate-app.jar:4.1.5]
        at io.crate.execution.support.MultiActionListener.onFailure(MultiActionListener.java:77) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:62) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1085) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1202) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1176) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:673) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:679) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[crate-app.jar:4.1.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [crate00][10.12.43.42:4300][internal:crate:sql/analyze/fetch_samples]
Caused by: io.crate.exceptions.GroupByOnArrayUnsupportedException: Column "working_hours.work_from" has a value that is an array. Group by doesn't work on Arrays
        at io.crate.expression.reference.doc.lucene.IntegerColumnReference.setNextDocId(IntegerColumnReference.java:56) ~[crate-app.jar:4.1.5]
        at io.crate.statistics.ReservoirSampler$DocIdToRow.apply(ReservoirSampler.java:241) ~[crate-app.jar:4.1.5]
        at io.crate.statistics.ReservoirSampler.lambda$getSamples$0(ReservoirSampler.java:208) ~[crate-app.jar:4.1.5]
        at io.crate.common.collections.Lists2.map(Lists2.java:94) ~[crate-app.jar:4.1.5]
        at io.crate.statistics.ReservoirSampler.getSamples(ReservoirSampler.java:205) ~[crate-app.jar:4.1.5]
        at io.crate.statistics.ReservoirSampler.getSamples(ReservoirSampler.java:118) ~[crate-app.jar:4.1.5]
        at io.crate.statistics.TransportAnalyzeAction.lambda$new$1(TransportAnalyzeAction.java:113) ~[crate-app.jar:4.1.5]
        at io.crate.execution.support.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:48) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.jar:4.1.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.1.5]
        ... 3 more
```

**Steps to reproduce**:

1. Create table:
```
CREATE TABLE IF NOT EXISTS "test" (
   "device_id" TEXT,
   "is_manual" BOOLEAN,
   "working_hours" ARRAY(OBJECT(DYNAMIC) AS (
      "work_from" INTEGER,
      "work_till" INTEGER
   )),
   "merged" TIMESTAMP WITH TIME ZONE,
   "id_page" TEXT,
   PRIMARY KEY ("device_id", "is_manual")
)

>> Table "test" created.
```

2. Insert one row:
```
insert into test (device_id, is_manual, working_hours, merged, id_page) values ('test', true, [ { work_from = 1, work_till = 2 }, { work_from = 3, work_till = 4 } ], current_timestamp, 'test');

>> 1 row inserted.
```

3. Execute Analize statement:
```
analyze;

>> ERROR: GroupByOnArrayUnsupportedException: Column "working_hours.work_from" has a value that is an array. Group by doesn't work on Arrays
```

**Comment by mfussenegger** [comment]
Thank you for the report.  

This will be fixed with the next hotfix release,  see https://github.com/crate/crate/issues/10004 and https://github.com/crate/crate/pull/10006

**Comment by mfussenegger** [comment]
We've a 4.1.6 release out in the testing channels which contains the fix.
