### ISSUE TITLE
crate-node tool throws exception

### ISSUE THREAD

**Issue by marregui** [crate/crate#10166]
*Problem*

When executing the following command on a stopped node, to detach it from its cluster:

```
crate-node detach-cluster -Cpath.conf="config" -Cpath.home="." -Cpath.data="data"
```

(for valid specifications of the values for `path.conf`, 'path.home', 'path.data') 

we get a bonus exception, despite the command succeeding:

```
Do you want to proceed?
Confirm [y/N] y
Node was successfully detached from the cluster
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/elasticsearch/core/internal/io/IOUtils
	at org.elasticsearch.cli.MultiCommand.close(MultiCommand.java:82)
	at org.elasticsearch.cli.Command.lambda$main$0(Command.java:70)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.core.internal.io.IOUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more
```

**Comment by marregui** [comment]
Fix https://github.com/crate/crate/pull/10167
