### ISSUE TITLE
ALTER TABLE ADD COLUMN fails: Mapper for [num] conflicts with existing mapping in other types

### ISSUE THREAD

**Issue by chaudum** [crate/crate#10215]
**CrateDB version**:

4.1.8

```
cr> select version from sys.nodes;                                                                                                                                                                                  
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| version                                                                                                                                                                                               |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {"build_hash": "5aa831f029f84a516aa273dd786cd02a4f2a5a96", "build_snapshot": false, "minimum_index_compatibility_version": "3.0.1", "minimum_wire_compatibility_version": "4.0.0", "number": "4.1.8"} |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Environment description**:

Any (tar.gz on Linux, CrateDB Cloud / Docker)

**Problem description**:

After inserting a data into a table I expect to be able to add a column using `ALTER TABLE ADD COLUM`.

**Steps to reproduce**:

```
cr> CREATE TABLE IF NOT EXISTS "test" ("num" BIGINT INDEX OFF, "week" TIMESTAMP, PRIMARY KEY ("num", "week"));                                                                                                      
CREATE OK, 1 row affected  (0.211 sec)

cr> INSERT INTO "test" ("num", "week") VALUES (1, date_trunc('week', CURRENT_TIMESTAMP));                                                                                                                           
INSERT OK, 1 row affected  (0.025 sec)

cr> ALTER TABLE test ADD COLUMN browser text;                                                                                                                                                                       
SQLActionException[SQLParseException: Mapper for [num] conflicts with existing mapping in other types:
[mapper [num] has different [index] values, mapper [num] has different [analyzer]]]

SQLActionException: 400 Bad Request 4000 SQLParseException: Mapper for [num] conflicts with existing mapping in other types:
[mapper [num] has different [index] values, mapper [num] has different [analyzer]]
	at org.elasticsearch.index.mapper.FieldTypeLookup.validateField(FieldTypeLookup.java:160)
	at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:108)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:371)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:304)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:267)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:295)
	at io.crate.metadata.cluster.AlterTableClusterStateExecutor.updateMapping(AlterTableClusterStateExecutor.java:167)
	at io.crate.metadata.cluster.AlterTableClusterStateExecutor.execute(AlterTableClusterStateExecutor.java:139)
	at io.crate.metadata.cluster.AlterTableClusterStateExecutor.execute(AlterTableClusterStateExecutor.java:73)
	at io.crate.metadata.cluster.DDLClusterStateTaskExecutor.execute(DDLClusterStateTaskExecutor.java:38)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:309)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:209)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:141)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by mfussenegger** [comment]
Will be fixed with 4.2.2 (https://github.com/crate/crate/pull/10221)
