### ISSUE TITLE
Data nodes are getting removed and added frequently to the cluster

### ISSUE THREAD

**Issue by rmadulla** [crate/crate#10238]
**CrateDB version**: crate-4.1.5

**Environment description**:

 - JVM version: java -version 
 $ 130 03:23:54 [usprod] abdul@shadowcrate2data-0818d7d60d365ae8c:~$ /usr/java/11/bin/java --version
openjdk 11.0.6 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)
 - Kernel: uname -a
 $ 0 03:24:13 [usprod] abdul@shadowcrate2data-0818d7d60d365ae8c:~$ uname -a
Linux shadowcrate2data-0818d7d60d365ae8c 4.4.0-1099-aws #110-Ubuntu SMP Fri Nov 15 00:08:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Distribution: cat /etc/os-release
 $ 1 03:25:08 [usprod] abdul@shadowcrate2data-0818d7d60d365ae8c:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
 - Number of nodes; Please mention special master/data/client node configuration
 Master : 3
 Client: 18
 Data nodes: 50

**Problem description**:

1. Frequently the data nodes are getting removed and added from the cluster. 
$ 1 02:07:19 [usprod] abdul@shadowcrate2master-0d3a02bfac2dbf5e7:/shn/apps/crate/current/logs$ cat crate-usprod.log |grep -E 'added|removed'
[2020-07-17T00:30:55,925][INFO ][o.e.c.s.MasterService    ] [shadowcrate2master-0d3a02bfac2dbf5e7] node-left[{shadowcrate2data-0cffaa2ba520e9894}{68eW2m9NQUinYNTPn5Lj5A}{i71avsiRSp2T1YVGMF_GJg}{10.5.52.193}{10.5.52.193:4300}{zone=us-west-2b, http_address=127.0.0.1:4200} followers check retry count exceeded], term: 6, version: 311575, reason: removed {{shadowcrate2data-0cffaa2ba520e9894}{68eW2m9NQUinYNTPn5Lj5A}{i71avsiRSp2T1YVGMF_GJg}{10.5.52.193}{10.5.52.193:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}
[2020-07-17T00:30:56,272][INFO ][o.e.c.s.ClusterApplierService] [shadowcrate2master-0d3a02bfac2dbf5e7] removed {{shadowcrate2data-0cffaa2ba520e9894}{68eW2m9NQUinYNTPn5Lj5A}{i71avsiRSp2T1YVGMF_GJg}{10.5.52.193}{10.5.52.193:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}, term: 6, version: 311575, reason: Publication{term=6, version=311575}
[2020-07-17T00:31:02,623][INFO ][o.e.c.s.MasterService    ] [shadowcrate2master-0d3a02bfac2dbf5e7] node-join[{shadowcrate2data-0cffaa2ba520e9894}{68eW2m9NQUinYNTPn5Lj5A}{i71avsiRSp2T1YVGMF_GJg}{10.5.52.193}{10.5.52.193:4300}{zone=us-west-2b, http_address=127.0.0.1:4200} join existing leader], term: 6, version: 311577, reason: added {{shadowcrate2data-0cffaa2ba520e9894}{68eW2m9NQUinYNTPn5Lj5A}{i71avsiRSp2T1YVGMF_GJg}{10.5.52.193}{10.5.52.193:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}
[2020-07-17T00:31:05,707][INFO ][o.e.c.s.ClusterApplierService] [shadowcrate2master-0d3a02bfac2dbf5e7] added {{shadowcrate2data-0cffaa2ba520e9894}{68eW2m9NQUinYNTPn5Lj5A}{i71avsiRSp2T1YVGMF_GJg}{10.5.52.193}{10.5.52.193:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}, term: 6, version: 311577, reason: Publication{term=6, version=311577}
[2020-07-17T01:10:31,497][INFO ][o.e.c.s.MasterService    ] [shadowcrate2master-0d3a02bfac2dbf5e7] node-left[{shadowcrate2data-08836d2f1d72cb029}{qCMaxWcYQpGd_LmAOnlM0Q}{m98jwjA3QV61Da-Q2_apYQ}{10.5.52.163}{10.5.52.163:4300}{zone=us-west-2b, http_address=127.0.0.1:4200} followers check retry count exceeded], term: 6, version: 311746, reason: removed {{shadowcrate2data-08836d2f1d72cb029}{qCMaxWcYQpGd_LmAOnlM0Q}{m98jwjA3QV61Da-Q2_apYQ}{10.5.52.163}{10.5.52.163:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}
[2020-07-17T01:10:32,137][INFO ][o.e.c.s.ClusterApplierService] [shadowcrate2master-0d3a02bfac2dbf5e7] removed {{shadowcrate2data-08836d2f1d72cb029}{qCMaxWcYQpGd_LmAOnlM0Q}{m98jwjA3QV61Da-Q2_apYQ}{10.5.52.163}{10.5.52.163:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}, term: 6, version: 311746, reason: Publication{term=6, version=311746}
[2020-07-17T01:10:45,534][INFO ][o.e.c.s.MasterService    ] [shadowcrate2master-0d3a02bfac2dbf5e7] node-join[{shadowcrate2data-08836d2f1d72cb029}{qCMaxWcYQpGd_LmAOnlM0Q}{m98jwjA3QV61Da-Q2_apYQ}{10.5.52.163}{10.5.52.163:4300}{zone=us-west-2b, http_address=127.0.0.1:4200} join existing leader], term: 6, version: 311749, reason: added {{shadowcrate2data-08836d2f1d72cb029}{qCMaxWcYQpGd_LmAOnlM0Q}{m98jwjA3QV61Da-Q2_apYQ}{10.5.52.163}{10.5.52.163:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}
[2020-07-17T01:10:48,665][INFO ][o.e.c.s.ClusterApplierService] [shadowcrate2master-0d3a02bfac2dbf5e7] added {{shadowcrate2data-08836d2f1d72cb029}{qCMaxWcYQpGd_LmAOnlM0Q}{m98jwjA3QV61Da-Q2_apYQ}{10.5.52.163}{10.5.52.163:4300}{zone=us-west-2b, http_address=127.0.0.1:4200},}, term: 6, version: 311749, reason: Publication{term=6, version=311749}
2. some of the shards are getting stuck in UNASSIGNED state with the Error "Max retry attempt reached"
   We had to bounce the node from explanation and retry the reroute to bring it back GREEN.

**Comment by bputt** [comment]
we've seen this issue too (crate 4.13) and it does happen more frequently when the nodes are under load....also, the only way for us to resolve the unassigned shard issue was to add the 'REROUTE RETRY FAILED' as a solution in our nagios checks :/

we're using a similar version of openjdk and are using centos 7.latest

**Comment by mfussenegger** [comment]
Do you see any other warnings in the logs, like increased GC activity?

If this got worse in 4.1 compared to 4.0, it may also be related to https://github.com/crate/crate/issues/10240

**Comment by skaliappan** [comment]
Below logs are found on multiple nodes ,

`   [2020-07-17T04:53:33,235][ERROR][i.c.m.s.T.HealthResultReceiver] [shadowcrate2data-0f66fee94797014a2] error retrieving tables health
    io.crate.exceptions.JobKilledException: Job killed. Participating node=shadowcrate2data-0818d7d60d365ae8c disconnected.
    	at io.crate.exceptions.JobKilledException.of(JobKilledException.java:31) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.RootTask.kill(RootTask.java:240) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.TasksService.killTasks(TasksService.java:189) ~[crate-app.jar:4.1.5]
    --
    [2020-07-17T05:10:44,429][ERROR][i.c.m.s.T.HealthResultReceiver] [shadowcrate2data-0f66fee94797014a2] error retrieving tables health
    io.crate.exceptions.JobKilledException: Job killed. Received data for job=a245ad7c-a58f-4328-bf2b-29e690422466 but there is no job context present. This can happen due to bad network latency or if individual nodes are unresponsive due to high load
    	at io.crate.exceptions.JobKilledException.of(JobKilledException.java:31) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.RootTask.kill(RootTask.java:240) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.TasksService.killTasks(TasksService.java:189) ~[crate-app.jar:4.1.5]
    --
    [2020-07-17T05:12:13,773][ERROR][i.c.m.s.T.HealthResultReceiver] [shadowcrate2data-0f66fee94797014a2] error retrieving tables health
    io.crate.exceptions.JobKilledException: Job killed. Received data for job=19bdf2e8-d190-4dc0-ad29-82929cae6fab but there is no job context present. This can happen due to bad network latency or if individual nodes are unresponsive due to high load
    	at io.crate.exceptions.JobKilledException.of(JobKilledException.java:31) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.RootTask.kill(RootTask.java:240) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.TasksService.killTasks(TasksService.java:189) ~[crate-app.jar:4.1.5]
    --
    [2020-07-17T05:12:40,371][ERROR][i.c.m.s.T.HealthResultReceiver] [shadowcrate2data-0f66fee94797014a2] error retrieving tables health
    io.crate.exceptions.JobKilledException: Job killed. Received data for job=ea2d02f7-a083-4809-aa0c-ea3d0cdf621d but there is no job context present. This can happen due to bad network latency or if individual nodes are unresponsive due to high load
    	at io.crate.exceptions.JobKilledException.of(JobKilledException.java:31) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.RootTask.kill(RootTask.java:240) ~[crate-app.jar:4.1.5]
    	at io.crate.execution.jobs.TasksService.killTasks(TasksService.java:189) ~[crate-app.jar:4.1.5]
    --`

`    [2020-07-17T04:37:34,661][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638195]
    [2020-07-17T04:37:34,661][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638196]
    [2020-07-17T04:37:34,661][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638196]
    [2020-07-17T04:37:34,661][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638197]
    [2020-07-17T04:37:34,662][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638197]
    [2020-07-17T04:37:34,662][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638199]
    [2020-07-17T04:37:34,662][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638198]
    [2020-07-17T04:37:34,662][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638199]
    [2020-07-17T04:37:34,662][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638198]
    [2020-07-17T04:37:34,663][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638200]
    [2020-07-17T04:37:34,663][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638200]
    [2020-07-17T04:37:34,663][WARN ][o.e.t.TransportService   ] [shadowcrate2data-0f66fee94797014a2] Transport response handler not found of id [865638201]`
