### ISSUE TITLE
Flaky testTryCastReturnNullWhenCastingFailsOnRows (memory accounting leak?)

### ISSUE THREAD

**Issue by seut** [crate/crate#10353]
The test `testTryCastReturnNullWhenCastingFailsOnRows` is flaky. The exception indicates a possible memory accounting leak.

```
## FAILURE: Test testTryCastReturnNullWhenCastingFailsOnRows(io.crate.integrationtests.CastIntegrationTest)

REPRODUCE WITH: ./gradlew null -Dtests.seed=122CE6283E478B47 -Dtests.class=io.crate.integrationtests.CastIntegrationTest -Dtests.nightly=true -Dtests.method="testTryCastReturnNullWhenCastingFailsOnRows" -Dtests.nightly=true -Dtests.locale=lt -Dtests.timezone=Asia/Almaty


java.lang.AssertionError: Accounting breaker not reset to 0 on node: node_s1, are there still Lucene indices around?

Expected: <0L>
     but: was <988L>
	at __randomizedtesting.SeedInfo.seed([122CE6283E478B47:F7CD847992269B0C]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$33(InternalTestCluster.java:2187)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:802)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:776)
	at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2185)
	at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:88)
	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2229)
	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:442)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:1310)
	at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: java.lang.AssertionError: Accounting breaker not reset to 0 on node: node_s1, are there still Lucene indices around?

```

**Comment by mfussenegger** [comment]
I think this it not necessarily related to `testTryCastReturnNullWhenCastingFailsOnRows` alone.

I saw Accounting breaker failures lately - and every time several tests (usually in the same class) fail.

I think this is related to https://github.com/crate/crate/issues/10326 and the reader changes

**Comment by mfussenegger** [comment]
I think this is now fixed
