### ISSUE TITLE
Failing ConcurrentSeqNoVersioningIT#testSeqNoCASLinearizability

### ISSUE THREAD

**Issue by mkleen** [crate/crate#10364]
testSeqNoCASLinearizability in ConcurrentSeqNoVersioningIT is failing with the current state of master:

```
java.lang.AssertionError: [zydtkfzqtheg.t][1], node[hcuRvnwrQIGXymYrYfaHbg], [R], s[STARTED], a[id=uQpPUT5GSCCPzLMYmrSmCQ] seq_no_stats mismatch
Expected: <SeqNoStats{maxSeqNo=7, localCheckpoint=7, globalCheckpoint=7}>
     but: was <SeqNoStats{maxSeqNo=7, localCheckpoint=7, globalCheckpoint=6}>
```

**Comment by amotl** [comment]
Apparently, this just [happened again](https://github.com/crate/crate/actions/runs/11935662801/job/33267494524?pr=17024#step:4:4176) on CI/GHA. As I can observe you took some actions the last time, I am reopening this ticket to let you evaluate the situation once more.

**Comment by BaurzhanSakhariev** [comment]
Thanks @amotl, we had a card to track it, I edited your message with the information about other failures and removed card from the board.

**Comment by BaurzhanSakhariev** [comment]
```
[ERROR] io.crate.integrationtests.disruption.seqno.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability -- Time elapsed: 68.98 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[Must be linearizable] 
Expecting value to be true but was false
	at __randomizedtesting.SeedInfo.seed([8CB46E35E200B8C7:577A405FF8129A73]:0)
	at io.crate.integrationtests.disruption.seqno.ConcurrentSeqNoVersioningIT$Partition.assertLinearizable(ConcurrentSeqNoVersioningIT.java:505)
```

**Comment by BaurzhanSakhariev** [comment]
ackedIndexing test failed on 16.01 (maybe related)

**Comment by BaurzhanSakhariev** [comment]
new failures (24.01 and 27.01)
https://wacklig.pipifein.dev/github/crate/crate/case/io.crate.integrationtests.disruption.seqno.ConcurrentSeqNoVersioningIT/testSeqNoCASLinearizability

**Comment by BaurzhanSakhariev** [comment]
We merged https://github.com/crate/crate/pull/17553 on 05.03 but had another one failure on 10.03

```
https://wacklig.pipifein.dev/github/crate/crate/13845155-433a-40dc-b952-a0e2baebe82a/859e25f7-d8b9-43d4-8aab-3beaf5c0a22b

java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at __randomizedtesting.SeedInfo.seed([D7D7DB7FCE14124F:C19F515D40630FB]:0)
	at io.crate.integrationtests.disruption.seqno.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability(ConcurrentSeqNoVersioningIT.java:209)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1763)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:259)
	at java.base/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:437)
	at io.crate.integrationtests.disruption.seqno.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability(ConcurrentSeqNoVersioningIT.java:193)
	... 7 more
```

Maybe still just a test setup issue
