### ISSUE TITLE
Regression: SQLActionException[NullPointerException: at index 0]

### ISSUE THREAD

**Issue by chaudum** [crate/crate#10590]
**CrateDB version**:

`4.2.x` (worked with `4.0.12`)

**Environment description**:

 - Distribution: tarball
 - JVM version: `OpenJDK 64-Bit Server VM (build 14.0.2+12-Debian-1, mixed mode, sharing)` 
 - Kernel: `Linux technics1210 5.8.0-1-amd64 #1 SMP Debian 5.8.7-1 (2020-09-05) x86_64 GNU/Linux`

**Problem description**:

I expect that a GROUP BY on a CROSS JOIN works like it did with version 4.0.x

**Steps to reproduce**:

```console
$ cr8 run-crate latest-stable -- @crash -v --hosts {node.http_url} <<EOF
SELECT
  c.name as "name",
  max(h.severity) as "severity"
FROM
  sys.health h,
  sys.cluster c
GROUP BY
  1
;
EOF

# run-crate
===========

Skipping download, tarball alrady extracted at /home/christian/.cache/cr8/crates/crate-4.2.4
Starting Crate process
CrateDB launching:
    PID: 2196828
    Logs: /home/christian/.cache/cr8/crates/crate-4.2.4/logs/cr8-crate-run872663492.log
    Data: /tmp/tmp8z1barog (removed on stop)

Psql      : 127.0.0.1:5432
Http      : 127.0.0.1:4201
Transport : 127.0.0.1:4300
Cluster ready to process requests


# @crash
========

+-----------------------+-----------+---------+-----------+---------+
| server_url            | node_name | version | connected | message |
+-----------------------+-----------+---------+-----------+---------+
| http://127.0.0.1:4201 | Marmolada | 4.2.4   | TRUE      | OK      |
+-----------------------+-----------+---------+-----------+---------+
CONNECT OK
CLUSTER CHECK OK
TYPES OF NODE CHECK OK
SQLActionException[NullPointerException: at index 0]

SQLActionException: 500 Internal Server Error 5000 NullPointerException: at index 0
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:225)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:215)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:209)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:346)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:231)
	at io.crate.execution.engine.collect.sources.SystemCollectSource.recordsToRows(SystemCollectSource.java:109)
	at io.crate.execution.engine.collect.sources.SystemCollectSource.lambda$getIterator$3(SystemCollectSource.java:139)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2158)
	at io.crate.execution.engine.collect.sources.SystemCollectSource.lambda$getIterator$4(SystemCollectSource.java:138)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:147)
	at io.crate.data.join.JoinBatchIterator.loadNextBatch(JoinBatchIterator.java:100)
	at io.crate.data.MappedForwardingBatchIterator.loadNextBatch(MappedForwardingBatchIterator.java:52)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:70)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:45)
	at io.crate.data.CollectingBatchIterator.lambda$newInstance$2(CollectingBatchIterator.java:88)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:147)
	at io.crate.data.MappedForwardingBatchIterator.loadNextBatch(MappedForwardingBatchIterator.java:52)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:85)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:53)
	at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:92)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

Failure running: crash -v --hosts http://127.0.0.1:4201
```

The latest version this query worked was `4.0.12`:

```console
$ cr8 run-crate 4.0.x -- @crash -v --hosts {node.http_url} <<EOF

SELECT
  c.name as "name",
  max(h.severity) as "severity"
FROM
  sys.health h,
  sys.cluster c
GROUP BY
  1
;
EOF

# run-crate
===========

Downloading https://cdn.crate.io/downloads/releases/crate-4.0.12.tar.gz and extracting to /home/christian/.cache/cr8/crates
Starting Crate process
CrateDB launching:
    PID: 2198999
    Logs: /home/christian/.cache/cr8/crates/crate-4.0.12/logs/cr8-crate-run620606705.log
    Data: /tmp/tmph1__yqv8 (removed on stop)

Psql      : 127.0.0.1:5432
Http      : 127.0.0.1:4201
Transport : 127.0.0.1:4300
Cluster ready to process requests


# @crash
========

+-----------------------+-----------+---------+-----------+---------+
| server_url            | node_name | version | connected | message |
+-----------------------+-----------+---------+-----------+---------+
| http://127.0.0.1:4201 | Pizol     | 4.0.12  | TRUE      | OK      |
+-----------------------+-----------+---------+-----------+---------+
CONNECT OK
CLUSTER CHECK OK
TYPES OF NODE CHECK OK
+------+----------+
| name | severity |
+------+----------+
+------+----------+
SELECT 0 rows in set (0.042 sec)
```

**Comment by mfussenegger** [comment]
Thank you for the bug report. We'll have a fix for this in 4.2.6 (https://github.com/crate/crate/pull/10593)
