### ISSUE TITLE
Invalid data type when using parameters with `UNNEST` as joined table

### ISSUE THREAD

**Issue by chaudum** [crate/crate#10620]
**CrateDB version**:

4.2.5

**Environment description**:

Tarball installation

**Problem description**:

When using `UNNEST` as table generating function in a JOIN, I expect to be able to use a parameter as well.

However, the parameter needs to be cast explicitly: `UNNEST(?::ARRAY(TEXT)`

**Steps to reproduce**:

```py
from crate.client import connect

if __name__ == "__main__":
    with connect(error_trace=True) as conn:
        cur = conn.cursor()
        cur.execute("""
            DROP TABLE IF EXISTS t1
        """)
        cur.execute("""
            CREATE TABLE t1 (name TEXT, x TEXT)
        """)
        cur.execute("""
            INSERT INTO t1 (name, x) VALUES ('foo', 'a'), ('bar', 'b'), ('foobar', 'a')
        """)
        cur.execute("""
            REFRESH TABLE t1
        """)

        # SUCCEEDS
        cur.execute("""
            SELECT
              t2.x,
              count(*)
            FROM
              t1
              RIGHT JOIN UNNEST(['a', 'b', 'c']) AS t2 (x) ON t1.x = t2.x
            GROUP BY t2.x
            ORDER BY t2.x
        """)
        print("Query A")
        for row in cur.fetchall():
            print(row)

        # SUCCEEDS
        cur.execute("""
            SELECT
              t2.x,
              count(*)
            FROM
              t1
              RIGHT JOIN UNNEST(?::ARRAY(TEXT)) AS t2 (x) ON t1.x = t2.x
            GROUP BY t2.x
            ORDER BY t2.x
        """, (["a", "b", "c"],))
        print("Query B")
        for row in cur.fetchall():
            print(row)

        # FAILES
        cur.execute("""
            SELECT
              t2.x,
              count(*)
            FROM
              t1
              RIGHT JOIN UNNEST(?) AS t2 (x) ON t1.x = t2.x
            GROUP BY t2.x
            ORDER BY t2.x
        """, (["a", "b", "c"],))
        print("Query C")
        for row in cur.fetchall():
            print(row)
```

When executing:

```console
$ python params_unnest.py
Query A
['a', 2]
['b', 1]
['c', 1]
Query B
['a', 2]
['b', 1]
['c', 1]
Traceback (most recent call last):
  File "params_unnest.py", line 52, in <module>
    cur.execute("""
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/cursor.py", line 53, in execute
    self._result = self.connection.client.sql(sql, parameters,
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/http.py", line 331, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/http.py", line 458, in _json_request
    _raise_for_status(response)
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/http.py", line 187, in _raise_for_status
    raise ProgrammingError(error.get('message', ''),
crate.client.exceptions.ProgrammingError: SQLActionException[UnsupportedFeatureException: Cannot ORDER BY 'x': invalid data type 'undefined'.]
```

Similar error occurs when omitting ORDER BY:

```console
$ python params_unnest.py
Query A
['a', 2]
['b', 1]
['c', 1]
Query B
['a', 2]
['b', 1]
['c', 1]
Traceback (most recent call last):
  File "params_unnest.py", line 52, in <module>
    cur.execute("""
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/cursor.py", line 53, in execute
    self._result = self.connection.client.sql(sql, parameters,
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/http.py", line 331, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/http.py", line 458, in _json_request
    _raise_for_status(response)
  File "/home/christian/sandbox/crate/cloud-api/env/lib/python3.8/site-packages/crate/client/http.py", line 187, in _raise_for_status
    raise ProgrammingError(error.get('message', ''),
crate.client.exceptions.ProgrammingError: SQLActionException[SQLParseException: Couldn't create executionContexts from
NodeOperations: [1=>NodeOp{ phase{id=1/tableFunction, nodes=[CSffbDGfQkCRgDWz_qBISg], dist=BROADCAST}, downstreamNodes=[CSffbDGfQkCRgDWz_qBISg], downstreamPhase=3, downstreamInputId=1}, 0=>NodeOp{ phase{id=0/collect, nodes=[CSffbDGfQkCRgDWz_qBISg], dist=BROADCAST}, downstreamNodes=[CSffbDGfQkCRgDWz_qBISg], downstreamPhase=3, downstreamInputId=0}]
Leafs: [JoinPhase{executionNodes=[CSffbDGfQkCRgDWz_qBISg], executionPhaseId=3, name=nested-loop, joinType=RIGHT, joinCondition=(INPUT(0) = _cast(INPUT(1), 'text')), outputTypes=[undefined, bigint], jobId=19864fde-d2e9-4c48-aca1-b93baf7e1a30, executionNodes=[CSffbDGfQkCRgDWz_qBISg]}]
target-sources: [3=>[0, 1]]
original-error: UnsupportedOperationException: Cannot GROUP BY type: undefined]
```

**Comment by mfussenegger** [comment]
This is a limitation of our type system or type inference.

In 

```SQL
SELECT
              t2.x,
              count(*)
            FROM
              t1
              RIGHT JOIN UNNEST(?) AS t2 (x) ON t1.x = t2.x
            GROUP BY t2.x
            ORDER BY t2.x
```

The type for `?` is unknown and the next instance that gives a hint about the type is the join condition `t1.x = t2.x`. That's too far removed for our type inference system.


I'm afraid you'll have to stick with the manual cast.

**Comment by mfussenegger** [comment]
Closing this as we're unlikely to improve the type inference behaviour for such cases any time soon.

(But we'd take contributions for it)
