### ISSUE TITLE
Flaky SysSegmentsTableInfoTest test_retrieve_segment_information

### ISSUE THREAD

**Issue by mkleen** [crate/crate#10843]
REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=5FEC558EE4F1739B -Dtests.class=io.crate.integrationtests.SysSegmentsTableInfoTest -Dtests.method="test_retrieve_segment_information" -Dtests.locale=en-BE -Dtests.timezone=America/Danmarkshavn
java.lang.AssertionError: 
Expected: is "_0"
     but: was "_1"
	at __randomizedtesting.SeedInfo.seed([5FEC558EE4F1739B:DF642075F9004FB4]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at io.crate.integrationtests.SysSegmentsTableInfoTest.validateResponse(SysSegmentsTableInfoTest.java:60)

**Comment by mfussenegger** [comment]
See https://github.com/crate/crate/pull/10904
