### ISSUE TITLE
'Missing parameters' raised when using match predicate with limit  

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#10897]
**CrateDB version**: 4.3.3
On 4.3.2 all works fine

**Problem description**:
Exception raised when LIMIT value passed as parameter to SQL.
```
io.crate.shade.org.postgresql.util.PSQLException: ERROR: The assembled list of ParameterSymbols is invalid. Missing parameters.
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:442)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:366)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:145)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at TestCrate.testLimit(TestCrate.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Steps to reproduce**:
1. Create test table
```
create table test (
    "keywords" TEXT INDEX USING FULLTEXT WITH (
        analyzer = 'standard'
    )
)
```

Execute this JAVA code
```
	@Test
	public void testLimit() throws Exception {
		try (var conn = DriverManager.getConnection("jdbc:crate://HOST:5432/", "crate", "")) {
			try (var stmt = conn.prepareStatement(
					"select * from test where match (keywords, ?) using best_fields with (fuzziness=1, cutoff_frequency=1, analyzer='whitespace') limit ?")) {
				stmt.setObject(1, "text");
				stmt.setObject(2, 1);
				try (var rs = stmt.executeQuery()) {
					rs.next();
				}
			}
		}
	}
```

**Workaround**:
Pass LIMIT value directly to SQL, without parameters using.
```
	@Test
	public void testLimit() throws Exception {
		try (var conn = DriverManager.getConnection("jdbc:crate://HOST:5432/", "crate", "")) {
			try (var stmt = conn.prepareStatement(
					"select * from test where match (keywords, ?) using best_fields with (fuzziness=1, cutoff_frequency=1, analyzer='whitespace') limit 1")) {
				stmt.setObject(1, "text");
				try (var rs = stmt.executeQuery()) {
					rs.next();
				}
			}
		}
	}
```

**Comment by shm-dmitry** [comment]
Additional
I think problem in `match` predicate, because this sample also failed.
```
create table test (
    "keywords" TEXT INDEX USING FULLTEXT WITH (
        analyzer = 'standard'
    ),
    a object as (
        b int
    )
)
```
```
	@Test
	public void testWithAttribute() throws Exception {
		try (var conn = DriverManager.getConnection("jdbc:crate://crate00:5432/", "crate", "")) {
			try (var stmt = conn.prepareStatement(
					"select * from test where match (keywords, ?) using best_fields with (fuzziness=1, cutoff_frequency=1, analyzer='whitespace') and  a['b'] = ?")) {
				stmt.setObject(1, "text");
				stmt.setObject(2, 3);
				try (var rs = stmt.executeQuery()) {
					rs.next();
				}
			}
		}
	}
```

**Comment by mfussenegger** [comment]
Thank you for the detailed bug report. This should get fixed with https://github.com/crate/crate/pull/10899
