### ISSUE TITLE
COUNT DISTINCT for varchar column throws SQLParseException

### ISSUE THREAD

**Issue by jayeff** [crate/crate#11296]
**CrateDB version**: 4.5.0

**Problem description**:

I try to execute the query `SELECT COUNT(DISTINCT str) FROM varchartest LIMIT 100;` to get the number of distinct values for column `str`.

This query throws an exception: `SQLParseException[Cannot cast value 'abc' to type 'char']`

Error trace:

```
io.crate.exceptions.SQLParseException: Cannot cast value `abc` to type `char`
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:137)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:126)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:89)
	at io.crate.protocols.postgres.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:115)
	at io.crate.action.sql.RowConsumerToResultReceiver.lambda$consumeIt$1(RowConsumerToResultReceiver.java:92)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
	at io.crate.data.BatchIterators.lambda$collect$0(BatchIterators.java:74)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: io.crate.exceptions.ConversionException: Cannot cast value `abc` to type `char`
	at io.crate.expression.scalar.cast.ImplicitCastFunction.evaluate(ImplicitCastFunction.java:72)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:51)
	at io.crate.expression.InputRow.get(InputRow.java:46)
	at io.crate.execution.engine.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:39)
	at io.crate.execution.engine.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:26)
	at io.crate.execution.engine.aggregation.AggregateCollector.setRow(AggregateCollector.java:158)
	at io.crate.execution.engine.aggregation.AggregateCollector.iterate(AggregateCollector.java:134)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:65)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:45)
	at io.crate.data.CollectingBatchIterator.lambda$newInstance$2(CollectingBatchIterator.java:88)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:147)
	at io.crate.data.CompositeBatchIterator$AsyncCompositeBI.lambda$loadNextBatch$0(CompositeBatchIterator.java:222)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	... 3 more
```

**Steps to reproduce**:

Create table
```
create table varchartest (str varchar(10));
```

Sample records
```
insert into varchartest (str) values ('abc'), ('abc'), ('def');
```

Just COUNT or DISTINCT works:
```
SELECT COUNT(str) FROM varchartest LIMIT 100;
SELECT DISTINCT(str) FROM varchartest LIMIT 100;
```

Combined it throws the exception ⚡ 
```
SELECT COUNT(DISTINCT(str)) FROM varchartest LIMIT 100;
```

**Comment by mfussenegger** [comment]
Looks like there's a problem with the cast precedence semantics and `str` is incorrectly being cast to a `char`.

If the type changes to `varchar` instead of `varchar(10)` the example works.

We'll work on a fix for the next hotfix release.
