### ISSUE TITLE
Incorrect cast when inserting mixed types into text column

### ISSUE THREAD

**Issue by jayeff** [crate/crate#11519]
**CrateDB version**: 4.5.3

**Problem description**:

```
create table test (id text);
insert into test (id) values (3); --INSERT OK
insert into test (id) values ('a'); --INSERT OK
insert into test (id) values ('1'), (3); --INSERT OK
insert into test (id) values ('a'), (3);
--SQLParseException[Cannot cast `'a'` of type `text` to type `integer`]
```

**Expected behaviour**:

Last insert statements inserts two rows with id `'a'` and id `'3'`

**Stacktrace**:

<details> 
<summary>Stacktrace io.crate.exceptions.SQLParseException: Cannot cast `'a'` of type `text` to type `integer`</summary>

```
io.crate.exceptions.SQLParseException: Cannot cast `'a'` of type `text` to type `integer`
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:137)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:126)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2321)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:116)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:79)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:136)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:85)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: io.crate.exceptions.ConversionException: Cannot cast `'a'` of type `text` to type `integer`
	at io.crate.expression.scalar.cast.ImplicitCastFunction.normalizeSymbol(ImplicitCastFunction.java:106)
	at io.crate.expression.eval.EvaluatingNormalizer$BaseVisitor.normalizeFunction(EvaluatingNormalizer.java:241)
	at io.crate.expression.eval.EvaluatingNormalizer$BaseVisitor.visitFunction(EvaluatingNormalizer.java:228)
	at io.crate.expression.eval.EvaluatingNormalizer$BaseVisitor.visitFunction(EvaluatingNormalizer.java:121)
	at io.crate.expression.symbol.Function.accept(Function.java:241)
	at io.crate.expression.eval.EvaluatingNormalizer.normalize(EvaluatingNormalizer.java:261)
	at io.crate.analyze.relations.RelationAnalyzer.lambda$visitValues$5(RelationAnalyzer.java:743)
	at io.crate.common.collections.Lists2.map(Lists2.java:84)
	at io.crate.analyze.relations.RelationAnalyzer.visitValues(RelationAnalyzer.java:741)
	at io.crate.analyze.relations.RelationAnalyzer.visitValues(RelationAnalyzer.java:107)
	at io.crate.sql.tree.Values.accept(Values.java:41)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:136)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:107)
	at io.crate.sql.tree.Query.accept(Query.java:65)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:125)
	at io.crate.analyze.InsertAnalyzer.analyze(InsertAnalyzer.java:118)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitInsert(Analyzer.java:481)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitInsert(Analyzer.java:212)
	at io.crate.sql.tree.Insert.accept(Insert.java:102)
	at io.crate.analyze.Analyzer.analyze(Analyzer.java:197)
	at io.crate.action.sql.Session.parse(Session.java:284)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:242)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:206)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:115)
	... 45 more
```

</details>

**Comment by mfussenegger** [comment]
This is kinda expected. It first processes the records in `values` and tries to cast by precedence (integer has a higher precedence than text), only after that it takes the type of the target column into consideration.  Because of that, `('1'), (3);` works - it first casts `'1'` to `1` and later converts both `1` and `3` back to text.

Is there some kind of use-case behind this, or was this simply a mistake?

**Comment by proddata** [comment]
We were looking into replicating a "dynamic" data type that could hold various other supported data types.

similar to
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/dynamic
https://docs.microsoft.com/en-us/sql/t-sql/data-types/sql-variant-transact-sql?view=sql-server-ver15

**Comment by jayeff** [comment]
In this use case we would potentially store all values as text and cast later to "correct" data type. If this this doesn't work we maybe need another approach (or need to cast before insert but don't know if this is enforceable)

**Comment by mfussenegger** [comment]
@proddata Could you create a new dedicated feature request for the dynamic type (Including a use-case description?)

The initial issue will be solved with https://github.com/crate/crate/pull/11711
