### ISSUE TITLE
Primary Key cannot be dropped

### ISSUE THREAD

**Issue by walter-weinmann** [crate/crate#11609]
### CrateDB version

4.6.1

### CrateDB setup information

Official Docker Image: [see here](https://hub.docker.com/layers/crate/library/crate/4.6.1/images/sha256-8730cac778afd37c78bd75c0440c74fb75c1c68f703b86242ea567e7844c6820?context=explore)

### Steps to Reproduce

1. DDL Statement: CREATE TABLE

```
CREATE TABLE doc.country (
	pk_country_id bigint,
	country_map object,
	created timestamp with time zone,
	iso3166 text,
	modified timestamp with time zone,
	name text,
	CONSTRAINT country_pk PRIMARY KEY (pk_country_id)
);

```
2. DDL Statement: DROP INDEX

`ALTER TABLE country DROP CONSTRAINT country_pk`

### Expected Result

Primary key should be dropped

### Actual Result

```
2021-07-29 10:19:08,999 [DatabaseSeeder.java] INFO  Start CrateDB
io.crate.shade.org.postgresql.util.PSQLException: ERROR: Cannot find a CHECK CONSTRAINT named [country_pk], available constraints are: []
        at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:442)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:366)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:308)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:294)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:271)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.executeSQLStmnts(AbstractJdbcSeeder.java:1310)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.dropTableConstraints(AbstractJdbcSeeder.java:1207)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:415)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:119)
Processing of the script was aborted, error code=1
```

**Comment by proddata** [comment]
Hi @walter-weinmann 

CrateDB currently does not support named Primary Key constraints, so the table would not even be created.
also see https://github.com/crate/crate/issues/11025

**Comment by walter-weinmann** [comment]
Ok I see [here](https://crate.io/docs/crate/reference/en/4.6/sql/statements/alter-table.html#drop-constraint)

The CREATE TABLE statement was produced with DBeaver - so internally the primary key constraints are named.

Is there any chance of a fully implementation of adding and dropping constraints - at least for foreign, primary and unique keys?

**Comment by proddata** [comment]
> Is there any chance of a fully implementation of adding and dropping constraints - at least for foreign, primary and unique keys?

It is not planned to support foreign or unique keys anytime soon.

Since Lucene segments are written in an append only fashion, changing the schema or constraints is often best done by recreating a table with a new schema and moving data to the new table.

also see: unique keys: https://github.com/crate/crate/issues/10279

**Comment by proddata** [comment]
Since there is no new feature request or bug report, I will close this.

If you have any questions about using CrateDB I would like to refer you to https://community.crate.io/
