### ISSUE TITLE
Adding invalid azure repository breaks snapshotting

### ISSUE THREAD

**Issue by jayeff** [crate/crate#11673]
### CrateDB version

4.6.1

### CrateDB setup information

single node; local on macOS

### Steps to Reproduce

Create valid repository of type azure, snapshot and list snapshots:

```
CREATE REPOSITORY azurerepo TYPE azure
WITH (account = '<account>', container = '<container>', key ='<key>');

CREATE SNAPSHOT azurerepo.backup1 ALL;

SELECT name FROM sys.snapshots;
-- backup1

SELECT name FROM sys.repositories;
-- azurerepo
```

Create repository of type azure for account which does not exist:

```
CREATE REPOSITORY azurerepo2 TYPE azure
WITH (account = 'doesnotexist', container = '<container>', key ='<key>');
```

After about 2 minutes (maybe a tad more aggressive timeout could be considered here) an exception is raised:

```
RepositoryVerificationException[[azurerepo2] Unable to verify the repository, [azurerepo2] is not accessible on master node: StorageException '']
org.elasticsearch.repositories.RepositoryVerificationException: [azurerepo2] Unable to verify the repository, [azurerepo2] is not accessible on master node: StorageException ''
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1016)
	at org.elasticsearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:238)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Repository was not added to sys.repositories:

```
SELECT name FROM sys.repositories;
-- azurerepo
```

### Expected Result

`CREATE SNAPSHOT azurerepo.backup2 ALL;` and `SELECT name FROM sys.snapshots;` still work

### Actual Result

`CREATE SNAPSHOT azurerepo.backup2 ALL;` and `SELECT name FROM sys.snapshots;` are broken. Exception is raised again after about 2 minutes.

Error trace for both commands:

```
org.elasticsearch.repositories.RepositoryException: [azurerepo] could not read repository data from index blob
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1167)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1070)
	at io.crate.expression.reference.sys.snapshot.SysSnapshots.currentSnapshots(SysSnapshots.java:76)
	at io.crate.expression.reference.StaticTableDefinition.lambda$new$0(StaticTableDefinition.java:48)
	at io.crate.expression.reference.StaticTableDefinition.retrieveRecords(StaticTableDefinition.java:88)
	at io.crate.execution.engine.collect.sources.SystemCollectSource.lambda$getIterator$4(SystemCollectSource.java:144)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:146)
	at io.crate.data.MappedForwardingBatchIterator.loadNextBatch(MappedForwardingBatchIterator.java:51)
	at io.crate.data.LimitingBatchIterator.loadNextBatch(LimitingBatchIterator.java:69)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:84)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:52)
	at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:92)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.io.IOException: com.microsoft.azure.storage.StorageException: 
	at org.elasticsearch.repositories.azure.AzureBlobContainer.readBlob(AzureBlobContainer.java:84)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1151)
	... 14 more
Caused by: com.microsoft.azure.storage.StorageException: 
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:220)
	at com.microsoft.azure.storage.blob.CloudBlob.downloadAttributes(CloudBlob.java:1414)
	at com.microsoft.azure.storage.blob.BlobInputStream.<init>(BlobInputStream.java:191)
	at com.microsoft.azure.storage.blob.CloudBlob.openInputStream(CloudBlob.java:2687)
	at com.microsoft.azure.storage.blob.CloudBlob.openInputStream(CloudBlob.java:2643)
	at org.elasticsearch.repositories.azure.AzureStorageService.getInputStream(AzureStorageService.java:208)
	at org.elasticsearch.repositories.azure.AzureBlobStore.getInputStream(AzureBlobStore.java:112)
	at org.elasticsearch.repositories.azure.AzureBlobContainer.readBlob(AzureBlobContainer.java:79)
	... 15 more
Caused by: java.net.UnknownHostException: doesnotexist.blob.core.windows.net
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:645)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:115)
	... 22 more
```

Likely most interesting line is `Caused by: java.net.UnknownHostException: doesnotexist.blob.core.windows.net`

### Workaround

After a cluster reboot `CREATE SNAPSHOT azurerepo.backup2 ALL;` and `SELECT name FROM sys.snapshots;` work again

### Additional note

I tested S3 repositories as well but with S3 it's not possible to get CrateDB into this state.

**Comment by mfussenegger** [comment]
This got fixed via https://github.com/crate/crate/pull/11676
