### ISSUE TITLE
CrateDB 4.6 intermittently responds with "400 Bad Request" while starting up

### ISSUE THREAD

**Issue by teodorpatras** [crate/crate#11699]
### CrateDB version

4.6.2

### CrateDB setup information

CRATE_HEAP_SIZE: 1g

### Steps to Reproduce

1.  `docker-compose.yml`:
```
version: "3.6"
services:

  crate:
    image: crate/crate:4.6.2
    ports:
    - "4200:4200"
    environment:
      CRATE_HEAP_SIZE: 1g
```
2. Install the latest python client: `pip install crate`
3. Start the above CrateDB service.
4. While the database server is booting up, run the following python script (might need several attempts for the `400 Bad Request` to be returned by the server):
```
from crate import client

client.connect("127.0.0.1:4200")
```

### Expected Result

Connection refused. No exceptions raised, `<Connection <Client ['http://127.0.0.1:4200']>>` returned.

### Actual Result

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/.venv/lib/python3.8/site-packages/crate/client/connection.py", line 123, in __init__
    self.lowest_server_version = self._lowest_server_version()
  File "/project/.venv/lib/python3.8/site-packages/crate/client/connection.py", line 162, in _lowest_server_version
    _, _, version = self.client.server_infos(server)
  File "/project/.venv/lib/python3.8/site-packages/crate/client/http.py", line 403, in server_infos
    _raise_for_status(response)
  File "/project/.venv/lib/python3.8/site-packages/crate/client/http.py", line 209, in _raise_for_status
    raise ProgrammingError(message)
crate.client.exceptions.ProgrammingError: 400 Client Error: Bad Request
```

**Comment by amotl** [comment]
Hi there,

thank you very much for reporting this, @teodorpatras! I want to follow up on this by providing a concise and compact repro without having to use Docker Compose and without having to take several attempts to find the sweet spot where this error triggers.

1. Invoke this command in order to connect to CrateDB in a reasonable tight loop:
   ```
   while sleep 0.01; do python -c 'from crate import client; print(client.connect("127.0.0.1:4200"))'; done
   ```
2. While the command above is running, start a CrateDB instance:
   ```
   docker run -it --rm --publish=4200:4200 --publish=5432:5432 crate/crate:4.6.2
   ```

Indeed, it starts happening with CrateDB 4.6.0, I haven't been able to reproduce it with the most recent 4.5.x release, namely CrateDB 4.5.4.

With kind regards,
Andreas.

**Comment by amotl** [comment]
As kind of expected, it happens around the time when CrateDB is bringing up its HTTP interface through Netty:
```
[2021-09-02T20:50:13,868][INFO ][o.e.n.Node               ] [Großes Wiesbachhorn] starting ...
[2021-09-02T20:50:14,013][INFO ][psql                     ] [Großes Wiesbachhorn] publish_address {172.17.0.2:5432}, bound_addresses {127.0.0.1:5432}, {172.17.0.2:5432}
[2021-09-02T20:50:14,027][INFO ][o.e.h.n.Netty4HttpServerTransport] [Großes Wiesbachhorn] publish_address {172.17.0.2:4200}, bound_addresses {127.0.0.1:4200}, {172.17.0.2:4200}
[2021-09-02T20:50:14,040][INFO ][o.e.t.TransportService   ] [Großes Wiesbachhorn] publish_address {172.17.0.2:4300}, bound_addresses {127.0.0.1:4300}, {172.17.0.2:4300}
[2021-09-02T20:50:14,223][INFO ][o.e.b.BootstrapChecks    ] [Großes Wiesbachhorn] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2021-09-02T20:50:14,236][INFO ][o.e.c.c.ClusterBootstrapService] [Großes Wiesbachhorn] no discovery configuration found, will perform best-effort cluster bootstrapping after [3s] unless existing master is discovered
```

**Comment by teodorpatras** [comment]
Hi there

I am re-opening this issue because I can still reproduce it in the latest version - 4.6.3.

1. `while true; do python -c 'from crate import client; print(client.connect("127.0.0.1:4200"))'; done`
2. While the command above is running, start a CrateDB instance: `docker run -it --rm --publish=4200:4200 --publish=5432:5432 crate/crate:4.6.3`

Result:

```
Requesting...
...
crate.client.exceptions.ProgrammingError: 400 Client Error: Bad Request
```

**Comment by mfussenegger** [comment]
Should be fixed by https://github.com/crate/crate/pull/11773 - hopefully this time for good
