### ISSUE TITLE
Crate 4.6.4 fails to start  : too many open files

### ISSUE THREAD

**Issue by echarlus** [crate/crate#11787]
### CrateDB version

4.6.4

### CrateDB setup information

Number of Nodes : 1
Heap Size : 4Gb (default)
No specific java ops

MacOS 11.6
 Nom du modèle :	MacBook Pro
  Identifiant du modèle :	MacBookPro13,3
  Nom du processeur :	Intel Core i7 quatre cœurs
  Vitesse du processeur :	2,9 GHz
  Nombre de processeurs :	1
  Nombre total de cœurs :	4
  Cache de niveau 2 (par cœur) :	256 Ko
  Cache de niveau 3 :	8 Mo
  Technologie Hyper-Threading :	Activé
  Mémoire :	16 Go

Full DB has 14M records and has been upgraded from 2.3.11 by first moving to 3.3.6 and re-creating /migrating tables as specified in the manuals then to 4.0.12 (again re-creating/migrating the tables) and then to 4.1.8 -> 4.2.7 -> 4.3.4 -> 4.6.3

I had to increase the ulimit by setting ulimit -S -n 1048576 and previous versions where running fine until 4.6.4 :(

### Steps to Reproduce

Start the node with an existing DB that's running fine on 4.6.3

### Expected Result

Cluster state should turn green

### Actual Result

After some time, the process exits : 

[2021-10-01T11:30:40,755][WARN ][o.e.g.G.InternalPrimaryShardAllocator] [Predigstuhl] [ocell..partitioned.sensor_location.04732d9k64o36c1k60o30c1g][0]: failed to list shard for shard_started on node [IEGQEg3BS_yNrs2OHrpm4g]
org.elasticsearch.action.FailedNodeException: Failed node [IEGQEg3BS_yNrs2OHrpm4g]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:214) [crate-server.jar:?]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:188) [crate-server.jar:?]
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleException(TransportService.java:1048) [crate-server.jar:?]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1165) [crate-server.jar:?]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1139) [crate-server.jar:?]
	at org.elasticsearch.transport.TransportService$6.onFailure(TransportService.java:709) [crate-server.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [crate-server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [Predigstuhl][127.0.0.1:4300][internal:gateway/local/started_shards[n]]
Caused by: org.elasticsearch.ElasticsearchException: failed to load started shards
	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:168) ~[crate-server.jar:?]
	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:62) ~[crate-server.jar:?]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:237) ~[crate-server.jar:?]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:233) ~[crate-server.jar:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-server.jar:?]
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:698) ~[crate-server.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-server.jar:?]
	... 3 more
Caused by: java.nio.file.FileSystemException: /Users/charlus/Devpt/Ocell/Crate/crate-4.6.4/data/nodes/0/indices/ZqbImN6DS_iL2DkXq44Jvg/0/_state: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:419) ~[?:?]
	at java.nio.file.Files.newDirectoryStream(Files.java:544) ~[?:?]
	at org.elasticsearch.gateway.MetadataStateFormat.findMaxGenerationId(MetadataStateFormat.java:356) ~[crate-server.jar:?]
	at org.elasticsearch.gateway.MetadataStateFormat.loadLatestStateWithGeneration(MetadataStateFormat.java:435) ~[crate-server.jar:?]
	at org.elasticsearch.gateway.MetadataStateFormat.loadLatestState(MetadataStateFormat.java:459) ~[crate-server.jar:?]
	at org.elasticsearch.gateway%

**Comment by echarlus** [comment]
it appears that the issue was caused by the data, I copied again the database to the 4.6.4 directory and it started fine. sorry for the noise
