### ISSUE TITLE
Switching to plaintext doesn't seem to work occasionally 

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [crate/crate#11954]
related to https://github.com/crate/crate/issues/11546 - not yet released, has a bug caught by tests (occasionally flaky).

### CrateDB version

current master

### Steps to Reproduce

run test `io.crate.integrationtests.SSLTrustedZoneITest.test_switch_to_plaintext_enabled_downgrades_to_plaintext`
with options 
`-Dtests.seed=609F887A9B59B7F6 -Dtests.nightly=true -Dtests.locale="kl-Latn-GL" -Dtests.timezone=Australia/Sydney`

**another way to reproduce, proving that's it's bug**
completely remove body of the test and run empty test with the seed specified above - it fails with the same error.

test passes if I comment out [this line](https://github.com/crate/crate/blob/d2518c0aec42975b398e6a93eee9f450ea0027c2/server/src/main/java/org/elasticsearch/transport/netty4/HostBasedAuthHandler.java#L94) i.e down't downgrade and imitate normal behaviour without this feature.

### Expected Result

test passes 

### Actual Result

```
at __randomizedtesting.SeedInfo.seed([609F887A9B59B7F6:CD3ED7167BEF6B6B]:0)
	at java.base@17/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	at java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
	at app//org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:251)
	at app//org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:86)
	at app//org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:57)
	at app//org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:34)
	at app//org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:423)
	at app//org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:1279)
```

**Comment by BaurzhanSakhariev** [comment]
temporarily muted by https://github.com/crate/crate/pull/11955
