### ISSUE TITLE
StreamCorruptedException exception raised wile node running

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#12058]
### CrateDB version

4.6.6

### CrateDB setup information

path.data: /opt/crate/data
path.repo: /opt/crate/repo

network.host: 0.0.0.0

node.name: "ev-crate04"
node.master: true
node.data: true
node.attr.rack_id: m1

cluster.routing.allocation.awareness.attributes: rack_id

discovery.seed_hosts:
   - ev-crate02:4300
   - ev-crate03:4300
   - ev-crate00:4300
   - ev-crate01:4300
   - ev-crate04:4300

cluster.initial_master_nodes:
   - ev-crate02
   - ev-crate03
   - ev-crate00
   - ev-crate01
   - ev-crate04

gateway.expected_nodes: 5
gateway.recover_after_nodes: 3

auth.host_based.enabled: false

cluster.name: ev

stats.enabled: true

udc.enabled: false

psql.port: 5432

thread_pool.search.size: 50

lang.js.enabled: true

### Steps to Reproduce

I upgraded cratedb from 4.1.8 to 4.6.6 with full cluster restart.
After system starts I see errors in logs
```
[2022-01-17T14:52:54,041][WARN ][o.e.t.n.Netty4Transport  ] [ev-crate04] exception caught on transport layer [Netty4TcpChannel{localAddress=/10.17.65.10:4300, remoteAddress=/10.12.32.21:35068}], closing connection
io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: SSL/TLS request received but SSL/TLS is not enabled on this node, got (16,3,1,0)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.StreamCorruptedException: SSL/TLS request received but SSL/TLS is not enabled on this node, got (16,3,1,0)
	at org.elasticsearch.transport.TcpTransport.readHeaderBuffer(TcpTransport.java:796) ~[crate-server.jar:?]
	at org.elasticsearch.transport.TcpTransport.readMessageLength(TcpTransport.java:774) ~[crate-server.jar:?]
	at org.elasticsearch.transport.netty4.Netty4SizeHeaderFrameDecoder.decode(Netty4SizeHeaderFrameDecoder.java:45) ~[crate-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
```

Service log in attachment from test enviroment.[log.zip](https://github.com/crate/crate/files/7897057/log.zip)
On another nodes I see same errors - [log2.zip](https://github.com/crate/crate/files/7897151/log2.zip)

No load on cluster was at this moment.

I executes health check script `select /*healthcheck*/ * from sys.jobs where stmt not like '%/*healthcheck*/%'` 3 times per minute via `http://localhost:4200/_sql`. 
This scripts see error, and shut down node.
Health check log, as you can see - no load was on cluster.
```
    0 { End: 2022-01-19T14:55:49.282499159+03:00, ExitCode: 0, Output: Total SQL count = 0. OK , Start: 2022-01-19T14:55:48.871487682+03:00, $$hashKey: object:574207 }
    1 { End: 2022-01-19T14:56:04.729839455+03:00, ExitCode: 0, Output: Total SQL count = 0. OK , Start: 2022-01-19T14:56:04.287268863+03:00, $$hashKey: object:574208 }
    2 { End: 2022-01-19T14:56:20.104353366+03:00, ExitCode: 0, Output: Total SQL count = 0. OK , Start: 2022-01-19T14:56:19.733988086+03:00, $$hashKey: object:574209 }
    3 { End: 2022-01-19T14:56:40.137252422+03:00, ExitCode: -1, Output: Health check exceeded timeout (5s), Start: 2022-01-19T14:56:35.117520778+03:00, $$hashKey: object:574210 }
    4 { End: 2022-01-19T14:57:00.602902573+03:00, ExitCode: -1, Output: Health check exceeded timeout (5s), Star
```

### Expected Result

All works fine :)

### Actual Result

Nodes restarted by health check in random time.

**Comment by BaurzhanSakhariev** [comment]
Hi @shm-dmitry, thanks for your report.

Do you have `ssl.transport.mode` enabled on some nodes? This error might happen if some nodes have this setting enabled and some don't.

**Comment by shm-dmitry** [comment]
@BaurzhanSakhariev 
No.
Configuration file generated from same template and `ssl` disabled on all nodes.

**Comment by shm-dmitry** [comment]
@BaurzhanSakhariev , sorry for issue.
This is our security team scans network.
I saw errors on died node and I thinked - this is an error.
I will continue error investigating.
This issue can be closed.
