### ISSUE TITLE
"Can't handle Symbol" exception in subquery with DATE_BIN

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#12113]
### CrateDB version

4.7.0

### CrateDB setup information

Single-node local Docker container

### Steps to Reproduce

```sql
-- 1. create the table
CREATE TABLE sensor_readings (
   time TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 2. run this query on the empty table
SELECT *
FROM (
    SELECT DATE_BIN('5 minutes'::INTERVAL, "time", 0) AS ts_bin,
           ROW_NUMBER() OVER (PARTITION BY DATE_BIN('5 minutes'::INTERVAL, "time", 0) ORDER BY "time" ASC) AS "row_number"
    FROM "doc"."sensor_readings"
) x;
-- outcome: empty result set

-- 3. same query as before, but selecting ts_bin explicitly instead of using *
SELECT ts_bin
FROM (
    SELECT DATE_BIN('5 minutes'::INTERVAL, "time", 0) AS ts_bin,
           ROW_NUMBER() OVER (PARTITION BY DATE_BIN('5 minutes'::INTERVAL, "time", 0) ORDER BY "time" ASC) AS "row_number"
    FROM "doc"."sensor_readings"
) x;
-- outcome: UnsupportedFeatureException[Can't handle Symbol [Reference: time]]
```

### Expected Result

No exception, empty result set

### Actual Result

```
io.crate.exceptions.UnsupportedFeatureException: Can't handle Symbol [Reference: time]
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:141)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:128)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:116)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:79)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: Can't handle Symbol [Reference: time]
	at io.crate.expression.BaseImplementationSymbolVisitor.visitSymbol(BaseImplementationSymbolVisitor.java:100)
	at io.crate.expression.BaseImplementationSymbolVisitor.visitSymbol(BaseImplementationSymbolVisitor.java:42)
	at io.crate.expression.symbol.SymbolVisitor.visitReference(SymbolVisitor.java:38)
	at io.crate.metadata.Reference.accept(Reference.java:152)
	at io.crate.expression.InputFactory$Context.add(InputFactory.java:158)
	at io.crate.execution.engine.sort.Comparators.createComparatorWithEval(Comparators.java:75)
	at io.crate.execution.engine.sort.Comparators.createComparator(Comparators.java:60)
	at io.crate.execution.engine.window.WindowProjector.fromProjection(WindowProjector.java:135)
	at io.crate.execution.engine.pipeline.ProjectionToProjectorVisitor.visitWindowAgg(ProjectionToProjectorVisitor.java:685)
	at io.crate.execution.engine.pipeline.ProjectionToProjectorVisitor.visitWindowAgg(ProjectionToProjectorVisitor.java:127)
	at io.crate.execution.dsl.projection.WindowAggProjection.accept(WindowAggProjection.java:127)
	at io.crate.execution.dsl.projection.ProjectionVisitor.process(ProjectionVisitor.java:30)
	at io.crate.execution.engine.pipeline.ProjectionToProjectorVisitor.create(ProjectionToProjectorVisitor.java:705)
	at io.crate.execution.engine.pipeline.Projectors.<init>(Projectors.java:59)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterator(ShardCollectSource.java:249)
	at io.crate.execution.engine.collect.MapSideDataCollectOperation.createIterator(MapSideDataCollectOperation.java:58)
	at io.crate.execution.engine.collect.CollectTask.start(CollectTask.java:162)
	at io.crate.execution.jobs.RootTask.start(RootTask.java:191)
	at io.crate.execution.engine.JobLauncher.setupTasks(JobLauncher.java:240)
	at io.crate.execution.engine.JobLauncher.execute(JobLauncher.java:153)
	at io.crate.planner.operators.LogicalPlanner.executeNodeOpTree(LogicalPlanner.java:530)
	at io.crate.planner.operators.LogicalPlanner.doExecute(LogicalPlanner.java:481)
	at io.crate.planner.operators.LogicalPlanner.execute(LogicalPlanner.java:454)
	at io.crate.planner.operators.LogicalPlan.executeOrFail(LogicalPlan.java:220)
	at io.crate.planner.Plan.execute(Plan.java:73)
	at io.crate.action.sql.Session.singleExec(Session.java:679)
	at io.crate.action.sql.Session.execute(Session.java:474)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:259)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:206)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:115)
	... 43 more
```

**Comment by BaurzhanSakhariev** [comment]
Thanks for the report, will take a look
