### ISSUE TITLE
StackOverflowError causes crate to shutdown

### ISSUE THREAD

**Issue by bputt-e** [crate/crate#12227]
### CrateDB version

4.5.5

### CrateDB setup information

Num nodes: 31 (24 data nodes @ 16cpu/128gb)
Heap: 60GB for data node, 30GB for query node/ingest nodes

### Steps to Reproduce

Not sure how to reproduce, we had 2 data nodes that shutdown and the logs show a stackoverflow error

### Expected Result

Ideally crate doesn't shutdown

### Actual Result

Log output is attached

[crate-errr-log.txt](https://github.com/crate/crate/files/8262592/crate-errr-log.txt)

**Comment by jeeminso** [comment]
Thank you @bputt-e for taking your time to report this issue to Crate.

I was able to reproduce the error by streaming `Function` symbols between nodes with the latest nightly build as well. `ex) select * from t where concat('1',concat('2',concat('3'...`

```
Caused by: java.lang.StackOverflowError
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1453) ~[netty-buffer-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1440) ~[netty-buffer-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.75.Final.jar:4.1.75.Final]
	at org.elasticsearch.transport.netty4.ByteBufStreamInput.readByte(ByteBufStreamInput.java:170) ~[main/:?]
	at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:40) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readVInt(StreamInput.java:222) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readArraySize(StreamInput.java:1126) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:377) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readOptionalString(StreamInput.java:339) ~[main/:?]
	at io.crate.types.StringType.readValueFrom(StringType.java:282) ~[main/:?]
	at io.crate.types.StringType.readValueFrom(StringType.java:57) ~[main/:?]
	at io.crate.expression.symbol.Literal.<init>(Literal.java:84) ~[main/:?]
	at io.crate.expression.symbol.SymbolType.newInstance(SymbolType.java:72) ~[main/:?]
	at io.crate.expression.symbol.Symbols.fromStream(Symbols.java:159) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1069) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:1051) ~[main/:?]
	at io.crate.expression.symbol.Symbols.listFromStream(Symbols.java:146) ~[main/:?]
	at io.crate.expression.symbol.Function.<init>(Function.java:95) ~[main/:?]
	at io.crate.expression.symbol.SymbolType.newInstance(SymbolType.java:72) ~[main/:?]
	at io.crate.expression.symbol.Symbols.fromStream(Symbols.java:159) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1069) ~[main/:?]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:1051) ~[main/:?]
	at io.crate.expression.symbol.Symbols.listFromStream(Symbols.java:146) ~[main/:?]
	at io.crate.expression.symbol.Function.<init>(Function.java:95) ~[main/:?]
```

Please confirm that you have such usecases with a large nested function calls. If so, a quick workaround would be to increase the stack size.

**Comment by bputt-e** [comment]
I can't think of anything special we're doing that deals with a large number of possible values other than:

```
SELECT (CASE WHEN)....could be <100 values to choose from (our way of bucketing values into groups)

WHERE mytextcol in ('....', ....could be thousands of values passed in)
```

**Comment by mfussenegger** [comment]
Could you post a larger example of your `CASE` statement? Currently we normalize `CASE` statements to a stree structure for each condition. We may be able to flatten the representation to avoid  the StackOverflow

**Comment by mfussenegger** [comment]
Closing this in favour of https://github.com/crate/crate/issues/12674
