### ISSUE TITLE
A tale of a partioned table, multiple dynamic objects, nested objects, adding columns and a SQLParseException

### ISSUE THREAD

**Issue by jayeff** [crate/crate#12630]
### CrateDB version

4.8.1

### Steps to Reproduce

1. (Once upon a time...) We first created a table:

```
CREATE TABLE IF NOT EXISTS "doc"."testing" (
   "p1" text,
   "nested" OBJECT(DYNAMIC) AS (
      "sub1" OBJECT(DYNAMIC) AS (
         "sub2" BIGINT
        )
   ),
   "obj" OBJECT(DYNAMIC)
) PARTITIONED BY ("p1");
```

From my testing so far it seems to be important that table is partioned and it has nested object with at least one defined column (here: `nested['sub1']['sub2']`)

2. Insert new record with dynamic new column for `obj`:

```
INSERT INTO "doc"."testing" ("p1", "obj") VALUES ('a',  '{"new": 1}');
-- INSERT OK
```

3. Now add a new column for `obj` explicitly:

```
ALTER TABLE testing ADD COLUMN "obj"['added'] TEXT;
-- ALTER OK
```

4. Finally let's add another record with new column for `obj`:

```
INSERT INTO "doc"."testing" ("p1", "obj") VALUES ('a',  '{"newer": 1}');
-- SQLParseException[Can't overwrite default.properties.obj.position=5 with 4]
```

According to my testing this ordering (add dynamic column, alter table, another dynamic column) is important here. If you e.g. `ALTER TABLE ADD COLUMN` first adding subsequent dynamic columns works fine.

### Expected Result

`INSERT OK`

### Actual Result

`SQLParseException[Can't overwrite default.properties.obj.position=5 with 4]`

<details>
<summary>Stack trace</summary>

```
io.crate.exceptions.SQLParseException: Can't overwrite default.properties.obj.position=5 with 4
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:163)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:152)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.crate.rest.action.RestRowCountReceiver.fail(RestRowCountReceiver.java:84)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:58)
	at io.crate.planner.operators.InsertFromValues.lambda$execute$1(InsertFromValues.java:302)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.crate.planner.operators.InsertFromValues.lambda$execute$9(InsertFromValues.java:665)
	at io.crate.planner.operators.InsertFromValues$1.onResponse(InsertFromValues.java:703)
	at io.crate.planner.operators.InsertFromValues$1.onResponse(InsertFromValues.java:690)
	at io.crate.execution.support.RetryListener.onResponse(RetryListener.java:57)
	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$3(ActionListener.java:177)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:44)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishOnSuccess(TransportReplicationAction.java:844)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:767)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:753)
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleResponse(TransportService.java:1001)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1080)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1060)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:47)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:30)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$runWithPrimaryShardReference$2(TransportReplicationAction.java:415)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:66)
	at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:163)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:66)
	at org.elasticsearch.action.support.replication.ReplicationOperation.finish(ReplicationOperation.java:351)
	at org.elasticsearch.action.support.replication.ReplicationOperation.decPendingAndFinishIfNeeded(ReplicationOperation.java:332)
	at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:162)
	at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:154)
	at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult$1.onSuccess(TransportWriteAction.java:172)
	at org.elasticsearch.action.support.replication.TransportWriteAction$AsyncAfterWriteAction.maybeFinish(TransportWriteAction.java:293)
	at org.elasticsearch.action.support.replication.TransportWriteAction$AsyncAfterWriteAction.run(TransportWriteAction.java:307)
	at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.runPostReplicationActions(TransportWriteAction.java:179)
	at org.elasticsearch.action.support.replication.ReplicationOperation.handlePrimaryResult(ReplicationOperation.java:154)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:66)
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:235)
	at io.crate.execution.dml.TransportShardAction.shardOperationOnPrimary(TransportShardAction.java:114)
	at io.crate.execution.dml.TransportShardAction.shardOperationOnPrimary(TransportShardAction.java:63)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:921)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:126)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:422)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:340)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:66)
	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$21(IndexShard.java:2719)
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:93)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:296)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:246)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2693)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:862)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:336)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:302)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:59)
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:663)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Can't overwrite default.properties.obj.position=5 with 4
	at io.crate.execution.ddl.TransportSchemaUpdateAction.mergeIntoSource(TransportSchemaUpdateAction.java:233)
	at io.crate.execution.ddl.TransportSchemaUpdateAction.mergeIntoSource(TransportSchemaUpdateAction.java:225)
	at io.crate.execution.ddl.TransportSchemaUpdateAction.mergeIntoSource(TransportSchemaUpdateAction.java:225)
	at io.crate.execution.ddl.TransportSchemaUpdateAction.mergeIntoSource(TransportSchemaUpdateAction.java:225)
	at io.crate.execution.ddl.TransportSchemaUpdateAction.mergeIntoSource(TransportSchemaUpdateAction.java:214)
	at io.crate.execution.ddl.TransportSchemaUpdateAction.updateTemplate(TransportSchemaUpdateAction.java:204)
	at io.crate.execution.ddl.TransportSchemaUpdateAction$1.execute(TransportSchemaUpdateAction.java:164)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:701)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:318)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:213)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:153)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:191)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
	... 3 more
```
</details>

Maybe noteworthy too: After step 3 `ALTER TABLE ADD COLUMN` queries on `obj IS NOT null` will fail as well with error "NullPointerException[Cannot invoke "io.crate.metadata.Reference.column()" because "ref" is null]" <details>
<summary>Stack trace</summary>
```
java.lang.NullPointerException: Cannot invoke "io.crate.metadata.Reference.column()" because "ref" is null
	at io.crate.expression.predicate.IsNullPredicate.refExistsQuery(IsNullPredicate.java:130)
	at io.crate.expression.predicate.IsNullPredicate.refExistsQuery(IsNullPredicate.java:149)
	at io.crate.expression.predicate.NotPredicate.toQuery(NotPredicate.java:196)
	at io.crate.lucene.LuceneQueryBuilder$Visitor.visitFunction(LuceneQueryBuilder.java:248)
	at io.crate.lucene.LuceneQueryBuilder$Visitor.visitFunction(LuceneQueryBuilder.java:231)
	at io.crate.expression.symbol.Function.accept(Function.java:240)
	at io.crate.lucene.LuceneQueryBuilder.convert(LuceneQueryBuilder.java:121)
	at io.crate.execution.engine.collect.LuceneShardCollectorProvider.getUnorderedIterator(LuceneShardCollectorProvider.java:147)
	at io.crate.execution.engine.collect.ShardCollectorProvider.getIterator(ShardCollectorProvider.java:150)
	at io.crate.execution.engine.collect.ShardCollectorProvider.lambda$getFutureIterator$2(ShardCollectorProvider.java:118)
	at org.elasticsearch.index.shard.IndexShard.awaitShardSearchActive(IndexShard.java:3254)
	at io.crate.execution.engine.collect.ShardCollectorProvider.getFutureIterator(ShardCollectorProvider.java:116)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterators(ShardCollectSource.java:411)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterator(ShardCollectSource.java:275)
	at io.crate.execution.engine.collect.MapSideDataCollectOperation.createIterator(MapSideDataCollectOperation.java:58)
	at io.crate.execution.engine.collect.CollectTask.start(CollectTask.java:162)
	at io.crate.execution.jobs.RootTask.start(RootTask.java:191)
	at io.crate.execution.engine.JobLauncher.setupTasks(JobLauncher.java:255)
	at io.crate.execution.engine.JobLauncher.execute(JobLauncher.java:168)
	at io.crate.planner.operators.LogicalPlanner.executeNodeOpTree(LogicalPlanner.java:534)
	at io.crate.planner.operators.LogicalPlanner.doExecute(LogicalPlanner.java:485)
	at io.crate.planner.operators.LogicalPlanner.execute(LogicalPlanner.java:458)
	at io.crate.planner.operators.LogicalPlan.executeOrFail(LogicalPlan.java:220)
	at io.crate.planner.Plan.execute(Plan.java:73)
	at io.crate.action.sql.Session.singleExec(Session.java:676)
	at io.crate.action.sql.Session.execute(Session.java:471)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:259)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:206)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:115)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:79)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by jeeminso** [comment]
Thanks for reporting @jayeff, @amotl. The NPE issue seems to be independent of the column positions issue I have been tracking.

In summary, the first `select * from tbl where xo is null` will generate `LuceneShardCollectorProvider` and the second `select * from tbl where xo is null` will re-use the same `LuceneShardCollectorProvider` containing outdated `DocTableInfo` that is missing `foo`.

**Comment by amotl** [comment]
Thanks for your response, Minsoo. In this case, I will create a different issue from my report and your answer and will delete the corresponding comments afterwards.
