### ISSUE TITLE
io.crate.protocols.postgres.BindPostgresException: Failed to bind to [5432-5532]

### ISSUE THREAD

**Issue by sayalithange** [crate/crate#12736]
### CrateDB version

4.5.1

### CrateDB setup information

cluster.name: xyz
node.name: "xyz"
network.bind_host: xyz
network.publish_host: xyz
network.host: xyz
udc.enabled: false
path.data: /opt/crate_data
auth.host_based.enabled: false

Others are all default settings

### Steps to Reproduce

Note : There are no processes running on the port.

Unable to start the crate itself. Getting an exception : 

io.crate.protocols.postgres.BindPostgresException: Failed to bind to [5432-5532]
	at io.crate.protocols.postgres.PostgresNetty.bindAddress(PostgresNetty.java:245) ~[crate-server.jar:?]
	at io.crate.protocols.postgres.PostgresNetty.resolveBindAddress(PostgresNetty.java:212) ~[crate-server.jar:?]
	at io.crate.protocols.postgres.PostgresNetty.doStart(PostgresNetty.java:174) ~[crate-server.jar:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:60) ~[crate-server.jar:?]
	at org.elasticsearch.node.Node.start(Node.java:825) ~[crate-server.jar:?]
	at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:204) ~[crate-app.jar:4.7.1]
	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:268) [crate-app.jar:4.7.1]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:158) [crate-app.jar:4.7.1]
	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:138) [crate-app.jar:4.7.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) [crate-server.jar:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [crate-cli.jar:?]
	at org.elasticsearch.cli.Command.main(Command.java:90) [crate-cli.jar:?]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:91) [crate-app.jar:4.7.1]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) [crate-app.jar:4.7.1]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Cannot assign requested address
[2022-07-11T17:44:17,364][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [xyz] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: io.crate.protocols.postgres.BindPostgresException: Failed to bind to [5432-5532]
	at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:30) ~[crate-app.jar:4.7.1]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:162) ~[crate-app.jar:4.7.1]
	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:138) ~[crate-app.jar:4.7.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) ~[crate-server.jar:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[crate-cli.jar:?]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[crate-cli.jar:?]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:91) ~[crate-app.jar:4.7.1]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) ~[crate-app.jar:4.7.1]
Caused by: io.crate.protocols.postgres.BindPostgresException: Failed to bind to [5432-5532]
	at io.crate.protocols.postgres.PostgresNetty.bindAddress(PostgresNetty.java:245) ~[crate-server.jar:?]
	at io.crate.protocols.postgres.PostgresNetty.resolveBindAddress(PostgresNetty.java:212) ~[crate-server.jar:?]
	at io.crate.protocols.postgres.PostgresNetty.doStart(PostgresNetty.java:174) ~[crate-server.jar:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:60) ~[crate-server.jar:?]
	at org.elasticsearch.node.Node.start(Node.java:825) ~[crate-server.jar:?]
	at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:204) ~[crate-app.jar:4.7.1]
	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:268) ~[crate-app.jar:4.7.1]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:158) ~[crate-app.jar:4.7.1]

### Expected Result

crate should start smoothly.

### Actual Result

Getting an exception

**Comment by proddata** [comment]
I will close this for now.
