### ISSUE TITLE
`SQLParseException` when using sub select on an array

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13003]
### CrateDB version

5.0.1

### Steps to Reproduce

Below are minimal reproducible steps from a scenario reported by a CrateDB user to the Customer Engineering team:
1. Create tables:
   ```sql
   CREATE TABLE IF NOT EXISTS "doc"."t1" (
      "a" INTEGER
   );

   CREATE TABLE IF NOT EXISTS "doc"."t2" (
      "b" INTEGER
   );

   CREATE TABLE IF NOT EXISTS "doc"."t3" (
      "a" INTEGER,
      "b" ARRAY(INTEGER)
   );
   ```
2. Run the query:
   ```sql
   SELECT *
   FROM t1
   LEFT JOIN t3 USING (a)
   WHERE t3.b[1] IN (SELECT b FROM t2);
   ```
   Note: I'm aware doing a `LEFT JOIN` and then a `WHERE` condition on the joined relation makes it effectively an `INNER JOIN`. The error does not occur when changing `LEFT JOIN` to `JOIN`.

### Expected Result

No `SQLParseException`.

### Actual Result

```
io.crate.exceptions.SQLParseException: Couldn't resolve value for subQuery: (SELECT b FROM (doc.t2))
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:163)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:152)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:116)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:79)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Couldn't resolve value for subQuery: (SELECT b FROM (doc.t2))
	at io.crate.planner.operators.SubQueryResults.getSafe(SubQueryResults.java:42)
	at io.crate.analyze.SymbolEvaluator.visitSelectSymbol(SymbolEvaluator.java:86)
	at io.crate.analyze.SymbolEvaluator.visitSelectSymbol(SymbolEvaluator.java:48)
	at io.crate.expression.symbol.SelectSymbol.accept(SelectSymbol.java:68)
	at io.crate.expression.BaseImplementationSymbolVisitor.visitFunction(BaseImplementationSymbolVisitor.java:64)
	at io.crate.expression.BaseImplementationSymbolVisitor.visitFunction(BaseImplementationSymbolVisitor.java:42)
	at io.crate.expression.symbol.Function.accept(Function.java:184)
	at io.crate.planner.optimizer.rule.RewriteFilterOnOuterJoinToInnerJoin.couldMatchOnNull(RewriteFilterOnOuterJoinToInnerJoin.java:281)
	at io.crate.planner.optimizer.rule.RewriteFilterOnOuterJoinToInnerJoin.apply(RewriteFilterOnOuterJoinToInnerJoin.java:164)
	at io.crate.planner.optimizer.rule.RewriteFilterOnOuterJoinToInnerJoin.apply(RewriteFilterOnOuterJoinToInnerJoin.java:105)
	at io.crate.planner.optimizer.Optimizer.tryApplyRules(Optimizer.java:108)
	at io.crate.planner.optimizer.Optimizer.optimize(Optimizer.java:59)
	at io.crate.planner.optimizer.Optimizer.lambda$optimize$0(Optimizer.java:60)
	at io.crate.common.collections.Lists2.mapIfChange(Lists2.java:110)
	at io.crate.planner.optimizer.Optimizer.optimize(Optimizer.java:60)
	at io.crate.planner.optimizer.Optimizer.lambda$optimize$0(Optimizer.java:60)
	at io.crate.common.collections.Lists2.mapIfChange(Lists2.java:110)
	at io.crate.planner.optimizer.Optimizer.optimize(Optimizer.java:60)
	at io.crate.planner.operators.LogicalPlanner.plan(LogicalPlanner.java:234)
	at io.crate.planner.operators.LogicalPlanner$Visitor.visitSelectStatement(LogicalPlanner.java:550)
	at io.crate.planner.operators.LogicalPlanner$Visitor.visitSelectStatement(LogicalPlanner.java:539)
	at io.crate.analyze.relations.AnalyzedRelation.accept(AnalyzedRelation.java:114)
	at io.crate.planner.operators.LogicalPlanner.plan(LogicalPlanner.java:168)
	at io.crate.planner.Planner.visitSelectStatement(Planner.java:242)
	at io.crate.planner.Planner.visitSelectStatement(Planner.java:152)
	at io.crate.analyze.relations.AnalyzedRelation.accept(AnalyzedRelation.java:114)
	at io.crate.planner.Planner.plan(Planner.java:216)
	at io.crate.action.sql.Session.singleExec(Session.java:645)
	at io.crate.action.sql.Session.execute(Session.java:471)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:259)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:206)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:115)
	... 45 more
```

**Comment by echarlus** [comment]
@hammerhead thanks for reporting this. FYI the issue is also present on 4.x versions (at least 4.8.3)

**Comment by seut** [comment]
@hammerhead We can reproduce this and are working on a fix. Thank you for reporting.

**Comment by matriv** [comment]
@hammerhead As a workaround the query can be written as:
```sql
SELECT *
FROM t1
LEFT JOIN t3 USING (a)
INNER JOIN t2 ON t3.b[1] = t2.b
```
