### ISSUE TITLE
class_cast_exception in query with ORDER BY against partitioned table with replicas

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13166]
### CrateDB version

5.0.2

### CrateDB setup information

2 nodes cluster in k8s
resources: limits: memory: 3072Mi
CRATE_HEAP_SIZE --> 768m

### Steps to Reproduce

0.- Setup a cluster (I have been unable to reproduce this without replicas)
1.- Create a table as follows
`CREATE TABLE repro1 ("timestamp" BIGINT,"txt1" TEXT,
   "month" TIMESTAMP WITH TIME ZONE GENERATED ALWAYS AS date_trunc('month', "timestamp")
) CLUSTERED INTO 4 SHARDS PARTITIONED BY ("month")`
2.- Insert 231 records of random data (could not reproduce with smaller number of records) - the data being random it will span multiple partitions
`cr8 insert-fake-data --hosts ....:4200 --table doc.repro1 --num-records 231`
3.- Wait until `SELECT COUNT(*) FROM repro1` returns 231 (but proceed while there are still underreplicated shards)
4.- Run this query
`SELECT _id ,txt1 FROM repro1 ORDER BY txt1 ASC LIMIT 500;`
`-- it works without ORDER BY or with LIMIT 100`

### Expected Result

231 records returned

### Actual Result

The query succeeds sometimes, but just retrying it a couple of times is sufficient to receive the error trace below.
Once all shards are fully replicated the error mutates permanently to a CircuitBreakingException[[query] Data too large, this again only happens when `ORDER BY` is used, the estimated memory requirement seems to always be the region of 462mb regardless of the amount of shards/records in the test. The actual amount of data is around 1 MB.

> `org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: class_cast_exception: class org.apache.lucene.util.BytesRef cannot be cast to class java.lang.String (org.apache.lucene.util.BytesRef is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')`

```java
org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: class_cast_exception: class org.apache.lucene.util.BytesRef cannot be cast to class java.lang.String (org.apache.lucene.util.BytesRef is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at io.crate.types.StringType$1.rangeQuery(StringType.java:68)
	at io.crate.execution.engine.collect.collectors.OptimizeQueryForSearchAfter.apply(OptimizeQueryForSearchAfter.java:101)
	at io.crate.execution.engine.collect.collectors.OptimizeQueryForSearchAfter.apply(OptimizeQueryForSearchAfter.java:42)
	at io.crate.execution.engine.collect.collectors.LuceneOrderedDocCollector.query(LuceneOrderedDocCollector.java:215)
	at io.crate.execution.engine.collect.collectors.LuceneOrderedDocCollector.searchMore(LuceneOrderedDocCollector.java:187)
	at io.crate.execution.engine.collect.collectors.LuceneOrderedDocCollector.collect(LuceneOrderedDocCollector.java:137)
	at io.crate.execution.engine.collect.collectors.OrderedDocCollector.get(OrderedDocCollector.java:82)
	at io.crate.execution.engine.collect.collectors.OrderedLuceneBatchIteratorFactory$Factory.loadFrom(OrderedLuceneBatchIteratorFactory.java:127)
	at io.crate.execution.engine.collect.collectors.OrderedLuceneBatchIteratorFactory$Factory.tryFetchMore(OrderedLuceneBatchIteratorFactory.java:120)
	at io.crate.execution.engine.distribution.merge.BatchPagingIterator.loadNextBatch(BatchPagingIterator.java:116)
	at io.crate.data.MappedForwardingBatchIterator.loadNextBatch(MappedForwardingBatchIterator.java:51)
	at io.crate.data.LimitingBatchIterator.loadNextBatch(LimitingBatchIterator.java:69)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:69)
	at io.crate.data.BatchIterators.lambda$collect$0(BatchIterators.java:71)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by matriv** [comment]
Was able to reproduce it with a docker cluster locally, will debug to get to the cause.
