### ISSUE TITLE
`SQLParseException` in nested `OBJECT` structures with same names but different data types

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13372]
### CrateDB version

5.1.2 (not reproducible on 4.6.6)

### Steps to Reproduce

1. Create this table:
   ```sql
   CREATE TABLE IF NOT EXISTS "t1" (
     "obj1" OBJECT(DYNAMIC) AS (
      "target" text,
      "obj2" OBJECT(DYNAMIC) AS (
         "target" REAL
      )
     )
   );
   ```
2. Insert a row: `INSERT INTO t1 VALUES ('{"obj2": null, "target": "Sensor"}');`
3. Query the table: `SELECT * FROM t1`

### Expected Result

One row is returned.

### Actual Result

```
io.crate.exceptions.SQLParseException: For input string: "Sensor"
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:162)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:151)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:164)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:120)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:87)
	at io.crate.protocols.postgres.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:114)
	at io.crate.action.sql.RowConsumerToResultReceiver.lambda$consumeIt$1(RowConsumerToResultReceiver.java:101)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:52)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:56)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:39)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:52)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:62)
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleException(TransportService.java:1022)
	at org.elasticsearch.transport.InboundHandler$2.doRun(InboundHandler.java:237)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutor.execute(EsExecutors.java:161)
	at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:232)
	at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:224)
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:112)
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:80)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:687)
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:70)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "Sensor"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:476)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.floatValue(AbstractXContentParser.java:205)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.floatValue(AbstractXContentParser.java:197)
	at io.crate.expression.reference.doc.lucene.SourceParser.parseByType(SourceParser.java:196)
	at io.crate.expression.reference.doc.lucene.SourceParser.parseValue(SourceParser.java:173)
	at io.crate.expression.reference.doc.lucene.SourceParser.parseObject(SourceParser.java:151)
	at io.crate.expression.reference.doc.lucene.SourceParser.parseObject(SourceParser.java:149)
	at io.crate.expression.reference.doc.lucene.SourceParser.parseObject(SourceParser.java:149)
	at io.crate.expression.reference.doc.lucene.SourceParser.parse(SourceParser.java:108)
	at io.crate.expression.reference.doc.lucene.SourceLookup.ensureSourceParsed(SourceLookup.java:80)
	at io.crate.expression.reference.doc.lucene.SourceLookup.get(SourceLookup.java:63)
	at io.crate.expression.reference.doc.lucene.DocCollectorExpression$ChildDocCollectorExpression.value(DocCollectorExpression.java:98)
	at io.crate.expression.InputRow.get(InputRow.java:45)
	at io.crate.execution.engine.distribution.StreamBucket$Builder.add(StreamBucket.java:75)
	at io.crate.execution.engine.fetch.FetchCollector.collect(FetchCollector.java:104)
	at io.crate.execution.engine.fetch.NodeFetchOperation.lambda$doFetch$3(NodeFetchOperation.java:193)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by proddata** [comment]
```sql
SELECT _raw FROM doc.t1;
-- _raw
-- {"obj1":{"obj2":null,"target":"Sensor"}}
```

**Comment by proddata** [comment]
@BaurzhanSakhariev seems to be a regression from `5.1.0` to `5.1.1`

**Comment by BaurzhanSakhariev** [comment]
Thanks for reporting, fix is being prepared in https://github.com/crate/crate/pull/13379

This is not only same name related issue, but combination of same name + null value of an object:

1. null value but **different** name works
```
CREATE TABLE IF NOT EXISTS "t1" (  
  "obj1" OBJECT(DYNAMIC) AS (  
    "text_target" text,  
      "obj2" OBJECT(DYNAMIC) AS (  
         "real_target" REAL  
      )  
    )  
);   

cr> INSERT INTO t1 VALUES ('{"obj2": null, "text_target": "Sensor"}');                                                                                                                                                                  
INSERT OK, 1 row affected  (0.047 sec)
cr> SELECT * FROM t1;                                                                                                                                                                                                                   
+-------------------------------------+
| obj1                                |
+-------------------------------------+
| {"obj2": {"text_target": "Sensor"}} |
+-------------------------------------+
SELECT 1 row in set (0.002 sec)
```

2. same name but not-null value works as well
```
CREATE TABLE IF NOT EXISTS "t1" ( 
      "obj1" OBJECT(DYNAMIC) AS ( 
       "target" text, 
       "obj2" OBJECT(DYNAMIC) AS ( 
          "target" REAL 
       ) 
      ) 
    );    
cr> INSERT INTO t1 VALUES ('{"obj2": {"target": "5.0"}, "target": "Sensor"}');                                                                                                                                                          
INSERT OK, 1 row affected  (0.047 sec)
cr> select * from t1;                                                                                                                                                                                                                   
+-----------------------------------------------+
| obj1                                          |
+-----------------------------------------------+
| {"obj2": {"target": 5.0}, "target": "Sensor"} |
+-----------------------------------------------+
SELECT 1 row in set (0.240 sec)
```
