### ISSUE TITLE
`StartupException` after swapping tables

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13380]
### CrateDB version

5.1.2

### Steps to Reproduce

1. Create the two tables:
   ```sql
    CREATE TABLE IF NOT EXISTS "telegraf"."metrics" (
       "hash_id" BIGINT INDEX OFF,
       "timestamp" TIMESTAMP WITH TIME ZONE,
       "name" TEXT,
       "fields" OBJECT(DYNAMIC) AS (
          "message" TEXT
       ),
       "year" TIMESTAMP WITH TIME ZONE GENERATED ALWAYS AS date_trunc('year', "timestamp")
    )
    CLUSTERED INTO 6 SHARDS
    PARTITIONED BY ("year");
    
    CREATE TABLE IF NOT EXISTS "telegraf"."metrics_new" (
       "hash_id" BIGINT INDEX OFF,
       "timestamp" TIMESTAMP WITH TIME ZONE,
       "name" TEXT,
       "fields" OBJECT(DYNAMIC) AS (
          "facility_code" BIGINT,
          "message" TEXT INDEX using fulltext
       ),
       "year" TIMESTAMP WITH TIME ZONE GENERATED ALWAYS AS date_trunc('year', "timestamp")
    )
    CLUSTERED INTO 6 SHARDS
    PARTITIONED BY ("year");
2. Insert some data: `cr8 insert-fake-data --hosts "http://localhost:4200" --table telegraf.metrics_new -n 3 && cr8 insert-fake-data --hosts "http://localhost:4200" --table telegraf.metrics -n 90000`
3. Refresh tables: `REFRESH TABLE telegraf.metrics; REFRESH TABLE telegraf.metrics_new`
4. Swap the tables: `ALTER CLUSTER SWAP TABLE "telegraf"."metrics_new" TO "telegraf.metrics";` (note the particularity regarding quoting here: `TO "telegraf.metrics"` instead of `TO "telegraf"."metrics"`)

### Expected Result

Successful execution

### Actual Result

After restarting the node, it doesn't come up again:
```
2022-12-15 16:32:45 org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Invalid index name: partitioned
2022-12-15 16:32:45     at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:30) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45     at io.crate.bootstrap.CrateDB.init(CrateDB.java:162) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45     at io.crate.bootstrap.CrateDB.execute(CrateDB.java:138) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45     at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) ~[crate-server.jar:?]
2022-12-15 16:32:45     at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[crate-cli.jar:?]
2022-12-15 16:32:45     at org.elasticsearch.cli.Command.main(Command.java:90) ~[crate-cli.jar:?]
2022-12-15 16:32:45     at io.crate.bootstrap.CrateDB.main(CrateDB.java:91) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45     at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45 Caused by: java.lang.IllegalArgumentException: Invalid index name: partitioned
2022-12-15 16:32:45     at io.crate.metadata.IndexParts.assertEmpty(IndexParts.java:196) ~[crate-server.jar:?]
2022-12-15 16:32:45     at io.crate.metadata.IndexParts.<init>(IndexParts.java:86) ~[crate-server.jar:?]
2022-12-15 16:32:45     at io.crate.metadata.IndexParts.<init>(IndexParts.java:51) ~[crate-server.jar:?]
2022-12-15 16:32:45     at io.crate.metadata.PartitionName.fromIndexOrTemplate(PartitionName.java:227) ~[crate-server.jar:?]
2022-12-15 16:32:45     at io.crate.metadata.PartitionName.templateName(PartitionName.java:66) ~[crate-server.jar:?]
2022-12-15 16:32:45     at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadata(GatewayMetaState.java:236) ~[crate-server.jar:?]
2022-12-15 16:32:45     at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:199) ~[crate-server.jar:?]
2022-12-15 16:32:45     at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:133) ~[crate-server.jar:?]
2022-12-15 16:32:45     at org.elasticsearch.node.Node.start(Node.java:926) ~[crate-server.jar:?]
2022-12-15 16:32:45     at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:204) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45     at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:268) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45     at io.crate.bootstrap.CrateDB.init(CrateDB.java:158) ~[crate-app.jar:5.1.2]
2022-12-15 16:32:45     ... 6 more
```

**Comment by hlcianfagna** [comment]
Following the repro steps ```doc."telegraf.metrics"``` (table with . in the name) is accessible to me, but it is not shown in http://localhost:4200/#!/tables

**Comment by hammerhead** [comment]
Updated the description, I was missing partitioning on the second table. Now, the node crashes and doesn't restart any more.

**Comment by jeeminso** [comment]
Had a quick look, `"telegraf.metrics"` is resolved to `doc.telegraf.metrics` (which should not exist) that is why there was no exception from `swap table` statement.

**Comment by jeeminso** [comment]
The `startupException` and metadata recovery are handled by https://github.com/crate/crate/pull/13404, closing.
