### ISSUE TITLE
NullPointerException when JOINing view with aliased column

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13414]
### CrateDB version

5.2.0 -SNAPSHOT-9962f28

### CrateDB setup information

Single node started with 
docker run --publish 4200:4200 --publish 5432:5432 crate/crate:nightly-5.2.0 -Cdiscovery.type=single-node

### Steps to Reproduce

```sql
CREATE TABLE test1 (testid INTEGER,category INTEGER);

INSERT INTO test1 (	testid	,category	)
VALUES (	1	,1	)	,(	2	,2	);

CREATE TABLE testcategories (	category INTEGER	,description TEXT	);

INSERT INTO testcategories VALUES (	1	,'a'	)	,(	2	,'b'	);

CREATE VIEW vw_test AS
SELECT test1.testid
	,testcategories.category AS aliasedcategoryid
	,testcategories.description
FROM test1
INNER JOIN testcategories ON test1.category = testcategories.category;

SELECT *
FROM GENERATE_SERIES(1, 2)
CROSS JOIN vw_test;
```

### Expected Result

4 rows (works in postgresql)

### Actual Result

```
java.lang.NullPointerException: Mapping must exist for output from source. `category` is missing in {_fetchid=_fetchid, _fetchid=_fetchid, description=description, category AS aliasedcategoryid=aliasedcategoryid, testid=testid}
	at java.base/java.util.Objects.requireNonNull(Objects.java:360)
	at io.crate.planner.operators.Rename.rewriteToFetch(Rename.java:163)
	at io.crate.planner.operators.NestedLoopJoin.rewriteToFetch(NestedLoopJoin.java:335)
	at io.crate.planner.optimizer.rule.RewriteToQueryThenFetch.apply(RewriteToQueryThenFetch.java:85)
	at io.crate.planner.optimizer.rule.RewriteToQueryThenFetch.apply(RewriteToQueryThenFetch.java:53)
	at io.crate.planner.optimizer.Optimizer.tryApplyRules(Optimizer.java:109)
	at io.crate.planner.optimizer.Optimizer.optimize(Optimizer.java:60)
	at io.crate.planner.operators.LogicalPlanner.plan(LogicalPlanner.java:253)
	at io.crate.planner.operators.LogicalPlanner$Visitor.visitSelectStatement(LogicalPlanner.java:579)
	at io.crate.planner.operators.LogicalPlanner$Visitor.visitSelectStatement(LogicalPlanner.java:568)
	at io.crate.analyze.relations.AnalyzedRelation.accept(AnalyzedRelation.java:114)
	at io.crate.planner.operators.LogicalPlanner.plan(LogicalPlanner.java:167)
	at io.crate.planner.Planner.visitSelectStatement(Planner.java:245)
	at io.crate.planner.Planner.visitSelectStatement(Planner.java:155)
	at io.crate.analyze.relations.AnalyzedRelation.accept(AnalyzedRelation.java:114)
	at io.crate.planner.Planner.plan(Planner.java:219)
	at io.crate.action.sql.Session.singleExec(Session.java:693)
	at io.crate.action.sql.Session.execute(Session.java:507)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:261)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:208)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:117)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:81)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by BaurzhanSakhariev** [comment]
Hi @hlcianfagna, thanks for reporting the issue!

Do you use AdminUI?  

When I connect via `crash` query works fine and fails in AdminUI because it adds `LIMIT`  clause at the end.

Looks like issue happens only when both `AS` and `LIMIT` are used. Otherwise query works if I remove either of them.

**Comment by hlcianfagna** [comment]
You are right, I was testing this from the AdminUI, I see now the issue only occurs when `LIMIT` is also used.
