### ISSUE TITLE
`IndexOutOfBoundsException` on `FETCH BACKWARD` beyond the beginning of a cursor

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#13455]
### CrateDB version

5.2.0-SNAPSHOT-519ef38

### Steps to Reproduce

Reporting this on behalf of @marijaselakovic and @hlcianfagna:

```sql
cr> create table testcursor (a int);                                                                                                        
CREATE OK, 1 row affected  (0.320 sec)
cr> insert into testcursor select * from generate_series(1, 10000000);                                                                      
INSERT OK, 10000000 rows affected  (54.849 sec)
cr> BEGIN; 
                                                                                                                                            
BEGIN OK, 0 rows affected  (0.001 sec)
cr> DECLARE order_cursor SCROLL CURSOR FOR select * from testcursor order by a;                                                            
DECLARE OK, 0 rows affected  (1.254 sec)
cr> FETCH BACKWARD FROM order_cursor;                                                                                                      
IndexOutOfBoundsException[fromIndex = -2]
cr> FETCH FORWARD FROM order_cursor;                                                                                                       
+---+
| a |
+---+
| 1 |
+---+
FETCH 1 row in set (0.873 sec)
cr> FETCH FORWARD FROM order_cursor;                                                                                                       
+---+
| a |
+---+
| 2 |
+---+
FETCH 1 row in set (0.001 sec)
cr> FETCH FORWARD FROM order_cursor;                                                                                                       
+---+
| a |
+---+
| 3 |
+---+
FETCH 1 row in set (0.001 sec)
cr> FETCH BACKWARD FROM order_cursor;                                                                                                      
+---+
| a |
+---+
| 2 |
+---+
FETCH 1 row in set (0.002 sec)
cr> FETCH BACKWARD FROM order_cursor;                                                                                                      
+---+
| a |
+---+
| 1 |
+---+
FETCH 1 row in set (0.000 sec)
cr> FETCH BACKWARD FROM order_cursor;                                                                                                      
IndexOutOfBoundsException[fromIndex = -1]
```

### Expected Result

No exception

### Actual Result

```
java.lang.IndexOutOfBoundsException: fromIndex = -2
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at io.crate.action.sql.Cursor.triggerConsumer(Cursor.java:208)
	at io.crate.action.sql.Cursor.fetch(Cursor.java:88)
	at io.crate.planner.FetchPlan.executeOrFail(FetchPlan.java:50)
	at io.crate.planner.Plan.execute(Plan.java:73)
	at io.crate.action.sql.Session.singleExec(Session.java:724)
	at io.crate.action.sql.Session.execute(Session.java:507)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:261)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:208)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:117)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:81)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by hlcianfagna** [comment]
In PostgreSQL the behavior is as follows:

```
DECLARE order_cursor SCROLL CURSOR FOR select * from testcursor order by a   ;
FETCH BACKWARD FROM order_cursor;
```
--> empty result set, no error

```FETCH FROM order_cursor;```
--> first row, same as CrateDB

```FETCH BACKWARD FROM order_cursor;```
--> empty result set, no error

```FETCH FROM order_cursor;```
--> first row, **CrateDB returns the second row**
