### ISSUE TITLE
SchemaUnknownException instead of ColumnUnknownException when user does not have permissions on search_path schema and CTE is used

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13561]
### CrateDB version

5.3.0 -SNAPSHOT-f9b7ea6

### CrateDB setup information

Single node started with
```bash
docker run --publish 4200:4200 --publish 5432:5432 crate/crate:nightly-5.3.0-20230131 -Cdiscovery.type=single-node
```

### Problem description

Permissions seem to be checked differently when using a CTE, any issues there?

The error message is also misleading, which is confusing when troubleshooting a query with a typo.

### Steps to Reproduce

1.- Run these commands as `crate`:
```sql
CREATE TABLE testschema.testtable (a int);
CREATE USER testpermissionsbuguser  WITH (password='...');
GRANT DQL ON SCHEMA testschema TO testpermissionsbuguser;
```
2.- Now connect as `testpermissionsbuguser`
```bash
crash -U testpermissionsbuguser --verbose
```
3.- 
```sql
SHOW search_path;
```
--> `doc` , we do not have permissions here, but that is ok as we will only be working on the `testschema` which we will refer to explicitly every time

4.-
```sql
select doesnotexist from testschema.testtable;
```
--> `ColumnUnknownException` as expected, this is good

5.-
```sql
WITH alldata AS (SELECT a from testschema.testtable) 
select doesnotexist FROM alldata;
```
--> `SchemaUnknownException[Schema 'doc' unknown]`
--> why?

### Actual Result

```
SchemaUnknownException[Schema 'doc' unknown]

io.crate.exceptions.SchemaUnknownException: Schema 'doc' unknown
        at io.crate.user.Privileges.ensureUserHasPrivilege(Privileges.java:107)
        at io.crate.auth.AccessControlImpl$MaskSensitiveExceptions.visitTableScopeException(AccessControlImpl.java:897)
        at io.crate.auth.AccessControlImpl$MaskSensitiveExceptions.visitTableScopeException(AccessControlImpl.java:884)
        at io.crate.exceptions.TableScopeException.accept(TableScopeException.java:34)
        at io.crate.auth.AccessControlImpl.ensureMaySee(AccessControlImpl.java:148)
        at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:153)
        at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:164)
        at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:120)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
        at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:118)
        at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:81)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
        at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Expected Result

`ColumnUnknownException`

**Comment by proddata** [comment]
Don't think this is connected to CTEs directly.

```sql
SELECT doesnotexist;                                                                                                                                            
-- SchemaUnknownException[Schema 'doc' unknown]

SHOW search_path;                                                                                                                                               
+-------------------+
| setting           |
+-------------------+
| pg_catalog, georg |
+-------------------+
```

What is somewhat strange is, that it refers to `doc`, even when `doc` is not on the `search_path`

**Comment by jeeminso** [comment]
> What is somewhat strange is, that it refers to doc, even when doc is not on the search_path

the table is resolved to `EmptyRowTableFunction` and in the process of generating the exception, `doc` is appended.
Also, `ColumnUnknownException` was properly generated initially but was converted to `SchemaUnknownException` in the process of making the exception more sensible with respect to the user privileges.

**Comment by jeeminso** [comment]
Hello @matriv, similar to the recent `drop function` bug, this should be a bug right?

**Comment by matriv** [comment]
@jeeminso yep, it's a misleading error message so bug.

**Comment by jeeminso** [comment]
This issue can be generalized to `select a from empty_row()`. We treat table functions (or any other functions can be used in the from clause) as tables implicitly. By the time that the execution reaches privilege checks, it is hard to differentiate
```
SELECT a FROM empty_row();
// or
SELECT a FROM empty_row; // here 'empty_row' is a regular table where 'a' does not exist.
```
And the former is treated as the latter leading to unnecessary privilege checks.

---

Another variation of this issue:
```
cr> select a from abs();                                                                                                                            
MissingPrivilegeException[Missing privilege for user 'test']

// should be:
UnsupportedFeatureException[Unknown function: abs(). Possible candidates: abs(double precision):double precision, abs(real):real, abs(byte):byte, abs(smallint):smallint, abs(integer):integer, abs(bigint):bigint]
```
