### ISSUE TITLE
Support comparison/ORDER BY/MIN/MAX on intervals

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13576]
### CrateDB version

5.2.0 (built 9986243/2023-01-12T12:22:57Z

### CrateDB setup information

Single node started with 
```bash
docker run --publish 4200:4200 --publish 5432:5432 crate/crate:5.2.0 -Cdiscovery.type=single-node
```

### Problem description

Following a question in the Community I was experimenting using windowing functions and `age` and hit this issue. 
I simplified the repro scenario query and data as much as I could.

### Steps to Reproduce

```sql
CREATE TABLE test1 (id1 TEXT,ut TIMESTAMP);

INSERT INTO test1(id1, ut) VALUES ('r', '2022-01-01 06:00:00'),('r', '2022-01-01 01:00:00');	

WITH cte1
AS (
	SELECT id1
		,age(ut, '2022-01-01 03:00:00'::TIMESTAMP) AS distance
	FROM test1
	)
SELECT id1
	,row_number() OVER (PARTITION BY id1 ORDER BY distance) AS rn
FROM cte1;
```

Minimal examples:

```sql
SELECT
    x
FROM
    unnest(['1 day'::interval, '2 days'::interval]) AS t (x)
ORDER BY
    x;
```

```sql
SELECT
    max(x)
FROM
    unnest(['1 day'::interval, '2 days'::interval]) AS t (x);
```

```sql
SELECT
    min(x)
FROM
    unnest(['1 day'::interval, '2 days'::interval]) AS t (x);
```

### Actual Result

```
ClassCastException[class org.joda.time.Period cannot be cast to class java.lang.Comparable (org.joda.time.Period is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')]

java.lang.ClassCastException: class org.joda.time.Period cannot be cast to class java.lang.Comparable (org.joda.time.Period is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')
        at io.crate.execution.engine.sort.OrderingByPosition.lambda$arrayOrdering$1(OrderingByPosition.java:76)
        at io.crate.execution.engine.sort.NullAwareComparator.compare(NullAwareComparator.java:50)
        at java.base/java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:221)
        at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.base/java.util.TimSort.sort(TimSort.java:220)
        at java.base/java.util.Arrays.sort(Arrays.java:1307)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
        at io.crate.execution.engine.sort.Sort.parallelSort(Sort.java:46)
        at io.crate.execution.engine.window.WindowFunctionBatchIterator.sortAndComputeWindowFunctions(WindowFunctionBatchIterator.java:160)
        at io.crate.execution.engine.window.WindowFunctionBatchIterator.lambda$of$1(WindowFunctionBatchIterator.java:103)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
        at io.crate.execution.engine.window.WindowFunctionBatchIterator.lambda$of$3(WindowFunctionBatchIterator.java:103)
        at io.crate.data.CollectingBatchIterator.lambda$newInstance$4(CollectingBatchIterator.java:98)
        at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:146)
        at io.crate.data.MappedForwardingBatchIterator.loadNextBatch(MappedForwardingBatchIterator.java:51)
        at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:86)
        at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:52)
        at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:92)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Expected Result

PostgreSQL outputs 2 records:

r	1
r	2

**Comment by hlcianfagna** [comment]
Please note that it is not a simple case of intervals not being comparable as 
```sql
SELECT id1,age(ut, '2022-01-01 03:00:00'::TIMESTAMP) AS distance
FROM test1 order by distance;
```
works without issues.

**Comment by matriv** [comment]
> Please note that it is not a simple case of intervals not being comparable as
> 
> ```sql
> SELECT id1,age(ut, '2022-01-01 03:00:00'::TIMESTAMP) AS distance
> FROM test1 order by distance;
> ```
> 
> works without issues.

I also get the same Exception for this, this is because the `org.joda.Period` we use internally to represent intervals in java, doesn't implement Comparable.

As a workaround on can do this:
```
WITH cte1
AS (
	SELECT id1
		,age(ut, '2022-01-01 03:00:00'::TIMESTAMP) AS distance
	FROM test1
	)
SELECT id1
	,row_number() OVER (PARTITION BY id1 ORDER BY EXTRACT(EPOCH FROM distance)) AS rn
FROM cte1;
```

**Comment by matriv** [comment]
So other operations will also fail, like:
```
SELECT MIN(age(ut, '2022-01-01 03:00:00'::TIMESTAMP)) FROM test1 ORDER BY 1; 
```
or
```
SELECT MAX(age(ut, '2022-01-01 03:00:00'::TIMESTAMP)) FROM test1 ORDER BY 1; 
```

In my opinion we shouldn't fix this, but instead provide a nice error message in analysis phase like we do for `MAX_BY/MIN_BY`:
```
cr> SELECT MAX_BY(id1, age(ut, '2022-01-01 03:00:00'::TIMESTAMP)) FROM test1 ORDER BY 1;                      
UnsupportedFeatureException[Cannot use `max_by` on values of type interval]
```

Comparing the 2 period means anyway that internally we need to do the `EXTRACT(EPOCH FROM <period>` anyway which has significant overhead, so Imho, we should not make it implicitly but let the user write this in the SQL.

What do you think?

**Comment by matriv** [comment]
If we want to allow it, transparently, I see 2 solutions.
1. In the `OrderingByPosition#rowOrdering/arrayOrdering` make an `instanceof`, check for `Period` and extract epoch to use in the comparison. (Also in `MaximumAggregation`/`MininumAggregation`)
2. To avoid this ugly instanceof, we introduce our own Period extending `org.joda.Period` which implements `Comparable` which extracts EPOCH to do the comparison.

The 2nd one is more elegant but requires quite a bit more work.

**Comment by matriv** [comment]
Error message is now provided early and not during runtime with https://github.com/crate/crate/pull/13588.

Keeping the issue open to discuss if we want to implement comparison for intervals.

**Comment by matriv** [comment]
psql example:
```
matriv=> select interval '720 hours' > interval '30 days';
 ?column? 
----------
 f
(1 row)

matriv=> select interval '721 hours' > interval '30 days';
 ?column? 
----------
 t
(1 row)

matriv=> select interval '720 hours 1 min' > interval '30 days';
 ?column? 
----------
 t
(1 row)
```

**Comment by matriv** [comment]
Instead of wrapping joda's `Period` with a class implementing `Comparable` , we should use the `IntervalType#compare` which already exists, so in places like `OrderingByPosition`  we should use the data type and its comparator, rather than casting the `Object`s to `Comparable`: https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/execution/engine/sort/OrderingByPosition.java#L61 & https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/execution/engine/sort/OrderingByPosition.java#L76

**Comment by mfussenegger** [comment]
We added support for ORDER BY, MAX, MIN and comparison operators on intervals in https://github.com/crate/crate/pull/13971
