### ISSUE TITLE
IllegalStateException when using correlated subquery and join

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#13592]
### CrateDB version

5.3.0-20230203

### CrateDB setup information

Single node started with
```bash
docker run --publish 4200:4200 --publish 5432:5432 crate/crate:nightly-5.3.0-20230203 -Cdiscovery.type=single-node
```

### Problem description

Correlated subqueries seem to fail when there is a `JOIN` in the main query.

In the example below the same subquery works if there is a single table in the `FROM` and the `JOIN` works if we remove the subquery.

### Steps to Reproduce

```sql
CREATE TABLE listofsomething (somethingid int,somethingdescription TEXT);
INSERT INTO listofsomething (somethingid,somethingdescription) VALUES (1,'A'),(2,'B');

CREATE TABLE listofanotherthing (anotherid int,value TEXT,versionid INT);
INSERT INTO listofanotherthing (anotherid,value,versionid) VALUES ('88','old',1),('88','new',2);

CREATE TABLE mappingtable (somethingidfk INT,anotherthingidfk INT);
INSERT INTO mappingtable (somethingidfk,anotherthingidfk) VALUES (1,88);

SELECT somethingdescription,
	(SELECT value
	FROM listofanotherthing
	WHERE listofanotherthing.anotherid=mappingtable.anotherthingidfk
	ORDER BY versionid DESC
	LIMIT 1)
FROM listofsomething
JOIN mappingtable ON listofsomething.somethingid=mappingtable.somethingidfk;
```

### Actual Result

```
IllegalStateException[OuterColumn `anotherthingidfk` must appear in input of CorrelatedJoin]

java.lang.IllegalStateException: OuterColumn `anotherthingidfk` must appear in input of CorrelatedJoin
        at io.crate.planner.operators.SubQueryResults$1.visitOuterColumn(SubQueryResults.java:84)
        at io.crate.planner.operators.SubQueryResults$1.visitOuterColumn(SubQueryResults.java:78)
        at io.crate.expression.symbol.OuterColumn.accept(OuterColumn.java:79)
        at io.crate.expression.symbol.DefaultTraversalSymbolVisitor.visitFunction(DefaultTraversalSymbolVisitor.java:39)
        at io.crate.expression.symbol.Function.accept(Function.java:197)
        at io.crate.planner.operators.SubQueryResults.lambda$forCorrelation$0(SubQueryResults.java:92)
        at io.crate.analyze.QueriedSelectRelation.visitSymbols(QueriedSelectRelation.java:175)
        at io.crate.planner.operators.SubQueryResults.forCorrelation(SubQueryResults.java:92)
        at io.crate.execution.engine.CorrelatedJoinProjector.<init>(CorrelatedJoinProjector.java:63)
        at io.crate.execution.engine.pipeline.ProjectionToProjectorVisitor.visitCorrelatedJoin(ProjectionToProjectorVisitor.java:737)
        at io.crate.execution.engine.pipeline.ProjectionToProjectorVisitor.visitCorrelatedJoin(ProjectionToProjectorVisitor.java:140)
        at io.crate.execution.dsl.projection.CorrelatedJoinProjection.accept(CorrelatedJoinProjection.java:97)
        at io.crate.execution.dsl.projection.ProjectionVisitor.process(ProjectionVisitor.java:30)
        at io.crate.execution.engine.pipeline.ProjectionToProjectorVisitor.create(ProjectionToProjectorVisitor.java:747)
        at io.crate.execution.engine.pipeline.Projectors.<init>(Projectors.java:59)
        at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterator(ShardCollectSource.java:249)
        at io.crate.execution.engine.collect.MapSideDataCollectOperation.createIterator(MapSideDataCollectOperation.java:58)
        at io.crate.execution.engine.collect.CollectTask.start(CollectTask.java:162)
        at io.crate.execution.jobs.RootTask.start(RootTask.java:198)
        at io.crate.execution.jobs.RootTask.start(RootTask.java:184)
        at io.crate.execution.engine.JobLauncher.setupTasks(JobLauncher.java:268)
        at io.crate.execution.engine.JobLauncher.execute(JobLauncher.java:172)
        at io.crate.planner.operators.LogicalPlanner.executeNodeOpTree(LogicalPlanner.java:565)
        at io.crate.planner.operators.LogicalPlanner.doExecute(LogicalPlanner.java:508)
        at io.crate.planner.operators.LogicalPlanner.execute(LogicalPlanner.java:481)
        at io.crate.planner.operators.LogicalPlan.executeOrFail(LogicalPlan.java:219)
        at io.crate.planner.Plan.execute(Plan.java:73)
        at io.crate.action.sql.Session.singleExec(Session.java:716)
        at io.crate.action.sql.Session.execute(Session.java:499)
        at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:261)
        at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:208)
        at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:117)
        at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:81)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
        at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Expected Result

|somethingdescription|value|
|--------------------|-----|
|A|new|

as in PostgreSQL

**Comment by jeeminso** [comment]
### workaround:
swapping left and right tables of the join operation can avoid the exception:
```
cr> SELECT somethingdescription, 
      (SELECT value 
      FROM listofanotherthing 
      WHERE listofanotherthing.anotherid=mappingtable.anotherthingidfk 
      ORDER BY versionid DESC 
      LIMIT 1) 
    FROM mappingtable    // swap
    JOIN listofsomething // swap
    ON listofsomething.somethingid=mappingtable.somethingidfk;                                                                 
+----------------------+----------------------------------------------+
| somethingdescription | (SELECT value FROM (doc.listofanotherthing)) |
+----------------------+----------------------------------------------+
| A                    | new                                          |
+----------------------+----------------------------------------------+
SELECT 1 row in set (0.005 sec)
```

**Comment by jeeminso** [comment]
The reason for the workaround is visible from the following two explain outputs:

Explain output of the original query:
```
+---------------------------------------------------------------------------------------------------------------------+
| EXPLAIN                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------+
| Eval[somethingdescription, (SELECT value FROM (doc.listofanotherthing))]                                            |
|   └ HashJoin[(somethingid = somethingidfk)]                                                                         |
|     ├ CorrelatedJoin[somethingdescription, somethingid, (SELECT value FROM (doc.listofanotherthing))]               |
|     │  └ Collect[doc.listofsomething | [somethingdescription, somethingid] | true]                                  |
|     │  └ SubPlan                                                                                                    |
|     │    └ Eval[value]                                                                                              |
|     │      └ Limit[2::bigint;0::bigint]                                                                             |
|     │        └ Limit[1::bigint;0]                                                                                   |
|     │          └ OrderBy[versionid DESC]                                                                            |
|     │            └ Collect[doc.listofanotherthing | [value, versionid, anotherid] | (anotherid = anotherthingidfk)] |
|     └ Collect[doc.mappingtable | [somethingidfk] | true]                                                            |
+---------------------------------------------------------------------------------------------------------------------+
```

Explain output of the swapped query:
```
+---------------------------------------------------------------------------------------------------------------------+
| EXPLAIN                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------+
| Eval[somethingdescription, (SELECT value FROM (doc.listofanotherthing))]                                            |
|   └ HashJoin[(somethingid = somethingidfk)]                                                                         |
|     ├ CorrelatedJoin[somethingidfk, anotherthingidfk, (SELECT value FROM (doc.listofanotherthing))]                 |
|     │  └ Collect[doc.mappingtable | [somethingidfk, anotherthingidfk] | true]  <-- see that the correlatedJoin operator has access to anotherthingidfk                                     |
|     │  └ SubPlan                                                                                                    |
|     │    └ Eval[value]                                                                                              |
|     │      └ Limit[2::bigint;0::bigint]                                                                             |
|     │        └ Limit[1::bigint;0]                                                                                   |
|     │          └ OrderBy[versionid DESC]                                                                            |
|     │            └ Collect[doc.listofanotherthing | [value, versionid, anotherid] | (anotherid = anotherthingidfk)] |
|     └ Collect[doc.listofsomething | [somethingdescription, somethingid] | true]                                     |
+---------------------------------------------------------------------------------------------------------------------+
```

**Comment by jeeminso** [comment]
Thanks for reporting @hlcianfagna, I will continue to work on it.
