### ISSUE TITLE
`IllegalStateException[Symbol 'io.crate.expression.symbol.Symbol' not supported]` when trying to select on ambiguous column name

### ISSUE THREAD

**Issue by proddata** [crate/crate#13709]
### CrateDB version

5.2.2

### CrateDB setup information

only reproducible on multi-node cluster (!)

### Problem description

would consider this rather as a ux improvement, not a high priority :bug:

### Steps to Reproduce

```sql
CREATE TABLE t_symbol (b real); 
WITH base AS (SELECT b as b, b as b FROM t_symbol) 
    SELECT  b  FROM base LIMIT 1;
```

### Actual Result

(on multi-node cluster)
```
Error!

IllegalStateException[Symbol 'io.crate.expression.symbol.Symbol' not supported]

java.lang.IllegalStateException: Symbol 'io.crate.expression.symbol.Symbol' not supported
	at io.crate.analyze.TableIdentsExtractor$TableIdentSymbolVisitor.visitSymbol(TableIdentsExtractor.java:83)
	at io.crate.analyze.TableIdentsExtractor$TableIdentSymbolVisitor.visitSymbol(TableIdentsExtractor.java:79)
	at io.crate.expression.symbol.SymbolVisitor.visitAlias(SymbolVisitor.java:82)
	at io.crate.expression.symbol.AliasSymbol.accept(AliasSymbol.java:71)
	at io.crate.analyze.TableIdentsExtractor.extract(TableIdentsExtractor.java:76)
	at io.crate.exceptions.AmbiguousColumnException.getTableIdents(AmbiguousColumnException.java:42)
	at io.crate.auth.AccessControlImpl$MaskSensitiveExceptions.visitTableScopeException(AccessControlImpl.java:896)
	at io.crate.auth.AccessControlImpl$MaskSensitiveExceptions.visitTableScopeException(AccessControlImpl.java:884)
	at io.crate.exceptions.TableScopeException.accept(TableScopeException.java:34)
	at io.crate.auth.AccessControlImpl.ensureMaySee(AccessControlImpl.java:148)
```

### Expected Result

(as on a single node)
```
Error!

AmbiguousColumnException[Column "b" is ambiguous]
```

**Comment by jeeminso** [comment]
Thanks for reporting @proddata. Please help double check the trigger condition - instead of multi node, I was able to reproduce from a single node but with a user without 'doc' privilege.

**Comment by jeeminso** [comment]
Could you please confirm if https://github.com/crate/crate/pull/13728 resolved multi node case as well? @proddata

**Comment by proddata** [comment]
> ```sql
> WITH base AS (SELECT b as b, b as b FROM t_symbol) 
>     SELECT  b  FROM base LIMIT 1;
> ```

Seems to work

```
AmbiguousColumnException[Column "b" is ambiguous]
```

Tested with a nightly docker image

**Comment by jeeminso** [comment]
Thank you!
