### ISSUE TITLE
OutOfMemory when deleting lots of records

### ISSUE THREAD

**Issue by matriv** [crate/crate#13700]
### CrateDB version

5.3.0-SNAPSHOT

### CrateDB setup information

No. nodes = 1
CRATE_HEAP_SIZE=1g

### Problem description

Node dies with OutOfMemory when trying deleting 10m rows from a table.
It also dies quickly after starting it up again.

### Steps to Reproduce

```
create table test(a int, s string); 
insert into test select a, 'asdf' || a from generate_series(1, 10000000, 1) as a; 
refresh table test;
delete from test;
```

### Actual Result

```
[2023-02-20T13:20:59,855][INFO ][o.e.i.IndexingMemoryController] [Glanderspitze] now throttling indexing for shard [[source][0]]: segment writing can't keep up
[2023-02-20T13:21:00,472][INFO ][o.e.i.IndexingMemoryController] [Glanderspitze] now throttling indexing for shard [[source][3]]: segment writing can't keep up
[2023-02-20T13:21:00,925][INFO ][o.e.i.IndexingMemoryController] [Glanderspitze] now throttling indexing for shard [[source][1]]: segment writing can't keep up
[2023-02-20T13:21:06,745][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Glanderspitze] fatal error in thread [cratedb[Glanderspitze][generic][T#5]], exiting
java.lang.OutOfMemoryError: Java heap space
	at org.apache.lucene.util.BytesRefHash.rehash(BytesRefHash.java:377) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:293) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:193) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.IndexingChain$PerField.invert(IndexingChain.java:1210) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.IndexingChain.processField(IndexingChain.java:690) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.IndexingChain.processDocument(IndexingChain.java:575) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:242) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:432) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1532) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1817) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1470) ~[lucene-core-9.5.0.jar:9.5.0 13803aa6ea7fee91f798cfeded4296182ac43a21 - 2023-01-25 16:44:59]
	at org.elasticsearch.index.engine.InternalEngine.deleteInLucene(InternalEngine.java:1486) ~[crate-server.jar:?]
	at org.elasticsearch.index.engine.InternalEngine.delete(InternalEngine.java:1326) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard.delete(IndexShard.java:944) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard.applyDeleteOperation(IndexShard.java:909) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:1380) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard.runTranslogRecovery(IndexShard.java:1413) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard.lambda$openEngineAndRecoverFromTranslog$8(IndexShard.java:1461) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard$$Lambda$3000/0x0000000801832248.run(Unknown Source) ~[?:?]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:471) ~[crate-server.jar:?]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:446) ~[crate-server.jar:?]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:123) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1466) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:447) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:99) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.StoreRecovery$$Lambda$2998/0x00000008018372b0.get(Unknown Source) ~[?:?]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:230) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:97) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1738) ~[crate-server.jar:?]
	at org.elasticsearch.index.shard.IndexShard$$Lambda$2993/0x0000000801836108.accept(Unknown Source) ~[?:?]
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) ~[crate-server.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-server.jar:?]
```

### Expected Result

Throttle the operation or at least have the CB kick in and prevent the JVM to die.

**Comment by matriv** [comment]
I played around a bit, I used jprofiler and checked that for `ShardDeleteRequest$Item`, for **29776** allocations we consume **1429248** bytes. and the `io.crate.execution.dml.ShardRequest.Item#ramBytesUsed` overestimates this with **108** bytes, but this is still not enough for the CB to kick in before OutOfMemory.

When I manually used **256** bytes in `io.crate.execution.engine.indexing.ShardDMLExecutor#addRowToRequest` then the CB kicks in and the node continues to work. Of course that's just a finding, and ideally we need to throttle the deletes before reaching CircuitBreaker limits.

I also tried to manually set the `doThrottle` flag to always `true` in `org.elasticsearch.indices.IndexingMemoryController.ShardsIndicesStatusChecker#runUnlocked` before executing the delete but this doesn't help the situation.
