### ISSUE TITLE
ArrayIndexOutOfBoundsException when using INSERT ... ON CONFLICT ... DO UPDATE

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14213]
### CrateDB version

Tested nightly-5.4.0-20230529 , 5.3.2 , and 5.3.1

### CrateDB setup information

Docker container started with `discovery.type=single-node`

### Problem description

I am getting am `ArrayIndexOutOfBoundsException` when trying to run a simple `INSERT ... ON CONFLICT ... DO UPDATE`
The issue does not occur if the generated column is removed.

### Steps to Reproduce

```sql
CREATE TABLE tbl1 (
  col1 TEXT, 
  ts TIMESTAMP,
  "month" TIMESTAMP GENERATED ALWAYS AS date_trunc('month', ts),  
  v DOUBLE,
  PRIMARY KEY (col1, "month", ts)
);

INSERT INTO tbl1 (col1, ts, v) VALUES ('A', '2023-05-29 19:00'::TIMESTAMP, 1);

INSERT INTO tbl1 (col1, ts, v) VALUES ('A', '2023-05-29 19:00'::TIMESTAMP, 2) 
ON CONFLICT (col1,"month",ts) DO UPDATE SET v=excluded.v;
```

### Actual Result

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
	at io.crate.execution.dml.upsert.UpdateToInsert.convert(UpdateToInsert.java:252)
	at io.crate.execution.dml.upsert.TransportShardUpsertAction.indexItem(TransportShardUpsertAction.java:448)
	at io.crate.execution.dml.upsert.TransportShardUpsertAction.processRequestItems(TransportShardUpsertAction.java:218)
	at io.crate.execution.dml.upsert.TransportShardUpsertAction.processRequestItems(TransportShardUpsertAction.java:101)
	at io.crate.execution.dml.TransportShardAction$1.call(TransportShardAction.java:121)
	at io.crate.execution.dml.TransportShardAction$1.call(TransportShardAction.java:118)
	at io.crate.execution.dml.TransportShardAction.wrapOperationInKillable(TransportShardAction.java:146)
	at io.crate.execution.dml.TransportShardAction.lambda$shardOperationOnPrimary$1(TransportShardAction.java:124)
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:230)
	at io.crate.execution.dml.TransportShardAction.shardOperationOnPrimary(TransportShardAction.java:114)
	at io.crate.execution.dml.TransportShardAction.shardOperationOnPrimary(TransportShardAction.java:63)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:928)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:126)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:429)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:347)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:75)
	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$21(IndexShard.java:2721)
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:103)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:292)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:242)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2695)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:869)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:343)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:309)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:59)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:683)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Expected Result

v updated to 2 as in PostgreSQL 

to test in PostgreSQL create the table with:
```sql
CREATE TABLE tbl1 (
  col1 TEXT, 
  ts TIMESTAMP,
  "month" TIMESTAMP GENERATED ALWAYS AS (date_trunc('month', ts)) STORED,  
  v DOUBLE precision,
  PRIMARY KEY (col1, "month", ts)
);
```

**Comment by hlcianfagna** [comment]
Tested a couple more versions:

5.3.0 --> ArrayIndexOutOfBoundsException
5.2.7 --> works
