### ISSUE TITLE
Allow CHECK constraints defintion at sub-column level

### ISSUE THREAD

**Issue by matriv** [crate/crate#14355]
### Problem Statement

Currently a user cannot define a `CHECK` constraint at the sub-column (of an object col) level:
```
CREATE TABLE t(o OBJECT AS (oo OBJECT AS (ooi INTEGER) CHECK (oo['ooi'] > 100)));
```
or
```
CREATE TABLE t(o OBJECT AS (oo OBJECT AS (ooi INTEGER CHECK (ooi > 100))));
```
And the same applies for `ALTER TABLE t ADD COLUMN...`

Internally, this happens because during the 1st pass of analysis, an `ExpressionAnalyzer` with `FieldProvider.TO_LITERAL_VALIDATE_NAME` is used,  and then an implicit cast (e.g. _cast('ooi', integer) is automatically introduced to support the check expression, which in turn fails during normalization as 'ooi' is understood as literal, not as a col.

With: https://github.com/crate/crate/pull/14354, we explicitly disallowed such definitions in order to provide a nice error message to the user instead of `ConversionException`.

### Considered Alternatives

There are 2 workarounds for this, define the `CHECK` constraint at table-level or at root object-level:
```
CREATE TABLE t(o OBJECT AS (oo OBJECT AS (ooi INTEGER)) CHECK (o['oo']['ooi'] > 100));
```
or:
```
CREATE TABLE t(o OBJECT AS (oo OBJECT AS (ooi INTEGER)), CHECK (o['oo']['ooi'] > 100));
```
(or with a name):
```
CREATE TABLE t(o OBJECT AS (oo OBJECT AS (ooi INTEGER)), constraint check_oii CHECK (o['oo']['ooi'] > 100));
```

**Comment by matriv** [comment]
Ideally, the whole logic of 1st (and maybe 2nd pass) should be refactor to have a unique code path for constraint processing.

**Comment by BaurzhanSakhariev** [comment]
Thanks for providing workaround! 
Declaring CHECK constraint at the sub-column is possible with https://github.com/crate/crate/pull/14360 and will be available in 5.5

**Comment by matriv** [comment]
This is not fixed as originally planned:
```
create table t (i int, o1 object as (o2 object as (b int check (b > 100))))
```
throws:
```
Column b unknown
io.crate.exceptions.ColumnUnknownException: Column b unknown
	at __randomizedtesting.SeedInfo.seed([6932FE62094C189A:9F0CDBB94CF507C4]:0)
	at app//io.crate.analyze.TableElementsAnalyzer.resolveField(TableElementsAnalyzer.java:333)
	at app//io.crate.analyze.TableElementsAnalyzer.resolveField(TableElementsAnalyzer.java:98)
	at app//io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:944)
	at app//io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:444)
	at app//io.crate.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:38)
	at app//io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:776)
	at app//io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:444)
	at app//io.crate.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:80)
	at app//io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:245)
	at app//io.crate.analyze.TableElementsAnalyzer$ColumnAnalyzer.processConstraint(TableElementsAnalyzer.java:559)
	at app//io.crate.analyze.TableElementsAnalyzer$ColumnAnalyzer.visitColumnDefinition(TableElementsAnalyzer.java:526)
	at app//io.crate.analyze.TableElementsAnalyzer$ColumnAnalyzer.visitColumnDefinition(TableElementsAnalyzer.java:499)
	at app//io.crate.sql.tree.ColumnDefinition.accept(ColumnDefinition.java:148)
	at app//io.crate.analyze.TableElementsAnalyzer$ColumnAnalyzer.visitColumnDefinition(TableElementsAnalyzer.java:536)
	at app//io.crate.analyze.TableElementsAnalyzer$ColumnAnalyzer.visitColumnDefinition(TableElementsAnalyzer.java:499)
	at app//io.crate.sql.tree.ColumnDefinition.accept(ColumnDefinition.java:148)
	at app//io.crate.analyze.TableElementsAnalyzer$ColumnAnalyzer.visitColumnDefinition(TableElementsAnalyzer.java:536)
	at app//io.crate.analyze.TableElementsAnalyzer$ColumnAnalyzer.visitColumnDefinition(TableElementsAnalyzer.java:499)
	at app//io.crate.sql.tree.ColumnDefinition.accept(ColumnDefinition.java:148)
	at app//io.crate.analyze.TableElementsAnalyzer.analyze(TableElementsAnalyzer.java:344)
	at app//io.crate.analyze.CreateTableStatementAnalyzer.analyze(CreateTableStatementAnalyzer.java:46)
	at app//io.crate.analyze.Analyzer$AnalyzerDispatcher.visitCreateTable(Analyzer.java:392)
	at app//io.crate.analyze.Analyzer$AnalyzerDispatcher.visitCreateTable(Analyzer.java:236)
	at app//io.crate.sql.tree.CreateTable.accept(CreateTable.java:76)
	at app//io.crate.analyze.Analyzer.analyze(Analyzer.java:219)
	at app//io.crate.testing.SQLExecutor.analyze(SQLExecutor.java:809)
	at app//io.crate.testing.SQLExecutor.analyze(SQLExecutor.java:818)
	at app//io.crate.analyze.CreateAlterTableStatementAnalyzerTest.analyze(CreateAlterTableStatementAnalyzerTest.java:127)
	at app//io.crate.analyze.CreateAlterTableStatementAnalyzerTest.analyze(CreateAlterTableStatementAnalyzerTest.java:122)
	at app//io.crate.analyze.CreateAlterTableStatementAnalyzerTest.test_check_constraint_on_nested_object_sub_column_has_correct_type_and_expression(CreateAlterTableStatementAnalyzerTest.java:1425)
```

it only works if you specify the full path:
```
create table t (i int, o1 object as (o2 object as (b int check (o1['o2']['b'] > 100))))
```

I've opened: https://github.com/crate/crate/pull/14411 to clarify this.



Imho, if we decide that this is enough and we don't want to support referring only to the subcolumn, without full path, we still need to improve the error message, What do you think?

**Comment by mfussenegger** [comment]
I had kept this open for a reason as I was still on this. That's why the PR also didn't include a changes entry in regards to it or a "Closes xy" notice.

Please leave this be for now?

**Comment by matriv** [comment]
@mfussenegger sure, thx! should I close this: https://github.com/crate/crate/pull/14412 as well then?

**Comment by matriv** [comment]
I'm merging #14412, to have a nicer error msg, and the tests in place, and keeping this issue open.
