### ISSUE TITLE
NullPointerException when using WHERE clause, DISTANCE, and subquery, in presence of statistics only

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14381]
### CrateDB version

5.3.3 and nightly-5.4.0-20230707

### CrateDB setup information

Single node started with docker and `-Cdiscovery.type=single-node`

### Problem description

`NullPointerException` only in the presence of statistics

### Steps to Reproduce

```sql
CREATE TABLE IF NOT EXISTS "hernan"."issrandomdatasimple" (
   "ts" TIMESTAMP WITH TIME ZONE NOT NULL,
   "g_ts" TIMESTAMP WITH TIME ZONE GENERATED ALWAYS AS now(),
   "position" GEO_POINT NOT NULL
) CLUSTERED INTO 1 SHARDS;

insert into hernan.issrandomdatasimple(ts,position)
select b,[(random()*360)-180,(random()*180)-90]
from generate_series(1,500) a(b);

CREATE TABLE hernan.world_citiessimple (
   "city" TEXT,   "city_ascii" TEXT,   "location" GEO_POINT,
   "country" TEXT,   "iso2" TEXT,   "iso3" TEXT,
   "admin_name" TEXT,   "capital" TEXT,   "population" BIGINT
) CLUSTERED INTO 1 SHARDS;

insert into hernan.world_citiessimple (city ,location ,country ,capital )
select concat('City',b::TEXT),
	[(random()*360)-180,(random()*180)-90],
	concat('Country',floor(random()*224)::TEXT),
	case when random()<0.00548133735139880881759722848397 then 'primary' else '' end
from generate_series(1,42143) a(b);

ANALYZE;

SELECT DISTANCE(i.position, location)
    FROM (select position from hernan.issrandomdatasimple order by ts desc limit 1) i
    ,hernan.world_citiessimple
WHERE capital = 'primary' ;
--> run the SELECT a couple of times if the exception does not occur right away
```

### Actual Result

```
java.lang.NullPointerException: Cannot load from object array because "this.cells" is null
	at io.crate.data.UnsafeArrayRow.get(UnsafeArrayRow.java:52)
	at io.crate.execution.engine.fetch.FetchRows$1.lambda$visitFetchReference$1(FetchRows.java:113)
	at io.crate.expression.InputRow.get(InputRow.java:45)
	at io.crate.execution.engine.collect.RowCollectExpression.setNextRow(RowCollectExpression.java:42)
	at io.crate.execution.engine.collect.RowCollectExpression.setNextRow(RowCollectExpression.java:29)
	at io.crate.execution.engine.pipeline.MapRowUsingInputs.apply(MapRowUsingInputs.java:65)
	at io.crate.execution.engine.pipeline.MapRowUsingInputs.apply(MapRowUsingInputs.java:49)
	at io.crate.data.BatchIterators$2.currentElement(BatchIterators.java:132)
	at io.crate.data.join.JoinBatchIterator.tryMoveRight(JoinBatchIterator.java:85)
	at io.crate.data.join.CrossJoinNLBatchIterator.tryAdvanceRight(CrossJoinNLBatchIterator.java:72)
	at io.crate.data.join.CrossJoinNLBatchIterator.moveNext(CrossJoinNLBatchIterator.java:53)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:41)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:41)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:75)
	at io.crate.action.sql.RowConsumerToResultReceiver.lambda$consumeIt$1(RowConsumerToResultReceiver.java:101)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:44)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:54)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:39)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:44)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:54)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:39)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:44)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:57)
	at org.elasticsearch.transport.TransportService$5.handleResponse(TransportService.java:515)
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleResponse(TransportService.java:1013)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1082)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1062)
	at io.crate.execution.support.NodeActionRequestHandler.lambda$messageReceived$0(NodeActionRequestHandler.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Expected Result

Something like:
```
+------------------------------+
| distance(position, location) |
+------------------------------+
|           8250423.589253138  |
|           7398905.708084949  |
|           9718522.67265814   |
|          11110201.078590997  |
|           4449022.457656989  |
|           9233819.048600523  |
...
```

**Comment by matriv** [comment]
I've narrowed it down to:
```
create table tt1(a int, b int);
create table tt2(a int, b int, c int);
insert into tt1(a, b) SELECT a, a FROM generate_series(1,100,1) as g(a);
insert into tt2(a, b, c) SELECT a, a, a FROM generate_series(1,100,1) as g(a);
refresh table tt1, tt2;
analyze;

SELECT *
FROM (select a from tt1 order by b desc limit 1) i, tt2
WHERE c >= 50;
```
1. There is a switch involved so the `i` which produces only 1 row is moved to the right side
2. It doesn't fail if there is no `WHERE` clause
3. It doesn't fail if the `i` doesn't have a fetch phase, e.g.:
    ```
    SELECT *
        FROM (select b from tt1 order by b desc limit 1) i, tt2
    WHERE c >= 50;
    ```

**Comment by matriv** [comment]
Thx for reporting @hlcianfagna! Issue has been fixed and will be available with next hotfix release(s).
