### ISSUE TITLE
Connection from DBeaver with errors

### ISSUE THREAD

**Issue by arturohu** [crate/crate#14395]
### CrateDB version

5.3.3

### CrateDB setup information

MAX_MAP_COUNT=262144
CRATE_HEAP_SIZE=4g

### Problem description

We are trying to connect to CrateDB from DBeaver using the CrateDB connector, but we receive an error.

The tables were migrated from CrateDB 4.x. Moreover, using psycopg or the Crate Web UI, everything is working. 

- CrateDB 5.3.3
- DBeaver 23.1.2
- crate-jdbc: 2.7.0

### Steps to Reproduce

1. Create DBeaver Connection using CrateDB connector (port 5432)
2. Access to a table using the interface to show the data
3. Scroll the table

### Actual Result

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:187)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:295)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:332)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 7 more
Caused by: java.lang.NullPointerException: fields must be non-null
	at io.crate.shade.org.postgresql.jdbc.PgResultSet.<init>(PgResultSet.java:148)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.createResultSet(PgStatement.java:155)
	at io.crate.shade.org.postgresql.jdbc.PgStatement$StatementResultHandler.handleResultRows(PgStatement.java:205)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2060)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:442)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:366)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:308)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:294)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:271)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	... 8 more
```

### Expected Result

We expect the table.

Thank you in advance!

**Comment by arturohu** [comment]
Hi @matriv,

Than you for your quick response.

I have tried with the PostgreSQL connector in DBeaver, but I receive the following error when I try to expand the Tables section on the UI:

```
ERROR: Relation 'pg_depend' unknown
  Where: io.crate.metadata.Schemas.resolveTableInfo(Schemas.java:132)
io.crate.analyze.relations.RelationAnalyzer.visitTable(RelationAnalyzer.java:735)
io.crate.analyze.relations.RelationAnalyzer.visitTable(RelationAnalyzer.java:115)
io.crate.sql.tree.Table.accept(Table.java:74)
io.crate.analyze.relations.RelationAnalyzer.visitAliasedRelation(RelationAnalyzer.java:685)
io.crate.analyze.relations.RelationAnalyzer.visitAliasedRelation(RelationAnalyzer.java:115)
io.crate.sql.tree.AliasedRelation.accept(AliasedRelation.java:55)
io.crate.analyze.relations.RelationAnalyzer.visitJoin(RelationAnalyzer.java:280)
io.crate.analyze.relations.RelationAnalyzer.visitJoin(RelationAnalyzer.java:115)
io.crate.sql.tree.Join.accept(Join.java:71)
io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:415)
io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:115)
io.crate.sql.tree.QuerySpecification.accept(QuerySpecification.java:101)
io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:150)
io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:115)
io.crate.sql.tree.Query.accept(Query.java:72)
io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:133)
io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:139)
io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:530)
...
```

In spite of the problem, I can set the query manually and scroll up to the error similar than the one using CrateDB connector:

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3919)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:295)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:332)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.lang.NullPointerException: fields must be non-null
	at org.postgresql.jdbc.PgResultSet.<init>(PgResultSet.java:146)
	at org.postgresql.jdbc.PgStatement.createResultSet(PgStatement.java:158)
	at org.postgresql.jdbc.PgStatement$StatementResultHandler.handleResultRows(PgStatement.java:208)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2068)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	... 13 more
```

Should PostgreSQL DBeaver connector work propperly with CrateDB 5.3.3?

Thank you.

**Comment by hlcianfagna** [comment]
Hi @arturohu , the issue pointing to `pg_depend` when expanding the Tables section seems to have appeared at some point between DBeaver version 23.0.0 (March 2023) and 23.1.1
Implementing `pg_depend` is tracked in https://github.com/crate/crate/issues/12101 and in https://github.com/crate/crate/issues/13234
In the meanwhile I see 2 options, you could run DBeaver 23.0.0 or you can workaround the issue by deploying this mock up:
```sql
CREATE TABLE postgres.pg_depend (
    classid integer,    objid integer,    objsubid integer,    refclassid integer ,    
    refobjid integer ,    refobjsubid integer,    deptype text);
```
As CrateDB does not have FK constraints I do not see any issues mocking this up in this context.
This worked for me on the `postgres` schema but depending on the catalog name and search path you are configuring you may need to deploy this on a different schema.
I hope this helps.

**Comment by arturohu** [comment]
Thank you @proddata!

Now with the new CrateDB connector on **DBeaver 23.1.3** and setting true "**Use SQL to limit fetch size**" on Data Editor, I have a correct behavior fetching tables from **CrateDB 5.4.0**

**Comment by seut** [comment]
Looks like the issue is solved by the new DBeaver CrateDB integration. Otherwise please reopen.
