### ISSUE TITLE
`NotSerializableExceptionWrapper` on `UNNEST` with alias

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#14434]
### CrateDB version

5.4.0 / 5.3.2

### CrateDB setup information

Three nodes

### Problem description

There is a `NotSerializableExceptionWrapper` when modeling an `ARRAY(OBJECT)`, using `UNNEST` on it, and re-using the original column name as an alias for the `UNNEST`.

### Steps to Reproduce

```sql
CREATE TABLE test2 (a ARRAY(OBJECT));

INSERT INTO test2 VALUES (['{"b": 1}']);

SELECT a['b']
FROM (
  SELECT UNNEST(a) AS a
  FROM doc.test2
) x
LIMIT 100;
```

### Actual Result

```
org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: class_cast_exception: class java.lang.Long cannot be cast to class java.util.List (java.lang.Long and java.util.List are in module java.base of loader 'bootstrap')
	at io.crate.types.ArrayType$ArrayStreamer.writeValueTo(ArrayType.java:363)
	at io.crate.execution.engine.distribution.StreamBucket$Builder.add(StreamBucket.java:76)
	at io.crate.data.BatchIterators.lambda$collect$0(BatchIterators.java:59)
	at io.crate.data.BatchIterator.move(BatchIterator.java:157)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:59)
	at io.crate.execution.engine.distribution.SingleBucketBuilder.accept(SingleBucketBuilder.java:56)
	at io.crate.execution.engine.collect.CollectTask.lambda$new$0(CollectTask.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1623)
```

### Expected Result

Successful query execution.

**Comment by matriv** [comment]
This is because `a` is used again to alias the un-nested a array(object), so the analysis is confused and things it will expect an `array(long)` instead of plain `long` as the type of `a['b']`. It doesn't fail if we alias it differently, let's say `aa`:
```
SELECT aa['b']
    FROM (
      SELECT UNNEST(a) AS aa
      FROM test
    ) x
    LIMIT 100;
```

**Comment by matriv** [comment]
I spotted that when the same name is used for the alias, then the method here:
https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/metadata/table/TableInfo.java#L65 is responsible for returning the wrong data type.

**Comment by mfussenegger** [comment]
Thanks for the report, it's fixed with https://github.com/crate/crate/pull/14500
