### ISSUE TITLE
Cannot reset `"cluster.routing.allocation.enable"` to ` 'ALL'`

### ISSUE THREAD

**Issue by WalBeh** [crate/crate#14459]
### CrateDB version

5.2.8

### CrateDB setup information

Number of nodes: 3
Cloud: CR3 Product (scaled from CR2)

```yaml
    - event: compute_changed
        payload:
          new_cpu_limit: 7
          new_cpu_request: 7
          new_heap_ratio: 0.25
          new_memory_limit: "30064771072"
          new_memory_request: "30064771072"
          old_cpu_limit: 3.5
          old_cpu_request: 3.5
          old_heap_ratio: 0.25
          old_memory_limit: "15032385536"
          old_memory_request: "15032385536"
```

### Problem description

```sql
set global persistent "cluster.routing.allocation.enable" = 'ALL';
```
returns and `error` 
```
SQLParseException[unknown setting [archived.cluster.routing.allocation.disk.watermark.low] did you mean any of [cluster.routing.allocation.disk.watermark.low, cluster.routing.allocation.disk.watermark.high]?]
```

In the logs we spotted this: 
```


2023-07-24 09:19:10 | [2023-07-24T07:19:10,400][INFO ][o.e.c.r.a.AllocationService] [data-hot-1] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[content_metric_week][0]]]). |  
-- | -- | --
  |   | 2023-07-24 09:19:30 | [2023-07-24T07:19:30,981][INFO ][o.e.c.r.a.DiskThresholdMonitor] [data-hot-1] low disk watermark [92%] no longer exceeded on [SdeyXItWTtK1BO48sY8UGw][data-hot-0][/data/data0/nodes/0] free: 96.6gb[9.5%] |  
  |   | 2023-07-24 09:19:30 | [2023-07-24T07:19:30,981][INFO ][o.e.c.r.a.DiskThresholdMonitor] [data-hot-1] low disk watermark [92%] no longer exceeded on [mjBXB9GeRB-B-E5_inKAmg][data-hot-1][/data/data0/nodes/0] free: 87.9gb[8.7%] |  
  |   | 2023-07-24 09:20:35 | [2023-07-24 07:20:35,822][INFO][exporter] latest_repo=system_backup_20230721122201 updated_at=1690179816183 |  
  |   | 2023-07-24 09:22:01 | [2023-07-24 07:22:01,289][INFO][backup] Number of repos fetched from sys.repositories table: 1 |  
  |   | 2023-07-24 09:22:01 | [2023-07-24 07:22:01,295][INFO][backup] Latest repository: system_backup_20230721122201 |  
  |   | 2023-07-24 09:22:02 | [2023-07-24 07:22:02,738][INFO][backup] Creating partial snapshot: 20230724072202 |  
  |   | 2023-07-24 09:22:02 | [2023-07-24T07:22:02,899][INFO ][o.e.s.SnapshotsService   ] [data-hot-1] snapshot [system_backup_20230721122201:20230724072202/ZP54NfU-SLKNftKlCnISKA] started |  
  |   | 2023-07-24 09:23:57 | [2023-07-24T07:23:57,302][INFO ][o.e.s.SnapshotsService   ] [data-hot-1] snapshot [system_backup_20230721122201:20230724072202/ZP54NfU-SLKNftKlCnISKA] completed with state [SUCCESS] |  
  |   | 2023-07-24 09:23:59 | [2023-07-24 07:23:59,574][INFO][backup] Creating partial snapshot done. |  
  |   | 2023-07-24 09:23:59 | [2023-07-24 07:23:59,579][INFO][backup] Rotating repositories older than system_backup_20230721122201 |  
  |   | 2023-07-24 09:23:59 | [2023-07-24 07:23:59,682][INFO][backup] Rotating snapshots for system_backup_20230721122201 older than 14 days |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,541][WARN ][o.e.a.a.c.s.TransportClusterUpdateSettingsAction] [data-hot-1] ignoring existing invalid transient setting: [cluster.routing.allocation.disk.watermark.low] with value [92%]; archiving |  
  |   | 2023-07-24 09:30:19 | java.lang.IllegalArgumentException: low disk watermark [92%] more than high disk watermark [90%]



2023-07-24 09:30:19 | [2023-07-24T07:30:19,541][WARN ][o.e.a.a.c.s.TransportClusterUpdateSettingsAction] [data-hot-1] ignoring existing invalid transient setting: [cluster.routing.allocation.disk.watermark.low] with value [92%]; archiving |  
-- | -- | --
  |   | 2023-07-24 09:30:19 | java.lang.IllegalArgumentException: low disk watermark [92%] more than high disk watermark [90%] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings.doValidateAsPercentage(DiskThresholdSettings.java:203) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings.doValidate(DiskThresholdSettings.java:177) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings$LowDiskWatermarkValidator.validate(DiskThresholdSettings.java:114) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.routing.allocation.DiskThresholdSettings$LowDiskWatermarkValidator.validate(DiskThresholdSettings.java:103) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.common.settings.Setting.get(Setting.java:490) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.common.settings.Setting.get(Setting.java:457) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.common.settings.AbstractScopedSettings.archiveUnknownOrInvalidSettings(AbstractScopedSettings.java:784) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.action.admin.cluster.settings.SettingsUpdater.partitionKnownAndValidSettings(SettingsUpdater.java:146) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.action.admin.cluster.settings.SettingsUpdater.updateSettings(SettingsUpdater.java:75) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.action.admin.cluster.settings.TransportClusterUpdateSettingsAction$1.execute(TransportClusterUpdateSettingsAction.java:194) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:701) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:318) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:213) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:150) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:153) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:191) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222) ~[crate-server.jar:?] |  
  |   | 2023-07-24 09:30:19 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] |  
  |   | 2023-07-24 09:30:19 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] |  
  |   | 2023-07-24 09:30:19 | at java.lang.Thread.run(Thread.java:1589) ~[?:?] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,561][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-2] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,562][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-2] updating [cluster.routing.allocation.enable] from [all] to [new_primaries] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,562][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-2] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,562][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-2] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,562][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-2] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,562][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-2] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,563][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,563][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.enable] from [all] to [new_primaries] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,563][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,563][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,563][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,563][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,570][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-1] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,570][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-1] updating [cluster.routing.allocation.enable] from [all] to [new_primaries] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,570][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-1] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,570][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-1] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,570][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-1] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:19 | [2023-07-24T07:30:19,570][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-1] updating [cluster.routing.allocation.disk.watermark.low] from [92%] to [85%] |  
  |   | 2023-07-24 09:30:31 | [2023-07-24T07:30:31,603][INFO ][o.e.c.r.a.DiskThresholdMonitor] [data-hot-1] low disk watermark [85%] e




```

## Backgrounder
While on the 24x7 watch on the weekend I got alerted about a cluster beeing `YELLOW` for some time already. I figured that the `low disk watermark` being reached,  prevented the cluster from allocating shards. Therefore I _worked around it_ by issuing 

```sql
set global transient "cluster.routing.allocation.disk.watermark.low" = '90%';
```

Why did I choose _transient_? I wanted to fix it temporarily and did not see any evil on transient. I expected a node restart would not do any harm, other than resetting the low watermark to _default_ .

Next part of the trivia. The cluster was yellow again on this fine monday morning with the same issue.  I increased the low water disk mark again to `92%`.  A few minutes later a COMPUTE SCALE (CR2->CR3 = more CPU/RAM) was triggered in the cloud console which does a rolling restart and sets the 
```sql
set global persistent "cluster.routing.allocation.enable" = 'new_primaries';
```  

The scale operation briefly stucked, as the cluster had the same issue again with allocating shards (due to the TRANSIENT setting), only after the customer removed old data, the  scale operation took on. But only to the point where the operator needs to reset routing allocation to  `set global persistent "cluster.routing.allocation.enable" = 'ALL';` 

A rolling restart of the cluster was done after the scaling. Which did not improve the situation.

### Actual Result

```
cr> set global persistent "cluster.routing.allocation.enable" = 'ALL';
SQLParseException[unknown setting [archived.cluster.routing.allocation.disk.watermark.low] did you mean any of [cluster.routing.allocation.disk.watermark.low, cluster.routing.allocation.disk.watermark.high]?]

io.crate.exceptions.SQLParseException: unknown setting [archived.cluster.routing.allocation.disk.watermark.low] did you mean any of [cluster.routing.allocation.disk.watermark.low, cluster.routing.allocation.disk.watermark.high]?
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:162)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:151)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:164)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:120)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.rest.action.RestRowCountReceiver.fail(RestRowCountReceiver.java:84)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:63)
	at io.crate.execution.support.OneRowActionListener.accept(OneRowActionListener.java:67)
	at io.crate.execution.support.OneRowActionListener.accept(OneRowActionListener.java:35)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:52)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:173)
	at org.elasticsearch.action.ActionListener$6.onFailure(ActionListener.java:281)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:56)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:39)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onFailure(AckedClusterStateUpdateTask.java:96)
	at org.elasticsearch.action.admin.cluster.settings.TransportClusterUpdateSettingsAction$1.onFailure(TransportClusterUpdateSettingsAction.java:188)
	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onFailure(MasterService.java:513)
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.notifyFailedTasks(MasterService.java:440)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:153)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:191)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalArgumentException: unknown setting [archived.cluster.routing.allocation.disk.watermark.low] did you mean any of [cluster.routing.allocation.disk.watermark.low, cluster.routing.allocation.disk.watermark.high]?
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:408)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:358)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:329)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:300)
	at org.elasticsearch.action.admin.cluster.settings.SettingsUpdater.updateSettings(SettingsUpdater.java:94)
	at org.elasticsearch.action.admin.cluster.settings.TransportClusterUpdateSettingsAction$1.execute(TransportClusterUpdateSettingsAction.java:194)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:701)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:318)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:213)
	... 8 more

cr>
```

### Expected Result

 `set global persistent "cluster.routing.allocation.enable" = 'ALL';`  should run without an error being returned.

**Comment by WalBeh** [comment]
This maybe an interesting detail about the cause: 

```syslog


2023-07-24 09:30:31 | [2023-07-24T07:30:31,603][INFO ][o.e.c.r.a.DiskThresholdMonitor] [data-hot-1] low disk watermark [85%] exceeded on [SdeyXItWTtK1BO48sY8UGw][data-hot-0][/data/data0/nodes/0] free: 97.7gb[9.7%], replicas will not be assigned to this node |  
-- | -- | --
  |   | 2023-07-24 09:30:31 | [2023-07-24T07:30:31,603][INFO ][o.e.c.r.a.DiskThresholdMonitor] [data-hot-1] low disk watermark [85%] exceeded on [mjBXB9GeRB-B-E5_inKAmg][data-hot-1][/data/data0/nodes/0] free: 85.7gb[8.5%], replicas will not be assigned to this node |  
  |   | 2023-07-24 09:30:31 | [2023-07-24T07:30:31,603][INFO ][o.e.c.r.a.DiskThresholdMonitor] [data-hot-1] low disk watermark [85%] exceeded on [JC7XZjx4TRat9gf5ADhN3w][data-hot-2][/data/data0/nodes/0] free: 104.7gb[10.3%], replicas will not be assigned to this node |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,549][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.high] from [90%] to [95%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,549][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.flood_stage] from [95%] to [96%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.high] from [90%] to [95%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.flood_stage] from [95%] to [96%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.high] from [90%] to [95%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.flood_stage] from [95%] to [96%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.high] from [90%] to [95%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.flood_stage] from [95%] to [96%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.high] from [90%] to [95%] |  
  |   | 2023-07-24 09:31:58 | [2023-07-24T07:31:58,550][INFO ][o.e.c.s.ClusterSettings  ] [data-hot-0] updating [cluster.routing.allocation.disk.watermark.flood_stage] from [95%] to [96%]

```

The `high` watermark had **previously** changed been to `90%`. `flood_stage` to `95%`.  

Then on the weekend I changed `low` from `85%` to `90%` and this morning to `92%`. I did not notice that I passed the high water mark 🙈 but everything seemed fine, until we bounced one of the nodes with the operator (that previously set routing allocation to `new_primaries`. Which also seemed to work, until the bounce.

**Comment by matriv** [comment]
I've managed to get to this state only artificially with the following code change:
![Screenshot_20230725_163542](https://github.com/crate/crate/assets/5058131/57189ddc-4106-498d-8110-a4c859cb74d6)
So when setting the `low` watermark, it moves it to `archived.` and from then on it's impossible to set any other cluster setting as it's complaining for the existence of an `archived.` setting.
Doing a full cluster restart makes the `archived` `low` setting disappear, and you can set again any cluster setting.

I haven't been able to reproduce the situation on a running cluster, I've tried to set low and high concurrently from different clients and I've tried to make a rolling restart during changing the settings, hoping that it's produce during recover of the cluster state: https://github.com/crate/crate/blob/master/server/src/main/java/org/elasticsearch/gateway/Gateway.java#L133 but nothing worked.

Provided a fix, to at least be able to reset `archived.*` cluster settings while the cluster is running, and then be able to set again any cluster setting, without the need to fully restart the cluster.
