### ISSUE TITLE
Rolling upgrade from 5.4.0 to 5.4.1 fails with `java.lang.IllegalStateException`

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#14555]
### CrateDB version

5.4.1

### CrateDB setup information

CrateDB Edge three-nodes cluster

### Problem description

The first node upgraded to 5.4.1 fails to join the cluster and remains unavailable.

### Steps to Reproduce

Start a rolling upgrade of a three-nodes cluster. The error message indicates an issue related to view metadata changes in 5.4.1, I don't have exact steps to reproduce yet with a specific view definition.

### Actual Result

```
[2023-08-08T06:28:34,210][INFO ][o.e.c.c.JoinHelper       ] [data-hot-crate-data-hot-f4ae0c70-1438-46cf-a577-abff62c3593a-2] failed to join {data-hot-crate-data-hot-f4ae0c70-1438-46cf-a577-abff62c3593a-0}{msx5erdrReW2S6nK1ytP9g}{Jduy0y2LRx2k_dl4FHCNCQ}{10.1.105.199}{10.1.105.199:4300}{dm}{node_name=hot, http_address=10.1.105.199:4200} with JoinRequest{sourceNode={data-hot-crate-data-hot-f4ae0c70-1438-46cf-a577-abff62c3593a-2}{zu9oj4HoRHW1rRH11XZ43A}{zcVqrFd5SO2ERz3sd-FNSw}{10.1.29.135}{10.1.29.135:4300}{dm}{node_name=hot, http_address=10.1.29.135:4200}, minimumTerm=83, optionalJoin=Optional.empty}
org.elasticsearch.transport.RemoteTransportException: [data-hot-crate-data-hot-f4ae0c70-1438-46cf-a577-abff62c3593a-0][10.1.105.199:4300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$2.onFailure(Coordinator.java:501) ~[crate-server.jar:?]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:62) ~[crate-server.jar:?]
	at org.elasticsearch.transport.TransportService$5.handleException(TransportService.java:521) ~[crate-server.jar:?]
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleException(TransportService.java:1021) ~[crate-server.jar:?]
	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:287) ~[crate-server.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [data-hot-crate-data-hot-f4ae0c70-1438-46cf-a577-abff62c3593a-2][10.1.29.135:4300][internal:cluster/coordination/join/validate]
Caused by: java.lang.IllegalStateException: unexpected byte [0x17]
	at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:542) ~[crate-server.jar:?]
	at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:532) ~[crate-server.jar:?]
	at io.crate.metadata.SearchPath.createSearchPathFrom(SearchPath.java:60) ~[crate-server.jar:?]
	at io.crate.metadata.view.ViewMetadata.<init>(ViewMetadata.java:39) ~[crate-server.jar:?]
	at io.crate.metadata.view.ViewsMetadata.<init>(ViewsMetadata.java:59) ~[crate-server.jar:?]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:46) ~[crate-server.jar:?]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[crate-server.jar:?]
	at org.elasticsearch.cluster.metadata.Metadata.readFrom(Metadata.java:518) ~[crate-server.jar:?]
	at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:697) ~[crate-server.jar:?]
	at org.elasticsearch.cluster.coordination.ValidateJoinRequest.<init>(ValidateJoinRequest.java:39) ~[crate-server.jar:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:55) ~[crate-server.jar:?]
	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:203) ~[crate-server.jar:?]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:107) ~[crate-server.jar:?]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:96) ~[crate-server.jar:?]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:675) ~[crate-server.jar:?]
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:143) ~[crate-server.jar:?]
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:118) ~[crate-server.jar:?]
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:83) ~[crate-server.jar:?]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:71) ~[crate-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[netty-handler-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Expected Result

Node successfully joins the cluster after upgrading.

**Comment by mfussenegger** [comment]
Thanks for the report. I unfortunately missed to add version handling to the serialization logic in https://github.com/crate/crate/pull/14491

Should get fixed with https://github.com/crate/crate/pull/14556
