### ISSUE TITLE
ClassCastException with DEFAULT value and RETURNING clause

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14747]
### CrateDB version

nightly-5.5.0-20230926

### CrateDB setup information

-Cdiscovery.type=single-node

### Problem description

Trying to get a generated default value returned after an `INSERT` I am seeing a `ClassCastException`.

### Steps to Reproduce

```sql
create table testrandom (a int, b int default floor(random()*1000));
insert into testrandom(a) values (1) returning b;
```

### Actual Result

```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at io.crate.types.IntegerType.valueBytes(IntegerType.java:40)
	at io.crate.breaker.EstimateRowSize.applyAsLong(EstimateRowSize.java:48)
	at io.crate.breaker.RowAccountingWithEstimators.accountForAndMaybeBreak(RowAccountingWithEstimators.java:69)
	at io.crate.breaker.RowAccountingWithEstimators.accountForAndMaybeBreak(RowAccountingWithEstimators.java:33)
	at io.crate.rest.action.RestResultSetReceiver.setNextRow(RestResultSetReceiver.java:64)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:77)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:57)
	at io.crate.planner.operators.InsertFromValues.lambda$execute$2(InsertFromValues.java:303)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.crate.planner.operators.InsertFromValues.lambda$execute$10(InsertFromValues.java:655)
	at io.crate.planner.operators.InsertFromValues$1.onResponse(InsertFromValues.java:703)
	at io.crate.planner.operators.InsertFromValues$1.onResponse(InsertFromValues.java:690)
	at io.crate.execution.support.RetryListener.onResponse(RetryListener.java:57)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:54)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:39)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:44)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishOnSuccess(TransportReplicationAction.java:850)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:773)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:759)
	at org.elasticsearch.transport.TransportService$5.handleResponse(TransportService.java:514)
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleResponse(TransportService.java:1012)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1081)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1061)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:47)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:30)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$runWithPrimaryShardReference$2(TransportReplicationAction.java:421)
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:99)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:71)
	at org.elasticsearch.action.support.replication.ReplicationOperation.finish(ReplicationOperation.java:351)
	at org.elasticsearch.action.support.replication.ReplicationOperation.decPendingAndFinishIfNeeded(ReplicationOperation.java:332)
	at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:162)
	at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:154)
	at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult$1.onSuccess(TransportWriteAction.java:171)
	at org.elasticsearch.action.support.replication.TransportWriteAction$AsyncAfterWriteAction.maybeFinish(TransportWriteAction.java:289)
	at org.elasticsearch.action.support.replication.TransportWriteAction$AsyncAfterWriteAction.lambda$run$0(TransportWriteAction.java:308)
	at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.notifyList(AsyncIOProcessor.java:121)
	at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.drainAndProcessAndRelease(AsyncIOProcessor.java:99)
	at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.put(AsyncIOProcessor.java:83)
	at org.elasticsearch.index.shard.IndexShard.sync(IndexShard.java:3017)
	at org.elasticsearch.action.support.replication.TransportWriteAction$AsyncAfterWriteAction.run(TransportWriteAction.java:306)
	at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.runPostReplicationActions(TransportWriteAction.java:178)
	at org.elasticsearch.action.support.replication.ReplicationOperation.handlePrimaryResult(ReplicationOperation.java:154)
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:99)
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:240)
	at io.crate.execution.dml.TransportShardAction.shardOperationOnPrimary(TransportShardAction.java:114)
	at io.crate.execution.dml.TransportShardAction.shardOperationOnPrimary(TransportShardAction.java:63)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:927)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:126)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:428)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:346)
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:99)
	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$21(IndexShard.java:2721)
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:127)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:292)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:242)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2695)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:868)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:342)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:308)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:59)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:682)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Expected Result

```
postgres=# create table testrandom (a int, b int default floor(random()*1000));
CREATE TABLE
postgres=# insert into testrandom(a) values (1) returning b;
  b  
-----
 181
(1 row)

INSERT 0 1
postgres=# select * from testrandom;
 a |  b  
---+-----
 1 | 181
(1 row)
```

**Comment by hlcianfagna** [comment]
This seems to be a regression. 
It was working in 5.4.3
```
cr> select version();
+----------------------------------------------------------------------------------------------------------------------+
| pg_catalog.version()                                                                                                 |
+----------------------------------------------------------------------------------------------------------------------+
| CrateDB 5.4.3 (built f34a1e0/2023-09-05T15:03:45Z, Linux 5.15.0-56-generic amd64, OpenJDK 64-Bit Server VM 20.0.2+9) |
+----------------------------------------------------------------------------------------------------------------------+
SELECT 1 row in set (0.012 sec)
cr> create table testrandom (a int, b int default floor(random()*1000));
CREATE OK, 1 row affected  (0.963 sec)
cr>  insert into testrandom(a) values (1) returning b;
+-----+
|   b |
+-----+
| 489 |
+-----+
INSERT 1 row in set (0.044 sec)
```
