### ISSUE TITLE
UnsupportedFeatureException with CASE statement with NULL

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#14763]
### CrateDB version

5.4.3 and nightly-5.5.0-20230927

### CrateDB setup information

-Cdiscovery.type=single-node

### Problem description

qlikcloud.com generates SQL statements with CASE constructs which can return integers or NULLs and it is hitting the exception below.

### Steps to Reproduce

```sql
SELECT  CASE col1
	WHEN 'value2'	THEN 2
	WHEN 'value3'	THEN NULL				
	ELSE NULL
	END 
FROM (select 'value1' as col1) a;
```

### Actual Result

```
io.crate.exceptions.UnsupportedFeatureException: Data types of all result expressions of a CASE statement must be equal, found: [integer, undefined]
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:154)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:141)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:116)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:80)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.UnsupportedOperationException: Data types of all result expressions of a CASE statement must be equal, found: [integer, undefined]
	at io.crate.analyze.expressions.ExpressionAnalyzer.ensureResultTypesMatch(ExpressionAnalyzer.java:1275)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitSimpleCaseExpression(ExpressionAnalyzer.java:533)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitSimpleCaseExpression(ExpressionAnalyzer.java:444)
	at io.crate.sql.tree.SimpleCaseExpression.accept(SimpleCaseExpression.java:56)
	at io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:245)
	at io.crate.analyze.relations.select.SelectAnalysis.toSymbol(SelectAnalysis.java:63)
	at io.crate.analyze.relations.select.SelectAnalyzer$InnerVisitor.visitSingleColumn(SelectAnalyzer.java:63)
	at io.crate.analyze.relations.select.SelectAnalyzer$InnerVisitor.visitSingleColumn(SelectAnalyzer.java:59)
	at io.crate.sql.tree.SingleColumn.accept(SingleColumn.java:78)
	at io.crate.analyze.relations.select.SelectAnalyzer.lambda$analyzeSelectItems$0(SelectAnalyzer.java:54)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at io.crate.analyze.relations.select.SelectAnalyzer.analyzeSelectItems(SelectAnalyzer.java:54)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:440)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:115)
	at io.crate.sql.tree.QuerySpecification.accept(QuerySpecification.java:101)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:150)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:115)
	at io.crate.sql.tree.Query.accept(Query.java:72)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:133)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:139)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:530)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:236)
	at io.crate.sql.tree.Query.accept(Query.java:72)
	at io.crate.analyze.Analyzer.analyze(Analyzer.java:219)
	at io.crate.action.sql.Session.analyze(Session.java:324)
	at io.crate.action.sql.Session.parse(Session.java:314)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:235)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:206)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:115)
	... 43 more
```

### Expected Result

```
 case 
------
     
(1 row)
```

**Comment by matriv** [comment]
Thx for reporting, Issue has been fixed and will be available with next hotfix release.
