### ISSUE TITLE
Issue with using extended query protocol in DBeaver (Received resultset tuples, but no field structure for them)

### ISSUE THREAD

**Issue by proddata** [crate/crate#14778]
### CrateDB version

5.4.2 / Master

### Problem description

It seems like DBeaver with PG JDBC (42.5.2) currently can lead to issues, when scrolling in a result set that breaks the connection with the following:

```
Caused by: java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2301)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
```

### Steps to Reproduce

It is easy to replicate in DBeaver, however not so sure how to replicate it externally.

```sql
create table a as select * from generate_series(1,1000,1) g(a);
```

```sql
select * from a;
```
DBeaver intially fetches 200 records.
Scrolling past 200 records triggers another:
```sql
select * from a;
```

CrateDB - WireShark
<img src="https://github.com/crate/crate/assets/23557193/8d9bf037-12a2-4130-9400-4d9e5c17bd2f" width="300" />

PG16 - WireShark
<img src="https://github.com/crate/crate/assets/23557193/bab04977-a32c-414f-83db-1e6cf7f7616e" width="300" />

### Actual Result

it doesn't work

### Expected Result

it works

---

### ♻️ Workaround

Only use extended query protocol for prepared statements:
<img src="https://github.com/crate/crate/assets/23557193/fae1741c-1019-4a16-a2b5-f84625988d9a" width="400" />

**Comment by mfussenegger** [comment]
@proddata can you check if https://github.com/crate/crate/issues/14778 resolves the issue?

**Comment by proddata** [comment]
> @proddata can you check if https://github.com/crate/crate/pull/14955 resolves the issue?
Seems to resolve it ✅ 

Tested with
DBeaver Version 23.2.3.202310221533
`master` -> reproducible
`j/fetch-interleaved` -> not reproducible

**Comment by matriv** [comment]
Thx @proddata !
