### ISSUE TITLE
WHERE count_alias > 1  fails with unknown column

### ISSUE THREAD

**Issue by robd003** [crate/crate#15266]
### CrateDB version

5.4.6

### CrateDB setup information

Any sized cluster

### Problem description

Unable to filter results with a count() as column_alias

### Steps to Reproduce

Any table schema.

```SELECT user_id, session_id, COUNT(user_id) AS cnt FROM "af_dev"."user_session" WHERE cnt > 1 GROUP BY user_id, session_id order BY cnt DESC;```

### Actual Result

```
io.crate.exceptions.ColumnUnknownException: Column cnt unknown
	at io.crate.analyze.relations.FullQualifiedNameFieldProvider.resolveField(FullQualifiedNameFieldProvider.java:169)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:944)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:444)
	at io.crate.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:38)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:776)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:444)
	at io.crate.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:80)
	at io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:245)
	at io.crate.analyze.expressions.ExpressionAnalyzer.lambda$generateQuerySymbol$1(ExpressionAnalyzer.java:254)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.crate.analyze.expressions.ExpressionAnalyzer.generateQuerySymbol(ExpressionAnalyzer.java:254)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:423)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:115)
	at io.crate.sql.tree.QuerySpecification.accept(QuerySpecification.java:101)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:150)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:115)
	at io.crate.sql.tree.Query.accept(Query.java:72)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:133)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:139)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:530)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:236)
	at io.crate.sql.tree.Query.accept(Query.java:72)
	at io.crate.analyze.Analyzer.analyze(Analyzer.java:219)
	at io.crate.action.sql.Session.analyze(Session.java:327)
	at io.crate.action.sql.Session.parse(Session.java:317)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:236)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:207)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:116)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:81)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:135)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Expected Result

Being able to filter results with a count() should work.

**Comment by matriv** [comment]
This is not a bug but a standard SQL behavior, look at PostgreSQL for example:
```
matriv=> create table user_session(user_id int, session_id int);
CREATE TABLE
matriv=> SELECT user_id, session_id, COUNT(user_id) AS cnt FROM "user_session" WHERE cnt > 1 GROUP BY user_id, session_id order BY cnt DESC;
ERROR:  column "cnt" does not exist
LINE 1: ..., COUNT(user_id) AS cnt FROM "user_session" WHERE cnt > 1 GR...
                                                             ^
matriv=> SELECT * FROM (SELECT user_id, session_id, COUNT(user_id) AS cnt FROM "user_session" GROUP BY user_id, session_id order BY cnt DESC) WHERE cnt > 1;
 user_id | session_id | cnt 
---------+------------+-----
(0 rows)

```
`cnt` alias is not available for WHERE filter in the query it's created, but only available from an outside context (outer queries).

Check for example MySQL docs:
https://docs.oracle.com/cd/E17952_01/mysql-5.7-en/problems-with-alias.html

**Comment by amotl** [comment]
@matriv is right, the `HAVING` clause is probably what you are looking at when aiming to filter using conditions including the `COUNT()` function. [^1]

[^1]: https://cratedb.com/docs/crate/reference/en/latest/general/dql/selects.html#having

**Comment by matriv** [comment]
thx for the followup @amotl !

**Comment by robd003** [comment]
Thanks @amotl

Merry Christmas to the entire CrateDB team 🎄
