### ISSUE TITLE
Problem with Npgsql 8: A PostgreSQL type with the name 'unknown' was not found in the current database info

### ISSUE THREAD

**Issue by amotl** [crate/crate#15281]
### CrateDB version

5.5.1

### CrateDB setup information

Standard, e.g. Docker.

### Problem description

When connecting to CrateDB using Npgsql 8.0.0, which has been released in November 2023, it fails like outlined at https://github.com/crate/crate-qa/pull/289 and below, with the error message `A PostgreSQL type with the name 'unknown' was not found in the current database info`. The problem has also been reported on the community forum, and there is also an upstream conversation about this topic.

- [CrateDB 5.5 not working out of the box with Npgsql 8: A PostgreSQL type with the name 'unknown' was not found in the current database info](https://community.cratedb.com/t/cratedb-5-5-not-working-out-of-the-box-with-npgsql-8-a-postgresql-type-with-the-name-unknown-was-not-found-in-the-current-database-info/1689)
- https://github.com/npgsql/npgsql/issues/5503

### Steps to Reproduce

I can't provide a dedicated repro yet, but the corresponding code in crate-qa already triggers the problem, see https://github.com/crate/crate-qa/pull/289.

### Actual Result

```csharp
Unhandled exception. System.ArgumentException: A PostgreSQL type with the name 'unknown' was not found in the current database info
   at Npgsql.Internal.NpgsqlDatabaseInfo.GetPostgresType(String pgName)
   at Npgsql.Internal.PgSerializerOptions..ctor(NpgsqlDatabaseInfo databaseInfo, Func`1 timeZoneProvider)
   at Npgsql.NpgsqlDataSource.Bootstrap(NpgsqlConnector connector, NpgsqlTimeout timeout, Boolean forceReload, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
   at stock_npgsql.Program.Main(String[] args) in /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr@2/tests/client_tests/stock_npgsql/Program.cs:line 81
   at stock_npgsql.Program.<Main>(String[] args)
Failure running: /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr@2/tests/client_tests/stock_npgsql/bin/Debug/net8.0/stock_npgsql 127.0.0.1 5432
script returned exit code 1
```

### Expected Result

Connecting to CrateDB works, even with Npgsql 8.x.x.

[^1]: https://community.cratedb.com/t/cratedb-5-5-not-working-out-of-the-box-with-npgsql-8-a-postgresql-type-with-the-name-unknown-was-not-found-in-the-current-database-info/1689

### Possible Solutions

@roji, the author of Npgsql, recommends at https://github.com/npgsql/npgsql/issues/5503#issuecomment-1867937124:

> [...] the `unknown` type is a standard type in PostgreSQL, and therefore Npgsql depends on it. I'd recommend getting in touch with CrateDB to see what can be done on their side.

**Comment by amotl** [comment]
@roji: Thank you for tagging @NinoFloris. Nino, I just discovered you made an attempt with https://github.com/npgsql/npgsql/commit/a5aa54b3d to fix this on behalf of Npgsql, thank you very much for your efforts.

I guess it will be a good idea to take the chance to improve PostgreSQL compatibility on CrateDB, but, at the same time, we can't travel back in time to improve previous releases, so your compatibility fix could be suitable for people aiming to use Npgsql 8 to connect to previous versions of CrateDB.
