### ISSUE TITLE
`ALTER TABLE RENAME TO` does not check for target name collision, making data inaccessible

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#15316]
### CrateDB version

5.5.2

### Problem description

`ALTER TABLE RENAME TO` does not check if the target name already exists. If a non-partitioned table A exists, and a partitioned table B is renamed to A, it makes data from both tables inaccessible.

### Steps to Reproduce

```sql
-- create a table, insert some data
CREATE TABLE t1(a INTEGER, b INTEGER);
INSERT INTO t1 VALUES (1, 2), (3, 4);

-- rename the table
ALTER TABLE t1 RENAME TO t2;

-- re-create the original table, but with partitioning
CREATE TABLE t1(a INTEGER, b INTEGER) PARTITIONED BY (a);

-- accidental second renaming
ALTER TABLE t1 RENAME TO t2;
```

### Actual Result

```sql
SELECT * FROM t2;
```

```
io.crate.exceptions.SQLParseException: Trying to create partition name from the name of a non-partitioned table t2
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:152)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:141)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:88)
	at io.crate.protocols.postgres.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:115)
	at io.crate.action.sql.RowConsumerToResultReceiver.lambda$consumeIt$1(RowConsumerToResultReceiver.java:106)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:52)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:56)
	at org.elasticsearch.action.ActionListener.accept(ActionListener.java:39)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.action.FutureActionListener.onFailure(FutureActionListener.java:52)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:62)
	at org.elasticsearch.transport.TransportService$5.handleException(TransportService.java:520)
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleException(TransportService.java:1020)
	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:287)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutor.execute(EsExecutors.java:161)
	at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:282)
	at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:274)
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:131)
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:96)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:675)
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:143)
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:118)
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:83)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:71)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Trying to create partition name from the name of a non-partitioned table t2
	at io.crate.metadata.PartitionName.fromIndexOrTemplate(PartitionName.java:230)
	at io.crate.expression.reference.doc.lucene.LuceneReferenceResolver.getImplementation(LuceneReferenceResolver.java:126)
	at io.crate.execution.engine.fetch.NodeFetchOperation$TableFetchInfo.createCollector(NodeFetchOperation.java:89)
	at io.crate.execution.engine.fetch.NodeFetchOperation.doFetch(NodeFetchOperation.java:189)
	at io.crate.execution.engine.fetch.NodeFetchOperation.fetch(NodeFetchOperation.java:144)
	at io.crate.execution.engine.fetch.TransportFetchNodeAction.nodeOperation(TransportFetchNodeAction.java:97)
	at io.crate.execution.support.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:48)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:59)
	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:331)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1583)
```

### Expected Result

Having the second `ALTER TABLE RENAME` fail, saying there already is a table with the same name.

**Comment by amotl** [comment]
Hi. Thanks for reporting. I know it is technically unrelated, but still it would be so sweet if this could be resolved together with GH-14833, or vice versa ;]. It might roughly be the same code needing to be adjusted?

**Comment by jeeminso** [comment]
FYI, renaming views is also affected:
```
cr> CREATE TABLE x (x INT);                                                                                                                 
CREATE OK, 1 row affected  (0.127 sec)
cr> CREATE VIEW xv AS SELECT 1;                                                                                                             
CREATE OK, 1 row affected  (0.025 sec)
cr> ALTER TABLE xv RENAME TO x;                                                                                                             
ALTER OK, -1 rows affected  (0.025 sec)
cr> SELECT * FROM x;                                                                                                                        
+---+
| x |
+---+
+---+
SELECT 0 rows in set (0.003 sec)
cr> SELECT * FROM xv;                                                                                                                       
RelationUnknown[Relation 'xv' unknown]
cr> DROP TABLE x;                                                                                                                           
DROP OK, 1 row affected  (0.030 sec)
cr> SELECT * FROM x;                                                                                                                        
+---+
| 1 |
+---+
| 1 |
+---+
SELECT 1 row in set (0.006 sec)
cr> DROP TABLE x;                                                                                                                           
RelationUnknown[Relation 'x' unknown]
cr> DROP VIEW x;                                                                                                                            
DROP OK, 1 row affected  (0.026 sec)
cr> SELECT * FROM x;                                                                                                                        
RelationUnknown[Relation 'x' unknown]
```

**Comment by matriv** [comment]
> Hi. Thanks for reporting. I know it is technically unrelated, but still it would be so sweet if this could be resolved together with [GH-14833](https://github.com/crate/crate/issues/14833), or vice versa ;]. It might roughly be the same code needing to be adjusted? At least, I see some semantic relatedness.

It's not only technically unrelated, but this is a bug, while the other is an improvement and should be implemented in a next release and not as a bugfix.
