### ISSUE TITLE
 Issues with Remote Query Results and JDBC Errors in CrateDB 5.4.3

### ISSUE THREAD

**Issue by c224600** [crate/crate#15403]
### CrateDB version

5.4.3

### Problem description

When executing remote queries using crate-jdbc-2.7.0.jar and crate-jdbc-2.6.0.jar with CrateDB 5.4.3, the query results return zero (0), or the following error is encountered:

In contrast, CrateDB version 4.1.8 operates normally without these issues.

When performing remote queries using Apache/2.4.57, Apache Tomcat/10.1.17, mybatis-3.3.0.jar, and mybatis-spring-1.2.3.jar, the result list returns zero (0) despite the tables containing data and the queries being correctly formulated.

### Steps to Reproduce

When executing remote queries using crate-jdbc-2.7.0.jar and crate-jdbc-2.6.0.jar with CrateDB 5.4.3, the query results return zero (0), or the following error is encountered:
php
Copy code
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
    at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:189)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
    at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:295)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:332)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
    ... 7 more
Caused by: java.lang.NullPointerException: fields must be non-null
    at io.crate.shade.org.postgresql.jdbc.PgResultSet.<init>(PgResultSet.java:148)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.createResultSet(PgStatement.java:155)
    at io.crate.shade.org.postgresql.jdbc.PgStatement$StatementResultHandler.handleResultRows(PgStatement.java:205)
    at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2060)
    at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:442)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:366)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:308)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:294)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:271)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
    ... 8 more
This error occurs when selecting a table and viewing data in DBeaver 23.3.2 connected to CrateDB 5.4.3.

### Actual Result

return value 0;

### Expected Result

return value ok;

**Comment by proddata** [comment]
ello @c224600,

Could you provide additional details to help us understand the issue better? I'm interested in knowing whether this problem occurs across all tables or if it's isolated to a table upgraded from version 4.1.8. Additionally, it would be helpful if you could check the sys.jobs_log table for any failed queries that might shed more light on this.

Regarding JDBC drivers, we've been advising the use of the standard PostgreSQL JDBC driver over our custom Crate JDBC driver for most use cases for some time now. 

Also, it's worth noting that DBeaver now offers a new connection type which utilizes the standard pg JDBC driver. This might be relevant depending on your setup.

<img width="397" alt="image" src="https://github.com/crate/crate/assets/23557193/d9fca46c-9776-441b-b664-74dfb8d2af1a">

**Comment by mfussenegger** [comment]
Closing this due to lack of feedback. If you can provide the requested information please post them and we'll reopen the issue
