### ISSUE TITLE
ElasticsearchUncaughtExceptionHandler] [crate1] uncaught exception in thread [main]

### ISSUE THREAD

**Issue by cocoaway** [crate/crate#15778]
### CrateDB version

5.6.1 docker image on arm64

### CrateDB setup information

Docker compose , cluster of 3 nodes.
Running on a virtual machine with Oracle Linux 9 virtualized on MacOS Sonoma, AppleSilicon M2.
VM created using Orbstack.

### Problem description

Node does not start due to 
```shell
 Caused by: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0), name:docker0 (docker0)]
```

### Steps to Reproduce

Run the compose.

```yml
services:
  crate1:
    image: crate:5.6.1
    container_name: node-crate1

    environment:
      - CRATE_HEAP_SIZE=4g
    volumes:
      - cratedb-vol:/data
          
    command: ["crate",
     "-Ccluster.name=oceanic",
     "-Cnode.name=crate1",
     "-Cnetwork.host=_site_",
     "-Cdiscovery.seed_hosts= 198.19.249.135, 198.19.249.20",
     "-Ccluster.initial_master_nodes= 198.19.249.232, 198.19.249.135, 198.19.249.20", 
     "-Cgateway.expected_data_nodes=3",
     "-Cgateway.recover_after_data_nodes=2"]

    restart: always
    network_mode: "host"

volumes:
  cratedb-vol:
    external: true
```

### Actual Result

``` shell
Attaching to node-crate1
node-crate1  | Mar 30, 2024 3:09:54 PM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
node-crate1  | INFO: Using MemorySegmentIndexInput with Java 21; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
node-crate1  | [2024-03-30T15:09:54,938][INFO ][o.e.e.NodeEnvironment    ] [crate1] using [1] data paths, mounts [[/data (/dev/vdb1)]], net usable_space [810.9gb], net total_space [822gb], types [btrfs]
node-crate1  | [2024-03-30T15:09:54,939][INFO ][o.e.e.NodeEnvironment    ] [crate1] heap size [4gb], compressed ordinary object pointers [true]
node-crate1  | [2024-03-30T15:09:54,952][INFO ][o.e.n.Node               ] [crate1] node name [crate1], node ID [QyNKYa22RU-B838vGJnkig], cluster name [oceanic]
node-crate1  | [2024-03-30T15:09:54,953][INFO ][o.e.n.Node               ] [crate1] version[5.6.1], pid[1], build[ed23d5a/NA], OS[Linux/6.7.10-orbstack-00140-g04c64cb35a2e/aarch64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/21.0.2+13-LTS]
node-crate1  | [2024-03-30T15:09:55,257][INFO ][o.e.p.PluginsService     ] [crate1] no modules loaded
node-crate1  | [2024-03-30T15:09:55,257][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [cr8-copy-s3]
node-crate1  | [2024-03-30T15:09:55,257][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [crate-functions]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [crate-jmx-monitoring]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [crate-lang-js]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [es-analysis-common]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [es-analysis-phonetic]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [es-repository-azure]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [io.crate.plugin.SrvPlugin]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [io.crate.udc.plugin.UDCPlugin]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [org.elasticsearch.plugin.repository.url.URLRepositoryPlugin]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [org.elasticsearch.repositories.s3.S3RepositoryPlugin]
node-crate1  | [2024-03-30T15:09:55,258][INFO ][o.e.p.PluginsService     ] [crate1] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
node-crate1  | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
node-crate1  | SLF4J: Defaulting to no-operation (NOP) logger implementation
node-crate1  | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
node-crate1  | [2024-03-30T15:09:55,596][INFO ][o.e.d.DiscoveryModule    ] [crate1] using discovery type [zen] and seed hosts providers [settings]
node-crate1  | [2024-03-30T15:09:56,152][INFO ][psql                     ] [crate1] PSQL SSL support is disabled.
node-crate1  | [2024-03-30T15:09:56,258][INFO ][i.c.n.c.PipelineRegistry ] [crate1] HTTP SSL support is disabled.
node-crate1  | [2024-03-30T15:09:56,271][WARN ][o.e.g.DanglingIndicesState] [crate1] gateway.auto_import_dangling_indices is disabled, dangling indices will not be detected or imported
node-crate1  | [2024-03-30T15:09:56,292][INFO ][o.e.n.Node               ] [crate1] initialized
node-crate1  | [2024-03-30T15:09:56,292][INFO ][o.e.n.Node               ] [crate1] starting ...
node-crate1  | [2024-03-30T15:09:56,300][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [crate1] uncaught exception in thread [main]
node-crate1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0), name:docker0 (docker0)]
node-crate1  | 	at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:30) ~[crate-app-5.6.1.jar:?]
node-crate1  | 	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:113) ~[crate-app-5.6.1.jar:?]
node-crate1  | 	at io.crate.server.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:87) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:120) ~[crate-libs-cli-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.cli.Command.main(Command.java:86) ~[crate-libs-cli-5.6.1.jar:?]
node-crate1  | 	at io.crate.bootstrap.CrateDB.main(CrateDB.java:68) ~[crate-app-5.6.1.jar:?]
node-crate1  | Caused by: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0), name:docker0 (docker0)]
node-crate1  | 	at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:185) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:214) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:188) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:107) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at io.crate.protocols.postgres.PostgresNetty.resolveBindAddress(PostgresNetty.java:229) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at io.crate.protocols.postgres.PostgresNetty.doStart(PostgresNetty.java:194) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:60) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.node.Node.start(Node.java:917) ~[crate-server-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:220) ~[crate-app-5.6.1.jar:?]
node-crate1  | 	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:272) ~[crate-app-5.6.1.jar:?]
node-crate1  | 	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:109) ~[crate-app-5.6.1.jar:?]
node-crate1  | 	... 4 more
```

### Expected Result

CrateDB node to start correctly.

**Comment by proddata** [comment]
Hi @cocoaway 

This seems more like an issue with your network configuration, but not a bug in CrateDB. When using `network.host=_site_` CrateDB tries to bind to a site local private IP address, but there doesn't seem to be any available on your network. You might want to change your network config use `network.host=_[INTERFACE]_` or `network.host=<machines_ip>` with the concrete IP address of the machine instead.


Site local private addresses:
•	10.0.0.0 to 10.255.255.255
•	172.16.0.0 to 172.31.255.255
•	192.168.0.0 to 192.168.255.255

![image](https://github.com/crate/crate/assets/23557193/50a66739-b87b-49a3-a8c2-7a3242714353)

**Comment by cocoaway** [comment]
Hi @proddata , you are right, thank for checking.
The issue is due to Orbstack Linux VMs on Mac.  Same configuration but executed on UTM Linux VMs on Mac works perfectly.
