### ISSUE TITLE
ClassCastException on function with RETURNS OBJECT

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16156]
### CrateDB version

5.7.1

### CrateDB setup information

Single node

### Problem description

`CREATE FUNCTION` accepts `RETURNS OBJECT` , but a ClassCastException is thrown when the function is executed.

### Steps to Reproduce

```sql
CREATE FUNCTION test() 
RETURNS TEXT
LANGUAGE JAVASCRIPT
AS
$$
	function test() {return '{"field1":123,"field2":"abc"}'}
$$;

SELECT test()::OBJECT(STRICT) AS ("field1" BIGINT,"Ref" TEXT)
--> works

DROP FUNCTION test();

CREATE FUNCTION test() 
RETURNS OBJECT(STRICT) AS ("field1" BIGINT,"field2" TEXT)
LANGUAGE JAVASCRIPT
AS
$$
	function test() {return '{"field1":123,"field2":"abc"}'}
$$;
```

### Actual Result

```
java.lang.ClassCastException: Cannot convert 'com.oracle.truffle.api.strings.TruffleString'(language: Java, type: com.oracle.truffle.api.strings.TruffleString) to Java type 'java.util.Map': Unsupported target type.
	at com.oracle.truffle.host.HostEngineException.classCast(HostEngineException.java:65)
	at com.oracle.truffle.host.HostInteropErrors.cannotConvertPrimitive(HostInteropErrors.java:69)
	at com.oracle.truffle.host.HostToTypeNode.convertImpl(HostToTypeNode.java:233)
	at com.oracle.truffle.host.HostToTypeNode.doGeneric(HostToTypeNode.java:155)
	at com.oracle.truffle.host.HostToTypeNodeGen$Uncached.execute(HostToTypeNodeGen.java:365)
	at com.oracle.truffle.host.HostLanguageService.toHostType(HostLanguageService.java:130)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$PrimitiveValue.asClass(PolyglotValueDispatch.java:1871)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$PrimitiveValue.asTypeLiteral(PolyglotValueDispatch.java:1890)
	at org.graalvm.polyglot.Value.as(Value.java:1668)
	at io.crate.operation.language.PolyglotValues.toCrateObject(PolyglotValues.java:63)
	at io.crate.operation.language.PolyglotScalar$CompiledFunction.evaluate(PolyglotScalar.java:112)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.InputRow.get(InputRow.java:45)
	at io.crate.breaker.CellsSizeEstimator$1.estimateSize(CellsSizeEstimator.java:53)
	at io.crate.breaker.CellsSizeEstimator.estimateSize(CellsSizeEstimator.java:83)
	at io.crate.breaker.TypedRowAccounting.accountForAndMaybeBreak(TypedRowAccounting.java:74)
	at io.crate.breaker.TypedRowAccounting.accountForAndMaybeBreak(TypedRowAccounting.java:36)
	at io.crate.rest.action.RestResultSetReceiver.setNextRow(RestResultSetReceiver.java:64)
	at io.crate.protocols.postgres.RetryOnFailureResultReceiver.setNextRow(RetryOnFailureResultReceiver.java:73)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:77)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:57)
	at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Expected Result

```
{"field2":"abc","field1":123}
```

Or `CREATE FUNCTION` to thrown an error when invoked with `RETURNS OBJECT`

**Comment by seut** [comment]
@hlcianfagna 
Your 2nd function is not returning an object but a string instead.
Changing the function to return a valid JS object will result in a working function:
```
cr> CREATE FUNCTION test()
    RETURNS OBJECT(STRICT) AS ("field1" BIGINT,"field2" TEXT)
    LANGUAGE JAVASCRIPT
    AS
    $$
    ^Ifunction test() {return {"field1":123,"field2":"abc"};}
    $$;
CREATE OK, 1 row affected (0.032 sec)
cr> select test()['field1'];
+-------------+
| 123::bigint |
+-------------+
|         123 |
+-------------+
SELECT 1 row in set (0.007 sec)
```

**Comment by hlcianfagna** [comment]
That is great, sorry did not think of that option.
