### ISSUE TITLE
Test failure: SwapTableITest#test_swap_source_nonpartitioned_target_partitioned_with_drop_source

### ISSUE THREAD

**Issue by romseygeek** [crate/crate#16261]
```
[2024-06-29T13:09:30,853][INFO ][i.c.e.d.TransportSwapRelationsAction] [[cratedb[node_s0][masterService#updateTask][T#1]]] Swapping tables [xqynipndvrhu.source <-> xqynipndvrhu.target]
[2024-06-29T13:09:31,295][INFO ][o.e.i.s.IndexShard       ] [[cratedb[node_s0][generic][T#5]]] [xqynipndvrhu.target][1] ignoring recovery of a corrupt translog entry
java.lang.IllegalArgumentException: unexpected mapping update
	at org.elasticsearch.index.shard.IndexShard.runTranslogRecovery(IndexShard.java:1473) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.lambda$openEngineAndRecoverFromTranslog$8(IndexShard.java:1516) ~[classes/:?]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:469) ~[classes/:?]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:444) ~[classes/:?]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:121) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1521) ~[classes/:?]
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:443) ~[classes/:?]
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:99) ~[classes/:?]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:239) ~[classes/:?]
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:97) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1792) ~[classes/:?]
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) ~[classes/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[classes/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
[2024-06-29T13:10:01,294][INFO ][i.c.e.d.TransportSwapRelationsAction] [[cratedb[node_s0][generic][T#3]]] Switched name of relations, but the operation timed out waiting for enough shards to be started
```

```
WARNING: Uncaught exception in thread: Thread[#4410,cratedb[node_s0][clusterApplierService#updateTask][T#1],5,TGRP-SwapTableITest]
java.lang.AssertionError: new global checkpoint [-1] is lower than previous one [0]
	at __randomizedtesting.SeedInfo.seed([716919F8CE5FA40C]:0)
	at org.elasticsearch.index.seqno.ReplicationTracker.updateGlobalCheckpointOnPrimary(ReplicationTracker.java:1284)
	at org.elasticsearch.index.seqno.ReplicationTracker.activatePrimaryMode(ReplicationTracker.java:1031)
	at org.elasticsearch.index.shard.IndexShard.updateShardState(IndexShard.java:455)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateShard(IndicesClusterStateService.java:637)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:583)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:254)
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:501)
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:491)
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:468)
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:415)
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
```

**Comment by romseygeek** [comment]
So I think there are several problems here:
* There is a bug in the translog parsing code where the 'ignore unknown columns' behaviour is reversed - we ought to be failing on unknown values in the translog if the column policy is set to 'strict', but are in fact doing the opposite.  This is a simple fix.
* That's not really what's causing the swap table problem though.  This appears to be caused by the newly swapped tables recovering from the translog of the previous version of the table.  Which is just plain wrong, but because it happens so rarely it's difficult to work out why.  I'm going to up the IndexShard logging on the swap table test to see if we can get more visibility on this if it fails again.  But I think this is an existing issue that the translog changes have just made more obvious.
* Thirdly, there are a couple of lines in IndexShard where, if we are recovering from a local store and we hit an error, instead of failing we just log a message and continue.  But this then trips a later assertion about global checkpoints.  So I think we should remove this leniency entirely.
