### ISSUE TITLE
Cannot add new column to a partitioned table after changing the number of shards

### ISSUE THREAD

**Issue by matriv** [crate/crate#16521]
### CrateDB version

5.7.1, master

### CrateDB setup information

Can be reproduced with one 1 node locally

### Problem description

New column cannot be added to a partitioned table, if the number of shards has been changed in-between.

### Steps to Reproduce

```
cr> create table t_parted(a int, b int) clustered into 2 shards partitioned by (b);
CREATE OK, 1 row affected (0.084 sec)
cr> insert into t_parted(a, b) values(1, 1), (2, 2);
INSERT OK, 2 rows affected (2.915 sec)
cr> alter table t_parted set (number_of_shards = 3);
ALTER OK, -1 rows affected (0.054 sec)
cr> insert into t_parted(a, b) values(3, 3), (4, 4);
INSERT OK, 2 rows affected (2.244 sec)
cr> refresh table t_parted;
REFRESH OK, 4 rows affected (0.006 sec)
cr> select count(*) from sys.shards where table_name = 't_parted';
+----------+
| count(*) |
+----------+
|       10 |
+----------+
SELECT 1 row in set (0.007 sec)
(2 partitions initially with 2 shards each = 4 shards + 2 new partitions with 6 shards each = 6 shards, total 10 shards)
cr> alter table t_parted add column c int;
```

### Actual Result

```
IllegalStateException[primaryTerms length is [2] but should be equal to number of shards [3]]

java.lang.IllegalStateException: primaryTerms length is [2] but should be equal to number of shards [3]
        at org.elasticsearch.cluster.metadata.IndexMetadata$Builder.build(IndexMetadata.java:1085)
        at org.elasticsearch.cluster.metadata.Metadata$Builder.put(Metadata.java:664)
        at io.crate.metadata.doc.DocTableInfo.writeTo(DocTableInfo.java:1058)
        at io.crate.execution.ddl.tables.AlterTableTask.execute(AlterTableTask.java:57)
        at io.crate.metadata.cluster.DDLClusterStateTaskExecutor.execute(DDLClusterStateTaskExecutor.java:38)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:665)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:280)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:175)
        at org.elasticsearch.cluster.service.MasterService.lambda$doStart$0(MasterService.java:121)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:170)
        at org.elasticsearch.cluster.service.BatchedTask.run(BatchedTask.java:70)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Expected Result

Column is added

**Comment by hlcianfagna** [comment]
It can also be reproed in 5.8.1
