### ISSUE TITLE
`Can't handle Symbol` exception on referencing column from CTE in subquery

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#16793]
### CrateDB version

5.8.3

### CrateDB setup information

Four nodes CrateDB Cloud

### Problem description

There is an exception trying to reference a column from a CTE in a subquery.

### Steps to Reproduce

Tabel structure:
```sql
CREATE TABLE IF NOT EXISTS "t1" (
   "data" OBJECT(DYNAMIC) AS (
      "_id" TEXT NOT NULL,
   )
   PRIMARY KEY ("data"['_id'])
)
CLUSTERED BY ("data"['_id']) INTO 9 SHARDS
```

Query:
```sql
WITH main_desc_0 AS (
    SELECT t.data['_id']
    FROM t1 t
)
SELECT
    (
        SELECT data['_id']
        FROM t1 p
        WHERE p.data['_id'] = main_desc_0.data['_id']
        LIMIT 1
    ) AS x
FROM main_desc_0;
```

### Actual Result

The query *succeeds* on an *empty* table.

It *fails* on a *non-empty* table with 100 rows. Data can be shared in private if needed.
```
io.crate.exceptions.SQLParseException: Couldn't create execution plan from logical plan because of: Can't handle Symbol [OuterColumn: data['_id']]:
Rename[data['_id']] AS p (rows=1)
  └ Limit[2::bigint;0::bigint] (rows=1)
    └ Limit[1::bigint;0] (rows=1)
      └ Get[<original schema name redacted>.t1 | data['_id'] | DocKeys{data['_id']} | (data['_id'] = data['_id'])] (rows=1)
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:211)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:200)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:117)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:88)
	at io.crate.protocols.postgres.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:97)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:114)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:57)
	at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.IllegalArgumentException: Couldn't create execution plan from logical plan because of: Can't handle Symbol [OuterColumn: data['_id']]:
Rename[data['_id']] AS p (rows=1)
  └ Limit[2::bigint;0::bigint] (rows=1)
    └ Limit[1::bigint;0] (rows=1)
      └ Get[<original schema name redacted>.t1 | data['_id'] | DocKeys{data['_id']} | (data['_id'] = data['_id'])] (rows=1)
	at io.crate.expression.BaseImplementationSymbolVisitor.visitSymbol(BaseImplementationSymbolVisitor.java:103)
	at io.crate.expression.BaseImplementationSymbolVisitor.visitSymbol(BaseImplementationSymbolVisitor.java:43)
	at io.crate.expression.symbol.SymbolVisitor.visitOuterColumn(SymbolVisitor.java:98)
	at io.crate.expression.symbol.OuterColumn.accept(OuterColumn.java:84)
	at io.crate.analyze.SymbolEvaluator.evaluate(SymbolEvaluator.java:69)
	at io.crate.analyze.where.DocKeys$DocKey.lambda$getId$0(DocKeys.java:67)
	at io.crate.common.collections.Lists$LazyMapList.get(Lists.java:385)
	at io.crate.common.collections.Lists.getOnlyElement(Lists.java:200)
	at io.crate.analyze.where.DocKeys$DocKey.getId(DocKeys.java:64)
	at io.crate.planner.operators.Get.build(Get.java:107)
	at io.crate.planner.operators.Limit.build(Limit.java:113)
	at io.crate.planner.operators.Limit.build(Limit.java:113)
	at io.crate.planner.operators.Rename.build(Rename.java:197)
	at io.crate.planner.operators.RootRelationBoundary.build(RootRelationBoundary.java:60)
	at io.crate.planner.operators.LogicalPlanner.getNodeOperationTree(LogicalPlanner.java:621)
	at io.crate.planner.operators.LogicalPlanner.doExecute(LogicalPlanner.java:600)
	at io.crate.planner.operators.LogicalPlanner.execute(LogicalPlanner.java:570)
	at io.crate.planner.operators.LogicalPlan.executeOrFail(LogicalPlan.java:216)
	at io.crate.planner.Plan.execute(Plan.java:73)
	at io.crate.execution.engine.CorrelatedJoinProjector$BindAndExecuteSubQuery.apply(CorrelatedJoinProjector.java:91)
	at io.crate.execution.engine.CorrelatedJoinProjector$BindAndExecuteSubQuery.apply(CorrelatedJoinProjector.java:74)
	at io.crate.data.AsyncFlatMapBatchIterator.loadNextBatch(AsyncFlatMapBatchIterator.java:117)
	at io.crate.data.MappedForwardingBatchIterator.loadNextBatch(MappedForwardingBatchIterator.java:51)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:91)
	... 5 more
Caused by: java.lang.UnsupportedOperationException: Can't handle Symbol [OuterColumn: data['_id']]
	... 29 more
```

### Expected Result

Successful execution.

**Comment by matriv** [comment]
fails when at least one value is inserted, e.g.:
```
insert into t1 values('{"_id" : "foo"}');
```

**Comment by matriv** [comment]
It also fails without the CTE expression, just a nested select:
```
SELECT
        (
            SELECT data['_id']
            FROM t1 p
            WHERE p.data['_id'] = tt1.data['_id']
            LIMIT 1
        ) AS x
    FROM (SELECT t1.data['_id'] FROM t1) as tt1;
```

**Comment by matriv** [comment]
thank you @hammerhead for reporting this issue. It has been fixed and will be available with the upcoming hotfix releases for 5.8 and 5.9
