### ISSUE TITLE
Cannot update `OBJECT` if used as partition key, even if it remains identical

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#16815]
### CrateDB version

5.8.3

### CrateDB setup information

Single-node standard deployment

### Problem description

When using CrateDB to store CDC events, a typical data model looks like `(pk, entity)` where the PK comes from the source table and `entity` is a JSON document with several attributes. `INSERT`, `UPDATE`, and `DELETE` statements are typically replicated which all can be executed on such a data model.

However, partitioning is needed for such a table due to its constantly increasing size. When creating a generated column from within the `entity` object, it is no longer possible to run `UPDATE`/`INSERT ON CONFLICT DO UPDATE` statements changing `entity`, even if the attribute that the generated column is based on remains identical.

CrateDB fails with `Updating a column which is referenced in a partitioned by generated column expression is not supported`, which is technically correct, as `entity` is updated, but on the other side, the property inside `entity` which is used for partitioning did not actually change.

### Steps to Reproduce

```sql
CREATE TABLE x (
  pk VARCHAR NOT NULL, 
  entity OBJECT(DYNAMIC) AS ("createdAt" TIMESTAMP),
  "createdAtMonth" GENERATED ALWAYS AS date_trunc('month', entity['createdAt']),
  PRIMARY KEY (pk, "createdAtMonth")
)
PARTITIONED BY("createdAtMonth");

-- initial insert is ok
INSERT INTO x (pk, entity) VALUES (1, '{"createdAt": 1729231524257, "v": 5}');
-- same insert statement as before, no change in createdAt, but it fails with the exception below
INSERT INTO x (pk, entity) VALUES (1, '{"createdAt": 1729231524257, "v": 5}') ON CONFLICT (pk, "createdAtMonth") DO UPDATE set entity = EXCLUDED.entity;
```

### Actual Result

```
io.crate.exceptions.ColumnValidationException: Validation failed for entity: Updating a column which is referenced in a partitioned by generated column expression is not supported
	at io.crate.analyze.relations.DocTableRelation.ensureNotUpdated(DocTableRelation.java:118)
	at io.crate.analyze.relations.DocTableRelation.ensureColumnCanBeUpdated(DocTableRelation.java:109)
	at io.crate.analyze.relations.DocTableRelation.getField(DocTableRelation.java:69)
	at io.crate.analyze.relations.DocTableRelation.getField(DocTableRelation.java:41)
	at io.crate.analyze.relations.NameFieldProvider.resolveField(NameFieldProvider.java:61)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:966)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:445)
	at io.crate.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:38)
	at io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:246)
	at io.crate.analyze.InsertAnalyzer.getUpdateAssignments(InsertAnalyzer.java:322)
	at io.crate.analyze.InsertAnalyzer.processUpdateAssignments(InsertAnalyzer.java:346)
	at io.crate.analyze.InsertAnalyzer.analyze(InsertAnalyzer.java:146)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitInsert(Analyzer.java:534)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitInsert(Analyzer.java:257)
	at io.crate.sql.tree.Insert.accept(Insert.java:102)
	at io.crate.analyze.Analyzer.analyze(Analyzer.java:240)
	at io.crate.action.sql.Session.analyze(Session.java:304)
	at io.crate.action.sql.Session.parse(Session.java:294)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:235)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:206)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:114)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:82)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:159)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:155)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.elasticsearch.transport.netty4.Netty4InboundStatsHandler.channelRead(Netty4InboundStatsHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Expected Result

Don't use `entity['createdAt']` for partitioning, but generate a new timestamp using `NOW()`. This has the disadvantage of no longer being able to efficiently prune partitions on queries such as `WHERE entity['createdAt'] >= '2024-10-01'`.

**Comment by BaurzhanSakhariev** [comment]
Hi @hammerhead, thanks for reporting the issue.

Sine in this example there is no intent to update entity object, I think  `DO NOTHING` can be used as a workaround. 
```
INSERT INTO x (pk, entity)
VALUES (1, '{"createdAt": 1729231524257, "v": 5}')
ON CONFLICT (pk, "createdAtMonth") DO NOTHING;
```

**Comment by hammerhead** [comment]
The example was overly simplified, in reality, there are sequences such as this where `DO NOTHING` is not applicable:
```sql
-- start: Table is empty

-- succeeds, 1 row inserted
INSERT INTO x (pk, entity) VALUES (1, '{"createdAt": 1729231524257, "v": 5}') ON CONFLICT (pk, "createdAtMonth") DO UPDATE set entity = EXCLUDED.entity;

-- pk and entity['createdAt'] remain identical, but entity['v'] has changed -> INSERT will fail
-- entity['v'] should be updated
-- The application sending the statement doesn't know if there is already a previous version of this row, hence the upsert rather than an UPDATE
INSERT INTO x (pk, entity) VALUES (1, '{"createdAt": 1729231524257, "v": 10}') ON CONFLICT (pk, "createdAtMonth") DO UPDATE set entity = EXCLUDED.entity;
```

**Comment by BaurzhanSakhariev** [comment]
Side note: I think ON CONFLICT fails even against empty table.

Regarding updating "safe part which is not used in partition by column or i or in gen column used in partition by column"
Granular update would work, but I in practice can be cumbersome if you have many sub-columns.

```
INSERT INTO x (pk, entity)
VALUES (1, '{"createdAt": 1729231524257, "v": 10}')
ON CONFLICT (pk, "createdAtMonth") DO UPDATE set entity['v'] = 10
```

**Comment by BaurzhanSakhariev** [comment]
I actually don't think it's a bug - we don't know upfront whether inserted value is "safe" before executing the query.

We need to actually execute, hit the conflict, check values and don't reject inserts which are not effectively updating partitioned/generated_involved_in_partitioned columns.

That's probably possible but should be a feature:

Don't reject `ON CONFLICT ... DO UPDATE SET column = given value/excluded` on analysis. Instead, check each row on runtime and reject if it tries to update "stable" columns. It will add some tax as we could compare large objects per row. 

Another question is primitive columns - there can be "safe" updates where new values are same with existing values but not sure it's practical because it means "keep old value of a primitive column == do nothing"? 

Maybe can be useful for insert from select where we want to 
```
 INSERT INTO x (pk, primitive_parted_by_column)
 select a, b from t
 ON CONFLICT (pk, primitive_parted_by_column) DO UPDATE primitive_parted_by_column = exclude.b; 

// safely reject actual updates but insert new values
```

**Comment by henrikingo** [comment]
Thanks Baur for drilling into this.

My opinion (not final verdict) is in this case clear: This works as designed. You can update the fields that aren't part of a partition key and you cannot update the fields that are. Pretty straightforward.

Yes, it can be a bit tedious if your partition key is submerged somewhere deep inside the object, and surrounded by lots of other fields. But users are free to design their schema as they wish. They can have an OBJECT/JSON structure where the createdAt column is conveniently separated:

    {"createdAt": 1729231524257, allOtherData: {a:..., b:...}}

...or not, but we shouldn't prioritize a task that is mostly about making it more convenient to not do the right thing.

Another reason why I think current behavior is good, is that for many database engines an upsert is an operation that can be a "blind write", that is, we can accept the write and log it, without needing to read the old row for checking things. (...for example, whether a partition key value is changing or the same.)
