### ISSUE TITLE
Casting error attempting to cast values that could be skipped

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16858]
### CrateDB version

5.8.3 and crate/crate:nightly-5.10.0-2024-10-24-00-02

### CrateDB setup information

Reproed both with single node and with 3 nodes.

### Problem description

With a table structure with an `ARRAY(OBJECT(IGNORED))` where a field may be a number or a string, trying to unnest and filter out only the numbers that meet a certain condition, we get an error message about the engine trying to cast the strings to numbers.

### Steps to Reproduce

```sql
CREATE TABLE test (data OBJECT AS (attributes ARRAY(OBJECT (IGNORED))));

INSERT INTO test
VALUES ('{"attributes":[{"key":"number","value":1},{"key":"string","value":"abc"}]}');

SELECT *
FROM (
	SELECT *
	FROM (
		SELECT unnest(data ['attributes']) attribute
		FROM test
		) a
	WHERE attribute ['key'] = 'number'
	) b
WHERE attribute ['value'] > 0;

/* Also tried */

with b as (
	SELECT *
	FROM (
		SELECT unnest(data ['attributes']) attribute
		FROM test
		) a
	WHERE attribute ['key'] = 'number'
)
SELECT *
FROM b
WHERE attribute ['value'] > 0;

/* Workaround */

SELECT *
FROM (
	SELECT unnest(data ['attributes']) attribute
	FROM test
	) a
WHERE attribute ['key'] = 'number'
AND TRY_CAST(attribute ['value'] AS BIGINT)>0; 
```

### Actual Result

```
io.crate.exceptions.SQLParseException: Cannot cast value `abc` to type `integer`
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:211)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:200)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:172)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:127)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:931)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2401)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:125)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:86)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:159)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:155)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.elasticsearch.transport.netty4.Netty4InboundStatsHandler.channelRead(Netty4InboundStatsHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: io.crate.exceptions.ConversionException: Cannot cast value `abc` to type `integer`
	at io.crate.expression.scalar.cast.ImplicitCastFunction.castToTargetType(ImplicitCastFunction.java:108)
	at io.crate.expression.scalar.cast.ImplicitCastFunction.evaluate(ImplicitCastFunction.java:98)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.operator.CmpOperator.evaluate(CmpOperator.java:61)
	at io.crate.expression.operator.CmpOperator.evaluate(CmpOperator.java:41)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.operator.AndOperator.evaluate(AndOperator.java:117)
	at io.crate.expression.operator.AndOperator.evaluate(AndOperator.java:47)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.InputCondition.matches(InputCondition.java:38)
	at io.crate.expression.RowFilter.test(RowFilter.java:61)
	at io.crate.expression.RowFilter.test(RowFilter.java:35)
	at io.crate.data.FilteringBatchIterator.moveNext(FilteringBatchIterator.java:44)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:41)
	at io.crate.data.LimitingBatchIterator.moveNext(LimitingBatchIterator.java:57)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:41)
	at io.crate.session.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:75)
	at io.crate.session.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:57)
	at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more
```

### Expected Result

```
+-------------------------------+
| attribute                     |
+-------------------------------+
| {"key": "number", "value": 1} |
+-------------------------------+
```

**Comment by hlcianfagna** [comment]
Another workaround is:
```sql
set optimizer_merge_filters=false;
```

**Comment by mfussenegger** [comment]
On a first glance this looks like working as expected to me.
Due to object(ignored) there's no type information on value. The `> 0` therefore dictates the type. 

Using a try_cast seems like the proper solution here

**Comment by hlcianfagna** [comment]
Ok, just for future reference, on an actual dataset with the query I was looking at I get much better performance with the `optimizer_merge_filters=false` workaround.

**Comment by mfussenegger** [comment]
> Ok, just for future reference, on an actual dataset with the query I was looking at I get much better performance with the optimizer_merge_filters=false workaround.


Do you have reproduction steps for this? That's somewhat surprising given that in both cases there is no index for the data in the ignored object.

**Comment by hlcianfagna** [comment]
@mfussenegger I can reproduce this consistently on 5.9.6 with non-public data, but I have not been able to reproduce this with mock data that I could share publicly. Let me DM you with the details.
