### ISSUE TITLE
SQLParseException on query with equals ANY and UNNEST

### ISSUE THREAD

**Issue by hlcianfagna** [crate/crate#16892]
### CrateDB version

5.8.3 and 5.9.1

### CrateDB setup information

Reproed both on single node and with 3 nodes

### Problem description

I have arrays of objects.
The objects themselves have arrays of objects.
After unnesting the "first level" objects I want to perform an `= ANY` filter, this seems to work on "normal" objects but not on objects coming out from an unnest operation.

### Steps to Reproduce

```sql
CREATE TABLE tbl_obj (obj OBJECT(DYNAMIC));

INSERT INTO tbl_obj (obj)
SELECT $$
	{
		"items": [{
				"item_status": {
					"field1": "abc"
				}
			}
		]
	}
$$;

REFRESH TABLE tbl_obj;

create table tbl_arr_obj_dynamic  (arr array(object(dynamic)));

insert into tbl_arr_obj_dynamic
select [obj] from tbl_obj;

REFRESH TABLE tbl_arr_obj_dynamic;

select * from tbl_obj;
/*
+-------------------------------------------------+
| obj                                             |
+-------------------------------------------------+
| {"items": [{"item_status": {"field1": "abc"}}]} |
+-------------------------------------------------+
*/
select unnest(arr) as obj
from tbl_arr_obj_dynamic;
/*
+-------------------------------------------------+
| obj                                             |
+-------------------------------------------------+
| {"items": [{"item_status": {"field1": "abc"}}]} |
+-------------------------------------------------+
*/

select *
from tbl_obj
WHERE 'abc'=ANY obj ['items']['item_status']['field1'];
--> 1 row

SELECT *
FROM (
		select unnest(arr) as obj
		from tbl_arr_obj_dynamic
) a
WHERE 'abc'=ANY obj ['items']['item_status']['field1'];
```

### Actual Result

```
io.crate.exceptions.SQLParseException: Base argument to subscript must be an object, not [{item_status={field1=abc}}]
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:211)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:200)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:172)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:127)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:88)
	at io.crate.session.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:98)
	at io.crate.session.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:114)
	at io.crate.session.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:57)
	at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.IllegalArgumentException: Base argument to subscript must be an object, not [{item_status={field1=abc}}]
	at io.crate.expression.scalar.SubscriptFunction.lookupByName(SubscriptFunction.java:213)
	at io.crate.expression.scalar.SubscriptFunction.evaluate(SubscriptFunction.java:188)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.scalar.SubscriptFunction.evaluate(SubscriptFunction.java:183)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.scalar.cast.ImplicitCastFunction.evaluate(ImplicitCastFunction.java:92)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.operator.any.AnyOperator.evaluate(AnyOperator.java:130)
	at io.crate.expression.operator.any.AnyOperator.evaluate(AnyOperator.java:56)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.InputCondition.matches(InputCondition.java:38)
	at io.crate.expression.RowFilter.test(RowFilter.java:61)
	at io.crate.expression.RowFilter.test(RowFilter.java:35)
	at io.crate.data.FilteringBatchIterator.moveNext(FilteringBatchIterator.java:44)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:41)
	at io.crate.data.LimitingBatchIterator.moveNext(LimitingBatchIterator.java:57)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:41)
	at io.crate.session.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:75)
	... 5 more
```

### Expected Result

```
+-------------------------------------------------+
| obj                                             |
+-------------------------------------------------+
| {"items": [{"item_status": {"field1": "abc"}}]} |
+-------------------------------------------------+
```

**Comment by matriv** [comment]
I think that something is wrong with unnest, see below:
```
SELECT 1 row in set (2.110 sec)
cr> SELECT pg_typeof(obj['items'])
    FROM (
      select unnest(arr) as obj
      from tbl_arr_obj_dynamic
    ) a;
+------------------------------------+
| pg_catalog.pg_typeof(obj['items']) |
+------------------------------------+
| object_array                       |
+------------------------------------+
SELECT 1 row in set (0.002 sec)
cr> SELECT pg_typeof(obj['items'])
    FROM tbl_obj;
+------------------------------------+
| pg_catalog.pg_typeof(obj['items']) |
+------------------------------------+
| object_array                       |
+------------------------------------+
SELECT 1 row in set (0.002 sec)


cr> SELECT pg_typeof(obj['items']['item_status'])
    FROM (
      select unnest(arr) as obj
      from tbl_arr_obj_dynamic
    ) a;
+---------------------------------------------------+
| pg_catalog.pg_typeof(obj['items']['item_status']) |
+---------------------------------------------------+
| undefined                                         |
+---------------------------------------------------+
SELECT 1 row in set (0.003 sec)
cr> SELECT pg_typeof(obj['items']['item_status'])
    FROM tbl_obj;
+---------------------------------------------------+
| pg_catalog.pg_typeof(obj['items']['item_status']) |
+---------------------------------------------------+
| object_array                                      |
+---------------------------------------------------+
SELECT 1 row in set (0.002 sec)
```
with unnest `item_status` is returned as undefined .

**Comment by matriv** [comment]
@hlcianfagna as a workaround you can just use `ANY` on `arr` without `unnest`:
```
cr> SELECT *
    FROM tbl_arr_obj_dynamic WHERE 'abc'=ANY arr['items']['item_status']['field1'];
+---------------------------------------------------+
| arr                                               |
+---------------------------------------------------+
| [{"items": [{"item_status": {"field1": "abc"}}]}] |
+---------------------------------------------------+
SELECT 1 row in set (0.002 sec)
```

**Comment by matriv** [comment]
Thank for reporting this issue @hlcianfagna ! It has been fixed and will be available with next hotfix release.
Keep in mind that this issue is irrelevant to unnest, it could simply be reproduced with:
```
SELECT {"o"= [{"oo"= {"x"= 10}}, {"oo"= {"x"= 20}}]}['o']['oo']['x']
```
