### ISSUE TITLE
`discovery.seed_providers` DNS SRV lookup should switch to TCP if it fails on UDP

### ISSUE THREAD

**Issue by WalBeh** [crate/crate#17148]
### Problem Statement

For Clusters using `SRV` as `seed_providers` eg. in a k8s environment, node discovery is configured like so:

### cratedb `command`
```
- -Cdiscovery.seed_providers=srv
- -Cdiscovery.srv.query=_cluster._tcp.crate-discovery-bb8a747d-f6ca-4713-8ced-bb1208e314f9.f70ad5ea-8d63-4ab0-a79e-43fbfed9129d.svc.cluster.local

```
During startup of the cratedb PODs, it is expected to see this kind of log entries. 

```
Caused by: java.net.UnknownHostException: Failed to resolve '_cluster._tcp.crate-discovery-bb8a747d-f6ca-4713-8ced-bb1208e314f9.f70ad5ea-8d63-4ab0-a79e-43fbfed9129d.svc.cluster.local.' [SRV(33)]
```

As the starting PODs are not yet `READY` in Kubernetes. As soons as the cratedb POD reports `READY`, it is added to the Kubernetes ServiceEndpoints and a DNS  records is created.

Depending on the DNS Servers configuration, the UDP packet size of such an DNS lookup might be limited to 512 bytes and therefore fails. Which means the DNS query fails and the node is not able to join the cluster.

### Possible Solutions

For clusters up to `8` nodes (using the DNS name pattern from above) `512 byte` UDP packet size works, for clusters with more than 8 Nodes adding a node or doing a rolling restart of a cratedb node fails.

A DNS lookup via TCP is not be limited in packet size. For example, for the venerable `dig` this is the default behavior: 
```
;; Truncated, retrying in TCP mode.
```
DNS SRV lookups _should loop_ over this sequence:
- Try on UDP and if it fails
- re-try via TCP

**Comment by goat-ssh** [comment]
Thanks @seut , here are logs after increase:
Loki logs: https://tools.cr8.net/grafana/goto/4obaAoSNR?orgId=1

```
crate Caused by: java.net.UnknownHostException: Failed to resolve '_cluster._tcp.crate-discovery-bb8a747d-f6ca-4713-8ced-bb1208e314f9.f70ad5ea-8d63-4ab0-a79e-43fbfed9129d.svc.cluster.local.' [SRV(33)]        
crate     at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1150) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                           
crate     at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1097) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                      
crate     at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:455) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                                    
crate     at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1055) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                      
crate     at io.netty.resolver.dns.DnsResolveContext.access$800(DnsResolveContext.java:70) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                                
crate     at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:528) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                      
crate     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                                   
crate     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                                  
crate     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                                
crate     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                                   
crate     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                                         
crate     at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                                       
crate     at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                                        
crate     at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:308) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                                   
crate     at io.netty.resolver.dns.DnsQueryContext.finishSuccess(DnsQueryContext.java:299) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                                                
crate     at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1491) ~[netty-resolver-dns-4.1.114.Final.jar:4.1.114.Final]                                              
crate     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                        
crate     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                        
crate     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                          
crate     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.114.Final.jar:4.1.114.Final]                                                        
crate     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                        
crate     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                        
crate     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                          
crate     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                               
crate     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                        
crate     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                        
crate     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                                        
crate     at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                         
crate     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                                                     
crate     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                                           
crate     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                                                    
crate     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.114.Final.jar:4.1.114.Final]                                                                                    
crate     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]                                                       
crate     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.114.Final.jar:4.1.114.Final]  
```

**Comment by seut** [comment]
@goat-ssh @WalBeh 
Thank you for the logs. So this is the issue that the k8 service endpoint isn't up yet and such the DNS resolver cannot be reached. This is somehow expected or?
How is this related to the TCP fallback or DNS package size?

**Comment by mfussenegger** [comment]
> For clusters up to 8 nodes (using the DNS name pattern from above) 512 byte UDP packet size works, for clusters with more than 8 Nodes adding a node or doing a rolling restart of a cratedb node fails.

Does this mean that dns srv discovery is currently effectively broken for > 8 nodes in kubernetes?
I also don't quite understand how this relates to the package size.

**Comment by WalBeh** [comment]
> Does this mean that dns srv discovery is currently effectively broken for > 8 nodes in kubernetes? I also don't quite understand how this relates to the package size.

That is what we saw on GCP, which per-default runs a the cluster internal DNS Server on UDP. Not entirely sure about how the packet size affects that, but it is very re-producable - on a DNS Server only returns UDP package. It is probably the combination of (in k8s), having UUID as the namespace and then each pod has also a UUID in it s name `crate-data-hot-<UUID>`, but it might be trickier at the end.

**Comment by seut** [comment]
@WalBeh Thank you for this additional information.
You're right, TCP fallback is currently not enabled. I've created a draft PR #17602 to enable this, but I currently have issues on how to test this.

**Comment by seut** [comment]
@WalBeh We've added DNS TCP fallback support with #17602, it will be available with the next `6.2` feature release.
