### ISSUE TITLE
Improve `SQLParseException` indicating which expression caused a casting error

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#17158]
### Problem Statement

When there is a type casting error, an `SQLParseException` is thrown. The exception mentions which value failed to be casted, but not which column or expression caused the error. For complex statements, it can become hard figuring out which is the offending expression.

**Example**

Consider this table and data:
```sql
CREATE TABLE t1 (a TEXT);
INSERT INTO t1 VALUES (1), (2), (''), (3);
```

And this query:
```sql
SELECT a::BIGINT
FROM t1
```

It rightfully fails with:
```
io.crate.exceptions.SQLParseException: Cannot cast value `` to type `bigint`
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:211)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:200)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:172)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:127)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:88)
	at io.crate.session.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:98)
	at io.crate.session.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:114)
	at io.crate.session.RowConsumerToResultReceiver.lambda$consumeIt$1(RowConsumerToResultReceiver.java:101)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:35)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:57)
	at org.elasticsearch.transport.TransportService$5.handleResponse(TransportService.java:515)
	at org.elasticsearch.transport.TransportService$TimeoutResponseHandler.handleResponse(TransportService.java:1013)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1082)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1062)
	at io.crate.execution.support.NodeActionRequestHandler.lambda$messageReceived$0(NodeActionRequestHandler.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: io.crate.exceptions.ConversionException: Cannot cast value `` to type `bigint`
	at io.crate.expression.scalar.cast.ExplicitCastFunction.evaluate(ExplicitCastFunction.java:68)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.expression.InputRow.get(InputRow.java:45)
	at io.crate.breaker.CellsSizeEstimator$1.estimateSize(CellsSizeEstimator.java:53)
	at io.crate.breaker.CellsSizeEstimator.estimateSize(CellsSizeEstimator.java:83)
	at io.crate.breaker.TypedRowAccounting.accountForAndMaybeBreak(TypedRowAccounting.java:74)
	at io.crate.breaker.TypedRowAccounting.accountForAndMaybeBreak(TypedRowAccounting.java:36)
	at io.crate.rest.action.RestResultSetReceiver.setNextRow(RestResultSetReceiver.java:64)
	at io.crate.session.RetryOnFailureResultReceiver.setNextRow(RetryOnFailureResultReceiver.java:68)
	at io.crate.session.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:77)
	... 19 more
```

This case is simple, there is only one column in `t1` and one expression. In a real-world case, the `SELECT` can be much more complex with many more columns and (nested) expressions. In such a case, it is not clear anymore which column or expression causes the error.

### Possible Solutions

The error message could be changed to some variant of the following:
```
Cannot cast value `` to type `bigint` for expression `a::BIGINT`
Cannot cast value `` to type `bigint` for column `t1.a`
```

**Comment by mfussenegger** [comment]
Sounds like a nice improvement but isn't easy to do given that there is a gap between where the error is raised and where we have the information about the expression.

Likely not a priority, but a PR would be welcome if it's not too impactful
