### ISSUE TITLE
Unexpected `Cannot cast value` exception when joining text with integer

### ISSUE THREAD

**Issue by hammerhead** [crate/crate#17165]
### CrateDB version

5.9.5

### CrateDB setup information

Standard single node

### Problem description

When joining a text column with an integer value, CrateDB attempts to cast the column to an integer, which fails with a casting exception.

This is unexpected for two reasons:
1. The same query with a `USING (a)` instead of `ON t1.a = i.a` rejects the query with `SQLParseException[JOIN/USING types text and integer varying cannot be matched]`.
2. If CrateDB wants to auto-cast values for improved usability, it should cast from integer to text, as text is the more generic data type

### Steps to Reproduce

```sql
CREATE TABLE t1 (
  a TEXT
);

INSERT INTO t1 VALUES (1), ('a');

WITH my_input_data AS (
  SELECT 1 AS a
)
SELECT *
FROM t1
JOIN my_input_data i ON t1.a = i.a;
```

### Actual Result

```
io.crate.exceptions.SQLParseException: Cannot cast value `a` to type `integer`
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:211)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:200)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:172)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:127)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:88)
	at io.crate.session.RetryOnFailureResultReceiver.fail(RetryOnFailureResultReceiver.java:98)
	at io.crate.session.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:114)
	at io.crate.session.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:57)
	at io.crate.execution.engine.InterceptingRowConsumer.lambda$tryForwardResult$1(InterceptingRowConsumer.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: io.crate.exceptions.ConversionException: Cannot cast value `a` to type `integer`
	at io.crate.expression.scalar.cast.ImplicitCastFunction.castToTargetType(ImplicitCastFunction.java:108)
	at io.crate.expression.scalar.cast.ImplicitCastFunction.evaluate(ImplicitCastFunction.java:98)
	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
	at io.crate.execution.engine.join.HashJoinOperation.lambda$getHashBuilderFromSymbols$1(HashJoinOperation.java:120)
	at io.crate.execution.engine.join.HashInnerJoinBatchIterator.buildBufferAndMatchRight(HashInnerJoinBatchIterator.java:190)
	at io.crate.execution.engine.join.HashInnerJoinBatchIterator.moveNext(HashInnerJoinBatchIterator.java:148)
	at io.crate.data.MappedForwardingBatchIterator.moveNext(MappedForwardingBatchIterator.java:41)
	at io.crate.session.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:75)
	... 5 more
```

### Expected Result

As described above, either rejection of the query due to data type mismatch, or auto-cast to the more generic data type.

**Comment by mfussenegger** [comment]
Sounds like a nice improvement but isn't easy to do given that there is a gap between where the error is raised and where we have the information about the expression.

Likely not a priority, but a PR would be welcome if it's not too impactful
