### ISSUE TITLE
NPE after table migration

### ISSUE THREAD

**Issue by jagheterfredrik** [crate/crate#1808]
I used to have a table like;
```create table event (timestamp timestamp primary key, host string primary key, eventid string primary key, data object);```

but wanted to have it partioned so I created a event_bak with the same schema, ran `insert into event_bak (select * from event)`, so far so good.

I then dropped the event table (`drop table event`) and created a new one using 
`create table event (timestamp timestamp primary key, host string primary key, eventid string primary key, day timestamp primary key, data object) clustered into 6 shards partitioned by (day);`

And migrated the data back using
`insert into event (timestamp, host, eventid, day, data) (select timestamp, host, eventid, date_trunc('day', timestamp) as day, data from event_bak);`

It seemed to work fine and everything is mostly working except when running
`select data['sessionid'] from event group by data['sessionid']`(data['sessionid'] is a string)

I am greeted by

```
SQLActionException[NPE in org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:229)]

java.lang.NullPointerException
	at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:229)
	at io.crate.operation.reference.doc.lucene.FieldCacheExpression.startCollect(FieldCacheExpression.java:44)
	at io.crate.operation.collect.LuceneDocCollector.doCollect(LuceneDocCollector.java:207)
	at io.crate.operation.collect.MapSideDataCollectOperation.doCollect(MapSideDataCollectOperation.java:352)
	at io.crate.operation.collect.MapSideDataCollectOperation.access$200(MapSideDataCollectOperation.java:69)
	at io.crate.operation.collect.MapSideDataCollectOperation$2.run(MapSideDataCollectOperation.java:330)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jagheterfredrik** [comment]
Managed to fix it after repeatedly issuing
```
delete from event;
drop table event;
insert into event (select * from event_bak)
```
a couple of times. Really scary behavior.

**Comment by mfussenegger** [comment]
This does indeed sound a bit scary. 
Thanks for reporting. We'll take a look at it and try to figure out what caused the issue. 

Which version of crate are you using?

**Comment by jagheterfredrik** [comment]
Thanks, I am using 0.47.7

**Comment by mfelsche** [comment]
The issue has been fixed on master and will be released with the next 0.47 and 0.48 hotfix releases.

Thanks for reporting! :)

**Comment by mfelsche** [comment]
BTW: your data was neither removed nor touched nor corrupted in any way.

**Comment by jagheterfredrik** [comment]
Good to know! Thanks @mfelsche
