### ISSUE TITLE
[v. 0.45.6] Node dropping out of the cluster

### ISSUE THREAD

**Issue by l7s** [crate/crate#1816]
Hi, I am running v. 0.45.6 and got the following problem:

1. Node fails to ping master (note: retry 1 out of 3)
```[2015-03-19 01:35:57,336][TRACE][discovery.zen.fd         ] [crate-eu-3] [master] failed to ping [[crate-eu-1][Nd1t6zk9TuGPzwDPjY3RAA][uk32.lan][inet[/192.168.10.32:4300]]{http_address=http://192.168.10.32:4200}], retry [1] out of [3]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [crate-eu-1][inet[/192.168.10.32:4300]][discovery/zen/fd/masterPing] request_id [5136942] timed out after [30000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)```

2. Second later (with no further re-tries - should be 2 more according to configuration) it drops out:
```[2015-03-19 01:35:57,749][WARN ][transport                ] [crate-eu-3] Received response for a request that has timed out, sent [30413ms] ago, timed out [413ms] ago, action [discovery/zen/fd/masterPing], node [[crate-eu-1][Nd1t6zk9TuGPzwDPjY3RAA][uk32.lan][inet[/192.168.10.32:4300]]{http_address=http://192.168.10.32:4200}], id [5136942]
[2015-03-19 01:35:58,606][INFO ][io.crate.http.netty.HttpBlobHandler] channel closed: java.nio.channels.ClosedChannelException
[2015-03-19 01:35:58,607][INFO ][io.crate.http.netty.HttpBlobHandler] channel closed: java.nio.channels.ClosedChannelException
[2015-03-19 01:35:58,608][INFO ][io.crate.http.netty.HttpBlobHandler] channel closed: java.nio.channels.ClosedChannelException
[2015-03-19 01:35:58,609][INFO ][io.crate.http.netty.HttpBlobHandler] channel closed: java.nio.channels.ClosedChannelException
[2015-03-19 01:38:35,002][INFO ][monitor.jvm              ] [crate-eu-3] [gc][young][1884759][119710] duration [881ms], collections [1]/[1.3s], total [881ms]/[17m], memory [464.1mb]->[310.2mb]/[643.8mb], all_pools {[young] [151.9mb]->[1.7mb]/[177mb]}{[survivor] [22.1mb]->[16.5mb]/[22.1mb]}{[old] [290.1mb]->[291.9mb]/[444.6mb]}
[2015-03-19 02:55:58,422][WARN ][monitor.jvm              ] [crate-eu-3] [gc][young][1889400][119821] duration [1.1s], collections [1]/[1.5s], total [1.1s]/[17.1m], memory [500.9mb]->[331.1mb]/[643.8mb], all_pools {[young] [176.8mb]->[6.3mb]/[177mb]}{[survivor] [4.7mb]->[4.8mb]/[22.1mb]}{[old] [319.4mb]->[320mb]/[444.6mb]}
[2015-03-19 03:20:59,768][INFO ][monitor.jvm              ] [crate-eu-3] [gc][young][1890901][119844] duration [818ms], collections [1]/[1s], total [818ms]/[17.1m], memory [504mb]->[372.8mb]/[643.8mb], all_pools {[young] [171.8mb]->[40.1mb]/[177mb]}{[survivor] [5.6mb]->[5.1mb]/[22.1mb]}{[old] [326.5mb]->[327.5mb]/[444.6mb]}```

Is it likely this has been fixed in newer releases? Is it worth upgrading to solve this? Or is there any other solution?

Regards,
Chris

**Comment by seut** [comment]
reading your supplied log, I wouldn't say for sure that the node was kicked out, do you have any more logs? afaik the connection close log entries are from a connected client...

**Comment by l7s** [comment]
sorry, I actually copied/pasted wrong logs above. The relevant logs are below:

uk32 crate-eu-1 [master node] https://dl.dropboxusercontent.com/u/3182365/crate/uk32-crate.log
uk34 crate-eu-3 [slave node] https://dl.dropboxusercontent.com/u/3182365/crate/uk34-crate.log

**Comment by seut** [comment]
don't really get your problem ;) because as far as i see at your logs, uk32 correctly tries to connect to the slave 3 times before giving up. seems like uk32 is the only one with valid shards uk34 should replicate, thats where the errors coming from. can you please describe what is your expected behaviour and maybe little more details about your table definition?

**Comment by l7s** [comment]
yes, you are right. We got the logs completely wrong. Indeed looks like there is no issue here. I will close this ticket now. Thanks.
