### ISSUE TITLE
Updating document with id failed

### ISSUE THREAD

**Issue by redhat-raptor** [crate/crate#1882]
Hello,

I started to use crate recently and configured a cluster of 3 nodes 2 days back. However seems like one of the nodes will always be throwing the following error. The error occurs continuously and takes all HDD space in hours.

 I have this in my config:

<pre>
node.name: mycrate1
cluster.name: mycluster
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts:
  - mycrate1.com:4300
  - mycrate2.com:4300
  - mycrate3.com:4300
discovery.zen.minimum_master_nodes: 2

# I tried to add the following to see if that fixes the issue. Before it was complaining about 50 queue.
threadpool.bulk.queue_size: 100
</pre>

<pre>
[2015-04-13 00:35:37,694][ERROR][io.crate.operation.projectors.UpdateProjector] Updating document with id JxLvSdgUSDS1PCKIqMqUiA failed {}
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution (queue capacity 100) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@7598c84b
	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:62)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.doStart(TransportShardReplicationOperationAction.java:415)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.start(TransportShardReplicationOperationAction.java:342)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction.doExecute(TransportShardReplicationOperationAction.java:97)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction.doExecute(TransportShardReplicationOperationAction.java:59)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at io.crate.operation.projectors.UpdateProjector.setNextRow(UpdateProjector.java:101)
	at io.crate.operation.collect.LuceneDocCollector.collect(LuceneDocCollector.java:180)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:193)
</pre>

Please help! Thanks in advance!

**Comment by mfelsche** [comment]
Thanks for reporting. I am investigating this.
What query/queries did you execute to run into this issue?

**Comment by redhat-raptor** [comment]
We use crate for storing users' activities on our site which generates thousands of events per min. the system also does simple SELECT queries to see if the user's id is already in our system. Crate is actually connected with our NodeJS server.

**Comment by mfelsche** [comment]
Do you use bulk-inserts? Do you make use of the ON DUPLICATE KEY UPDATE ... clause?

**Comment by redhat-raptor** [comment]
As number of user events can be quite high, the NodeJS app mostly inserts records. However when a user's ID is generated, system updates all old events to have the user id. That's the only update that we run.

No, we do not use ON DUPLICATE KEY UPDATE clause.

**Comment by mfelsche** [comment]
Thank you very much!
I'll keep you posted on this.
Until i come up with a fix, does it help to increase the ``threadpool.bulk.queue_size`` further as a temporary workaround?

**Comment by redhat-raptor** [comment]
threadpool.bulk.queue_size helped buy couple of hours. threadpool.bulk.queue_size was 50 by default then I changed to 100, 300, 3000, 30000 however the error did show up after a while and the error log started chew up all disk spaces.

**Comment by redhat-raptor** [comment]
As the error says <code>Updating document with id JxLvSdgUSDS1PCKIqMqUiA failed</code>  I removed the "UPDATE" statement in my script and the error stopped showing up!

I run a simple update like: <code>UPDATE table_name set user_id = 'some-user-id' where track-id = 'some-track-id'</code>

**Comment by mfelsche** [comment]
The update query is clearly causing this.
The poolsize of the ``bulk`` threadpool that is currently used defaults to the number of processors available. If you have a that high concurrency, maybe it is worth to increase the ``threadpool.bulk.size`` too. 

BTW: we will switch to the ``index`` threadpool for the update operation with the next minor release and implement some (internal and fully transparent) retry logic for the update statement execution.

**Comment by mfelsche** [comment]
We've spotted the issue and it will be fixed with the next hotfix releases for 0.47 and 0.48.

Thank you very much for reporting! :)

**Comment by redhat-raptor** [comment]
Really feeling great to hear that!
