### ISSUE TITLE
"drop [blob] table if exists fails" if used from the Java client

### ISSUE THREAD

**Issue by wallner** [crate/crate#2133]
Trying to conditionally drop tables using  the `if exists` clause from the Java client fails:
```Java
public class ConnectorTest {
    final static CrateClient crateClient = new CrateClient("localhost:4300");

    public static void main(String[] args)  {

        crateClient.sql("drop table if exists metadata").actionGet();
        crateClient.sql("drop blob table if exists table videos").actionGet();
    }
}
```
Raises an exception:

```
Exception in thread "main" SQLActionException{errorCode=4000, status=BAD_REQUEST, stackTrace='io.crate.exceptions.SQLParseException: line 1:27: no viable alternative at input 'table'
	at io.crate.action.sql.TransportBaseSQLAction.esToCrateException(TransportBaseSQLAction.java:262)
	at io.crate.action.sql.TransportBaseSQLAction.buildSQLActionException(TransportBaseSQLAction.java:297)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:189)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:74)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
...
```

The exactly same SQL does work from both `crash` and the admin web interface. Might it be caused by the Java client using the binary protocol?

**Comment by mfussenegger** [comment]
`table if exists table` in the second example seems to be wrong?

Should probably be `drop blob table if exists videos`

**Comment by wallner** [comment]
Oh dear. I'm sorry. to have bothered you. It's a combination of an update of the crate installation and a cut'n'paste error. I'll just call it a day, take this pillow here and crawl back to bed, embarrassed.
