### ISSUE TITLE
COPY TO S3 bucket does not work

### ISSUE THREAD

**Issue by wnkz** [crate/crate#2234]
I think there is an issue with the `COPY TO` command when writing in an S3 bucket.
Using Crate `0.49.4` on Docker with a 3 nodes cluster.
Here is an example:

```sql
cr> create table t (id integer primary key, label string) ;
CREATE OK (1.031 sec)
cr> insert into t (id, label) values (0, 'zero'), (1, 'one'), (2, 'two') ;
INSERT OK, 3 rows affected (0.101 sec)
cr> COPY t TO DIRECTORY 's3://my-bucket/crate/test' ;
_
```

And then the query hangs forever.

Now, here is what's created on S3:

```shell
> aws s3 ls s3://my-bucket/crate/test/                                                                                                                    
2015-07-08 10:17:39          0 t_0_.json
2015-07-08 10:17:43          0 t_4_.json
```

So the "folders" are properly created, some files too but they remain empty.

Here are the crate logs (this error is repeated multiple times on slaves nodes):

```
[2015-07-08 08:17:34,775][INFO ][com.amazonaws.http.AmazonHttpClient] x-amzn-RequestId: not available
[2015-07-08 08:17:34,808][INFO ][com.amazonaws.http.AmazonHttpClient] AWS Request ID: 96276505845335C7
[2015-07-08 08:18:04,845][INFO ][com.amazonaws.http.AmazonHttpClient] Unable to execute HTTP request: my-bucket.s3.amazonaws.com failed to respond
org.apache.http.NoHttpResponseException: my-bucket.s3.amazonaws.com failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:66)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:462)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
	at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:2808)
	at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:2793)
	at io.crate.operation.projectors.writer.OutputS3$S3OutputStream.close(OutputS3.java:174)
	at io.crate.operation.projectors.writer.OutputS3.close(OutputS3.java:72)
	at io.crate.operation.projectors.WriterProjector.endProjection(WriterProjector.java:166)
	at io.crate.operation.projectors.WriterProjector.finish(WriterProjector.java:199)
	at io.crate.operation.collect.LuceneDocCollector.doCollect(LuceneDocCollector.java:238)
	at io.crate.operation.collect.MapSideDataCollectOperation.doCollect(MapSideDataCollectOperation.java:425)
	at io.crate.operation.collect.MapSideDataCollectOperation.access$000(MapSideDataCollectOperation.java:77)
	at io.crate.operation.collect.MapSideDataCollectOperation$2$1.run(MapSideDataCollectOperation.java:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mfussenegger** [comment]
Thanks for reporting.

Seems we haven't used the S3 API correctly and invoked it in a way that could lead to an infinite loop somewhere in the AWS SDK.
I think it worked fine for files that were > 5MB (but haven't confirmed that).

Anyway, a fix for this is in master (https://github.com/crate/crate/pull/2250) and will also be part of the next hotfix releases
