### ISSUE TITLE
Problem with column names

### ISSUE THREAD

**Issue by joergrech** [crate/crate#2337]
I try to select data in Crate using the Java client (in groovy) and get the following error. Note that the Exception mentioned a changed column name "_scraperun" with a small "r".

query: SELECT * FROM profile WHERE _scrapeRun=5 LIMIT 2

Caught: SQLActionException{errorCode=4043, status=NOT_FOUND, stackTrace='io.crate.exceptions.ColumnUnknownException: Column _scraperun unknown
	at io.crate.analyze.relations.FullQualifedNameFieldProvider.resolveField(FullQualifedNameFieldProvider.java:125)
	at io.crate.analyze.relations.FullQualifedNameFieldProvider.resolveField(FullQualifedNameFieldProvider.java:51)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:736)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:392)
	at io.crate.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:49)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:589)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:392)
	at io.crate.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:108)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:135)
	at io.crate.analyze.relations.RelationAnalyzer.analyzeWhere(RelationAnalyzer.java:248)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:87)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:47)
	at io.crate.sql.tree.QuerySpecification.accept(QuerySpecification.java:116)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:61)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:65)
	at io.crate.analyze.SelectStatementAnalyzer.visitQuery(SelectStatementAnalyzer.java:44)
	at io.crate.analyze.SelectStatementAnalyzer.visitQuery(SelectStatementAnalyzer.java:31)
	at io.crate.sql.tree.Query.accept(Query.java:89)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:100)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:43)
	at io.crate.sql.tree.Query.accept(Query.java:89)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.Analyzer.analyze(Analyzer.java:37)
	at io.crate.action.sql.TransportSQLAction.getAnalysis(TransportSQLAction.java:73)
	at io.crate.action.sql.TransportSQLAction.getAnalysis(TransportSQLAction.java:53)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:185)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:74)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:136)
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:124)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:217)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:96)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
'}

Btw. how can I change the column name? The following SQL does not work:

ALTER TABLE profile RENAME COLUMN "_scrapeRun" TO "_scraperun";

**Comment by dobe** [comment]
hi @joergrech 

the underscore is reserved for system columns (see https://crate.io/docs/stable/sql/ddl.html#naming-restrictions and https://crate.io/docs/stable/sql/ddl.html#system-columns). Can you tell me how you created the table with such column names, this might be a bug. Also this error message is very confusing, we will change that.

Is it a big problem, that underscores are not allowed as a starting character of a column name, can you tell me a bit about your use-case.

thx, bernd

**Comment by joergrech** [comment]
Hi Bernd,
  the table was created by importing json data from MongoDB via the COPY command ("COPY profile FROM out.json") as described in the docs (https://crate.io/docs/stable/best_practice/migrating_from_mongodb.html). 
As I only want to test crate: is it possible to alter the column names or do I need to delete the table, change the column names in the json file and reimport?

Bye,
Joerg

**Comment by dobe** [comment]
jep, copy from does no validation (see https://crate.io/docs/stable/sql/dml.html#id1) . so the only solution is currently to change the json file, since the json gets imported directly as the raw document.

**Comment by dobe** [comment]
oh, you probably just need to quote the column name if it is camel case:
```
SELECT * FROM profile WHERE "_scrapeRun"=5 LIMIT 2
```

**Comment by joergrech** [comment]
I tried it with a single quote but that did not work:

SELECT * FROM profile WHERE '_scrapeRun'=5 LIMIT 2

SELECT * FROM profile WHERE '_scrapeRun'='5' LIMIT 2

Currently I'm reimporting so I can't check the double quotes.

**Comment by joergrech** [comment]
Interestingly I now found out the a) selecting with a column name in single quotes does not work (it works without single quotes or with double quotes) and b) column names have to be lower case or within double quotes or they cannot be used (scrapeRun will be changed to scraperun and then the Exception is thrown that it cannot find the column. Values, however, have to be encased in single quotes - crate will interpret values in double quotes as column (and throw an exception in the Java client).

**Comment by mfussenegger** [comment]
Yes this is how quoting in SQL works. 

See also https://crate.io/docs/en/latest/sql/reference/lexical_structure.html?highlight=lexical and this https://github.com/crate/crate/issues/1421 issue.

**Comment by dobe** [comment]
i am closing this issue, since it seems to be related to quoting. we can re-open if that is not the case
