### ISSUE TITLE
crate-admin blank after upgrading to 0.52.3

### ISSUE THREAD

**Issue by Samuman** [crate/crate#3040]
Hello.

After I upgraded to Crate 0.52.3 admin page is not loading anymore. Page is completely blank. I tried this on multiple nodes and even a new instance on Google Cloud Platform had the same issue.

Browser:
Google Chrome 46.0.2490.86 (32-bits)

This is the error log from browser console:

    Uncaught Error: [$injector:modulerr] Failed to instantiate module crate due to:
    Error: [$injector:modulerr] Failed to instantiate module truncate due to:
    Error: [$injector:nomod] Module 'truncate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
    http://errors.angularjs.org/1.3.15/$injector/nomod?p0=truncate
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:412
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:8758
    at b (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:8330)
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:8642
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:17076
    at f (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:797)
    at n (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:16924)
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:17093
    at f (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:797)
    at n (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:16924)
    http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=truncate&p1=Error%…3A4200%2F_plugin%2Fcrate-admin%2Fscripts%2F21417c0c.angular.js%3A1%3A16924)
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:412
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:17352
    at f (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:797)
    at n (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:16924)
    at http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:17093
    at f (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:797)
    at n (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:16924)
    at Sa (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:18614)
    at h (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:6443)
    at Object._ [as bootstrap] (http://node1:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:6753)
    http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=crate&p1=Error%3A%…%3A4200%2F_plugin%2Fcrate-admin%2Fscripts%2F21417c0c.angular.js%3A1%3A6753)

**Comment by chaudum** [comment]
hi @Samuman 
thanks for reporting the issue. we'll take a look and let you know when it is resolved.
best,
christian

**Comment by mikethebeer** [comment]
Hi @Samuman ,

fix is already in crate-admin 0.15. (see https://github.com/crate/crate-admin/issues/173)

**Comment by mikethebeer** [comment]
Fix is in new version of Crate 0.52.4 stable
https://github.com/crate/crate/releases/tag/0.52.4
