### ISSUE TITLE
rejected execution (queue capacity 50)

### ISSUE THREAD

**Issue by ghsau** [crate/crate#3229]
StatementCallback; uncategorized SQLException for SQL [UPDATE merchant_sea SET tag_name=['XXXX','YYYY','ZZZZ'],tag_id=[10,18,70] WHERE serial_number='CH01154630']; SQL state [null]; error code [0]; rejected execution (queue capacity 50) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@3eed7c1c; nested exception is java.sql.SQLException: rejected execution (queue capacity 50) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@3eed7c1c

**ENV**
- server version: 0.47.7, nodes: 5
- client version: 0.51.6
- jdbc version: 1.9.1

`UPDATE merchant_sea SET tag_name=['XXXX','YYYY','ZZZZ'],tag_id=[10,18,70] WHERE serial_number='CH01154630'`

**merchant_sea**
- Configured Replicas: 4
- Configured Shards: 2

The serial_number is **primary key**, QPS average 20. How can I solve this problem?
Look forward to your favourable reply.

**Detail stack info**

io.crate.action.sql.SQLActionException: rejected execution (queue capacity 50) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@3eed7c1c
        at io.crate.action.sql.TransportBaseSQLAction.buildSQLActionException(TransportBaseSQLAction.java:357) ~[na:na]
        at io.crate.action.sql.TransportBaseSQLAction$2.onFailure(TransportBaseSQLAction.java:239) ~[na:na]
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[na:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.setExceptionAndMaybeLog(Futures.java:1704) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.setOneValue(Futures.java:1755) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture.access$400(Futures.java:1608) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.Futures$CombinedFuture$2.run(Futures.java:1686) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[na:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202) ~[guava-15.0.jar:na]
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) ~[guava-15.0.jar:na]
        at io.crate.executor.transport.task.UpsertByIdTask$1.onFailure(UpsertByIdTask.java:165) ~[na:na]
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$2.handleException(TransportShardReplicationOperationAction.java:462) ~[na:na]
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleException(MessageChannelHandler.java:185) ~[na:na]
        at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:175) ~[na:na]
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:125) ~[na:na]

**Comment by mikethebeer** [comment]
Hi @ghsau,
thanks for reporting the issue. we'll take a look and let you know if we could reproduce your problem.
Best,
Michael

**Comment by bogensberger** [comment]
Hi @ghsau,

thanks for reporting the issue. Could you please provide me the following information?
- table schema of merchant_sea (just execute: SHOW CREATE TABLE merchant_sea;)
- are you doing bulk updates?
- how many updates are you doing in parallel?
- could you also provide me the settings file of the nodes if possible?

Thanks,
Philipp
