### ISSUE TITLE
Unable to start Exception org.elasticsearch.ElasticsearchIllegalStateException: Failed to created node environment 	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:172)

### ISSUE THREAD

**Issue by denisbetsi** [crate/crate#3434]
After a stress test, one of the test tables became critical with message Shard Missing. Attempts to restart the servers resulted in Crate service unable to restart.

Last error was:
Exception
org.elasticsearch.ElasticsearchIllegalStateException: Failed to created node environment
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:172)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:82)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:267)
Caused by: java.nio.file.AccessDeniedException: /crate-data-1/crate
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:132)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:170)

Prior to the crash there were tons of messages

[2016-04-13 18:54:12,703][WARN ][netty.channel.socket.nio.AbstractNioSelector] Failed to accept a connection.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Prior to that there were

[2016-04-13 18:53:31,735][WARN ][gateway.local.state.meta ] [ip-10-0-0-11] failed to find dangling indices
java.nio.file.FileSystemException: /var/lib/crate/crate/nodes/0/indices: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at org.elasticsearch.env.NodeEnvironment.findAllIndices(NodeEnvironment.java:712)
	at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.clusterChanged(LocalGatewayMetaState.java:253)
	at org.elasticsearch.gateway.local.LocalGateway.clusterChanged(LocalGateway.java:215)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Now looking at the last error message 

Caused by: java.nio.file.AccessDeniedException: /crate-data-1/crate

I examined that folder where all the data of crate should of been housed. That whole directory is now completely EMPTY. So all data is gone somewhere.

Very concerned about going into production if this is a possibility.

I am trying to recreate these folders by hand right now to see If I can restart it.  Obviously all of the data has disappeared somehow.

**Comment by joemoe** [comment]
hi @denisbetsi, thanks for reporting this. we will definitely have a look at this. we'll keep you posted.

**Comment by jodok** [comment]
i've been discussing this with denis on intercom. the root cause is the "too many open files". i'm not sure how helpful the debugging is going to be. rather make sure that the centos6 series also set the ulimits correctly.

**Comment by joemoe** [comment]
yes, we are heading this way first!

**Comment by joemoe** [comment]
hi @denisbetsi, this is fixed for you. right?

**Comment by denisbetsi** [comment]
I had to reinstall crate and start over on a new cluster. Increasing ulimit on amazon boxes and making sure there's at least 1 replica and few shards made sure that issue didn't come back. Thank you.
