### ISSUE TITLE
ClassCastException during INSERT

### ISSUE THREAD

**Issue by hasnainjaved** [crate/crate#3474]
Hi,

With the following table definition, inserting data results in an exception (crate version 0.54.8)

`'CREATE TABLE my_table ("id" string PRIMARY KEY, "field1" array(object AS ("stringField" string, "integerField" integer)), "field2" array(object AS ("stringField" string, "integerField" integer)), "field3" array(object AS ("id" long PRIMARY KEY, "stringField" string, "integerField" integer))) WITH (number_of_replicas='0', refresh_interval='1000', column_policy='dynamic')'`

Stack trace below

`SQLActionException{errorCode=5000, status=INTERNAL_SERVER_ERROR, stackTrace='java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.Map
	at io.crate.analyze.InsertFromValuesAnalyzer.addValues(InsertFromValuesAnalyzer.java:269)
	at io.crate.analyze.InsertFromValuesAnalyzer.analyzeValues(InsertFromValuesAnalyzer.java:198)
	at io.crate.analyze.InsertFromValuesAnalyzer.analyze(InsertFromValuesAnalyzer.java:121)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitInsertFromValues(Analyzer.java:122)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitInsertFromValues(Analyzer.java:108)
	at io.crate.sql.tree.InsertFromValues.accept(InsertFromValues.java:90)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.Analyzer.analyze(Analyzer.java:102)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:202)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:191)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:80)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:139)
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:127)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:222)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:96)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

If the primary key is removed from the nested object array column `field3`, the insert goes through with out any errors.

Kind Regards

**Comment by joemoe** [comment]
hi @hasnainjaved, we will look into this. thanks for reporting.

**Comment by kovrus** [comment]
hi @hasnainjaved!
Thank you for reporting and using Crate. Crate does not allow to set primary key constraints within an array column object type. We have just added a check for such cases, which weren't exitiing before.

**Comment by hasnainjaved** [comment]
Hello,

Thanks for the fix. Could you kindly make it clear in the documentation as well ?    

https://crate.io/docs/reference/sql/reference/create_table.html#primary-key-constraint

Kind Regards.
