### ISSUE TITLE
Error while trying to make select on second level arrays

### ISSUE THREAD

**Issue by axelex** [crate/crate#3635]
I'm trying to run this query:
- select categories['items']['id'],categories['items']['parent_id'] from assets order by _id asc limit 100;
and I'm getting this error:
- 'SQLActionException[java.util.ArrayList cannot be cast to java.lang.Number]'

categories is an array of objects and items is as well an array of objects.
both columns(categories['items']['id'],categories['items']['parent_id']) are of type integer inside the arrays;
when changed their type to string the query worked, but the fields should be type integer.

Can someone help me with this issue?
Thank you!

**Comment by mfussenegger** [comment]
Thanks for reporting, we'll take a look at it. It seems to be a bug
Steps to reproduce:

    cr> create table assets (categories array(object as (items array(object as (id int)))));
    cr> insert into assets (categories) values ([{items=[{id=10}, {id=20}]}]);

	cr> select categories['items']['id'] from assets;
	SQLActionException[ClassCastException: java.util.ArrayList cannot be cast to java.lang.Number]

	SQLActionException: INTERNAL_SERVER_ERROR 5000 ClassCastException: java.util.ArrayList cannot be cast to java.lang.Number
		at io.crate.types.IntegerType.value(IntegerType.java:68)
		at io.crate.types.IntegerType.value(IntegerType.java:31)
		at io.crate.types.ArrayType.value(ArrayType.java:75)
		at io.crate.types.ArrayType.value(ArrayType.java:32)
		at io.crate.operation.reference.doc.lucene.DocCollectorExpression$1.value(DocCollectorExpression.java:72)
		at io.crate.operation.InputRow.get(InputRow.java:47)
		at io.crate.executor.transport.StreamBucket$Builder.add(StreamBucket.java:68)
		at io.crate.operation.fetch.FetchCollector.collect(FetchCollector.java:93)
		at io.crate.operation.fetch.NodeFetchOperation.doFetch(NodeFetchOperation.java:98)
		at io.crate.executor.transport.TransportFetchNodeAction$3.doRun(TransportFetchNodeAction.java:130)

**Comment by matriv** [comment]
Bug had been fixed and will be available in versions: 0.54.10 and 0.55.
