### ISSUE TITLE
Connect to 'localhost:4300' failed / Message not fully read error

### ISSUE THREAD

**Issue by camsaul** [crate/crate#3786]
Crate has [completely stopped working for us folks at Metabase today](https://circleci.com/gh/metabase/metabase) for reasons I don't understand. In my server logs I see (repeatedly):

```
java.sql.SQLException - Connect to 'localhost:4300' failed
io.crate.client.jdbc.CrateConnection$connect (CrateConnection.java:57)
io.crate.client.jdbc.CrateDriver$connect (CrateDriver.java:116)
```

and in the Crate logs I see (repeatedly):
```
[2016-07-11 17:33:28,672][WARN ][transport.netty          ] [Puishannt] exception caught on transport layer [[id: 0x36be0566, /127.0.0.1:49826 => /127.0.0.1:4300]], closing connection
java.lang.IllegalStateException: Message not fully read (request) for requestId [0], action [cluster/nodes/info], readerIndex [39] vs expected [57]; resetting
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:120)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

This is happening with tests that previously worked fine. In addition to our CI box, I'm able to reproduce this on my local machine with crate 0.55.0, 0.55.1, and 0.55.2, and all versions of Metabase.

**Comment by chaudum** [comment]
@camsaul this is due to the update from 0.54 to 0.55 (we released 0.55 stable yesterday).
crate java/jdbc client versions are always bound to a specific crate server version (see https://github.com/crate/crate-jdbc/tree/1.13#compatibility)

**Comment by mikethebeer** [comment]
@camsaul https://github.com/metabase/metabase/pull/2934

**Comment by camsaul** [comment]
That fixed it. Feel free to close this.

Would it make sense to have an error message letting someone know they're using an unsupported version of the client library? It came as a huge shock to me that a new minor release of the Create server would break compatibility with the previous release of the Crate client library.

**Comment by Agn3s** [comment]
Hello, I'm sorry to post here, I see this topic is closed. You say the problem is fixed, but I installed crate.io 0.55.4 and metabase 0.19.3 and when I try to add data in metabase i get a database connection error. Can you help me please? Thanks a lot.
