### ISSUE TITLE
error message in log files during upgrade to 0.55.2

### ISSUE THREAD

**Issue by jodok** [crate/crate#3791]
i'm updating a cluster from 0.54.9 to 0.55.2 and the migration procress of indices is running already for close to one hour. i see periodically the error the the table stats can't be retrieved. which is obvious, since the cluster isn't fully operational.
my expected user behaviour: start the process that gathers table stats at a later point, or - don't show that error in the log files.

```
Jul 12 14:17:30 data-01.pangea.local crate[4134]: [2016-07-12 14:17:30,668][ERROR][io.crate.planner.TableStatsService] [data-01] error retrieving table stats
Jul 12 14:17:30 data-01.pangea.local crate[4134]: SQLActionException: INTERNAL_SERVER_ERROR 5000 NullPointerException in io.crate.executor.transport.TransportExecutor$TaskCollectingVisitor.executionPhasesTask(TransportExecutor.java:217)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.executor.transport.TransportExecutor$TaskCollectingVisitor.executionPhasesTask(TransportExecutor.java:217)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.executor.transport.TransportExecutor$TaskCollectingVisitor.visitPlan(TransportExecutor.java:211)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.executor.transport.TransportExecutor$TaskCollectingVisitor.visitPlan(TransportExecutor.java:170)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.planner.PlanVisitor.visitCollectAndMerge(PlanVisitor.java:69)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.planner.node.dql.CollectAndMerge.accept(CollectAndMerge.java:53)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.planner.PlanVisitor.process(PlanVisitor.java:41)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.executor.transport.TransportExecutor.newJob(TransportExecutor.java:144)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.action.sql.TransportBaseSQLAction.executePlan(TransportBaseSQLAction.java:245)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.action.sql.TransportBaseSQLAction.processAnalysis(TransportBaseSQLAction.java:235)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:214)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:200)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:82)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.planner.TableStatsService.updateStats(TableStatsService.java:77)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at io.crate.planner.TableStatsService.run(TableStatsService.java:73)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:640)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Jul 12 14:17:30 data-01.pangea.local crate[4134]: at java.lang.Thread.run(Thread.java:745)
```

**Comment by chaudum** [comment]
@jodok fix is on `master` on branch `0.55`
will be released with next hotfix
