### ISSUE TITLE
MASTER and DATA node has an ESTABLISHED connection but Recv-Q is not zero for a long time

### ISSUE THREAD

**Issue by jaykelin** [crate/crate#3990]
crate 0.55.2 cluster
10.1.113.172 - master
10.1.113.175、10.1.113.176
`[root@10_1_113_172 logs]# netstat -nap  | grep 4300 | grep 10.1.113.175`

> tcp        0      0 ::ffff:10.1.113.172:6488    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6485    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6492    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp   **121347**      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2063    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2066    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6482    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6489    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2059    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2064    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6490    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2057    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6493    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp   **2092697**      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2056    ESTABLISHED 63545/java          
> tcp    **78319**      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2065    ESTABLISHED 63545/java          
> tcp   **148138**      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2061    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6484    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2068    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2060    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2058    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6491    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp   **112078**      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2062    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6494    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6486    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:4300    ::ffff:10.1.113.175:2067    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6487    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java          
> tcp        0      0 ::ffff:10.1.113.172:6483    ::ffff:10.1.113.175:4300    ESTABLISHED 63545/java

above 5 socket with Recv-Q not zero for a long time， and not change. I‘m confused, how that could by happened.

and then i check the logs of DATA node[10.1.113.175], there are many WARN info, like this 

> [WARN ][indices.cluster          ] [crate175] [[.partitioned.tableName.045j4c1h6omj0dpd64sg][6]] marking and sending shard failed due to [failed recovery]  
> ......... nested: ElasticsearchTimeoutException[no activity after [30m]];
>         at org.elasticsearch.indices.recovery.RecoveriesCollection$RecoveryMonitor.doRun(RecoveriesCollection.java:235)
>         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: ElasticsearchTimeoutException[no activity after [30m]]

at the same time， JDBC connect to cluster is not working :

> Error: java.io.IOException: java.sql.SQLException: Connect to '10.1.113.172:4300' failed
> ....
> Caused by: java.sql.SQLException: Connect to '10.1.113.172:4300' failed
> at io.crate.client.jdbc.CrateConnection.connect(CrateConnection.java:60)
> at io.crate.client.jdbc.CrateDriver.connect(CrateDriver.java:76)
> at java.sql.DriverManager.getConnection(DriverManager.java:571)
> ....
> Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.1.113.172}{10.1.113.172:4300}]]
> at io.crate.shade.org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
> at io.crate.shade.org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
> at io.crate.client.InternalCrateClient.execute(InternalCrateClient.java:85)
> at io.crate.client.InternalCrateClient.execute(InternalCrateClient.java:68)
> at io.crate.client.InternalCrateClient.sql(InternalCrateClient.java:57)
> at io.crate.client.CrateClient.sql(CrateClient.java:145)
> at io.crate.client.jdbc.CrateStatement.execute(CrateStatement.java:65)
> at io.crate.client.jdbc.CrateStatementBase.executeQuery(CrateStatementBase.java:37)
> at io.crate.client.jdbc.CrateDatabaseMetaData.getDatabaseProductVersion(CrateDatabaseMetaData.java:79)
> at io.crate.client.jdbc.CrateConnection.connect(CrateConnection.java:57)

**Comment by chaudum** [comment]
Hi @jaykelin 
I don't quite understand your issue 😑
Could you provide some more information about how you configured the nodes (`crate.yml`, ...) of the cluster and how you try to connect with JDBC (version, ...).
In Crate you usually don't have the notation of master/data nodes if not explicitly configured.
And if you only have dedicated master and data nodes but no client nodes, you won't be able to connect.

**Comment by jaykelin** [comment]
Hi @chaudum 
I have fixed this problem, solution that in https://github.com/crate/crate/issues/3984 i try to explain.

By the way, I suggest that crate.io team can provide an optimal configuration in the production environment
