### ISSUE TITLE
Exception error on POST request with SQLAlchemy

### ISSUE THREAD

**Issue by amrbz** [crate/crate#4423]
Good day
I'm using Docker, Python 2.7, Flask and SQLAlchemy to work with Crate 0.56.3. 

I'm sending a post request from client to server. Here is my **app.py** file

```
import json
import sys
from flask import Flask, request, Response, jsonify
from flask_cors import CORS, cross_origin

app = Flask(__name__)
CORS(app)

from properties import getProperties
from properties import addProperty

@app.route('/properties', methods = ['GET', 'POST', 'OPTIONS'])
@cross_origin()
def properties():
    if request.method == 'GET':
        properties = getProperties()
        data = list()
        for property in properties:
            row = {
                'id': property.id,
                'propertyName': property.property_name,
                'totalNumberOfRooms': property.total_number_of_rooms,
                'publicationDate': str(property.publication_date),
                'contactPersonName': property.contact_person_name,
                'city': property.city,
                'country': property.country,
                'zipCode': property.zip_code,
                'contactNumber': property.contact_number,
                'alternativeNumber': property.alternative_number,
                'location': property.location,
                'checkInTime': str(property.check_in_time),
                'checkOutTime': str(property.check_out_time)}

            data.append(row)

        return Response(response=json.dumps({'properties': data}, ensure_ascii=False, indent=4), status=200, mimetype='application/json; charset=utf-8')
    elif request.method == 'POST':
        return addProperty()


if __name__ == '__main__':
    sys.setdefaultencoding('utf-8')
    app.run()
```

**properties.py**

```
import uuid
import sqlalchemy as sa
from datetime import datetime
from sqlalchemy import exc, Column, String, Integer, DateTime, ARRAY
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import scoped_session, sessionmaker
from DB import engine
from flask import request

DBSession = scoped_session(sessionmaker())
Base = declarative_base()

DBSession.configure(bind=engine)
Base.metadata.bind = engine

class Property(Base):
    __tablename__ = 'properties'
    id = Column(String, default=lambda: str(uuid.uuid4()), primary_key=True)
    publication_date = Column(DateTime, default=lambda: datetime.now())
    city = Column(String)
    country = Column(String)
    zip_code = Column(String)
    address = Column(String)


def getProperties():
    properties = DBSession.query(Property).order_by(Property.publication_date).all()
    DBSession.close()
    return properties
![screenshot from 2016-11-12 18-12-28](https://cloud.githubusercontent.com/assets/13852826/20238878/d81edb00-a905-11e6-9d3a-d0f1ce6a38bd.png)


def addProperty():
    data = request.get_json()

    property = Property()

    property.city = data['city']
    property.country = data['country']
    property.zip_code = data['zipCode']
    property.address = data['address']
    property.contact_number = data['contactNumber']

    try:
        DBSession.add(property)
        DBSession.commit()
    except exc.SQLAlchemyError:
        DBSession.rollback()
        raise
    finally:
        client = Base.metadata.bind.raw_connection().connection.client
        client.sql("refresh table")
        DBSession.close()
```

And on commit Exception error raises.

```
root@cs55357:~# docker logs backend 
[12/Nov/2016:15:09:47] ENGINE Bus STARTING
[12/Nov/2016:15:09:47] ENGINE Started monitor thread '_TimeoutMonitor'.
[12/Nov/2016:15:09:47] ENGINE Started monitor thread 'Autoreloader'.
[12/Nov/2016:15:09:48] ENGINE Serving on http://0.0.0.0
[12/Nov/2016:15:09:48] ENGINE Bus STARTED
[2016-11-12 15:09:53,056] ERROR in app: Exception on /properties [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/opt/web/app.py", line 49, in properties
    return addProperty()
  File "/opt/web/properties.py", line 64, in addProperty
    client.sql("refresh table")
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 304, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 416, in _json_request
    _raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 170, in _raise_for_status
    error_trace=error_trace)
ProgrammingError: SQLActionException[SQLParseException: line 1:14: no viable alternative at input '<EOF>']
```

What caused the exception error?

**Comment by mfussenegger** [comment]
As seen in your stacktrace the error is caused by `client.sql("refresh table")`:

```
 File "/opt/web/properties.py", line 64, in addProperty
    client.sql("refresh table")
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 304, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 416, in _json_request
    _raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/http.py", line 170, in _raise_for_status
    error_trace=error_trace)
ProgrammingError: SQLActionException[SQLParseException: line 1:14: no viable alternative at input '<EOF>']
```


REFRESH TABLE requires one or more table names as parameters. See https://crate.io/docs/reference/sql/reference/refresh.html

**Comment by amrbz** [comment]
@mfussenegger Thank you very much! That worked )

**Comment by amrbz** [comment]
Quick question. 
```
property = DBSession.query(Property).get(property_id)
property.property_name = 'Hotel Bob Marley'
DBSession.commit()
```
According to 100500 sources this code must update a `property_name` value of `property` object. But it does not. Why?

**Comment by celaus** [comment]
@amrbz Hi, I am not sure what you are looking for :) can you explain in more detail? is there any error?

**Comment by amrbz** [comment]
Yes, there is an error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2333, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cptree.py", line 287, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/opt/web/app.py", line 134, in property_basic_info
    return update_property_basic_info(property_id)
  File "/opt/web/properties.py", line 168, in update_property_basic_info
    DBSession.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 172, in save_obj
    mapper, table, update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 732, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1015, in _execute_clauseelement
    fn(self, elem, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/sqlalchemy/compiler.py", line 88, in crate_before_execute
    return rewrite_update(clauseelement, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/crate/client/sqlalchemy/compiler.py", line 64, in rewrite_update
    for key, val in _params.items():
AttributeError: 'list' object has no attribute 'items'
```

As a result can't update a record

**Comment by chaudum** [comment]
@amrbz related to https://github.com/crate/crate-python/issues/187 ?

**Comment by amrbz** [comment]
@chaudum Great, all good now. Thanks! )
