### ISSUE TITLE
java.sql.SQLException: ColumnUnknownException without any reason

### ISSUE THREAD

**Issue by RaniRaven** [crate/crate#4525]
**CrateDB version**: 0.56/4

**JVM version**: 1.8.0.111

**OS version / environment description**: N/A

**Problem description**:

I get this exception while trying to query crate JDBC, using a data virtualization product.
Note that the simple JDBC application is working.
It seems like some of the JDBC api-s were not implemented correctly there.

Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
Cause: ColumnUnknownException: Column shipdate unknown

com.compositesw.cdms.webapi.WebapiException: Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
Cause: ColumnUnknownException: Column shipdate unknown
	Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
	at com.compositesw.cdms.webapi.PrefetchCursor$LoadPipeThread.run(PrefetchCursor.java:284)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
	at com.compositesw.server.qe.QueryResult.next(SourceFile:349)
	at com.compositesw.cdms.webapi.PrefetchCursor$LoadPipeThread.run(PrefetchCursor.java:264)
	... 3 more
Caused by: Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
	at com.compositesw.server.cursors.SortedCursor.a(SourceFile:439)
	at com.compositesw.server.cursors.SortedCursor.next(SourceFile:236)
	at com.compositesw.server.qe.physical.operator.ExternalMergeSort.next(SourceFile:175)
	at com.compositesw.server.qe.topology.SelectPTree.nextInternal(SourceFile:399)
	at com.compositesw.server.qe.topology.SelectPTree.next(SourceFile:378)
	at com.compositesw.server.qe.QueryResult.next(SourceFile:333)
	... 4 more
Caused by: Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
	at com.compositesw.server.cursors.AbstractHashCursor.prepare(SourceFile:391)
	at com.compositesw.server.cursors.GroupByCursor.prepare(SourceFile:618)
	at com.compositesw.server.cursors.GroupByCursor.next(SourceFile:434)
	at com.compositesw.server.qe.physical.operator.HashGroupByNode.next(SourceFile:250)
	at com.compositesw.server.cursors.SortedCursor.c(SourceFile:476)
	at com.compositesw.server.cursors.SortedCursor.b(SourceFile:47)
	at com.compositesw.server.cursors.SortedCursor$a.run(SourceFile:416)
	... 3 more
Caused by: Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
	at com.compositesw.server.cursors.AbstractHashCursor.loadHash(SourceFile:648)
	at com.compositesw.server.cursors.AbstractHashCursor$b.run(SourceFile:425)
	... 3 more
Caused by: Unable to retrieve result from data source "/shared/PoC2/DataSources/CrateTryStandAloneJDBC" during
    query execution.  Failed query: "SELECT
    lineitem.returnflag,lineitem.linestatus,lineitem.quantity,lineitem.extendedprice,lineitem.discount,lineitem.tax
    FROM lineitem lineitem WHERE lineitem.shipdate <= '1998-09-01 00:00:00'".  [data-3923000]
	at com.compositesw.cdms.ds.jdbc.JdbcConnectionTableCursor.next(JdbcConnectionTableCursor.java:240)
	at com.compositesw.data.cursor.MeterCursor.next(MeterCursor.java:86)
	at com.compositesw.server.qe.physical.operator.SqlScan.next(SourceFile:761)
	at com.compositesw.server.cursors.AbstractHashCursor.loadHash(SourceFile:455)
	... 4 more
Caused by: java.sql.SQLException: ColumnUnknownException: Column shipdate unknown
	at io.crate.client.jdbc.CrateStatement.execute(CrateStatement.java:72)
	at io.crate.client.jdbc.CrateStatementBase.executeQuery(CrateStatementBase.java:37)
	at com.compositesw.cdms.ds.jdbc.JdbcConnectionTableCursor.createResultSet(JdbcConnectionTableCursor.java:471)
	at com.compositesw.cdms.ds.jdbc.JdbcConnectionTableCursor.next(JdbcConnectionTableCursor.java:192)
	... 7 more
Caused by: SQLActionException: NOT_FOUND 4043 ColumnUnknownException: Column shipdate unknown
	at io.crate.analyze.relations.FullQualifedNameFieldProvider.resolveField(FullQualifedNameFieldProvider.java:125)
	at io.crate.analyze.relations.FullQualifedNameFieldProvider.resolveField(FullQualifedNameFieldProvider.java:41)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:586)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitQualifiedNameReference(ExpressionAnalyzer.java:258)
	at io.crate.sql.tree.QualifiedNameReference.accept(QualifiedNameReference.java:44)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:460)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitComparisonExpression(ExpressionAnalyzer.java:258)
	at io.crate.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:90)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:147)
	at io.crate.analyze.relations.RelationAnalyzer.analyzeWhere(RelationAnalyzer.java:300)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:121)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:56)
	at io.crate.sql.tree.QuerySpecification.accept(QuerySpecification.java:116)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:73)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:77)
	at io.crate.analyze.SelectStatementAnalyzer.visitQuery(SelectStatementAnalyzer.java:43)
	at io.crate.analyze.SelectStatementAnalyzer.visitQuery(SelectStatementAnalyzer.java:31)
	at io.crate.sql.tree.Query.accept(Query.java:89)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:121)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:117)
	at io.crate.sql.tree.Query.accept(Query.java:89)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:31)
	at io.crate.analyze.Analyzer.analyzedStatement(Analyzer.java:111)
	at io.crate.analyze.Analyzer.analyze(Analyzer.java:105)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:210)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:200)
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:82)
	at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:137)
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:133)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:245)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	at com.compositesw.cdms.webapi.WebapiException_SOAPSerializer.doDeserialize(WebapiException_SOAPSerializer.java:58)
	at com.sun.xml.rpc.encoding.ObjectSerializerBase.deserialize(ObjectSerializerBase.java:209)
	at com.sun.xml.rpc.encoding.ReferenceableSerializerImpl.deserialize(ReferenceableSerializerImpl.java:172)
	at com.compositesw.cdms.webapi.service.WMetaDataSvc_dataset_fetch_Fault_SOAPSerializer.deserializeDetail(WMetaDataSvc_dataset_fetch_Fault_SOAPSerializer.java:54)
	at com.sun.xml.rpc.encoding.SOAPFaultInfoSerializer.doDeserialize(SOAPFaultInfoSerializer.java:151)
	at com.sun.xml.rpc.encoding.ObjectSerializerBase.deserialize(ObjectSerializerBase.java:209)
	at com.sun.xml.rpc.encoding.ReferenceableSerializerImpl.deserialize(ReferenceableSerializerImpl.java:172)
	at com.compositesw.cdms.webapi.service.WMetaDataSvc_Stub._readBodyFaultElement(WMetaDataSvc_Stub.java:25090)
	at com.sun.xml.rpc.client.StreamingSender._send(StreamingSender.java:238)
	at com.compositesw.cdms.webapi.service.WMetaDataSvc_Stub.dataset_fetch(WMetaDataSvc_Stub.java:13847)
	at com.compositesw.cdms.webapi.WDataset$FetcherThread.run(WDataset.java:273)

Version Information: Studio 7.0.4.00.00, Build ID Build: 58e9f86-2016-07-28, Server 7.0.4.00.00

**Steps to reproduce**:

**Use case**:
It seems that every table will cause this through the specific tests, that can be understood from the exception.

**Feature description**:

**Comment by celaus** [comment]
Hi! That's weird ... what version of the JDBC driver are you using? 

additionally, is the query working in other drivers (crash uses crate-python, or the web interface)?

Cheers, Claus

**Comment by joemoe** [comment]
hi @RaniRaven, can you answer @celaus questions?

**Comment by mfussenegger** [comment]
Closing this. Feel free to re-open the issue if this is still an issue and you can provide the information @celaus asked for.
