### ISSUE TITLE
QueryParsingException exception for valid timestamp

### ISSUE THREAD

**Issue by l7s** [crate/crate#4661]
**CrateDB version**: 0.54.5

**JVM version**: 1.8.0_60

**OS version / environment description**: Debian 7 x64

**Problem description**:

Sending request as below:
```
POST /_sql HTTP/1.1.
Host: 192.168.10.32:4200.
User-Agent: Guzzle/5.3.0 curl/7.26.0 PHP/5.5.17-1~dotdeb.1.
Content-Type: application/json.
Content-Length: 114.
.
{"stmt":"DELETE FROM stats WHERE timestamp = ? AND id NOT IN (?, ?)","args":["1360368000000","5992622","5992632"]}
```

results in `org.elasticsearch.index.query.QueryParsingException` being thrown:

```
[2017-01-07 13:04:32,167][DEBUG][action.deletebyquery     ] [crate-eu-1] [stats][1], node[Bm8Jxe46R6CWDEmwNtST7A], [P], s[STARTED]: Failed to execute [delete_by_query {[stats][], query [{"query":{"bool":{"must":[{"term":{"timestamp":1360368000000}},{"bool":{"must_not":{"filtered":{"query":{"match_all":{}},"filter":{"terms":{"id":[5992622,5992632]}}}}}}]}}}]}]
org.elasticsearch.index.query.QueryParsingException: [stats] Failed to parse
	at org.elasticsearch.index.query.IndexQueryParserService.parseQuery(IndexQueryParserService.java:370)
	at org.elasticsearch.index.shard.IndexShard.prepareDeleteByQuery(IndexShard.java:549)
	at org.elasticsearch.action.deletebyquery.TransportShardDeleteByQueryAction.shardOperationOnPrimary(TransportShardDeleteByQueryAction.java:116)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:590)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:444)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid format: "1360368000000" is malformed at "0000"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseValue(DateFieldMapper.java:276)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.indexedValueForSearch(DateFieldMapper.java:265)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.termQuery(NumberFieldMapper.java:277)
	at org.elasticsearch.index.query.TermQueryParser.parse(TermQueryParser.java:105)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:307)
	at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:93)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:307)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
	at org.elasticsearch.index.query.IndexQueryParserService.parseQuery(IndexQueryParserService.java:354)
	... 8 more
```

**Steps to reproduce**: 

1. Create table as below:
```
CREATE TABLE stats (
  id long primary key,
  partner_id integer,
  web_product_id integer,
  customer_id integer,
  user_id integer,
  country string,
  metric string,
  value float,
  timestamp timestamp,
  object_class string,
  object_id string
);
```

2. Run query: `{"stmt":"DELETE FROM stats WHERE timestamp = ? AND id NOT IN (?, ?)","args":["1360368000000","5992622","5992632"]}`

**Comment by matriv** [comment]
Hello @l7s,

This is issue has been resolved in later releases. Our current release is 1.0.1, would it be possible for you to upgrade to that [release?](https://crate.io/releasenotes/stable-release-1-0-1/)

**Comment by l7s** [comment]
Hi, thanks for update. Can we upgrade straight from 0.54.5 to 1.0.1 ? Is data files format backward compatible? Or shall we upgrade first to some intermediary version (which?) before upgrading to 1.0.1 ?

Regards,
Chris

**Comment by matriv** [comment]
Hi!

The data files are backwards compatible but there is a possible BREAKING change regarding the blob storage: (see release note link on previous comment). Moreover there are several other breaking changes in the in between versions which might affect you. I would suggest to check the BREAKING changes in the changelog file between these lines:
https://github.com/crate/crate/blob/1.0/CHANGES.txt#L1066
https://github.com/crate/crate/blob/1.0/CHANGES.txt#L50

A major change is that the current stable release (1.0.1) requires java 8 and the cratedb client is now using the [Postgres Wire Protocol](https://crate.io/docs/reference/protocols/postgres.html).

I'd suggest to read the BREAKING changes and ask for any clarification you'd need there before upgrading. Of course Ideally you should try to upgrade a testing/staging cluster before upgrading any production environment.

**Comment by l7s** [comment]
Hi, I can confirm after upgrading to v. 1.0.1 the problem is resolved. I think we can close this issue now.
Regards,
Chris

**Comment by matriv** [comment]
Great!
