### ISSUE TITLE
Channel is already closed

### ISSUE THREAD

**Issue by makeyang** [crate/crate#5297]
**CrateDB version**:
1.1
**JVM version**:
8u60
**OS version / environment description**:
CentOS release 6.6 (Final)
**Problem description**:

server throw below execption:

```
[2017-04-10 18:58:11,402][ERROR][io.crate.action.ActionListeners] error sending failure: java.lang.IllegalStateException: Channel is already closed
java.lang.IllegalStateException: Channel is already closed
	at org.elasticsearch.transport.netty.NettyTransportChannel.close(NettyTransportChannel.java:157)
	at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:131)
	at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:68)
	at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:152)
	at io.crate.action.ActionListeners$1.onFailure(ActionListeners.java:51)
	at io.crate.action.ActionListeners$1.onResponse(ActionListeners.java:44)
	at io.crate.action.ActionListeners$1.onResponse(ActionListeners.java:38)
	at io.crate.executor.transport.distributed.TransportDistributedResultAction$SendResponsePageResultListener.needMore(TransportDistributedResultAction.java:166)
	at io.crate.jobs.PageDownstreamContext.releaseListenersAndCloseContext(PageDownstreamContext.java:96)
	at io.crate.jobs.PageDownstreamContext.lambda$new$0(PageDownstreamContext.java:88)
	at io.crate.operation.merge.BatchPagingIterator.close(BatchPagingIterator.java:113)
	at io.crate.jobs.PageDownstreamContext.innerKill(PageDownstreamContext.java:290)
	at io.crate.jobs.AbstractExecutionSubContext.kill(AbstractExecutionSubContext.java:114)
	at io.crate.jobs.JobExecutionContext$RemoveSubContextListener.onFailure(JobExecutionContext.java:265)
	at io.crate.jobs.JobExecutionContext$RemoveSubContextListener.accept(JobExecutionContext.java:275)
	at io.crate.jobs.JobExecutionContext$RemoveSubContextListener.accept(JobExecutionContext.java:232)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.crate.jobs.SubExecutionContextFuture.completeExceptionally(SubExecutionContextFuture.java:111)
	at io.crate.jobs.SubExecutionContextFuture.close(SubExecutionContextFuture.java:63)
	at io.crate.jobs.AbstractExecutionSubContext.kill(AbstractExecutionSubContext.java:120)
	at io.crate.jobs.JobExecutionContext.kill(JobExecutionContext.java:202)
	at io.crate.jobs.JobContextService.killContexts(JobContextService.java:172)
	at io.crate.jobs.JobContextService.killJobs(JobContextService.java:196)
	at io.crate.executor.transport.kill.TransportKillJobsNodeAction.doKill(TransportKillJobsNodeAction.java:45)
	at io.crate.executor.transport.kill.TransportKillJobsNodeAction.doKill(TransportKillJobsNodeAction.java:32)
	at io.crate.executor.transport.kill.TransportKillNodeAction.nodeOperation(TransportKillNodeAction.java:78)
	at io.crate.executor.transport.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:43)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:372)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-04-10 18:58:11,402][TRACE][indices.breaker.request  ] [request] Adjusted breaker by [-16440] bytes, now [32880]
[2017-04-10 18:58:11,402][TRACE][indices.breaker.request  ] [request] Adjusted breaker by [16440] bytes, now [49320]
[2017-04-10 18:58:11,402][TRACE][transport.tracer         ] [A01-R04-I91-46] [738][crate/sql/node/merge/add_rows] sent response
[2017-04-10 18:58:11,403][TRACE][io.crate.jobs.NestedLoopContext] [A01-R04-I91-46] killing id=3 ctx=NestedLoopContext{id=3, leftCtx=PageDownstreamContext{id=2, numBuckets=10, exhausted={0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, closed=true}, rightCtx=null, closed=true} cause=java.lang.InterruptedException: Job killed
[2017-04-10 18:58:11,403][TRACE][io.crate.jobs.JobContextService] [A01-R04-I91-46] JobExecutionContext closed for job 9abcddaa-8c44-4abc-95b1-3689bf941693 removed it - 0 executionContexts remaining
java.lang.InterruptedException: Job killed
	at io.crate.jobs.AbstractExecutionSubContext.kill(AbstractExecutionSubContext.java:110)
	at io.crate.jobs.JobExecutionContext.kill(JobExecutionContext.java:202)
	at io.crate.jobs.JobContextService.killContexts(JobContextService.java:172)
	at io.crate.jobs.JobContextService.killJobs(JobContextService.java:196)
	at io.crate.executor.transport.kill.TransportKillJobsNodeAction.doKill(TransportKillJobsNodeAction.java:45)
	at io.crate.executor.transport.kill.TransportKillJobsNodeAction.doKill(TransportKillJobsNodeAction.java:32)
	at io.crate.executor.transport.kill.TransportKillNodeAction.nodeOperation(TransportKillNodeAction.java:78)
	at io.crate.executor.transport.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:43)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:372)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-04-10 18:58:11,404][TRACE][indices.breaker.request  ] [request] Adjusted breaker by [-16440] bytes, now [16440]
[2017-04-10 18:58:11,404][TRACE][transport.tracer         ] [A01-R04-I91-46] [68][crate/sql/node/merge/add_rows] sent response
[2017-04-10 18:58:11,404][TRACE][tasks                    ] [A01-R04-I91-46] unregister task for id: 190
[2017-04-10 18:58:11,404][TRACE][transport.tracer         ] [A01-R04-I91-46] [154][crate/sql/kill_jobs] received response from [{A01-R04-I91-46}{TOl2cm8KQVujRH46lMcP3Q}{172.28.91.46}{172.28.91.46:4360}{info.extended.type=sigar, http_address=172.28.91.46:4300}]
[2017-04-10 18:58:11,404][TRACE][io.crate.executor.transport.executionphases.InterceptingBatchConsumer] Killed 3 jobs before forwarding the failure=java.lang.NullPointerException
```

**Comment by mfussenegger** [comment]
Do you have a bit more information - what kind of queries were you executing? Did the client receive any error?

Are you able to reproduce this issue?

**Comment by joemoe** [comment]
hey @makeyang, can you provide answers to the questions of @mfussenegger?

**Comment by makeyang** [comment]
@mfussenegger  @joemoe 
I can't reproduce this issue. when I restart some time, it 'disappear'
