### ISSUE TITLE
upgrading from 1.0.6 to 1.1.2 fails for partitioned table

### ISSUE THREAD

**Issue by sonix07** [crate/crate#5379]
**CrateDB version**:1.1.2

**JVM version**:docker

**OS version / environment description**:docker

**Problem description**:
```
[/data/zelos-crate/nodes/0/indices/.partitioned.sometable.04732d1n68r3ge1g60o30c1g/1] please check and remove them if possible
	at io.crate.metadata.doc.CrateMetaDataUpgradeService.upgradeIndexMetaData(CrateMetaDataUpgradeService.java:76)
	at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:232)
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:89)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at io.crate.node.CrateNode.<init>(CrateNode.java:50)
	at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:193)
	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:300)
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:50)
Caused by: java.lang.IllegalStateException: [[.partitioned.sometable.04732d1n68r3ge1g60o30c1g][1]] no shard state found in any of: [/data/zelos-crate/nodes/0/indices/.partitioned.sometable.04732d1n68r3ge1g60o30c1g/1] please check and remove them if possible
	at io.crate.metadata.doc.CrateMetaDataUpgradeService.upgradeShardMetaData(CrateMetaDataUpgradeService.java:198)
	at io.crate.metadata.doc.CrateMetaDataUpgradeService.upgradeIndexMapping(CrateMetaDataUpgradeService.java:112)
	at io.crate.metadata.doc.CrateMetaDataUpgradeService.upgradeIndexMetaData(CrateMetaDataUpgradeService.java:73)
	... 28 more
```

table: doc.sometable	
shards: 36
docs: 23285982	
size: 4459487836 

```
+-------------+---------------+--------------------+----------------+----------------+----------------+------+-------------------------------------------------+-------------------------------------------------------------------------------+
| name        | crate_version |          memory_gb |   heap_size_gb |   disk_size_gb | max_open_files | cpus | uname                                           | jvm                                                                           |
+-------------+---------------+--------------------+----------------+----------------+----------------+------+-------------------------------------------------+-------------------------------------------------------------------------------+
| zelos1crate | 1.0.6         | 15.406768798828125 | 3.821044921875 | 460.7607421875 |        1048576 |    4 | Linux 007da64bf71a 3.10.0-514.el7.x86_64; amd64 | Java 1.8.0_121 Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13) |
| zelos2crate | 1.0.6         | 15.406768798828125 | 3.821044921875 | 460.7607421875 |        1048576 |    4 | Linux e644453c6d47 3.10.0-514.el7.x86_64; amd64 | Java 1.8.0_121 Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13) |
| zelos3crate | 1.0.6         | 15.406768798828125 | 3.821044921875 | 460.7607421875 |        1048576 |    4 | Linux de03eb1f2ebb 3.10.0-514.el7.x86_64; amd64 | Java 1.8.0_121 Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13) |
| zelos4crate | 1.0.6         | 15.406768798828125 | 3.821044921875 | 460.7607421875 |        1048576 |    4 | Linux decc74e53c2f 3.10.0-514.el7.x86_64; amd64 | Java 1.8.0_121 Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13) |
| zelos5crate | 1.0.6         | 15.406768798828125 | 3.821044921875 | 460.7607421875 |        1048576 |    4 | Linux 69d4f25db19a 3.10.0-514.el7.x86_64; amd64 | Java 1.8.0_121 Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13) |
| zelos6crate | 1.0.6         | 15.406768798828125 | 3.821044921875 | 460.7607421875 |        1048576 |    4 | Linux dd506673414e 3.10.0-514.el7.x86_64; amd64 | Java 1.8.0_121 Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13) |
| zelos7crate | 1.0.6         | 15.406768798828125 | 3.821044921875 | 460.7607421875 |        1048576 |    4 | Linux ce5a3557834c 3.10.0-514.el7.x86_64; amd64 | Java 1.8.0_121 Oracle Corporation OpenJDK 64-Bit Server VM (build 25.121-b13) |
+-------------+---------------+--------------------+----------------+----------------+----------------+------+-------------------------------------------------+-------------------------------------------------------------------------------+
SELECT 7 rows in set (0.043 sec)

```

**Comment by matriv** [comment]
Hello @sonix07,

Could you please paste us the contents of the problematic dir: `/data/zelos-crate/nodes/0/indices/.partitioned.sometable.04732d1n68r3ge1g60o30c1g/1`
on the node that raised the exception?

**Comment by sonix07** [comment]
@matriv 
I only have /data/zelos-crate/nodes/0/indices/.partitioned.sometable.04732d1n68r3ge1g60o30c1g/
**0, 3, 5, _state** 
would one of them be of any help?
I've reverted back to 1.0.6

**Comment by matriv** [comment]
@sonix07 

Are you sure that the dir **1** is missing from the node that threw the exception?

**Comment by sonix07** [comment]
@matriv 
yes I've checked 3 times, node number 7 was having trouble with the update and there was no **1** unfortunately... Thanks for the your help btw!

**Comment by matriv** [comment]
Thanks for the info, we'll try to reproduce the issue.

**Comment by matriv** [comment]
@sonix07 as a conclusion for our direct discussion, 

The issue you encounter is caused because you tried to perform a rolling upgrade. Unfortunately rolling upgrade is not supported for 1.0.x -> 1.1.2 as you can see also [here](https://crate.io/docs/reference/release_notes/1.1.2.html#version-1-1-2), so please do an upgrade with full cluster shutdown as suggested.

Your idea for preventing nodes with incompatible versions to join each other in a cluster is very good and has been added to our backlog, thanks!
