### ISSUE TITLE
Query fails with EOFException after upgrading to 1.1.2

### ISSUE THREAD

**Issue by rps-v** [crate/crate#5421]
**CrateDB version**:
1.1.2

**JVM version**:
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version / environment description**:
Ubuntu 16.04.2

**Problem description**:
After updating our cluster to 1.1.2 from 1.0.5, some of our queries are failing with an exception:
SQLActionException[RuntimeException: java.io.EOFException]

Query:
`select
	"A"."colA1",
	"A"."colA2",
	"A"."colA3",
	"A"."start_time",
	"A"."end_time"
	"B"."colB1" as "col_b_1",
	"C"."colC1" as "col_c_1",
	"D"."colD1" as "col_d_1"
from "A"
left join "B" on "A"."colA1" = "B"."colB2"
left join "C" on "B"."colB2" = "C"."colC2"
left join "D" on "A"."colA2" = "D"."colD2"
where "A"."deleted_at" is null and "colA2" in ('6da26df6-20dc-496e-96f9-8a37a03c8f4a', '4f9afe6e-eec7-4243-bdae-e11795f17f02', '36b0fae3-194b-432b-8d3c-1164b96ee0cd', '0a5f8743-b422-4e87-9764-8c2157157293', '72826b92-5e1e-4cc5-81c1-ce22c2f0d05b', '237d9983-77c1-4469-b9bf-b1a6cbb953e3', '73e7ded6-9475-4fd0-ad0c-ebea451a2309', '41e5df08-7ee3-47a2-8747-ca1df1bc1786') and ("start_time" >= 1491072240000 and "end_time" <= 1493232245056)`

Stacktrace:
`SQLActionException: INTERNAL_SERVER_ERROR 5000 RuntimeException: java.io.EOFException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at io.crate.executor.transport.StreamBucket$RowIterator.next(StreamBucket.java:147)
	at io.crate.executor.transport.StreamBucket$RowIterator.next(StreamBucket.java:129)
	at com.google.common.collect.Iterators$5.next(Iterators.java:558)
	at com.google.common.collect.ForwardingIterator.next(ForwardingIterator.java:48)
	at io.crate.operation.merge.BatchPagingIterator.moveNext(BatchPagingIterator.java:98)
	at io.crate.data.join.LeftJoinBatchIterator.moveLeftSide(LeftJoinBatchIterator.java:75)
	at io.crate.data.join.LeftJoinBatchIterator.moveNext(LeftJoinBatchIterator.java:62)
	at io.crate.data.ForwardingBatchIterator.moveNext(ForwardingBatchIterator.java:50)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:76)
	at io.crate.data.join.LeftJoinBatchIterator.moveLeftSide(LeftJoinBatchIterator.java:75)
	at io.crate.data.join.LeftJoinBatchIterator.moveNext(LeftJoinBatchIterator.java:62)
	at io.crate.data.ForwardingBatchIterator.moveNext(ForwardingBatchIterator.java:50)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:76)
	at io.crate.data.join.LeftJoinBatchIterator.moveLeftSide(LeftJoinBatchIterator.java:75)
	at io.crate.data.join.LeftJoinBatchIterator.moveNext(LeftJoinBatchIterator.java:62)
	at io.crate.data.ForwardingBatchIterator.moveNext(ForwardingBatchIterator.java:50)
	at io.crate.data.CloseAssertingBatchIterator.moveNext(CloseAssertingBatchIterator.java:55)
	at io.crate.data.LimitingBatchIterator.moveNext(LimitingBatchIterator.java:54)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:76)
	at io.crate.data.AsyncOperationBatchIterator.tryProcessBatchFromLoadedSource(AsyncOperationBatchIterator.java:156)
	at io.crate.data.AsyncOperationBatchIterator.uncheckedLoadNextBatch(AsyncOperationBatchIterator.java:134)
	at io.crate.data.AsyncOperationBatchIterator.loadNextBatch(AsyncOperationBatchIterator.java:130)
	at io.crate.action.sql.BatchConsumerToResultReceiver.consumeIt(BatchConsumerToResultReceiver.java:80)
	at io.crate.action.sql.BatchConsumerToResultReceiver.accept(BatchConsumerToResultReceiver.java:49)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.tryForwardResult(InterceptingBatchConsumer.java:81)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.accept(InterceptingBatchConsumer.java:68)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.join.NestedLoopOperation.lambda$new$0(NestedLoopOperation.java:55)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.operation.join.NestedLoopOperation$1.accept(NestedLoopOperation.java:106)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.join.NestedLoopOperation.lambda$new$0(NestedLoopOperation.java:55)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.operation.join.NestedLoopOperation$1.accept(NestedLoopOperation.java:106)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.join.NestedLoopOperation.lambda$new$0(NestedLoopOperation.java:55)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.operation.join.NestedLoopOperation$1.accept(NestedLoopOperation.java:106)
	at io.crate.jobs.PageDownstreamContext.triggerConsumer(PageDownstreamContext.java:148)
	at io.crate.jobs.PageDownstreamContext.mergeAndTriggerConsumer(PageDownstreamContext.java:162)
	at io.crate.jobs.PageDownstreamContext.setBucket(PageDownstreamContext.java:133)
	at io.crate.executor.transport.distributed.TransportDistributedResultAction.nodeOperation(TransportDistributedResultAction.java:125)
	at io.crate.executor.transport.distributed.TransportDistributedResultAction.nodeOperation(TransportDistributedResultAction.java:91)
	at io.crate.executor.transport.distributed.TransportDistributedResultAction.nodeOperation(TransportDistributedResultAction.java:46)
	at io.crate.executor.transport.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:43)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Steps to reproduce**:

**Use case**:

**Feature description**:

**Comment by joemoe** [comment]
hi @rps-v, we wil check this.

**Comment by mfussenegger** [comment]
Any chance that there are still some outdated nodes within the cluster? `EOFException` and `io.crate.executor.transport.StreamBucket$RowIterator.next(StreamBucket.java:147)` indicate a serialization error.

If all nodes have the same version, could you please also post the table schema if possible and provide some details about the cluster configuration (number of nodes, any dedicated master nodes, any dedicated client nodes) ?

**Comment by rps-v** [comment]
All the nodes were running the same version (1.1.2). Also tried on our dev cluster with only 1 node, same thing.

Just tried again on a fresh 1.1.2 install and now I get a different error for the same query (which works on the 1.0.5 server with the same data):

**SQLActionException[ArrayIndexOutOfBoundsException: 4]**
```SQLActionException: INTERNAL_SERVER_ERROR 5000 ArrayIndexOutOfBoundsException: 4
	at io.crate.data.join.CombinedColumn.get(CombinedColumn.java:53)
	at io.crate.data.RowBridging$2.get(RowBridging.java:66)
	at io.crate.operation.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:38)
	at io.crate.operation.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:26)
	at io.crate.operation.RowFilter.test(RowFilter.java:59)
	at io.crate.operation.RowFilter.test(RowFilter.java:35)
	at io.crate.operation.join.NestedLoopOperation.lambda$null$1(NestedLoopOperation.java:89)
	at io.crate.data.join.LeftJoinBatchIterator.tryAdvanceRight(LeftJoinBatchIterator.java:99)
	at io.crate.data.join.LeftJoinBatchIterator.moveLeftSide(LeftJoinBatchIterator.java:76)
	at io.crate.data.join.LeftJoinBatchIterator.moveNext(LeftJoinBatchIterator.java:62)
	at io.crate.data.ForwardingBatchIterator.moveNext(ForwardingBatchIterator.java:50)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:76)
	at io.crate.data.join.LeftJoinBatchIterator.moveLeftSide(LeftJoinBatchIterator.java:75)
	at io.crate.data.join.LeftJoinBatchIterator.moveNext(LeftJoinBatchIterator.java:62)
	at io.crate.data.ForwardingBatchIterator.moveNext(ForwardingBatchIterator.java:50)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:76)
	at io.crate.data.join.LeftJoinBatchIterator.moveLeftSide(LeftJoinBatchIterator.java:75)
	at io.crate.data.join.LeftJoinBatchIterator.moveNext(LeftJoinBatchIterator.java:62)
	at io.crate.data.ForwardingBatchIterator.moveNext(ForwardingBatchIterator.java:50)
	at io.crate.data.CloseAssertingBatchIterator.moveNext(CloseAssertingBatchIterator.java:55)
	at io.crate.data.LimitingBatchIterator.moveNext(LimitingBatchIterator.java:54)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:76)
	at io.crate.data.AsyncOperationBatchIterator.tryProcessBatchFromLoadedSource(AsyncOperationBatchIterator.java:156)
	at io.crate.data.AsyncOperationBatchIterator.uncheckedLoadNextBatch(AsyncOperationBatchIterator.java:134)
	at io.crate.data.AsyncOperationBatchIterator.loadNextBatch(AsyncOperationBatchIterator.java:130)
	at io.crate.action.sql.BatchConsumerToResultReceiver.consumeIt(BatchConsumerToResultReceiver.java:80)
	at io.crate.action.sql.BatchConsumerToResultReceiver.accept(BatchConsumerToResultReceiver.java:49)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.tryForwardResult(InterceptingBatchConsumer.java:81)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.accept(InterceptingBatchConsumer.java:68)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.join.NestedLoopOperation.lambda$new$0(NestedLoopOperation.java:55)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.operation.join.NestedLoopOperation$1.accept(NestedLoopOperation.java:106)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.join.NestedLoopOperation.lambda$new$0(NestedLoopOperation.java:55)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.operation.join.NestedLoopOperation$1.accept(NestedLoopOperation.java:106)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.join.NestedLoopOperation.lambda$new$0(NestedLoopOperation.java:55)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.operation.join.NestedLoopOperation$1.accept(NestedLoopOperation.java:106)
	at io.crate.data.ListenableBatchConsumer.accept(ListenableBatchConsumer.java:40)
	at io.crate.operation.collect.collectors.CompositeCollector$MultiConsumer.accept(CompositeCollector.java:104)
	at io.crate.operation.collect.BatchIteratorCollectorBridge$SyncBatchItCollector.doCollect(BatchIteratorCollectorBridge.java:63)
	at io.crate.operation.collect.collectors.CompositeCollector.doCollect(CompositeCollector.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rps-v** [comment]
Attached is the query and schema for the tables involved in it.

[schema+query.txt](https://github.com/crate/crate/files/963661/schema.query.txt)

**Comment by mfussenegger** [comment]
So far I had no luck in trying to reproduce the error.
Would it also be possible for you to provide me with some data?

Are you also able to produce this error if only 2 or 3 tables are joined?

**Comment by rps-v** [comment]
I prepared a pack with:
- data folder
- config folder
- sample query

Just unpack in a fresh install 1.1.2 (tarball package) folder.
Hopefully you can replicate the problem now.

[pack.zip](https://github.com/crate/crate/files/964487/pack.zip)

**Comment by mfussenegger** [comment]
This is great, thanks a lot. I've found the issue and I'm working on a fix - should make it into the next hotfix release (1.1.3)

**Comment by mfussenegger** [comment]
Fixed via https://github.com/crate/crate/pull/5458
