### ISSUE TITLE
Unpacking Crate on macOS causes .DS_Store issues

### ISSUE THREAD

**Issue by tommorris** [crate/crate#5473]
**CrateDB version**: 1.1.2

**JVM version**:

```
$ java -version
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (Zulu 8.19.0.1-macosx) (build 1.8.0_112-b16)
OpenJDK 64-Bit Server VM (Zulu 8.19.0.1-macosx) (build 25.112-b16, mixed mode)
```

**OS version / environment description**: macOS Sierra 10.12.3

**Problem description**:

I downloaded Crate from the website. I unzipped the zip file in the OS X Finder. Then I opened my terminal and tried to run `./bin/crate`

It thought `./plugins/.DS_Store` was a plugin and then failed to load it. I fixed it by removing the .DS_Store file, but making it ignore `.DS_Store` files (and equivalent on other platforms) seems like a sensible step.

```
~ $ cd ~/Downloads/crate-1.1.2 
~/Downloads/crate-1.1.2 $ ls
CHANGES.txt NOTICE      bin         lib
LICENSE.txt README.rst  config      plugins
~/Downloads/crate-1.1.2(master ✗) ./bin/crate
[2017-05-03 11:47:36,975][INFO ][node                     ] [Monte Vallecetta] version[2.4
.2], pid[18562], build[${build/NA]
[2017-05-03 11:47:36,976][INFO ][node                     ] [Monte Vallecetta] initializin
g ...
[2017-05-03 11:47:37,147][ERROR][io.crate.plugin          ] [Monte Vallecetta] Path [/User
s/tom/Downloads/crate-1.1.2/plugins/.DS_Store] does not contain a valid Crate or Elasticse
arch plugin
java.lang.RuntimeException: Path [/Users/tom/Downloads/crate-1.1.2/plugins/.DS_Store] does
 not contain a valid Crate or Elasticsearch plugin
        at io.crate.plugin.PluginLoader.findImplementations(PluginLoader.java:202)
        at io.crate.plugin.PluginLoader.<init>(PluginLoader.java:80)
        at io.crate.plugin.PluginLoaderPlugin.<init>(PluginLoaderPlugin.java:62)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessor
Impl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructor
AccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:475)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:102)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at io.crate.node.CrateNode.<init>(CrateNode.java:50)
        at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:193)
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:300)
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:50)
Exception in thread "main" ElasticsearchException[Failed to load plugin class [io.crate.pl
ugin.PluginLoaderPlugin]]; nested: InvocationTargetException; nested: RuntimeException[Pat
h [/Users/tom/Downloads/crate-1.1.2/plugins/.DS_Store] does not contain a valid Crate or E
lasticsearch plugin];
Likely root cause: java.lang.RuntimeException: Path [/Users/tom/Downloads/crate-1.1.2/plugins/.DS_Store] does not contain a valid Crate or Elasticsearch plugin
        at io.crate.plugin.PluginLoader.findImplementations(PluginLoader.java:202)
        at io.crate.plugin.PluginLoader.<init>(PluginLoader.java:80)
        at io.crate.plugin.PluginLoaderPlugin.<init>(PluginLoaderPlugin.java:62)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:475)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:102)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at io.crate.node.CrateNode.<init>(CrateNode.java:50)
        at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:193)
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:300)
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:50)
Refer to the log for complete error details.
```

**Steps to reproduce**: Download on macOS, unpack using Finder unzip function, try to run.

**Comment by chaudum** [comment]
hi @tommorris 
it looks like you've opened the `plugins/` folder in Finder before you started CrateDB from the terminal and it is by intent that non-plugin files cause that error. we may consider removing this limitation at some point but for the time being you would need to keep the plugins folder clean :)
to delete all .DS_Store files in a folder and its subfolders run `find . -name ".DS_Store" -delete`
