### ISSUE TITLE
after run SHOW TABLES command will throw exception

### ISSUE THREAD

**Issue by bububa** [crate/crate#5576]
1.1.2:

1.8.0_121:

centos 6.5:

**Problem description**:

AdminUI could not display TABLES;
after run SHOW TABLES command will throw exception:

```
SQLActionException: INTERNAL_SERVER_ERROR 5000 NullPointerException in io.crate.metadata.blob.InternalBlobTableInfoFactory.create(InternalBlobTableInfoFactory.java:82)
	at io.crate.metadata.blob.InternalBlobTableInfoFactory.create(InternalBlobTableInfoFactory.java:82)
	at io.crate.metadata.blob.BlobSchemaInfo.innerGetTableInfo(BlobSchemaInfo.java:81)
	at io.crate.metadata.blob.BlobSchemaInfo.access$000(BlobSchemaInfo.java:46)
	at io.crate.metadata.blob.BlobSchemaInfo$1.load(BlobSchemaInfo.java:59)
	at io.crate.metadata.blob.BlobSchemaInfo$1.load(BlobSchemaInfo.java:56)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at io.crate.metadata.blob.BlobSchemaInfo.getTableInfo(BlobSchemaInfo.java:87)
	at io.crate.metadata.blob.BlobSchemaInfo$2.apply(BlobSchemaInfo.java:75)
	at io.crate.metadata.blob.BlobSchemaInfo$2.apply(BlobSchemaInfo.java:71)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:650)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at io.crate.data.RowsBatchIterator.moveNext(RowsBatchIterator.java:77)
	at io.crate.data.CloseAssertingBatchIterator.moveNext(CloseAssertingBatchIterator.java:55)
	at io.crate.data.BatchRowVisitor.visitRows(BatchRowVisitor.java:48)
	at io.crate.data.BatchRowVisitor.visitRows(BatchRowVisitor.java:38)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:115)
	at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
	at io.crate.data.ForwardingBatchIterator.loadNextBatch(ForwardingBatchIterator.java:60)
	at io.crate.data.BatchRowVisitor.visitRows(BatchRowVisitor.java:59)
	at io.crate.data.BatchRowVisitor.visitRows(BatchRowVisitor.java:38)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:115)
	at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
	at io.crate.data.BatchRowVisitor.visitRows(BatchRowVisitor.java:59)
	at io.crate.data.BatchRowVisitor.visitRows(BatchRowVisitor.java:38)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:115)
	at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
	at io.crate.action.sql.BatchConsumerToResultReceiver.consumeIt(BatchConsumerToResultReceiver.java:80)
	at io.crate.action.sql.BatchConsumerToResultReceiver.accept(BatchConsumerToResultReceiver.java:49)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.tryForwardResult(InterceptingBatchConsumer.java:81)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.accept(InterceptingBatchConsumer.java:68)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.data.ListenableBatchConsumer.accept(ListenableBatchConsumer.java:40)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.collect.BatchIteratorCollectorBridge$AsyncBatchItCollector.invokeConsumer(BatchIteratorCollectorBridge.java:118)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at io.crate.operation.collect.BatchIteratorCollectorBridge$AsyncBatchItCollector.doCollect(BatchIteratorCollectorBridge.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Steps to reproduce**:
run SHOW TABLES command;

**Comment by matriv** [comment]
Hello @bububa 

Is it possible to send us the result of `select * from information_schema.tables;` ?

**Comment by bububa** [comment]
@matrix Sorry, I just upgrade crate to 2.0.0, bug got same error;
after run `select * from information_schema.tables; ` in 2.0.0 will get error exception:

```
SQLActionException: INTERNAL_SERVER_ERROR 5000 NullPointerException in org.apache.lucene.util.BytesRef.<init>(BytesRef.java:87)
	at org.apache.lucene.util.BytesRef.<init>(BytesRef.java:87)
	at io.crate.operation.reference.information.InformationSchemaExpressionFactories$37.value(InformationSchemaExpressionFactories.java:415)
	at io.crate.operation.reference.information.InformationSchemaExpressionFactories$37.value(InformationSchemaExpressionFactories.java:411)
	at io.crate.operation.InputRow.get(InputRow.java:46)
	at io.crate.data.RowColumns$ProxyInput.value(RowColumns.java:69)
	at io.crate.data.RowBridging$2.get(RowBridging.java:66)
	at io.crate.operation.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:38)
	at io.crate.operation.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:26)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:78)
	at io.crate.data.CloseAssertingBatchIterator.moveNext(CloseAssertingBatchIterator.java:55)
	at io.crate.data.LimitingBatchIterator.moveNext(LimitingBatchIterator.java:54)
	at io.crate.operation.aggregation.RowTransformingBatchIterator.moveNext(RowTransformingBatchIterator.java:76)
	at io.crate.data.ForwardingBatchIterator.moveNext(ForwardingBatchIterator.java:50)
	at io.crate.action.sql.BatchConsumerToResultReceiver.consumeIt(BatchConsumerToResultReceiver.java:60)
	at io.crate.action.sql.BatchConsumerToResultReceiver.accept(BatchConsumerToResultReceiver.java:48)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.tryForwardResult(InterceptingBatchConsumer.java:81)
	at io.crate.executor.transport.executionphases.InterceptingBatchConsumer.accept(InterceptingBatchConsumer.java:68)
	at io.crate.data.ListenableBatchConsumer.accept(ListenableBatchConsumer.java:40)
	at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
	at io.crate.operation.collect.BatchIteratorCollectorBridge$AsyncBatchItCollector.invokeConsumer(BatchIteratorCollectorBridge.java:118)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at io.crate.operation.collect.BatchIteratorCollectorBridge$AsyncBatchItCollector.doCollect(BatchIteratorCollectorBridge.java:96)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matriv** [comment]
But did you upgrade to 1.1.3 first? https://crate.io/docs/reference/en/2.0.0/release_notes/2.0.0.html
`If you are upgrading a cluster, you must be running CrateDB Version 1.1.3 or higher before you upgrade to 2.0.0.`

**Comment by matriv** [comment]
@bububa Could you please give us some more "history" info about your blob tables?
Did you create them in 1.1.2?
Did you create them in a prior to 1.1.x version?
Is there a chance that you did a rolling upgrade from < 1.1.x version to 1.1.x?

**Comment by joemoe** [comment]
hi @bububa, can you please provide feedback @matriv?

**Comment by bububa** [comment]
@matriv 
I upgraded from 1.1.3, but I made a mistake upgraded from 1.0.3 to 1.1.2 directly which may cause this issue.
Also I didn't create blob tables.

**Comment by joemoe** [comment]
@bububa, ok thanks. so now it works for you?

**Comment by bububa** [comment]
@joemoe, no, still in 2.0.0. do you mean I need to roll back to 1.0.3 and do rolling update to 1.1.3? does that means I need to dump the table and recreate the structue?

**Comment by matriv** [comment]
@bububa Yep, you need to drop and recreate your blob table(s). Doing a rolling upgrade between minor versions (not hotfixes) caused the issue.

**Comment by matriv** [comment]
@bububa Also, please keep in mind you cannot downgrade from 2.0.0 anymore!
