### ISSUE TITLE
MATCH query throw exception

### ISSUE THREAD

**Issue by bububa** [crate/crate#5601]
**CrateDB version**: 1.1.2

**JVM version**: 1.8.0_121

**OS version / environment description**: centos 6.5

**Problem description**:

MATCH throw exception
Query:
SELECT pid, _score FROM mytable WHERE MATCH(content_ft, 'test') ORDER BY _score DESC LIMIT 10;

```
SQLActionException: INTERNAL_SERVER_ERROR 5000 NullPointerException: Column must exist: _score
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.crate.operation.collect.collectors.LuceneOrderedDocCollector.nextPageQuery(LuceneOrderedDocCollector.java:193)
	at io.crate.operation.collect.collectors.LuceneOrderedDocCollector.query(LuceneOrderedDocCollector.java:168)
	at io.crate.operation.collect.collectors.LuceneOrderedDocCollector.searchMore(LuceneOrderedDocCollector.java:155)
	at io.crate.operation.collect.collectors.LuceneOrderedDocCollector.collect(LuceneOrderedDocCollector.java:125)
	at io.crate.operation.collect.collectors.OrderedDocCollector.get(OrderedDocCollector.java:61)
	at io.crate.operation.collect.collectors.OrderedLuceneBatchIteratorFactory$Factory.loadFrom(OrderedLuceneBatchIteratorFactory.java:107)
	at io.crate.operation.collect.collectors.OrderedLuceneBatchIteratorFactory$Factory.tryFetchMore(OrderedLuceneBatchIteratorFactory.java:100)
	at io.crate.operation.merge.BatchPagingIterator.loadNextBatch(BatchPagingIterator.java:122)
	at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
	at io.crate.data.LimitingBatchIterator.loadNextBatch(LimitingBatchIterator.java:66)
	at io.crate.data.ForwardingBatchIterator.loadNextBatch(ForwardingBatchIterator.java:60)
	at io.crate.data.ForwardingBatchIterator.loadNextBatch(ForwardingBatchIterator.java:60)
	at io.crate.data.BatchRowVisitor.visitRows(BatchRowVisitor.java:59)
	at io.crate.data.BatchRowVisitor.lambda$visitRows$0(BatchRowVisitor.java:61)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.operation.merge.BatchPagingIterator.completeLoad(BatchPagingIterator.java:157)
	at io.crate.operation.collect.collectors.OrderedLuceneBatchIteratorFactory$Factory.onNextRows(OrderedLuceneBatchIteratorFactory.java:121)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
**Steps to reproduce**:

```
create table mytable (
    iid string INDEX USING PLAIN primary key,
    pid long,
    uid long,
    aid long,
    sid long,
    status short,
    mtype short,
    affiliate_id integer,
    auction_id string INDEX OFF,
    title string INDEX OFF,
    url string INDEX OFF,
    pic string INDEX OFF,
    price long INDEX OFF,
    oriprice long INDEX OFF,
    wapprice long,
    cats string INDEX OFF,
    props string INDEX OFF,
    pics string INDEX OFF,
    sensitive short,
    cids array(long),
    cats_ft string INDEX using fulltext with (analyzer = 'whitespace'),
    content_ft string INDEX using fulltext with (analyzer = 'whitespace'),
    rand integer,
    jingxuan short,
    updated_at timestamp
) clustered by (iid) into 12 shards
WITH (number_of_replicas = 1);
```

**Use case**:

**Feature description**:

**Comment by mxm** [comment]
Hi @bububa! Thanks for reporting this error. I couldn't reproduce the exception with the schema and query you provided. However, I only inserted some really basic sample data. Could you give us some more information about your setup and provide some sample data which lets us reproduce the problem? Thank you.

**Comment by mxm** [comment]
Thanks again for reporting. We were able to reproduce the error. A fix should be included in the next release. Alternatively, building from master will also include the fix.
