### ISSUE TITLE
ORDER BY randomly not working with INNER JOINed tables

### ISSUE THREAD

**Issue by nook24** [crate/crate#5747]
If I `INNER JOIN` more than one table, the `ORDER BY` clause is randomly not working.

**CrateDB version**: 1.1.5

**JVM version**: Oracle Java 8 on Ubuntu 16.04
````
java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
````

**OS version / environment description**:
Ubuntu 16.04.2 LTS - amd64

**Problem description**:
If I INNER JOIN 3 tables, and want to ORDER BY the first table, i get the following stack trace.

If i ORDER BY a column from the second INNER JOINed table, its working without any problems. My workaround was, to use a LEFT JOIN. All querys are attached in the reproduce section.

````
SQLActionException: BAD_REQUEST 4000 SQLParseException: Couldn't create executionContexts from
NodeOperations: {4=NodeOp{ phase{id=4/nested-loop, nodes=[5NrB_ZHdQ9OAkhdHkxLL8w], dist=BROADCAST}, downstreamNodes=[5NrB_ZHdQ9OAkhdHkxLL8w], downstreamPhase=6, downstreamInputId=0}, 2=NodeOp{ phase{id=2/nested-loop, nodes=[5NrB_ZHdQ9OAkhdHkxLL8w], dist=BROADCAST}, downstreamNodes=[5NrB_ZHdQ9OAkhdHkxLL8w], downstreamPhase=4, downstreamInputId=0}, 0=NodeOp{ phase{id=0/collect, nodes=[5NrB_ZHdQ9OAkhdHkxLL8w], dist=BROADCAST}, downstreamNodes=[5NrB_ZHdQ9OAkhdHkxLL8w], downstreamPhase=2, downstreamInputId=0}, 1=NodeOp{ phase{id=1/collect, nodes=[5NrB_ZHdQ9OAkhdHkxLL8w], dist=SAME_NODE}, downstreamNodes=[5NrB_ZHdQ9OAkhdHkxLL8w], downstreamPhase=2, downstreamInputId=1}, 3=NodeOp{ phase{id=3/collect, nodes=[5NrB_ZHdQ9OAkhdHkxLL8w], dist=SAME_NODE}, downstreamNodes=[5NrB_ZHdQ9OAkhdHkxLL8w], downstreamPhase=4, downstreamInputId=1}, 5=NodeOp{ phase{id=5/collect, nodes=[5NrB_ZHdQ9OAkhdHkxLL8w], dist=SAME_NODE}, downstreamNodes=[5NrB_ZHdQ9OAkhdHkxLL8w], downstreamPhase=6, downstreamInputId=1}, 7=NodeOp{ phase{id=7/fetchPhase, nodes=[5NrB_ZHdQ9OAkhdHkxLL8w]}, downstreamNodes=[], downstreamPhase=2147483647, downstreamInputId=0}}
Leafs: [NestedLoopPhase{executionPhaseId=6, name=nested-loop, joinType=INNER, joinCondition=op_=(InputColumn{index=9, type=string},InputColumn{index=3, type=string}), outputTypes=[string, string, string, string, timestamp, string, string, string, string, string, string], jobId=1423ff09-7087-4033-a851-89a6f7890096, executionNodes=[5NrB_ZHdQ9OAkhdHkxLL8w]}]
target-sources: {2=[0, 1], 4=[2, 3], 6=[4, 5]}
original-error: Can't handle Symbol RELCOL(notificationhost, 2)
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:170)
	at io.crate.exceptions.SQLExceptions.createSQLActionException(SQLExceptions.java:120)
	at io.crate.rest.action.RestResultSetReceiver.fail(RestResultSetReceiver.java:104)
	at io.crate.protocols.postgres.SimplePortal$ResultReceiverRetryWrapper.fail(SimplePortal.java:275)
	at io.crate.action.sql.BatchConsumerToResultReceiver.accept(BatchConsumerToResultReceiver.java:53)
	at io.crate.executor.transport.executionphases.ExecutionPhasesTask.execute(ExecutionPhasesTask.java:143)
	at io.crate.executor.transport.TransportExecutor.lambda$execute$0(TransportExecutor.java:148)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669)
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997)
	at io.crate.executor.transport.TransportExecutor.execute(TransportExecutor.java:148)
	at io.crate.protocols.postgres.SimplePortal.sync(SimplePortal.java:186)
	at io.crate.action.sql.SQLOperations$Session.sync(SQLOperations.java:303)
	at io.crate.rest.action.RestSQLAction.executeSimpleRequest(RestSQLAction.java:139)
	at io.crate.rest.action.RestSQLAction.handleRequest(RestSQLAction.java:102)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:198)
	at org.elasticsearch.rest.RestController$RestHandlerFilter.process(RestController.java:280)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:261)
	at io.crate.rest.action.admin.AdminUIStaticFileRequestFilter.process(AdminUIStaticFileRequestFilter.java:74)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:264)
	at io.crate.rest.CrateRestFilter.process(CrateRestFilter.java:69)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:264)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:161)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:153)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:101)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:451)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at io.crate.http.netty.HttpBlobHandler.messageReceived(HttpBlobHandler.java:123)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
````

**Steps to reproduce**:

1. Load required tables and data
````SQL
CREATE TABLE IF NOT EXISTS statusengine_host_notifications (
  hostname string,
  contact_name string,
  command_name string,
  output string,
  start_time timestamp
  ) CLUSTERED INTO 4 shards with (number_of_replicas = '1-all');
  
CREATE TABLE IF NOT EXISTS openitcockpit_hosts (
  uuid string,
  name string
  ) CLUSTERED INTO 4 shards with (number_of_replicas = '1-all');

CREATE TABLE IF NOT EXISTS openitcockpit_contacts (
  uuid string,
  name string
  ) CLUSTERED INTO 4 shards with (number_of_replicas = '1-all');

CREATE TABLE IF NOT EXISTS openitcockpit_commands (
  uuid string,
  name string
  ) CLUSTERED INTO 4 shards with (number_of_replicas = '1-all');

INSERT INTO statusengine_host_notifications (hostname, contact_name, command_name, output, start_time)values
('e2e12371-cdb4-4dc4-9f45-148206c24fd1', '85b1cae0-24ea-43ef-9c81-61a0a3fd66be', 'cf635dc4-fe81-4138-91e9-5df6132edb5c', 'this is a test1', 1497857806),
('9f766701-cf65-4209-a9b2-127a3017860a', '85b1cae0-24ea-43ef-9c81-61a0a3fd66be', 'cf635dc4-fe81-4138-91e9-5df6132edb5c', 'this is a test2', 1497857806),
('a96625f0-fd46-4889-83cd-644e3c734142', '85b1cae0-24ea-43ef-9c81-61a0a3fd66be', '3a17d85a-f9e6-4321-b186-8c331bea6069', 'this is a test3', 1497857806);

INSERT INTO openitcockpit_hosts (name, uuid)values
('localhost', 'e2e12371-cdb4-4dc4-9f45-148206c24fd1'),
('kvm_host', '9f766701-cf65-4209-a9b2-127a3017860a'),
('linux-host', 'a96625f0-fd46-4889-83cd-644e3c734142');

INSERT INTO openitcockpit_contacts (name, uuid)VALUES
('Elizabeth', '85b1cae0-24ea-43ef-9c81-61a0a3fd66be'),
('Joe', '85b1cae0-24ea-43ef-9c81-61a0a3fd66be'),
('Norman', '85b1cae0-24ea-43ef-9c81-61a0a3fd66be');

INSERT INTO openitcockpit_commands (name, uuid)VALUES
('via email', 'cf635dc4-fe81-4138-91e9-5df6132edb5c'),
('via sms', '3a17d85a-f9e6-4321-b186-8c331bea6069');
````

2. Run this query, to reproduce the issue. In this query i like to order by `Host.name` which is running into an issue.
````SQL
SELECT 
  NotificationHost.*, 
  Host.*,
  Contact.*,
  Command.*
FROM 
  statusengine_host_notifications AS NotificationHost 
  INNER JOIN openitcockpit_hosts AS Host ON Host.uuid = NotificationHost.hostname 
  INNER JOIN openitcockpit_contacts AS Contact ON Contact.uuid = NotificationHost.contact_name 
  INNER JOIN openitcockpit_commands AS Command ON Command.uuid = NotificationHost.command_name 
WHERE 
  NotificationHost.start_time > 1497858806 
  AND NotificationHost.start_time < 1497856806 

ORDER BY
Host.name
ASC
````

3. If i just change the ORDER BY to `Contact.name` its workoing whitout any issue
````SQL
SELECT 
NotificationHost.*, 
Host.*,
Contact.*,
Command.*
FROM 
  statusengine_host_notifications AS NotificationHost 
  INNER JOIN openitcockpit_hosts AS Host ON Host.uuid = NotificationHost.hostname 
  INNER JOIN openitcockpit_contacts AS Contact ON Contact.uuid = NotificationHost.contact_name 
  INNER JOIN openitcockpit_commands AS Command ON Command.uuid = NotificationHost.command_name 
WHERE 
  NotificationHost.start_time > 1495006256 
  AND NotificationHost.start_time < 1502782256 

ORDER BY
Contact.name
ASC
````

4. Due to the fact, that i need to ORDER BY `Host.name` i joined this table using LEFT JOIN as a workaround
````SQL
SELECT 
  NotificationHost.*, 
  Host.*,
  Contact.*,
  Command.*
FROM 
  statusengine_host_notifications AS NotificationHost 
  LEFT JOIN openitcockpit_hosts AS Host ON Host.uuid = NotificationHost.hostname 
  INNER JOIN openitcockpit_contacts AS Contact ON Contact.uuid = NotificationHost.contact_name 
  INNER JOIN openitcockpit_commands AS Command ON Command.uuid = NotificationHost.command_name 
WHERE 
  NotificationHost.start_time > 1495006256 
  AND NotificationHost.start_time < 1502782256 

ORDER BY
Host.name
ASC
````
PS: The behavior is the same in a single node CrateDB installation, or in a multi node cluster.

Sorry for the long post :)

**Comment by mfussenegger** [comment]
> Sorry for the long post :)

Thanks for the detailed report. We can reproduce the issue and are going to take a closer look at it.

**Comment by matriv** [comment]
@nook24
This issue has been fixed by and will be released with the next hotfix releases.

Thanks for reporting!

**Comment by nook24** [comment]
I really appreciate this :)
