### ISSUE TITLE
JOIN OPERATION IS NOT WORKING ON TABLES

### ISSUE THREAD

**Issue by sasidharvenkata** [crate/crate#5765]
JOIN operation is not working

**CrateDB version**: 1.1.5

**JVM version**:  Oracle Java 8 on Windows 10

**OS version / environment description**:  Windows 10 64 bit
**Problem description**:
When I ran  JOIN ops on two  tables, I get the following stack trace.

Error!

SQLActionException[ValidationException: JOIN with sub queries is not supported]

SQLActionException: BAD_REQUEST 4000 ValidationException: JOIN with sub queries is not supported

         at io.crate.planner.consumer.NestedLoopConsumer$SubRelationConverter.visitAnalyzedRelation(NestedLoopConsumer.java:373)

         at io.crate.planner.consumer.NestedLoopConsumer$SubRelationConverter.visitAnalyzedRelation(NestedLoopConsumer.java:346)

         at io.crate.analyze.relations.AnalyzedRelationVisitor.visitQueriedDocTable(AnalyzedRelationVisitor.java:44)

         at io.crate.analyze.relations.QueriedDocTable.accept(QueriedDocTable.java:45)

         at io.crate.analyze.relations.AnalyzedRelationVisitor.process(AnalyzedRelationVisitor.java:32)

         at io.crate.planner.consumer.NestedLoopConsumer$Visitor.visitTwoTableJoin(NestedLoopConsumer.java:98)

         at io.crate.planner.consumer.NestedLoopConsumer$Visitor.visitTwoTableJoin(NestedLoopConsumer.java:77)

         at io.crate.analyze.TwoTableJoin.accept(TwoTableJoin.java:90)

         at io.crate.analyze.relations.AnalyzedRelationVisitor.process(AnalyzedRelationVisitor.java:32)

         at io.crate.planner.consumer.NestedLoopConsumer.consume(NestedLoopConsumer.java:61)

         at io.crate.planner.consumer.ConsumingPlanner.plan(ConsumingPlanner.java:64)

         at io.crate.planner.Planner$Context.planSubRelation(Planner.java:263)

         at io.crate.planner.consumer.ManyTableConsumer$Visitor.planSubRelation(ManyTableConsumer.java:397)

         at io.crate.planner.consumer.ManyTableConsumer$Visitor.visitMultiSourceSelect(ManyTableConsumer.java:377)

         at io.crate.planner.consumer.ManyTableConsumer$Visitor.visitMultiSourceSelect(ManyTableConsumer.java:370)

         at io.crate.analyze.MultiSourceSelect.accept(MultiSourceSelect.java:126)

         at io.crate.analyze.relations.AnalyzedRelationVisitor.process(AnalyzedRelationVisitor.java:32)

         at io.crate.planner.consumer.ManyTableConsumer.consume(ManyTableConsumer.java:56)

**Steps to reproduce**:

1. Load required tables and data
 **CREATE** **TABLE** **IF** **NOT** **EXISTS** `"doc"."policy" (
   "datetimestamp" STRING,
   "BMI" STRING,
   "HT" STRING,
   "id" STRING,
   "Medical_keyword" STRING)
   CLUSTERED INTO 4 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   number_of_replicas = '1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.disable_flush" = false,
   "translog.flush_threshold_ops" = 2147483647,
   "translog.flush_threshold_period" = 1800000,
   "translog.flush_threshold_size" = 536870912,
   "translog.interval" = 5000,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true
  ) `
**CREATE** **TABLE** **IF** **NOT** **EXISTS** `"doc"."base_reference" (
   "datetimestamp" STRING,
   "Ins_Age" STRING,
   "Product_Info_1-7" STRING,
   "InsuredInfo_1-6" STRING
)
CLUSTERED INTO 4 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   number_of_replicas = '1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.disable_flush" = false,
   "translog.flush_threshold_ops" = 2147483647,
   "translog.flush_threshold_period" = 1800000,
   "translog.flush_threshold_size" = 536870912,
   "translog.interval" = 5000,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true
)`

2. Run this query, to reproduce the issue 
` select pol.date_time,generation,load from (select datetimestamp as date_time, sum(cast(a.Ins_Age as float)) as generation 
                                                                 from policy a where datetimestamp !='' group by date_time order by date_time asc) as pol
                                                                 join
(select datetimestamp as date_time, sum(cast(a.Ins_Age as float)) as load 
                                                                 from base_reference a where datetimestamp !=''  group by date_time order by date_time asc) as base
                                                                 on pol.date_time = base.date_time `

**Use case**:

**Feature description**:

**Comment by matriv** [comment]
Hello @sasidharvenkata,

Your query tries to join subselects which is not supported in 1.1.x.
This feature will be available with the 2.1.x releases.

**Comment by sasidharvenkata** [comment]
Thanks @matriv ,

How soon will the 2.1.X releases be available

**Comment by matriv** [comment]
@sasidharvenkata According to current schedule the 1st testing release will be out by mid-July

**Comment by sasidhar-runku** [comment]
@matric, Do the join subselects available with the 2.1.x releases

**Comment by matriv** [comment]
@sasidhar-runku yes!
