### ISSUE TITLE
Timeout setting for table option write.wait_for_active_shards

### ISSUE THREAD

**Issue by leomkkwan** [crate/crate#5957]
**Use case**: Have a new timeout setting for table option write.wait_for_active_shards. Currently it is default to 30 seconds, and don't think it is configurable.

**Feature description**: On a high concurrnet insert environment, for example, web server log. If any node become temporary unaviable, shade will be under replicate and all write operation will wait 30 seconds. Which could make the web server become un-responsive becuase of all threads will be hold up for 30 seconds.

If we can set this timeout value to be a very low value, for example 200ms, those web server will not be stop responding. In this use case, losting log data is acceptable compare with unresponsive web server.

**Comment by joemoe** [comment]
hi @leomkkwan, thanks for suggesting this feature. i put it on our backlog. let's see how this fits our roadmap.

**Comment by mfussenegger** [comment]
As an alternative you can also set [write.wait_for_active_shards](https://crate.io/docs/crate/reference/sql/reference/create_table.html#write-wait-for-active-shards) to e.g. 1 so it will write immediately as long as the primary is available

**Comment by rps-v** [comment]
We hit this problem recently too, however it does not seem possible to set the 'write.wait_for_active_shards' setting via ALTER TABLE.

Is there any way to set it without having to recreate the table, maybe via the ES API ?

**Comment by seut** [comment]
@rps-v altering 'write.for_active_shards' should just work fine. did you maybe miss to quote this setting at the statement?

Example:
```alter table t1 set ("write.wait_for_active_shards" = 1);```

**Comment by rps-v** [comment]
@seut Already tried it like that.
```sql
alter table "myschema"."mytable" set ("write.wait_for_active_shards" = 1);
```

**SQLActionException[SQLParseException: Invalid property "write.wait_for_active_shards" passed to [ALTER | CREATE] TABLE statement]**
```
SQLActionException: BAD_REQUEST 4000 SQLParseException: Invalid property "write.wait_for_active_shards" passed to [ALTER | CREATE] TABLE statement
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:174)
	at io.crate.exceptions.SQLExceptions.createSQLActionException(SQLExceptions.java:121)
	at io.crate.action.sql.SQLOperations$Session.bind(SQLOperations.java:231)
	at io.crate.rest.action.RestSQLAction.executeSimpleRequest(RestSQLAction.java:150)
	at io.crate.rest.action.RestSQLAction.prepareRequest(RestSQLAction.java:114)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:66)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:243)
	at org.elasticsearch.rest.RestController$RestHandlerFilter.process(RestController.java:326)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:307)
	at io.crate.rest.action.admin.AdminUIStaticFileRequestFilter.process(AdminUIStaticFileRequestFilter.java:75)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:310)
	at io.crate.rest.CrateRestFilter.process(CrateRestFilter.java:73)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:310)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:203)
	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:116)
	at org.elasticsearch.http.netty3.Netty3HttpServerTransport.dispatchRequest(Netty3HttpServerTransport.java:490)
	at org.elasticsearch.http.netty3.Netty3HttpRequestHandler.messageReceived(Netty3HttpRequestHandler.java:62)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty3.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:85)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at io.crate.http.netty.HttpBlobHandler.messageReceived(HttpBlobHandler.java:119)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.transport.netty3.Netty3OpenChannelsHandler.handleUpstream(Netty3OpenChannelsHandler.java:81)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by seut** [comment]
@rps-v yes right, this is a bug which only affects partitioned table. we'll fix that asap and include that fix at the next hotfix releases. I've created a dedicated issue for that: https://github.com/crate/crate/issues/6038
You could fix set by using the ES API  https://www.elastic.co/guide/en/elasticsearch/reference/5.2/indices-update-settings.html on every partition index and https://www.elastic.co/guide/en/elasticsearch/reference/5.2/indices-templates.html on the partitioned table template.

**Comment by mfussenegger** [comment]
Closing this for now, as we've now immediate plans to make the timeout configurable. I think the way to go is to configure `write.wait_for_active_shards` instead.

If anyone can make a convincing argument why it should be possible to configure the timeout, feel free to re-open.
