### ISSUE TITLE
Receiving ConcurrentSnapshotExecutionException when running concurrent snapshots against different tables

### ISSUE THREAD

**Issue by tellezb** [crate/crate#5977]
**CrateDB version**: 1.1.6 (also seen in 1.0.5)

**JVM version**: 1.8.0_131

**OS version / environment description**: Amazon Linux AMI 2017.03

**Problem description**:
I am attempting to take a snapshot of my tables using multiple threads. One thread will take snapshots of all tables in one schema, and another thread will take snapshots of all tables in another schema. It seems that Crate is throwing an exception if more than 1 snapshot are occurring at the same time, even if the tables included in the snapshots don't cross.

> SQLActionException[ConcurrentSnapshotExecutionException: [apples_devmon_test.apples_devmon_test_1500314403677] a snapshot is already running]

> io.crate.shade.org.postgresql.util.PSQLException: ERROR: ConcurrentSnapshotExecutionException: [apples_devmon_test.apples_devmon_test_1500314403677] a snapshot is already running
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:433)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:359)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:916)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:970)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:980)

I've double checked that the snapshots are against separate tables (and schemas) and that they are using separate repositories. Here is an example of 2 snapshot commands which throw the ConcurrentSnapshotExecutionException (please note that apples_devmon_test and oranges_devmon_test are the schema names, as well as the repository names):

> CREATE SNAPSHOT apples_devmon_test.apples_devmon_test_1500314403677 TABLE apples_devmon_test.large_table_one WITH (wait_for_completion=true)

> CREATE SNAPSHOT oranges_devmon_test.oranges_devmon_test_1500314403677 TABLE oranges_devmon_test.large_table_one WITH (wait_for_completion=true)

I've also tested the snapshots against tables with different names (in different schemas) and end up with the same results:

> CREATE SNAPSHOT apples_devmon_test.apples_devmon_test_1500314403677 TABLE apples_devmon_test.large_table_one WITH (wait_for_completion=true)

> CREATE SNAPSHOT oranges_devmon_test.oranges_devmon_test_1500314403677 TABLE oranges_devmon_test.large_table_two WITH (wait_for_completion=true)

I would expect to receive this exception if 2 snapshots are working against the same table at the same time. But not when taking a snapshot of 2 completely different tables (or in different schemas).

**Comment by seut** [comment]
@tellezb 
As creating or dropping snapshots (no matter if one or multiple tables are affected) is affecting the global cluster state (in which, beside other data, all table metadata is stored), only 1 operation can run in parallel.
Otherwise the consistency of the global state could not be ensured.
