### ISSUE TITLE
Exception thrown when setting number_of_replicas with ALTER TABLE

### ISSUE THREAD

**Issue by rps-v** [crate/crate#5978]
**CrateDB version**:
2.0.4

**JVM version**:
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version / environment description**:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-47-generic x86_64)

**Problem description**:

SQLActionException[SQLParseException: unknown setting [index.version.created] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]

```
SQLActionException: BAD_REQUEST 4000 SQLParseException: unknown setting [index.version.created] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:174)
	at io.crate.exceptions.SQLExceptions.createSQLActionException(SQLExceptions.java:121)
	at io.crate.rest.action.RestRowCountReceiver.fail(RestRowCountReceiver.java:99)
	at io.crate.action.sql.BatchConsumerToResultReceiver.accept(BatchConsumerToResultReceiver.java:53)
	at io.crate.executor.transport.OneRowActionListener.accept(OneRowActionListener.java:59)
	at io.crate.executor.transport.OneRowActionListener.accept(OneRowActionListener.java:34)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.crate.executor.transport.AlterTableOperation.lambda$applyMultiFutureCallback$30(AlterTableOperation.java:575)
	at io.crate.concurrent.MultiBiConsumer.countdown(MultiBiConsumer.java:71)
	at io.crate.concurrent.MultiBiConsumer.onSuccess(MultiBiConsumer.java:60)
	at io.crate.concurrent.MultiBiConsumer.accept(MultiBiConsumer.java:50)
	at io.crate.concurrent.MultiBiConsumer.accept(MultiBiConsumer.java:34)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.crate.action.FutureActionListener.onResponse(FutureActionListener.java:45)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:91)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:87)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:224)
	at org.elasticsearch.action.ingest.IngestActionFilter.apply(IngestActionFilter.java:89)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:222)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:249)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:235)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:951)
	at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:1252)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.threadpool.ThreadPool.lambda$static$0(ThreadPool.java:147)
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1244)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1213)
	at org.elasticsearch.transport.netty3.Netty3MessageChannelHandler.messageReceived(Netty3MessageChannelHandler.java:73)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce**:

One node in our cluster failed, and due to a misconfiguration, the table had too many number of replicas set (which made writes fail). So we tried to modify the number of replicas for the underreplicated table with:
```sql
ALTER table "tracknamic"."timetable" SET (number_of_replicas=2);
```
SELECTs seem to work though.

**Use case**:

**Feature description**:

**Comment by Autophagy** [comment]
Hi @rps-v, thanks for reporting this. Would you be able to provide me with the version information of the table (`SELECT version FROM information_schema.tables WHERE table_schema = 'tracknamic' AND table_name = 'timetable'`), as well as the rough size of the table (in GB or rows).

Thank you!

**Comment by rps-v** [comment]
Here you go:
```
{"upgraded":{"elasticsearch":"2.4.2","cratedb":"1.1.2"},"created":null}  
```

The table has 32 records (172.8 KB).

Same error is thrown for other tables as well (one that has 1.1GB which gives the same response to the  provided query).

**Comment by Autophagy** [comment]
We have been investigating this, and the only way we have been able to replicate this issue is by doing a [rolling upgrade](https://crate.io/docs/crate/reference/best_practice/rolling_upgrade.html#rolling-upgrade) across a cluster from 1.1.x to 2.0.x, as doing a [full restart upgrade](https://crate.io/docs/crate/reference/best_practice/full_restart_upgrade.html#full-restart-upgrade) triggers a service to upgrade the indexes and archive any deprecated settings like `index.version.created`.

Is it possible that you did a rolling upgrade to 2.0, and not a full restart upgrade? There's currently no way to fix this if this is the case, but we are looking into being able to trigger this service in cases such as this.

**Comment by rps-v** [comment]
We tried doing a full restart upgrade (stopped all nodes) from 1.1.3 to 2.0.4 as per the documentation, but it failed (see #5923).
Then we deleted all the data and restored from a snapshot (made with 1.1.3).

Maybe that could be another cause, as no rolling upgrade was performed by us ?

**Comment by rps-v** [comment]
Just upgraded to 2.0.6 (full cluster restart) and the issue still persists, same exception thrown.

Is there any other way to reduce the number of replicas for a table ? This is quite a critical issue for us, especially if a node in the cluster fails.

**Comment by seut** [comment]
@rps-v 
Unfortunately @Autophagy was not correct when stating that we can reproduce this issue by doing any upgrade. The `index.version.created` setting is not a deprecated setting but it's internally and should never be set explicitly. While altering a table, this setting is never written by CrateDB.
The only way to reproduce it, was by manually modifying the partitioned table template using a CrateDB version < 2.0 as invalid template settings were ignored before.
Now they aren't, and we just write back all template settings when one is altering a partitioned table.
Did you maybe modify this template manually at the past?
The only way to fix this is by manually fixing the template (remove all `index.version` settings) using the ES API.

**Comment by rps-v** [comment]
We did not modify any template, only set the number_of_replicas via the ALTER TABLE query.

Are you refering to [this API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) ?

There is indeed an `settings.index.version` field for that table:
```
"tracknamic..partitioned.timetable.": {
    "order": 0,
    "template": "tracknamic..partitioned.timetable.*",
    "settings": {
      "index": {
        "number_of_shards": "6",
        "auto_expand_replicas": "2-all",
        "number_of_replicas": "1",
        "version": {
          "created": "2040299"
        }
      }
    },
```

**Comment by seut** [comment]
@rps-v yes exactly. hm really strange, I don't have any other idea how it could end up there..

**Comment by seut** [comment]
@rps-v also please aware: while modifying the template manually, ensure that no insert operations which are resulting in new partitions are happening. otherwise these new partitions won't be created  with the correct settings/mappings and are orphaned.

**Comment by seut** [comment]
@rps-v As I guess this now solved I'll close the issue, otherwise feel free to re-open it.
