### ISSUE TITLE
Increasing number of replicas stalls replication

### ISSUE THREAD

**Issue by rps-v** [crate/crate#5979]
**CrateDB version**:
2.0.4

**JVM version**:
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version / environment description**:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-47-generic x86_64)

**Problem description**:

Increasing the number of replicas stalls replication with the following warnings in logs:
```
[2017-07-18T23:22:29,394][WARN ][o.e.c.a.s.ShardStateAction] [s1] [tracknamic.vehicle][4] received shard failed for shard id [[tracknamic.vehicle][4]], allocation id [ucAgNTVRQCOaL4l2pY51kg], primary term [0], message [failed to create shard], failure [IOException[failed to obtain in-memory shard lock]; nested: ShardLockObtainFailedException[[tracknamic.vehicle][4]: obtaining shard lock timed out after 5000ms]; ]
java.io.IOException: failed to obtain in-memory shard lock
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:355) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:453) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:141) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:538) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:515) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:204) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.cluster.service.ClusterService.runTasksForExecutor(ClusterService.java:729) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:915) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:458) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) ~[crate-app-2.0.4.jar:2.0.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [tracknamic.vehicle][4]: obtaining shard lock timed out after 5000ms
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:713) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:632) ~[crate-app-2.0.4.jar:2.0.4]
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:285) ~[crate-app-2.0.4.jar:2.0.4]
        ... 13 more
```

**Steps to reproduce**:

- Increase number of replicas for a table
```
ALTER table "tracknamic"."vehicle" SET (number_of_replicas=2);
```
- Cluster state goes to Warning (underreplicated)
- Replication stalls (underreplicated records number freezes)

Cluster state never goes back to Green unless reducing number of replicas.

**Use case**:

**Feature description**:

**Comment by mfussenegger** [comment]
This could be somewhat related to https://github.com/crate/crate/issues/5926 in that the stalled updates keep a reference to the shards.

2.0.6 should be released any day now. Could you update once it's out and then check if this problem persists?

**Comment by rps-v** [comment]
Sure, will keep you updated.

Thank you !

**Comment by chaudum** [comment]
@rps-v 2.0.6 will be available from the stable repo tomorrow.

**Comment by chaudum** [comment]
@rps-v 2.0.6 was released yesterday. could you try to update and test if the issue still persists?

**Comment by rps-v** [comment]
@chaudum Yes, we will try to update to 2.0.6 and report back.

Thanks !

**Comment by rps-v** [comment]
Updated to 2.0.6 and it seems to be working now.

Thank you !

**Comment by rps-v** [comment]
It seems that this issue still persists. Just got a warning state on the cluster with stalled replication.

Tried changing the number of replicas for the affected table but it always gets stuck at the same number of underreplicated records.

Suddenly got lots of errors in logs (possibly after a node failed):
```
[2017-09-05T17:44:25,753][WARN ][i.c.e.t.TransportShardUpsertAction] [s4] [[myschema.mytable][4]] failed to perform indices:crate/data/write/upsert on replica [myschema.mytable][4], node[U5xEE2fkRJiHDDHRkSHe-w], [R], s[STARTED], a[id=94Fpj3JcSO6VEYvBpTpnnA]
org.elasticsearch.transport.RemoteTransportException: [s1][node1ip:4300][indices:crate/data/write/upsert[r]]
Caused by: java.lang.IllegalArgumentException: [tracknamic.vehicle][4] operation term [7] is too old (current [8])
	at org.elasticsearch.index.shard.IndexShard.acquireReplicaOperationLock(IndexShard.java:1668) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquireReplicaOperationLock(TransportReplicationAction.java:862) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:526) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:418) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:408) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1348) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app-2.0.6.jar:2.0.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

and 

```
[2017-09-05T17:44:56,376][WARN ][o.e.i.c.IndicesClusterStateService] [s4] [[myschema.anothertable][4]] marking and sending shard failed due to [failed to create shard]
java.io.IOException: failed to obtain in-memory shard lock
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:355) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:453) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:141) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:538) [crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:515) [crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:204) [crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.cluster.service.ClusterService.runTasksForExecutor(ClusterService.java:729) [crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:915) [crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:458) [crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) [crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) [crate-app-2.0.6.jar:2.0.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [tracknamic.device][4]: obtaining shard lock timed out after 5000ms
	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:713) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:632) ~[crate-app-2.0.6.jar:2.0.6]
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:285) ~[crate-app-2.0.6.jar:2.0.6]
	... 13 more
```

Additional server logs available via email.

**Comment by mfussenegger** [comment]
Can you email the additional logs to mathias {at} crate.io?

**Comment by rps-v** [comment]
@mfussenegger Done

**Comment by mfussenegger** [comment]
Unfortunately I can't tell much by the logs.

 - Would it also be possible to send us a heap dump of the node in question (s4) ? 
 - Does restarting the node in question (s4) resolve the issue?

**Comment by rps-v** [comment]
@mfussenegger 

- I sent you a heap dump of the node (via email)
- Did not try to restart the node yet, will try later

**Comment by mfussenegger** [comment]
You could also try using `curl -XPOST 'localhost:4200/_cluster/reroute?retry_failed'` if you've the ES API enabled.


It appears that one of the nodes was offline / unavailable for a while:

```
[2017-09-05T17:44:31,641][INFO ][i.c.d.SrvDiscovery       ] [s4] master_left [{s3}{ ...
[2017-09-05T17:44:31,642][WARN ][i.c.d.SrvDiscovery       ] [s4] master left (reason = failed to ping, tried [3] times, each with  maximum [30s] timeout), ...
```

Seems like the disappearance of a node caused a re-allocation. It then tries to
allocate shards on s4, but can't free the resources that have already been
there in time.

I first suspected that there is still some leak. But the heap you sent me looks
good on a first glance.

Were there any long running queries being executed on the cluster when this
issue appeared? Or did you take a snapshot that took a while?

**Comment by rps-v** [comment]
@mfussenegger 

Tried the `reroute` request but it did nothing (I sent you the response via email), cluster is still underreplicated.

I do not have any records of long queries that could have ran at that time.
Also, the snapshots for our cluster are broken, so none were taken (separate issue #5938).

Would a heap dump of the current master help (s3) ?

**Comment by mfussenegger** [comment]
A heap dump of the master won't help. The shardLocks are node specific.

I'd suggest for now to: 

 - Enable `stats.enabled` (Using `set global persistent stats.enabled = true`)
   This should help to debug the issue in case it occurs again.
 - Restart the node (s4)
 - If possible, also upgrade to 2.1.6 - There are no specific fixes that I've in mind that could be related to this issue, but I think the shard allocation code has undergone quite a few changes.

**Comment by rps-v** [comment]
@mfussenegger 
Restarted the nodes and now everything is fine. Will keep `stats.enabled = true` and report if it happens again.
