### ISSUE TITLE
Update from crate 1 to crate 2

### ISSUE THREAD

**Issue by Steve-hyas** [crate/crate#6163]
**CrateDB version**:
2.0.7
**JVM version**:
1.8

**OS version / environment description**:
Ubuntu
**Problem description**:
After upgrade crate refuses to start - or rather the elastic search engine refuses to start. Below is a stack trace. Coming from 1.1.4 to CrateDB version[2.0.7],

I understand the error message, but how do I fix this ?

```
java.lang.IllegalArgumentException: unknown setting [indices.recovery.compress] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:272) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:240) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.node.Node.<init>(Node.java:278) ~[crate-app-2.0.7.jar:2.0.7]
        at io.crate.node.CrateNode.<init>(CrateNode.java:58) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:201) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:201) ~[crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:297) [crate-app-2.0.7.jar:2.0.7]
        at io.crate.bootstrap.CrateDB.init(CrateDB.java:116) [crate-app-2.0.7.jar:2.0.7]
        at io.crate.bootstrap.CrateDB.execute(CrateDB.java:107) [crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) [crate-app-2.0.7.jar:2.0.7]
        at org.elasticsearch.cli.Command.main(Command.java:62) [crate-app-2.0.7.jar:2.0.7]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) [crate-app-2.0.7.jar:2.0.7]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:77) [crate-app-2.0.7.jar:2.0.7]
```
**Steps to reproduce**:
Starting with version 1.1.4 create a table. Upgrade to version 2.0.7

**Comment by matriv** [comment]
@Steve-hyas 

Please check the Breaking Changes here: https://crate.io/docs/crate/reference/en/2.0/release_notes/2.0.0.html#breaking-changes

You'll see that `indices.recovery.compress` setting has been removed, so you need to remove it from your `crate.yml` configuration.

**Comment by Steve-hyas** [comment]
@matriv  Thanks, I had found the release notes, but they did not say where those settings were in. I had thought it was in some system table somewhere.
