### ISSUE TITLE
Insert from subquery error

### ISSUE THREAD

**Issue by DLT1412** [crate/crate#6375]
**CrateDB version**: 2.0.6

**JVM version**:
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**OS version / environment description**: Centos 7

**Problem description**:
Error when add constant value to insert

```
SQLActionException[ArrayIndexOutOfBoundsException: 1]

SQLActionException: INTERNAL_SERVER_ERROR 5000 ArrayIndexOutOfBoundsException: 1
        at io.crate.data.RowColumns.get(RowColumns.java:47)
        at io.crate.data.RowBridging$2.get(RowBridging.java:66)
        at io.crate.operation.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:38)
        at io.crate.operation.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:26)
        at io.crate.operation.projectors.ShardingUpsertExecutor.lambda$createRowConsumer$0(ShardingUpsertExecutor.java:138)
        at io.crate.operation.projectors.BatchIteratorBackpressureExecutor.unsafeConsumeIterator(BatchIteratorBackpressureExecutor.java:166)
        at io.crate.operation.projectors.BatchIteratorBackpressureExecutor.safeConsumeIterator(BatchIteratorBackpressureExecutor.java:137)
        at io.crate.operation.projectors.BatchIteratorBackpressureExecutor.consumeIteratorAndExecute(BatchIteratorBackpressureExecutor.java:95)
        at io.crate.operation.projectors.ShardingUpsertExecutor.apply(ShardingUpsertExecutor.java:197)
        at io.crate.operation.projectors.ShardingUpsertExecutor.apply(ShardingUpsertExecutor.java:74)
        at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:132)
        at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
        at io.crate.data.ForwardingBatchIterator.loadNextBatch(ForwardingBatchIterator.java:60)
        at io.crate.executor.transport.distributed.DistributingConsumer.consumeIt(DistributingConsumer.java:127)
        at io.crate.executor.transport.distributed.DistributingConsumer.accept(DistributingConsumer.java:102)
        at io.crate.data.ListenableBatchConsumer.accept(ListenableBatchConsumer.java:40)
        at io.crate.operation.projectors.ProjectingBatchConsumer.accept(ProjectingBatchConsumer.java:104)
        at io.crate.operation.collect.BatchIteratorCollectorBridge$SyncBatchItCollector.doCollect(BatchIteratorCollectorBridge.java:63)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:458)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
**Steps to reproduce**:
```
CREATE TABLE IF NOT EXISTS "doc"."logstatus" (
   "log_date" TIMESTAMP,
   "num_docs" LONG,
   "schema_name" STRING,
   "table_name" STRING,
   "ts" TIMESTAMP GENERATED ALWAYS AS date_trunc('year', '+07:00', "log_date")
)
CLUSTERED INTO 1 SHARDS
PARTITIONED BY ("ts");
crash --hosts crate.xxx -c "insert into logstatus (log_date, num_docs, schema_name, table_name) (select "`date +%s`"000 as log_date, num_docs, schema_name , table_name from sys.shards where primary = true)" -v
```

**Comment by matriv** [comment]
Hi @DLT1412, thanks for reporting. We will look into that.

**Comment by seut** [comment]
@DLT1412 We have fixed this issue, it will be released with the next hotfix release.
Thanks for reporting.
