### ISSUE TITLE
CrateDB fails to standup in kubernetes

### ISSUE THREAD

**Issue by markvdw4** [crate/crate#6719]
I've been trying to standup CreateDB in kubernetes by following the guide posted here:
https://crate.io/docs/crate/guide/en/latest/scaling/kubernetes.html

I copied the given yaml definition and created it on a GKE cluster running version 1.8.4-gke.1. The statefulset and the service are created properly but when the pods start up they all fail with the following error:

`
[2018-01-05T16:17:55,540][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [Watzmann] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Unknown discovery type [srv]
	at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:31) ~[crate-app-2.2.4.jar:2.2.4]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:142) ~[crate-app-2.2.4.jar:2.2.4]
	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:118) ~[crate-app-2.2.4.jar:2.2.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:73) ~[crate-app-2.2.4.jar:2.2.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[crate-app-2.2.4.jar:2.2.4]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[crate-app-2.2.4.jar:2.2.4]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:87) ~[crate-app-2.2.4.jar:2.2.4]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:80) ~[crate-app-2.2.4.jar:2.2.4]
Caused by: java.lang.IllegalArgumentException: Unknown discovery type [srv]
	at org.elasticsearch.discovery.DiscoveryModule.<init>(DiscoveryModule.java:97) ~[crate-app-2.2.4.jar:2.2.4]
	at org.elasticsearch.node.Node.<init>(Node.java:425) ~[crate-app-2.2.4.jar:2.2.4]
	at io.crate.node.CrateNode.<init>(CrateNode.java:62) ~[crate-app-2.2.4.jar:2.2.4]
	at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:199) ~[crate-app-2.2.4.jar:2.2.4]
	at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:199) ~[crate-app-2.2.4.jar:2.2.4]
	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:282) ~[crate-app-2.2.4.jar:2.2.4]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:138) ~[crate-app-2.2.4.jar:2.2.4]
	... 6 more
`

After a number of retries the end state of all the pods is CrashLoopBackOff:

root@crate-dev:~/crate# k get pods
NAME      READY     STATUS             RESTARTS   AGE
crate-0   0/1       CrashLoopBackOff   4          3m
crate-1   0/1       CrashLoopBackOff   4          3m
crate-2   0/1       CrashLoopBackOff   4          3m

It looks like maybe the srv discovery plugin is not being installed?
  
Crate Docker:
Latest and 2.2

Kubernetes version:
1.8.4-gke.1

**Comment by mfussenegger** [comment]
There was a breaking change in CrateDB 2.1:

> `srv` and `azure` are no longer valid configuration options for `discovery.type`. Instead there is a new `discovery.zen.hosts_provider` settings which can be set to either srv or azure.

You'll have to adopt the configuration to use `discovery.zen.hosts_provider` instead of `discovery.type`. 

We'll update the guide accordingly. Thanks for pointing out

**Comment by mfussenegger** [comment]
Guide will be updated with https://github.com/crate/guide/pull/67 .
