### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by qasimakhan** [crate/crate#6728]
**CrateDB version**: 2.2.5

**JVM version**: 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version / environment description**:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Problem description**:
I have created testing environment with 3 data/master nodes. I dumped approximately 34 million records on it. The node with all backup shards crashed with following logs.

[2018-01-09T15:54:49,250][INFO ][o.e.m.j.JvmGcMonitorService] [Noc-3] [gc][93065] overhead, spent [19.2s] collecting in the last [46.5s]
[2018-01-09T15:54:49,250][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Noc-3] fatal error in thread [elasticsearch[Noc-3][management][T#3]], exiting
java.lang.OutOfMemoryError: Java heap space
        at org.apache.lucene.util.CloseableThreadLocal.set(CloseableThreadLocal.java:95) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextThreadLocal.set(ThreadContext.java:511) ~[crate-app-2.2.5.jar:2.2.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext.lambda$newStoredContext$2(ThreadContext.java:135) ~[crate-app-2.2.5.jar:2.2.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$$Lambda$1835/1321368652.close(Unknown Source) ~[?:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$StoredContext.restore(ThreadContext.java:348) ~[crate-app-2.2.5.jar:2.2.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:567) ~[crate-app-2.2.5.jar:2.2.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-01-09T15:54:49,432][ERROR][o.e.t.n.Netty4Utils      ] fatal error on the network layer
        at org.elasticsearch.transport.netty4.Netty4Utils.maybeDie(Netty4Utils.java:179)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:83)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)

**Steps to reproduce**:

CREATE TABLE IF NOT EXISTS "doc"."zbmccdr" (
   "billresponse" LONG,
   "datetime" STRING,
   "destination" STRING,
   "info" LONG,
   "sipresponse" LONG,
   "source" STRING
)
CLUSTERED INTO 6 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
)

The following is randomly generated data that is dumped into the table:
{"info": "2", "source": "923126560589", "destination": "923215314623", "billresponse": "0", "sipresponse": "183"}
{"info": "3", "source": "923318098257", "destination": "923315114709", "billresponse": "0", "sipresponse": "200"}
{"info": "3", "source": "923117795919", "destination": "923324367992", "billresponse": "3", "sipresponse": "603"}
{"info": "2", "source": "923316773220", "destination": "923120055185", "billresponse": "0", "sipresponse": "183"}
{"info": "3", "source": "923234099246", "destination": "923111397203", "billresponse": "2", "sipresponse": "200"}
{"info": "1", "source": "923321396169", "destination": "923339085138", "billresponse": "2", "sipresponse": "404"}
{"info": "0", "source": "923114377450", "destination": "923132782615", "billresponse": "-2", "sipresponse": "183"}
{"info": "0", "source": "923315457523", "destination": "923115437347", "billresponse": "-2", "sipresponse": "603"}
{"info": "0", "source": "923317046652", "destination": "923212535484", "billresponse": "1", "sipresponse": "200"}
{"info": "2", "source": "923222502655", "destination": "923334223759", "billresponse": "-3", "sipresponse": "500"}

**Comment by mfussenegger** [comment]
Thanks for reporting - couple of questions:

 1) Did you run any other queries besides just inserting records?

 2) Did you change any of the default settings (e.g. increase thread pool size
 or something like that, because some of these settings changes can translate to
 circumventing measures that should prevent out of memory errors)

 3) Did you adapt the CRATE_HEAP_SIZE environment parameter? What is it currently set to?

 4) Could you provide us with a memory dump created when a node dies with that
 error? You can create one by running CrateDB with the `CRATE_JAVA_OPTS`
 environment variable set to include `-XX:+HeapDumpOnOutOfMemoryError` (might
 want to optionally specify a path, by including
 `-XX:HeapDumpPath=/path/to/heap/dumps` as well within `CRATE_JAVA_OPTS`)

**Comment by mfussenegger** [comment]
Closing this because of no additional feedback. Please reopen once the questions in the above comment can be answered (at least 1 to 3)
