### ISSUE TITLE
Writing a spark dataframe to crate using overwrite mode generates type conflict exception and gets the table deleted

### ISSUE THREAD

**Issue by usmanskhan** [crate/crate#7118]
CrateDB version: 2.2.6

JVM version:

    CrateDB 2.2.6
    openjdk version "1.8.0_151"

OS version / environment description:

Linux Version
uname -a
```
4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Official CrateDB Docker images for each version
```
https://hub.docker.com/_/crate/
```

docker --version
```
Docker version 17.09.1-ce, build 19e2cf6
```

Problem description:
Writing a dataframe to crate using overwrite mode generates type conflict exception and gets the table deleted.

Steps to Replicate:

Create a Table : 
``` 
  CREATE TABLE IF NOT EXISTS "doc"."table_a" (
   "Source" STRING,
   "id" INTEGER,
   PRIMARY KEY ("id")
)
CLUSTERED BY ("id") INTO 4 SHARDS
WITH (
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.write" = false,
   column_policy = 'dynamic',
   "mapping.total_fields.limit" = 1000,
   number_of_replicas = '0-1',
   "recovery.initial_shards" = 'quorum',
   refresh_interval = 1000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'all'
);
```

Python Code to replicate the error :
 
```
from pyspark import SparkContext, Row
from pyspark.sql import SQLContext

CRATE_JDBC_DRIVER="io.crate.client.jdbc.CrateDriver"
crate_jdbc_str="jdbc:crate://%s:%d/?user=crate" %("localhost", 5432)
table_name = "h"
sc = SparkContext(appName="test")
sql_context = SQLContext(sc)

def read_values():
    df_crate = sql_context.read.format("jdbc").option("url", crate_jdbc_str)\
    .option("driver", CRATE_JDBC_DRIVER)\
    .option("dbtable", table_name) \
    .load()
    return df_crate

def write_values(data_frame, mode):
    data_frame.write.option("driver", CRATE_JDBC_DRIVER).jdbc(crate_jdbc_str,
                                                              table_name, mode)

expected_rows = [Row(id=112224, Source="asdwefs")]
expected_data_frame = sql_context.createDataFrame(expected_rows)
write_values(expected_data_frame, "append")
df=read_values()
print df.collect()
write_values(expected_data_frame, "overwrite")
```

Exception Thrown : 
```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
18/03/30 12:40:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/03/30 12:40:01 WARN Utils: Your hostname, in01nbk461-Latitude-5580 resolves to a loopback address: 127.0.1.1; using 10.1.19.164 instead (on interface wlp2s0)
18/03/30 12:40:01 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[Row(Source=u'some-name', id=112)]
Traceback (most recent call last):
  File "testing_crate.py", line 26, in <module>
    write_values(expected_data_frame, "overwrite")
  File "testing_crate.py", line 19, in write_values
    table_name, mode)
  File "/home/ukhan/Downloads/spark-2.2.0-bin-hadoop2.7/python/pyspark/sql/readwriter.py", line 820, in jdbc
    self._jwrite.mode(mode).jdbc(url, table, jprop)
  File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1160, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/ukhan/Downloads/spark-2.2.0-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/py4j/protocol.py", line 320, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o49.jdbc.
: io.crate.shade.org.postgresql.util.PSQLException: ERROR: SQLParseException: line 1:32: no viable alternative at input '"Source" TEXT'
        at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
        at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
        at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:433)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:359)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:306)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:292)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
        at io.crate.shade.org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:249)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createTable(JdbcUtils.scala:805)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:72)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:472)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
        at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:461)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by joemoe** [comment]
hi @usmanskhan,

we are not actively maintaining spark support in cratedb therefor we have no test setup to actively debug your problem. we are aware of some customers using cratedb with spark successfully. it is really strange that this code deletes the table.
here is a students project that used spark with cratedb, but this is java based.
https://github.com/Taliik/crate-spark-pipeline

thanks, 
joe

**Comment by usmanskhan** [comment]
Thanks for your time nevertheless

**Comment by joemoe** [comment]
hi @usmanskhan, i talked to @Taliik today.
it is not possible to use spark dataframes with the `overwrite` option at the moment. so you need to create the table upfront and then use it with the `append`. at the moment spark is not able to create a proper cratedb table they only support hive tables.

let me know if that works for you.
thanks,
joe

**Comment by mfussenegger** [comment]
With the compatibility improvements in CrateDB 4.0 (`TEXT` type), your example code works now.

But 

```python
df=read_values()
print(df.collect())
```

Will initially return an empty result, because a [REFRESH TABLE](https://crate.io/docs/crate/reference/en/latest/sql/statements/refresh.html) is necessary after a write for the data to become visible ([CrateDB is eventually consistent](https://crate.io/docs/crate/reference/en/latest/general/dql/refresh.html?highlight=eventual%20consistency))
