### ISSUE TITLE
cant run crate

### ISSUE THREAD

**Issue by CheyenneForbes** [crate/crate#7129]
i downloaded crate from github but when I try to run it with "`./app/build/install/crate/bin/crate`" I get this:

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
[2018-04-04T17:58:07,650][INFO ][o.e.n.Node               ] [Lastìa de Framónt] initializing ...
[2018-04-04T17:58:07,841][INFO ][o.e.e.NodeEnvironment    ] [Lastìa de Framónt] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [423.1gb], net total_space [450.3gb], types [rootfs]
[2018-04-04T17:58:07,841][INFO ][o.e.e.NodeEnvironment    ] [Lastìa de Framónt] heap size [955.3mb], compressed ordinary object pointers [true]
[2018-04-04T17:58:08,681][INFO ][i.c.plugin               ] [Lastìa de Framónt] plugins loaded: [hyperLogLog, lang-js, jmx-monitoring]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2018-04-04T17:58:09,703][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] no modules loaded
[2018-04-04T17:58:09,707][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [crate-azure-discovery]
[2018-04-04T17:58:09,708][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [es-repository-hdfs]
[2018-04-04T17:58:09,708][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [io.crate.plugin.BlobPlugin]
[2018-04-04T17:58:09,708][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [io.crate.plugin.CrateCorePlugin]
[2018-04-04T17:58:09,708][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [io.crate.plugin.HttpTransportPlugin]
[2018-04-04T17:58:09,709][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [io.crate.plugin.PluginLoaderPlugin]
[2018-04-04T17:58:09,709][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [io.crate.plugin.SrvPlugin]
[2018-04-04T17:58:09,709][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [io.crate.udc.plugin.UDCPlugin]
[2018-04-04T17:58:09,710][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [org.elasticsearch.analysis.common.CommonAnalysisPlugin]
[2018-04-04T17:58:09,710][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin]
[2018-04-04T17:58:09,710][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [org.elasticsearch.plugin.repository.url.URLRepositoryPlugin]
[2018-04-04T17:58:09,710][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [org.elasticsearch.repositories.s3.S3RepositoryPlugin]
[2018-04-04T17:58:09,710][INFO ][o.e.p.PluginsService     ] [Lastìa de Framónt] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[2018-04-04T17:58:09,749][INFO ][o.e.n.Node               ] [Lastìa de Framónt] node name [Lastìa de Framónt], node ID [Eedk7KCiTvCK90JaUr0RYg]
[2018-04-04T17:58:09,754][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Lastìa de Framónt] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
        at io.crate.node.CrateNode.startUpLogging(CrateNode.java:85) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at org.elasticsearch.node.Node.<init>(Node.java:285) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at io.crate.node.CrateNode.<init>(CrateNode.java:66) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:205) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:205) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:277) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at io.crate.bootstrap.CrateDB.execute(CrateDB.java:135) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.3.jar:3.0.0-SNAPSHOT-]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.3.jar:3.0.0-SNAPSHOT-]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:88) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:81) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 7
        at java.lang.String.substring(String.java:1963) ~[?:1.8.0_162]
        at io.crate.Build.<clinit>(Build.java:49) ~[crate-app-3.0.0-SNAPSHOT-.jar:3.0.0-SNAPSHOT-]
        ... 13 more
```

**Comment by CheyenneForbes** [comment]
When I run `"./app/build/install/crate/bin/crate -v"` i also get the error 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.crate.Version.main(Version.java:95)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 7
        at java.lang.String.substring(String.java:1963)
        at io.crate.Build.<clinit>(Build.java:49)
        ... 1 more
```

**Comment by mxm** [comment]
This happens when you don't have `git` installed or you downloaded the pure source without the `.git` directory. Either way, the build hash can't be determined. Seems like nobody has ever done that :)

Fix: https://github.com/crate/crate/pull/7137

**Comment by mxm** [comment]
@CheyenneForbes Seems like JNA is not available on your server. What kind of JVM are you using? Also please provide your OS.

**Comment by CheyenneForbes** [comment]
Ubuntu 14  and openjdk version "1.8.0_162"

**Comment by mxm** [comment]
Your kernel does not seem to support `seccomp` which is why the startup check fails. You can work around this by setting `system_call_filter` to `false`, e.g.  `crate -Cbootstrap.system_call_filter=false`.

**Comment by mxm** [comment]
@CheyenneForbes Did you get it running using the workaround?

Could you provide the output of `uname -a`?

**Comment by CheyenneForbes** [comment]
yes, thank you :)

**Comment by mxm** [comment]
You're welcome. Could you still provide the output of `uname -a`?

**Comment by CheyenneForbes** [comment]
`Linux localhost.localdomain 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by julian05060506** [comment]
I put log4j-slf4j-impl-2.11.0.jar into crate/lib ,solved.
you can download this jar from http://mvnrepository.com/,search this jar
