### ISSUE TITLE
Disable string length in partitioned tables

### ISSUE THREAD

**Issue by lserraga** [crate/crate#7244]
**CrateDB version**:  2.3.7

**Environment description**: 
- Official crate docker image
- Docker 17.12.0-ce over darwin/amd64

**Problem description**:

When creating a partitioned table and disabling the string limit in one of the columns crate will return success but the table is not queriable and always returns the same error (even when you try to drop it).

***Error! 
SQLActionException[ClassCastException: java.lang.String cannot be cast to java.lang.Boolean]***

Error trace:
```
SQLActionException: INTERNAL_SERVER_ERROR 5000 ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at io.crate.metadata.doc.DocIndexMetaData.internalExtractColumnDefinitions(DocIndexMetaData.java:390)
	at io.crate.metadata.doc.DocIndexMetaData.createColumnDefinitions(DocIndexMetaData.java:509)
	at io.crate.metadata.doc.DocIndexMetaData.build(DocIndexMetaData.java:576)
	at io.crate.metadata.doc.DocTableInfoBuilder.buildDocIndexMetaDataFromTemplate(DocTableInfoBuilder.java:156)
	at io.crate.metadata.doc.DocTableInfoBuilder.docIndexMetaData(DocTableInfoBuilder.java:81)
	at io.crate.metadata.doc.DocTableInfoBuilder.build(DocTableInfoBuilder.java:179)
	at io.crate.metadata.doc.InternalDocTableInfoFactory.create(InternalDocTableInfoFactory.java:55)
	at io.crate.metadata.doc.DocSchemaInfo.innerGetTableInfo(DocSchemaInfo.java:139)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.crate.metadata.doc.DocSchemaInfo.getTableInfo(DocSchemaInfo.java:145)
	at io.crate.metadata.doc.DocSchemaInfo.getTableInfo(DocSchemaInfo.java:108)
	at io.crate.metadata.Schemas.getTableInfo(Schemas.java:102)
	at io.crate.metadata.Schemas.getTableInfo(Schemas.java:120)
	at io.crate.analyze.DropTableAnalyzer.analyze(DropTableAnalyzer.java:45)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitDropTable(Analyzer.java:245)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitDropTable(Analyzer.java:204)
	at io.crate.sql.tree.DropTable.accept(DropTable.java:47)
	at io.crate.sql.tree.AstVisitor.process(AstVisitor.java:29)
	at io.crate.analyze.Analyzer.analyzedStatement(Analyzer.java:199)
	at io.crate.analyze.Analyzer.boundAnalyze(Analyzer.java:188)
	at io.crate.protocols.postgres.SimplePortal.bind(SimplePortal.java:139)
	at io.crate.action.sql.Session.bind(Session.java:274)
	at io.crate.rest.action.RestSQLAction.executeSimpleRequest(RestSQLAction.java:179)
	at io.crate.rest.action.RestSQLAction.prepareRequest(RestSQLAction.java:135)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:64)
	at io.crate.rest.CrateRestMainAction$RestFilter.handleRequest(CrateRestMainAction.java:255)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:262)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200)
	at io.crate.protocols.http.CrateNettyHttpServerTransport$CrateDispatcher.dispatchRequest(CrateNettyHttpServerTransport.java:119)
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:505)
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:80)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:162)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:122)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce**:

Create table:

```sql
CREATE TABLE
test (
   id INT,
   mode STRING,
   example STRING INDEX OFF STORAGE WITH (columnstore = false)
)
CLUSTERED INTO 4 SHARDS
PARTITIONED BY (mode);
```
Query table:
```sql
SELECT * FROM test
```

**Comment by seut** [comment]
@lserraga Thx a lot for reporting, this is indeed a bug. We already have a fix for this, I'll notify you once it is merged and backported.

**Comment by seut** [comment]
@lserraga We've fixed this by https://github.com/crate/crate/pull/7253, it will be released with the next hotfix release.

**Comment by lserraga** [comment]
@seut That's great, thank you!
