### ISSUE TITLE
IOException on startup

### ISSUE THREAD

**Issue by bputt** [crate/crate#7280]
**CrateDB version**: 3.0.0-SNAPSHOT-01a5fae

**Environment description**:

Centos 7.4
OpenJDK 1.8.0_161-b14

**Problem description**:
When crate starts, I get the following error:

```
[ERROR][o.e.g.GatewayMetaState    ] [node-name] failed to read local state, exiting...
org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:10, legacy: false, file:/data02/nodes/0/indices......./_state/state-10.st]
at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:196)
at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:334)
at org.elasticsearch.common.util.IndexFolderUpgrader.upgrade(IndexFolderUpgrader.java:90)
at org.elasticsearch.common.util.IndexFolderUpgrader.upgradeIndicesIfNeeded(IndexFolderUpgrader.java:128)
at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87)
at org.elasticsearch.node.Node.<init>(Node.java:397)
at io.crate.node.CrateNode.<init>(CrateNode.java:66)
at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:202)
at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:202)
at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:267)
at io.crate.bootstrap.CrateDb.init(CrateDB.java:155)
at io.crate.bootstrap.CrateDb.execute(CrateDB.java:135)
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
at org.elasticsearch.cli.Command.main(Command.java:90)
at io.crate.bootstrap.CrateDb.main(CrateDB.java:88)
at io.crate.bootstrap.CrateDb.main(CrateDB.java:81)
```

**Comment by bputt** [comment]
This is a new cluster, we're using multiple partitions and some of them went read-only. This is the issue when fixing the read-only drives and restarting crate.

**Comment by mxm** [comment]
I'm assuming you have corrupted CrateDB's cluster state then because some of the disk's partitions switch to read-only. If this is a new cluster without any data, please delete the data directories, set the drive partitions to read/write and restart CrateDB.

**Comment by bputt** [comment]
That's certainly possible, wanted to submit something here in case it might be a bug. Is it possible to make crate/elasticsearch a little more resilient when network latency issues occur?

**Comment by bputt** [comment]
Since replication was turned on, I'll just close this as it's most likely not an actual bug like you mentioned.

As for network latency, yes, it has nothing to do with this issue, just a question ☕️ which I'll redirect somewhere else

**Comment by mxm** [comment]
Feel free to open another issue for network related problems. We would definitely like to improve on any network problems.
