### ISSUE TITLE
Not enough active copies to meet shard count

### ISSUE THREAD

**Issue by bputt** [crate/crate#7293]
**CrateDB version**: 3.0.0 [new cluster]

**Environment description**:

CentOS 7.4
OpenJDK 1.8.0_161-b14

**Problem description**:

Almost all of the nodes in my cluster started logging the below error message and I'm not able to ingest data.

```
[o.e.i.sGlobalCheckpointSyncAction] [node-name] [namespaceName..partitioned.tableName.someId][0] global checkpoint sync failed
org.elasticsearch.transport.RemoteTransportException: [node-name][ip:4300][indices:admin/seq_no/global_checkpoint_sync[p]]
Caused by: org.elasticsearch.action.UnavailableShardsException: [namespaceName..partitioned.tableName.id][0] Not enough active copies to meet shard count of [ALL] (have 1, needed 2). Timeout: [1m], request: [GlobalCheckpointSyncAction.Request{shardId=[namespaceName..partitioned.tableName.id][0], timeout=1m,index='namespaceName..partitioned.tableName.id', waitForActiveShards=ALL}]
at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:98)
at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationaction.java:358)
at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationaction.java:298)
at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:974)
at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:971)
...
```

**Comment by bputt** [comment]
Full cluster restart fixed issue
