### ISSUE TITLE
Unable to import CSV file into crate

### ISSUE THREAD

**Issue by peterdn1** [crate/crate#7391]
**CrateDB version**:
2.3.11

**Environment description**:
 - JVM version: 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode)
 - Kernel: 
MSYS_NT-10.0 ... 2.6.0(0.304/5/3) 2016-09-07 20:45 x86_64 Msys

 Number of nodes; Please mention special master/data/client node configuration
1 node
**Problem description**:
Unable to import CVS file into crate, json import works

COPY ERROR (0.000 sec)
Error!
SQLActionException[NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes]

ERROR TRACE
SQLActionException: INTERNAL_SERVER_ERROR 5000 NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes
	at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:58)
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:103)
	at io.crate.expression.reference.file.LineContext.sourceAsMap(LineContext.java:49)
	at io.crate.expression.reference.file.LineContext.get(LineContext.java:58)
	at io.crate.expression.reference.file.ColumnExtractingLineExpression.value(ColumnExtractingLineExpression.java:38)
	at io.crate.execution.engine.collect.files.FileReadingIterator$1.get(FileReadingIterator.java:101)
	at io.crate.execution.engine.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:38)
	at io.crate.execution.engine.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:26)
	at io.crate.execution.engine.collect.RowShardResolver.setNextRow(RowShardResolver.java:78)
	at io.crate.execution.engine.indexing.GroupRowsByShard.accept(GroupRowsByShard.java:76)
	at io.crate.execution.engine.indexing.GroupRowsByShard.accept(GroupRowsByShard.java:45)
	at io.crate.data.BatchIterators$1.moveNext(BatchIterators.java:125)
	at io.crate.execution.engine.indexing.BatchIteratorBackpressureExecutor.consumeIterator(BatchIteratorBackpressureExecutor.java:151)
	at io.crate.execution.engine.indexing.BatchIteratorBackpressureExecutor.consumeIteratorAndExecute(BatchIteratorBackpressureExecutor.java:100)
	at io.crate.execution.engine.indexing.ShardingUpsertExecutor.apply(ShardingUpsertExecutor.java:212)
	at io.crate.execution.engine.indexing.ShardingUpsertExecutor.apply(ShardingUpsertExecutor.java:72)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:125)
	at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:77)
	at io.crate.data.BatchIterators.collect(BatchIterators.java:45)
	at io.crate.data.CollectingBatchIterator.lambda$newInstance$2(CollectingBatchIterator.java:81)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:125)
	at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
	at io.crate.data.MappedForwardingBatchIterator.loadNextBatch(MappedForwardingBatchIterator.java:52)
	at io.crate.action.sql.RowConsumerToResultReceiver.consumeIt(RowConsumerToResultReceiver.java:79)
	at io.crate.action.sql.RowConsumerToResultReceiver.accept(RowConsumerToResultReceiver.java:47)
	at io.crate.execution.engine.InterceptingRowConsumer.tryForwardResult(InterceptingRowConsumer.java:81)
	at io.crate.execution.engine.InterceptingRowConsumer.accept(InterceptingRowConsumer.java:68)
	at io.crate.data.ListenableRowConsumer.accept(ListenableRowConsumer.java:40)
	at io.crate.execution.engine.pipeline.ProjectingRowConsumer.accept(ProjectingRowConsumer.java:105)
	at io.crate.execution.engine.collect.BatchIteratorCollectorBridge$SyncBatchItCollector.doCollect(BatchIteratorCollectorBridge.java:64)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:575)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Steps to reproduce**:
CREATE TABLE users (id INT primary key, name STRING);

COPY users FROM 'file:///D:/wrk/crate-2.3.11/bin/Test-utf8.csv'
Test-utf8.csv
id,name
1,"Don't panic"
2,"Ford, you're turning into a penguin. Stop it."

**Comment by peterdn1** [comment]
Working in the 3.0 branch
