### ISSUE TITLE
aarch64 support for crate

### ISSUE THREAD

**Issue by anuscool** [crate/crate#7529]
i am trying to build crate using docker on aarch64 with alpine 3.7,but JRE is crashing but same is working with ubuntu and  centos on aarch64

**Comment by mfussenegger** [comment]
Could you provide some more information? 

1) Which version of CrateDB
2) What's the error message of the JRE crash?

**Comment by anuscool** [comment]
i am using 3.0.3 of crate and added this command   apk add --no-cache  libc6-compat in Dockerfile and when i run crate by command  docker run -p 4200:4200 crate then getting below error

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000003eb0, pid=1, tid=0x0000ffffa0f8fa78
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.8.0
# Distribution: Custom build (Wed Jun 13 18:00:44 UTC 2018)
# Problematic frame:
# C  0x0000000000003eb0
#
# Core dump written. Default location: /data/core or core.1
#
# An error report file with more information is saved as:
# /data/hs_err_pid1.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla

**Comment by mfussenegger** [comment]
Could you also provide the full `Dockerfile`?

**Comment by anuscool** [comment]
## -*- docker-image-name: "docker-crate" -*-
#
# Crate Dockerfile
# https://github.com/crate/docker-crate
#

FROM alpine:3.7
MAINTAINER Crate.IO GmbH office@crate.io

ENV GOSU_VERSION 1.9
RUN set -x \
    && apk add --no-cache --virtual .gosu-deps \
        dpkg \
        gnupg \
        curl \
    && export ARCH=$(echo $(dpkg --print-architecture) | cut -d"-" -f3) \
    && curl -o /usr/local/bin/gosu -fSL "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$ARCH" \
    && curl -o /usr/local/bin/gosu.asc -fSL "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$ARCH.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
    && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true \
    && apk del .gosu-deps

RUN addgroup crate && adduser -G crate -H crate -D

# install crate
ENV CRATE_VERSION 3.0.3
RUN apk add --no-cache --virtual .crate-rundeps \
        openjdk8-jre-base \
        python3 \
        openssl \
        curl \
    && apk add --no-cache  libc6-compat \
    && apk add --no-cache --virtual .build-deps \
        gnupg \
        tar \
    && curl -fSL -O https://cdn.crate.io/downloads/releases/crate-$CRATE_VERSION.tar.gz \
    && curl -fSL -O https://cdn.crate.io/downloads/releases/crate-$CRATE_VERSION.tar.gz.asc \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 90C23FC6585BC0717F8FBFC37FAAE51A06F6EAEB \
    && gpg --batch --verify crate-$CRATE_VERSION.tar.gz.asc crate-$CRATE_VERSION.tar.gz \
    && rm -rf "$GNUPGHOME" crate-$CRATE_VERSION.tar.gz.asc \
    && mkdir /crate \
    && tar -xf crate-$CRATE_VERSION.tar.gz -C /crate --strip-components=1 \
    && rm crate-$CRATE_VERSION.tar.gz \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && apk del .build-deps

ENV PATH /crate/bin:$PATH
# Default heap size for Docker, can be overwritten by args
ENV CRATE_HEAP_SIZE 512M

# This healthcheck indicates if a CrateDB node is up and running. It will fail
# if we cannot get any response from the CrateDB (connection refused, timeout
# etc). If any response is received (regardless of http status code) we
# consider the node as running.
HEALTHCHECK --timeout=30s --interval=30s CMD curl --fail --max-time 25 $(hostname):4200

RUN mkdir -p /data/data /data/log

VOLUME /data

ADD config/crate.yml /crate/config/crate.yml
ADD config/log4j2.properties /crate/config/log4j2.properties
COPY entrypoint_3.0.sh /docker-entrypoint.sh

WORKDIR /data

# http: 4200 tcp
# transport: 4300 tcp
# postgres protocol ports: 5432 tcp
EXPOSE 4200 4300 5432

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["crate"]

**Comment by anuscool** [comment]
Reason to add apk add --no-cache libc6-compat  this because i was getting below error

[2018-07-19T09:07:37,048][WARN ][o.e.b.Natives            ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna7270053301308272077.tmp: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /tmp/jna-3506402/jna7270053301308272077.tmp)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_171]
        at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_171]
        at java.lang.System.load(System.java:1086) ~[?:1.8.0_171]
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at com.sun.jna.Native.<clinit>(Native.java:140) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_171]
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.bootstrap.BootstrapProxy.initializeNatives(BootstrapProxy.java:104) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:162) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:267) [crate-app-3.0.3.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.init(CrateDB.java:155) [crate-app-3.0.3.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.execute(CrateDB.java:135) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:85) [crate-app-3.0.3.jar:3.0.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.1.4.jar:3.0.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.1.4.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:88) [crate-app-3.0.3.jar:3.0.3]
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:81) [crate-app-3.0.3.jar:3.0.3]
[2018-07-19T09:07:37,062][WARN ][o.e.b.Natives            ] cannot check if running as root because JNA is not available
[2018-07-19T09:07:37,062][WARN ][o.e.b.Natives            ] cannot install system call filter because JNA is not available
[2018-07-19T09:07:37,064][WARN ][o.e.b.Natives            ] cannot register console handler because JNA is not available
[2018-07-19T09:07:37,067][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2018-07-19T09:07:37,067][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_AS beacuse JNA is not available
[2018-07-19T09:07:37,067][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_FSIZE because JNA is not available
[2018-07-19T09:07:37,292][INFO ][o.e.n.Node               ] [Zehner] initializing ...

**Comment by mfussenegger** [comment]
Thank you for the details. As a workaround you could use a `Ubuntu` based image until we've time to look into this. See https://github.com/crate/docker-crate/pull/117

**Comment by mfussenegger** [comment]
I think this can be closed as the latest docker images should support aarch64
