### ISSUE TITLE
Crate Cluster not forming on Docker Swarm

### ISSUE THREAD

**Issue by taliaga** [crate/crate#7623]
**CrateDB version**:

3.0.5 (but it seems any > ~~2.0.6~~ 2.3.11)

**Environment description**:

- Official Crate Docker Image, e.g. crate:3.0.5
- 2-nodes local swarm (tried with 3 also, but 2 is faster to reproduce)
- Docker version 18.06.1-ce, build e68fc7a
- All replicas attached to a docker overlay network

**Problem description**:

The latest version of Crate (3.0.7) is not able to form a cluster when running on Docker Swarm mode as it used to until version ~~2.0.6~~ 2.3.11.

The previous idea was to use docker's `dnsrr` and set `-Cdiscovery.zen.ping.unicast.hosts` to the name of the docker service so the discovery would eventually gather all actual container endpoints.
This, plus using `-Cnetwork.host` flag, which I used to use with value `0.0.0.0` (none of the other options `_local_` nor `_site_` work now).

The issue seems to be in the discovery process (see logs at the end).

I wanted to understand a bit better what's the issue under the hood so as to better judge:
- If there's something I can do?
- Which are the options we'd have?

I also though opening this issue would be a good way to keep informed on what's decided on the matter.

Thanks for your work!

**Steps to reproduce**:

Running this `docker-compose.yml` would do.

```
version: '3.3'
services:
  crate:
    image: crate:3.0.5
    command: ["crate",
        "-Clicense.enterprise=false",
        "-Cgateway.expected_nodes=2",
        "-Cgateway.recover_after_nodes=1",
        "-Cgateway.recover_after_time=5m",
        "-Cdiscovery.zen.minimum_master_nodes=1",
        "-Cdiscovery.zen.ping.unicast.hosts=crate",
        "-Cdiscovery.zen.ping_timeout=15s",
        "-Cnetwork.host=_local_",
        "-Chttp.cors.enabled=true",
        '-Chttp.cors.allow-origin="*"']
    environment:
      - MAX_MAP_COUNT=262144
      - ES_JAVA_OPTS="-Xms1g -Xmx1g"
      - CRATE_HEAP_SIZE=1g
    deploy:
      endpoint_mode: dnsrr
      mode: global
      labels:
        - "traefik.port=4200"
        - "traefik.frontend.rule=Host:crate.mydomain.com"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.backend=crate"
        - "traefik.backend.loadbalancer.swarm=false"
      update_config:
        parallelism: 1
        delay: 10s

    volumes:
      - cratedata:/data
    networks:
      - backend

volumes:
  cratedata:

networks:
  backend:
    driver: overlay
```

**Additional Logs**:
```
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:35,812][INFO ][o.e.n.Node               ] [Tête du Clotonnet] initializing ...
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:36,037][INFO ][o.e.e.NodeEnvironment    ] [Tête du Clotonnet] using [1] data paths, mounts [[/data (/dev/sda1)]], net usable_space [15.3gb], net total_space [17.8gb], types [ext4]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:36,039][INFO ][o.e.e.NodeEnvironment    ] [Tête du Clotonnet] heap size [1015.6mb], compressed ordinary object pointers [true]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:37,385][INFO ][i.c.plugin               ] [Tête du Clotonnet] plugins loaded: [jmx-monitoring, hyperLogLog, lang-js]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
crate3_crate.0.t16mhtw8djlh@ms-worker0    | SLF4J: Defaulting to no-operation (NOP) logger implementation
crate3_crate.0.t16mhtw8djlh@ms-worker0    | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,398][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] no modules loaded
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,410][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [crate-azure-discovery]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,411][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [es-repository-hdfs]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,411][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [io.crate.plugin.BlobPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,411][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [io.crate.plugin.CrateCorePlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,411][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [io.crate.plugin.HttpTransportPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,411][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [io.crate.plugin.PluginLoaderPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,411][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [io.crate.plugin.SrvPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,412][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [io.crate.udc.plugin.UDCPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,412][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [org.elasticsearch.analysis.common.CommonAnalysisPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,414][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,414][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [org.elasticsearch.plugin.repository.url.URLRepositoryPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,415][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [org.elasticsearch.repositories.s3.S3RepositoryPlugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,415][INFO ][o.e.p.PluginsService     ] [Tête du Clotonnet] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,480][INFO ][o.e.n.Node               ] [Tête du Clotonnet] node name [Tête du Clotonnet], node ID [2HtcoZYZT_m-W6Onr4sZJg]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,548][INFO ][o.e.n.Node               ] [Tête du Clotonnet] CrateDB version[3.0.5], pid[1], build[8970370/2018-07-31T06:18:44Z], OS[Linux/4.9.93-boot2docker/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_171/25.171-b11]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:39,549][INFO ][o.e.n.Node               ] [Tête du Clotonnet] JVM arguments [-Xms1g, -Xmx1g, -Djava.awt.headless=true, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Xloggc:/data/log/gc.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=16, -XX:GCLogFileSize=64m, -XX:+DisableExplicitGC, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/data/data, -XX:+UnlockExperimentalVMOptions, -XX:+UseCGroupMemoryLimitForHeap, -Des.cgroups.hierarchy.override=/]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:43,177][INFO ][o.e.d.DiscoveryModule    ] [Tête du Clotonnet] using discovery type [zen]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:45,824][INFO ][i.c.p.s.SslContextProvider] HTTP SSL support is disabled.
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:46,878][INFO ][o.e.n.Node               ] [Tête du Clotonnet] initialized
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:46,879][INFO ][o.e.n.Node               ] [Tête du Clotonnet] starting ...
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:47,057][INFO ][psql                     ] [Tête du Clotonnet] PSQL SSL support is disabled.
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:47,262][INFO ][psql                     ] [Tête du Clotonnet] publish_address {127.0.0.1:5432}, bound_addresses {127.0.0.1:5432}
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:47,315][INFO ][i.c.p.h.CrateNettyHttpServerTransport] [Tête du Clotonnet] publish_address {127.0.0.1:4200}, bound_addresses {127.0.0.1:4200}
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:47,352][INFO ][o.e.t.TransportService   ] [Tête du Clotonnet] publish_address {127.0.0.1:4300}, bound_addresses {127.0.0.1:4300}
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:03:50,145][WARN ][o.e.d.z.UnicastZenPing   ] [Tête du Clotonnet] failed to resolve host [crate]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | java.net.UnknownHostException: crate: Name does not resolve
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:917) ~[crate-app-3.0.5.jar:3.0.5]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:872) ~[crate-app-3.0.5.jar:3.0.5]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:699) ~[crate-app-3.0.5.jar:3.0.5]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:213) ~[crate-app-3.0.5.jar:3.0.5]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [crate-app-3.0.5.jar:3.0.5]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:04:05,192][INFO ][o.e.c.s.MasterService    ] [Tête du Clotonnet] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {Tête du Clotonnet}{2HtcoZYZT_m-W6Onr4sZJg}{eX1oGcS7Q1CKRLQlpZKjow}{127.0.0.1}{127.0.0.1:4300}{http_address=127.0.0.1:4200}
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:04:05,208][INFO ][o.e.c.s.ClusterApplierService] [Tête du Clotonnet] new_master {Tête du Clotonnet}{2HtcoZYZT_m-W6Onr4sZJg}{eX1oGcS7Q1CKRLQlpZKjow}{127.0.0.1}{127.0.0.1:4300}{http_address=127.0.0.1:4200}, reason: apply cluster state (from master [master {Tête du Clotonnet}{2HtcoZYZT_m-W6Onr4sZJg}{eX1oGcS7Q1CKRLQlpZKjow}{127.0.0.1}{127.0.0.1:4300}{http_address=127.0.0.1:4200} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:04:05,216][INFO ][o.e.g.GatewayService     ] [Tête du Clotonnet] delaying initial state recovery for [5m]. expecting [2] nodes, but only have [1]
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:04:05,223][INFO ][o.e.n.Node               ] [Tête du Clotonnet] started
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:05:04,564][INFO ][o.e.n.Node               ] [Tête du Clotonnet] stopping ...
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:05:04,719][INFO ][o.e.n.Node               ] [Tête du Clotonnet] stopped
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:05:04,720][INFO ][o.e.n.Node               ] [Tête du Clotonnet] closing ...
crate3_crate.0.t16mhtw8djlh@ms-worker0    | [2018-08-30T14:05:04,786][INFO ][o.e.n.Node               ] [Tête du Clotonnet] closed
```

_Update: bump latest versions working (`2.3.11`) and not working (`3.0.7`) on docker swarm._

**Comment by taliaga** [comment]
Hi @quodt, thanks for the suggestion. 

I've tried using specific interfaces `_ethX_` as you suggested but without success.

There are some differences to consider from your example. For instance, you seem to be passing a variable with "hosts" for the unicast ping. I want this to still be the "crate" docker service name so that the deployment is independent of specific docker ips (users shouldn't know those).

From the logs, I see that what changed from previous versions is that now, when "bound to a non-loopback address" it triggers the bootstrap checks onto which the attempt to resolve host `crate` fails.

```
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:35,524][INFO ][o.e.n.Node               ] [Weißseespitze] initialized
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:35,529][INFO ][o.e.n.Node               ] [Weißseespitze] starting ...
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:35,631][INFO ][psql                     ] [Weißseespitze] PSQL SSL support is disabled.
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:35,830][INFO ][psql                     ] [Weißseespitze] publish_address {127.0.0.1:5432}, bound_addresses {0.0.0.0:5432}
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:35,878][INFO ][i.c.p.h.CrateNettyHttpServerTransport] [Weißseespitze] publish_address {127.0.0.1:4200}, bound_addresses {0.0.0.0:4200}
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:35,907][INFO ][o.e.t.TransportService   ] [Weißseespitze] publish_address {127.0.0.1:4300}, bound_addresses {0.0.0.0:4300}
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:35,938][INFO ][o.e.b.BootstrapChecks    ] [Weißseespitze] bound or publishing to a non-loopback address, enforcing bootstrap checks
ql2_crate.0.x048hb5di3lg@ms-manager0    | [2018-09-03T16:29:36,252][WARN ][o.e.d.z.UnicastZenPing   ] [Weißseespitze] failed to resolve host [crate]
ql2_crate.0.x048hb5di3lg@ms-manager0    | java.net.UnknownHostException: crate: Name does not resolve
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:917) ~[crate-app-3.0.5.jar:3.0.5]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:872) ~[crate-app-3.0.5.jar:3.0.5]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:699) ~[crate-app-3.0.5.jar:3.0.5]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:213) ~[crate-app-3.0.5.jar:3.0.5]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [crate-app-3.0.5.jar:3.0.5]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
ql2_crate.0.x048hb5di3lg@ms-manager0    | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by quodt** [comment]
Hi @taliaga,

do you also use `tasks.{{.Service.Name}}`? You may know that this will resolve to a multi IP A entry and not to the IP of the service load balancer. This is important for discovery.

**Comment by quodt** [comment]
@taliaga did you make it working?

**Comment by taliaga** [comment]
Sorry for the silence, I've been out for a while. I tried with ```tasks.{{.Service.Name}}``` but it didn't work. (thanks for such tip anyway). I wanted to try it again before reporting anything, but from what I recall, such template evaluated to something valid but the discovery phase still fails. I want to understand why.

Btw, did you (or anyone) make it work?

**Comment by quodt** [comment]
Hi @taliaga ,

I just did a test to start a cluster with your provided config and it wasn't working out of the box but i got it working with some minor changes. I did the test on a three node docker swarm.

This is the working config:

```
version: '3.3'
services:
  crate:
    image: crate:2.3.11
    command: ["crate",
        "-Clicense.enterprise=false",
        "-Cgateway.expected_nodes=3",
        "-Cgateway.recover_after_nodes=2",
        "-Cgateway.recover_after_time=5m",
        "-Cdiscovery.zen.minimum_master_nodes=2",
        "-Cdiscovery.zen.ping.unicast.hosts=tasks.crate",
        "-Cdiscovery.zen.ping_timeout=15s",
        "-Cnetwork.publish_host=_eth0_",
        "-Cnetwork.bind_host=0.0.0.0",
        "-Chttp.cors.enabled=true",
        '-Chttp.cors.allow-origin="*"']
    environment:
      - MAX_MAP_COUNT=262144
      - ES_JAVA_OPTS="-Xms256m -Xmx256m"
      - CRATE_HEAP_SIZE=512m
    deploy:
      endpoint_mode: dnsrr
      mode: global
      labels:
        - "traefik.port=4200"
        - "traefik.frontend.rule=Host:crate.mydomain.com"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.backend=crate"
        - "traefik.backend.loadbalancer.swarm=false"
      update_config:
        parallelism: 1
        delay: 10s

    networks:
      backend:

networks:
  backend:
    driver: overlay
```

As you can see i used version `2.3.11`. Not sure why it is not working with `3.0.5` but i'll check later. 
The differences in the configuration are these three options:

```
        "-Cdiscovery.zen.ping.unicast.hosts=tasks.crate",
        "-Cnetwork.publish_host=_eth0_",
        "-Cnetwork.bind_host=0.0.0.0",
```

The option `network.publish_host` has to point to the interface of the configured network, the option `network.bind_host` is set to listen on all interfaces and the option `discovery.zen.ping.unicast.hosts` is set to 'tasks.crate' to make sure it will resolve to the multi A entry to find all nodes of the crate service.

Please let me know if this is working for you as well.

**Comment by taliaga** [comment]
Thanks @quodt , that works with crate:2.3.11, so I'll update the "highest working version". 
I have just tried the same setting for `3.0.7` but the reported problem still persists.

**Comment by mfussenegger** [comment]
Sorry to close this, especially given the high quality of the problem report, but it appears that this is not about a bug in CrateDB and we'd like to keep this reserved for bug reports or feature requests. This seems to be docker/configuration related for which we've other channels.

**Comment by sonix07** [comment]
@taliaga I'm having the same issue but we have the enterprise support. I'll let you know when we get to the bottom of this behavior.

**Comment by jodok** [comment]
in my local tests i was able to solve the issue by changing the default dns ttl https://github.com/crate/docker-crate/pull/127

**Comment by sonix07** [comment]
@taliaga the problem is the alpine linux base image used for the container. I've built a custom crate container from this branch https://github.com/crate/docker-crate/tree/commoncrawl
using this 
Dockerfile: (It's not pretty as it is only meant for testing, and I'm not going to maintain this image)
```

FROM java:8-jre
MAINTAINER Crate Technology GmbH <office@crate.io>

RUN apt-get update && \
    apt-get install -y python3 && \
    rm -rf /var/lib/apt && \
    ln -s /usr/bin/python3 /usr/bin/python

# tmp folder on Crate CDN
ENV CDN_URL "https://cdn.crate.io/downloads/releases/"
# Crate version
ENV CRATE_VERSION "3.1.2"
ENV CRATE_URL "${CDN_URL}/crate-${CRATE_VERSION}.tar.gz"
# Commoncrawl Plugin version
#ENV PLUGIN_VERSION "1.3-SNAPSHOT"
#ENV PLUGIN_URL "${CDN_URL}/crate-commoncrawl-${PLUGIN_VERSION}.jar"

RUN useradd -ms /bin/bash crate

RUN mkdir -pv /crate && \
    wget -nv -O - ${CRATE_URL} | tar -xzC /crate --strip-components=1
# remove unused plugins and download commoncrawl plugin
#RUN rm -rf /crate/plugins/aws && \
#    rm -rf /crate/plugins/hdfs && \
#    rm -rf /crate/lib/sigar/*.so && \
#    rm -rf /crate/lib/sigar/*.dylib && \
#    rm -rf /crate/lib/sigar/*.dll && \
#    mkdir -pv /crate/plugins/commoncrawl && \
#    wget -nv -O /crate/plugins/commoncrawl/crate-commoncrawl-${PLUGIN_VERSION}.jar ${PLUGIN_URL}
RUN chown crate crate -R
USER crate
# add executable to path
ENV PATH /crate/bin:$PATH

VOLUME ["/data"]


ADD config/crate.yml /crate/config/crate.yml
ADD config/logging.yml /crate/config/logging.yml

WORKDIR /data

# http: 4200 tcp
# transport: 4300 tcp
EXPOSE 4200 4300

CMD ["crate"]
```

**Comment by taliaga** [comment]
thanks @sonix07. I'm not sure when I'll have time to be back to this issue, but you bring an interesting discovery (no pun intended) to continue the investigation.
