### ISSUE TITLE
NullPointerException when creating a nested object with a generated column.

### ISSUE THREAD

**Issue by celaus** [crate/crate#7642]
# CrateDB version:
3.1, branch azure-iot-hub-hackday

# Environment description:
Fedora 28
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

# Problem description:
NullPointer exception when creating a table that has a generated column in a nested object.

`create table a(a string, b as 1+1);` works
... but `create table a(a string, b OBJECT as (c AS 1+1));` fails with:

~~~
SQLActionException: 500 Internal Server Error 5000 NullPointerException in io.crate.analyze.AnalyzedColumnDefinition.addTypeOptions(AnalyzedColumnDefinition.java:256)
	at io.crate.analyze.AnalyzedColumnDefinition.addTypeOptions(AnalyzedColumnDefinition.java:256)
	at io.crate.analyze.AnalyzedColumnDefinition.toMapping(AnalyzedColumnDefinition.java:222)
	at io.crate.analyze.AnalyzedColumnDefinition.objectMapping(AnalyzedColumnDefinition.java:288)
	at io.crate.analyze.AnalyzedColumnDefinition.toMapping(AnalyzedColumnDefinition.java:242)
	at io.crate.analyze.AnalyzedTableElements.toMapping(AnalyzedTableElements.java:87)
	at io.crate.analyze.CreateTableAnalyzedStatement.mapping(CreateTableAnalyzedStatement.java:119)
	at io.crate.execution.ddl.tables.TableCreator.createIndexRequest(TableCreator.java:90)
	at io.crate.execution.ddl.tables.TableCreator.createTable(TableCreator.java:112)
	at io.crate.execution.ddl.tables.TableCreator.access$300(TableCreator.java:57)
	at io.crate.execution.ddl.tables.TableCreator$CreateTableResponseListener.onResponse(TableCreator.java:235)
	at io.crate.execution.ddl.tables.TableCreator.deleteOrphanedPartitions(TableCreator.java:213)
	at io.crate.execution.ddl.tables.TableCreator.deleteOrphans(TableCreator.java:172)
	at io.crate.execution.ddl.tables.TableCreator.create(TableCreator.java:84)
	at io.crate.execution.ddl.DDLStatementDispatcher$InnerVisitor.visitCreateTableStatement(DDLStatementDispatcher.java:150)
	at io.crate.execution.ddl.DDLStatementDispatcher$InnerVisitor.visitCreateTableStatement(DDLStatementDispatcher.java:141)
	at io.crate.analyze.CreateTableAnalyzedStatement.accept(CreateTableAnalyzedStatement.java:71)
	at io.crate.analyze.AnalyzedStatementVisitor.process(AnalyzedStatementVisitor.java:31)
	at io.crate.execution.ddl.DDLStatementDispatcher.apply(DDLStatementDispatcher.java:138)
	at io.crate.planner.node.ddl.GenericDDLPlan.execute(GenericDDLPlan.java:53)
	at io.crate.protocols.postgres.SimplePortal.sync(SimplePortal.java:222)
	at io.crate.action.sql.Session.sync(Session.java:407)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:272)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:214)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:119)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:162)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:131)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
~~~

**Steps to reproduce**:

Run the statements above :)

**Comment by mfussenegger** [comment]
Thanks for reporting the issue.

We'll support this in the upcoming 3.1 release but due to the size of the required changes we won't be backporting this to 3.0 but instead just improve the error from a NullPointerException to a meaningful error message.
