### ISSUE TITLE
#7808 is not resolved

### ISSUE THREAD

**Issue by daniel11c** [crate/crate#7953]
**CrateDB version**: 3.1.3

**Environment description**:
    Debian 8 (jessie) on AWS
    OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
    OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
    Crate.io v3.1.3-1~jessie
    5 nodes per cluster
    Kernel 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

**Problem description**:
Issue described in #7808 still occurs but with a lower rate. However we now have queries started via crash that were stopped with Ctrl+C and now cannot be killed anymore.

**Steps to reproduce**:
It's not something that can be reproduced with 100% rate. Just perform queries through JDBC driver or some heavy queries via crash, stop them with Ctrl+C. In some cases they cannot be later killed from sys.jobs.

**Comment by mfussenegger** [comment]
Do you have any error messages in the logs that would indicate some sort of failures?

I've checked some of our clusters running 3.1.3 and none have this problem.

**Comment by daniel11c** [comment]
[2018-12-10T10:08:57,994][WARN ][o.e.i.c.IndicesClusterStateService] [crate05] [[XXX.asset][2]] marking and sending shard failed due to [failed to create shard]
java.io.IOException: failed to obtain in-memory shard lock
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:389) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:510) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:141) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:552) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:529) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:231) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:495) ~[crate-app-3.1.3.jar:3.1.3]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_171]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:492) [crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:479) [crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) [crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:158) [crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [crate-app-3.1.3.jar:3.1.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [kora.asset][2]: obtaining shard lock timed out after 5000ms
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:668) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:587) ~[crate-app-3.1.3.jar:3.1.3]
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:327) ~[crate-app-3.1.3.jar:3.1.3]
        ... 17 more


or ....

[2018-12-10T10:36:03,010][ERROR][i.c.r.a.SqlHttpHandler   ] Error sending response
java.lang.NullPointerException: null
[2018-12-10T10:36:03,014][ERROR][i.c.r.a.SqlHttpHandler   ] Error sending response
java.lang.NullPointerException: null

**Comment by mfussenegger** [comment]
We do have another fix pending in regards to sys.jobs entries being stuck (coming in 3.1.4, https://github.com/crate/crate/commit/4511d1249cb2d2e1f33dafeff93481d2e5087845 and https://github.com/crate/crate/pull/7999) 

But I suspect the issue you're seeing is something else, so we'll dig a bit more.

**Comment by mfussenegger** [comment]
I haven't been able to reproduce any of the described issues here (job not killable), (stuck system queries).

I've run into a different issue that can cause stuck queries (which are killable) and we'll work on a fix for that. Meanwhile, if you've any more information that would allow us to reliably reproduce the issue you're encountering that would be very helpful.

**Comment by mfussenegger** [comment]
We've a fix for the stuck query issue I mentioned before (https://github.com/crate/crate/pull/8058)

Were you able to test out 3.1.4 to see if the issue you described still occurs? We still haven't found any way to produce stuck queries that are *not* killable.
