### ISSUE TITLE
NPE not serializable exception

### ISSUE THREAD

**Issue by bputt** [crate/crate#8066]
**CrateDB version**: 3.1.1
**Environment description**:
Java 1.8
CentOS 7.6
3 master nodes
2 query nodes
2 ingest nodes

**Problem description**:
When running a query on one of the master nodes, I get an exception ```SQLActionException[NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.NullPointerException]```. I can run the same query on any of the other nodes and don't have an issue. We'll probably narrow down the issue, but wanted to report in case you had any ideas in mind

**Steps to reproduce**:

```SELECT DISTINCT partitionkey FROM table WHERE someid = '' AND createdat >= 'YYYY-MM-DDTHH:MM:SS.sssZ' LIMIT 1```

No errors have been logged, so I'm guessing it's at the transport layer.

**Comment by mfussenegger** [comment]
Could you run the query in crash with `verbose` turned on and post the stacktrace? (Either start crash with `--verbose` or type `\verbose` inside the repl.)

**Comment by bputt** [comment]
restarted entire cluster, all good now

**Comment by Gmousse** [comment]
Hi !  Same issue, I re-open.

**CrateDB version**: 3.1.5
 **Environment description**:
Docker containers (official image)

**Problem description**:
We have exactly the same issue after our last update. When doing a DISTINCT or a GROUP BY on partition keys, crash raises:

```
SQLActionException[NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.NullPointerException]

SQLActionException: 500 Internal Server Error 5000 NotSerializableExceptionWrapper: unhandled_server_exception: java.lang.NullPointerException
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterators(ShardCollectSource.java:434)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterator(ShardCollectSource.java:289)
	at io.crate.execution.engine.collect.MapSideDataCollectOperation.createIterator(MapSideDataCollectOperation.java:56)
	at io.crate.execution.engine.collect.CollectTask.innerPrepare(CollectTask.java:133)
	at io.crate.execution.jobs.AbstractTask.prepare(AbstractTask.java:65)
	at io.crate.execution.jobs.RootTask.prepare(RootTask.java:195)
	at io.crate.execution.jobs.RootTask.<init>(RootTask.java:174)
	at io.crate.execution.jobs.RootTask.<init>(RootTask.java:53)
	at io.crate.execution.jobs.RootTask$Builder.build(RootTask.java:119)
	at io.crate.execution.jobs.TasksService.createTask(TasksService.java:139)
	at io.crate.execution.jobs.transport.TransportJobAction.nodeOperation(TransportJobAction.java:94)
	at io.crate.execution.jobs.transport.TransportJobAction.nodeOperation(TransportJobAction.java:50)
	at io.crate.execution.support.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:47)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1554)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce**:

```sql
SELECT DISTINCT(mypartitionkey) FROM mytable LIMIT 100;
```

OR 

```sql
SELECT mypartitionkey FROM mytable GROUP BY mypartitionkey LIMIT 100;
```

Please, reopen

**Comment by seut** [comment]
@Gmousse We are not able to reproduce this issue. Are you sure all nodes inside your cluster are running the same version?
If so, can you please give us more information like table schema & number of nodes or even exact steps to reproduce?
