### ISSUE TITLE
CrateDB lost data from partition

### ISSUE THREAD

**Issue by flascaray** [crate/crate#8259]
**CrateDB version**: 3.2.3

**Environment description**: 

docker 

-Cnode.name=bc-crate-vm1
-Cdiscovery.zen.ping.unicast.hosts=172.18.172.7,172.18.172.10,172.18.172.48
-Cdiscovery.zen.minimum_master_nodes=2
-Cgateway.recover_after_nodes=3
-Cnetwork.bind_host=0.0.0.0
-Cnetwork.publish_host=172.18.172.7
-Cgateway.expected_nodes=3
CRATE_HEAP_SIZE=4g

**Problem description**:

After doing some selects (no deletion) one partition disappeared !!!

**Steps to reproduce**:

I don't know how to reproduce it

The queries were like the following.

```sql
select event_id, provider_id, account_id ,meta['normalizedPositionId'],meta['positionId'],meta['seekerPositionId'], created from  moba.user_events e1
where created_month >= date_trunc('month', current_timestamp - (1000*60*60*24*30))
and country = 'AR'
order by created desc;
```

```sql
CREATE TABLE IF NOT EXISTS "moba"."user_events" (
   "account_id" STRING NOT NULL,
   "country" STRING NOT NULL,
   "created" TIMESTAMP NOT NULL,
   "created_month" STRING GENERATED ALWAYS AS CAST(date_trunc('month', "created") AS string),
   "event_id" STRING NOT NULL,
   "location" GEO_POINT,
   "message_id" STRING NOT NULL,
   "meta" OBJECT (DYNAMIC) AS (
      "categoryId" STRING,
      "customPosition" STRING,
      "gender_id" LONG,
      "normalizedPositionId" STRING,
      "payment" LONG,
      "paymentAmount" LONG,
      "paymentAmountPerHour" FLOAT,
      "paymentUnit" STRING,
      "paymentUnitHours" LONG,
      "paymentUnitId" STRING,
      "positionId" STRING,
      "positionOrder" LONG,
      "relatedPositions" BOOLEAN,
      "seekerPositionId" STRING
   ),
   "origin_ip" STRING,
   "provider_id" STRING,
   "seeker_id" STRING
)
CLUSTERED BY ("account_id") INTO 5 SHARDS
PARTITIONED BY ("country", "event_id", "created_month")
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '0-all',
   refresh_interval = 10000,
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "translog.durability" = 'ASYNC',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "warmer.enabled" = true,
   "write.wait_for_active_shards" = 'ALL'
)

```

**Comment by flascaray** [comment]
I never delete an index but the log says:

```java
[2019-02-18T15:35:01,805][WARN ][o.e.i.IndicesService     ] [bc-crate-vm1] [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g/O373eajCR425swm8UYgkfA] failed to delete index
org.elasticsearch.env.ShardLockObtainFailedException: [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g][0]: obtaining shard lock timed out after 0ms
	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:730) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:649) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.env.NodeEnvironment.lockAllForIndex(NodeEnvironment.java:595) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.env.NodeEnvironment.deleteIndexDirectorySafe(NodeEnvironment.java:546) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.indices.IndicesService.deleteIndexStoreIfDeletionAllowed(IndicesService.java:746) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.indices.IndicesService.deleteIndexStore(IndicesService.java:733) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:639) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:284) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:218) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:481) [crate-app-3.2.3.jar:3.2.3]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:478) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:465) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:416) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:160) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [crate-app-3.2.3.jar:3.2.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2019-02-18T16:05:01,815][WARN ][o.e.i.c.IndicesClusterStateService] [bc-crate-vm1] [[moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g/O373eajCR425swm8UYgkfA]] failed to complete pending deletion for index
org.elasticsearch.env.ShardLockObtainFailedException: [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g][0]: obtaining shard lock timed out after 1800000ms
	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:730) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:649) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.env.NodeEnvironment.lockAllForIndex(NodeEnvironment.java:595) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.indices.IndicesService.processPendingDeletes(IndicesService.java:1010) ~[crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService$2.doRun(IndicesClusterStateService.java:319) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [crate-app-3.2.3.jar:3.2.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [crate-app-3.2.3.jar:3.2.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by mfussenegger** [comment]
Were some of the nodes or all of them offline for some time? You've ` number_of_replicas = '0-all',` which means replicas are allowed to go to 0.

Are there any other errors in the log? The shard lock error alone doesn't lead to data loss.

**Comment by flascaray** [comment]
Hi @mfussenegger. I'm going to share the log of the 3 instances. 

From what I was seeing the instances were healthy.

The bc-crate-vm3.log has more information and I guess the problem occurred at 2019-02-18T15:35:01

[bc-crate-vm1.log](https://github.com/crate/crate/files/2881677/bc-crate-vm1.log)
[bc-crate-vm2.log](https://github.com/crate/crate/files/2881678/bc-crate-vm2.log)
[bc-crate-vm3.log](https://github.com/crate/crate/files/2881679/bc-crate-vm3.log)

**Comment by andreidan** [comment]
I had a look at the logs you provided and indeed it seems that `bc-crate-vm3` is the node that detected the issue. The first `FileNotFoundException` is present on 2019-02-11T21:30:08,196 
```
java.io.FileNotFoundException: no segments* file found in store(ByteSizeCachingDirectory(MMapDirectory@/data/data/nodes/0/indices/juMPXhayQImvFeZaZwXo5g/0/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@2b53795e)):
```
but the cluster recovers and is in GREEN state instantly
```
[2019-02-11T21:30:08,328][INFO ][o.e.c.r.a.AllocationService] [bc-crate-vm3] Cluster health status changed from [YELLOW] to [GREEN]
```

Everything seems to be running normally after that, 3 days later on 2019-02-14T19:18:11,879 the future problematic index is created

```
[2019-02-14T19:18:11,879][INFO ][o.e.a.a.i.c.TransportCreatePartitionsAction] [bc-crate-vm3] [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g] creating index, cause [bulk], templates [moba..partitioned.user_events., crate_defaults], shards [5]/[0], mappings [default]
[2019-02-14T19:18:11,881][INFO ][o.e.c.r.a.AllocationService] [bc-crate-vm3] updating number_of_replicas to [2] for indices [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g]
[2019-02-14T19:18:12,722][INFO ][o.e.c.r.a.AllocationService] [bc-crate-vm3] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g][2]] ...]).
[2019-02-14T19:18:12,792][INFO ][o.e.c.m.MetaDataMappingService] [bc-crate-vm3] [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g/O373eajCR425swm8UYgkfA] update_mapping [default]
[2019-02-14T19:18:25,281][INFO ][o.e.c.m.MetaDataMappingService] [bc-crate-vm3] [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g/O373eajCR425swm8UYgkfA] update_mapping [default]
```

and the cluster seems to be running in a GREEN state for 4 days until on 2019-02-18T15:35:01,766 a request to delete index `moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g/O373eajCR425swm8UYgkfA` is received and attempted (failed to execute)

```
[2019-02-18T15:35:01,766][INFO ][o.e.c.m.MetaDataDeleteIndexService] [bc-crate-vm3] [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g/O373eajCR425swm8UYgkfA] deleting index
[2019-02-18T15:35:01,844][WARN ][o.e.i.IndicesService     ] [bc-crate-vm3] [moba..partitioned.user_events.0c1k2kg7ad2k2ki390732d9k70sjee9i60o30c1g/O373eajCR425swm8UYgkfA] failed to delete index
```

Unfortunately, we'd need more information to figure out what's going on. Namely can you please provide: 

- the statements in the `sys.jobs_logs` from `2019-02-18` around `15:35:01` +- 15 minutes (the more the better) - trying to rule out a "drop table" statement that executed against the cluster would trigger this
- the FileNotFoundException that happened before points to something tampering with the data folder so can you please check for any filesystem and kernel communication issues? (`dmesg` should point out the possible errors)

**Comment by flascaray** [comment]
I was looking at the jobs_log and at 2019-02-18 12:35:01 I execute the following delete:

```sql
delete from moba.user_events
where created_month >= date_trunc('month', current_timestamp - (1000*60*60*24*30))
and event_id = 'SEARCH'
```
Obviously run it without wanting, the mistake was mine.
