### ISSUE TITLE
Window partitions or custom frame definitions are not supported

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#9057]
**CrateDB version**:
Latest docker

**Environment description**:
 - JVM version: JDK 8
 - Kernel: Linux ip-25-10-6-106 4.15.0-1044-aws
 - Distribution:  NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"

 - Number of nodes; 3

If using docker:

 - Docker: latest image
 - Problem can be reproduced without docker: 
    - [ ] didn't try

**Problem description**:
 I am querying data with group by and want to fetch latest record from each group usinf ROW_NUMBER function over partition on created_date. Table has partition by created_date

**Steps to reproduce**:

select mac_address,created_date,cluster_id,free_disk_bytes,ROW_NUMBER() OVER(partition by created_date order by created_date) 
from app_health ORDER BY 1, 2

**Comment by seut** [comment]
@bhagujava What error do you get when executing the statement?
I've just checked it with the latest/4.0.3 crate docker image and cannot reproduce it, window function including custom frames are supported on CrateDB 4.0, see https://crate.io/docs/crate/reference/en/4.0/general/builtins/window-functions.html.
Maybe your docker image is not updated to the latest latest?  ;)
You can verify the version you are running by simple executing:

```select version['number'] from sys.nodes; ```

**Comment by bhagujava** [comment]
@seut I have just updated latest docker image and got following error.



````
penJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2019-08-27T06:20:35,212][INFO ][o.e.e.NodeEnvironment    ] [raycrate01] using [1] data paths, mounts [[/data (/dev/mapper/raylife1--vg-root)]], net usable_space [41.4gb], net total_space [164.7gb], types [ext4]
[2019-08-27T06:20:35,217][INFO ][o.e.e.NodeEnvironment    ] [raycrate01] heap size [989.8mb], compressed ordinary object pointers [true]
[2019-08-27T06:20:35,441][INFO ][o.e.n.Node               ] [raycrate01] node name [raycrate01], node ID [rJl9t9ShRLOSoWUCTltxJA]
[2019-08-27T06:20:35,445][INFO ][o.e.n.Node               ] [raycrate01] version[4.0.3], pid[1], build[1b7058f/2019-08-06T15:47:53Z], OS[Linux/4.4.0-31-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/12.0.1/12.0.1+12]
[2019-08-27T06:20:35,907][INFO ][i.c.plugin               ] [raycrate01] plugins loaded: [jmx-monitoring, lang-js, enterpriseFunctions] 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2019-08-27T06:20:39,604][INFO ][o.e.p.PluginsService     ] [raycrate01] no modules loaded
[2019-08-27T06:20:39,628][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [crate-azure-discovery]
[2019-08-27T06:20:39,629][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [es-repository-hdfs]
[2019-08-27T06:20:39,629][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [io.crate.plugin.BlobPlugin]
[2019-08-27T06:20:39,629][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [io.crate.plugin.CrateCommonPlugin]
[2019-08-27T06:20:39,629][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [io.crate.plugin.HttpTransportPlugin]
[2019-08-27T06:20:39,629][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [io.crate.plugin.PluginLoaderPlugin]
[2019-08-27T06:20:39,630][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [io.crate.plugin.SrvPlugin]
[2019-08-27T06:20:39,630][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [io.crate.udc.plugin.UDCPlugin]
[2019-08-27T06:20:39,630][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [org.elasticsearch.analysis.common.CommonAnalysisPlugin]
[2019-08-27T06:20:39,630][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin]
[2019-08-27T06:20:39,630][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [org.elasticsearch.plugin.repository.url.URLRepositoryPlugin]
[2019-08-27T06:20:39,630][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [org.elasticsearch.repositories.azure.AzureRepositoryPlugin]
[2019-08-27T06:20:39,631][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [org.elasticsearch.repositories.s3.S3RepositoryPlugin]
[2019-08-27T06:20:39,631][INFO ][o.e.p.PluginsService     ] [raycrate01] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[2019-08-27T06:20:40,780][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [raycrate01] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [discovery.zen.minimum_master_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
    at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:31) ~[crate-app.jar:4.0.3]
    at io.crate.bootstrap.CrateDB.init(CrateDB.java:162) ~[crate-app.jar:4.0.3]
    at io.crate.bootstrap.CrateDB.execute(CrateDB.java:138) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:82) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.0.0.jar:4.0.3]
    at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.0.0.jar:4.0.3]
    at io.crate.bootstrap.CrateDB.main(CrateDB.java:91) ~[crate-app.jar:4.0.3]
    at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) ~[crate-app.jar:4.0.3]
Caused by: java.lang.IllegalArgumentException: unknown setting [discovery.zen.minimum_master_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
    at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:399) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:349) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:320) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:291) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:97) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.node.Node.<init>(Node.java:306) ~[crate-app.jar:4.0.3]
    at io.crate.node.CrateNode.<init>(CrateNode.java:61) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.bootstrap.BootstrapProxy$1.<init>(BootstrapProxy.java:184) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.bootstrap.BootstrapProxy.setup(BootstrapProxy.java:184) ~[crate-app.jar:4.0.3]
    at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:252) ~[crate-app.jar:4.0.3]
    at io.crate.bootstrap.CrateDB.init(CrateDB.java:158) ~[crate-app.jar:4.0.3]
    ... 6 more

````

**Comment by bhagujava** [comment]
I got it  some of  evn variable is deprecated and introduce new one.. I will update it and let you know about this.
