### ISSUE TITLE
Build fail version 4.0.4

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#9133]
**CrateDB version**:
4.0.4

**Environment description**:

 - JVM version: 12.0.2 or 1.8.0_201
 - Kernel: 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Distribution: VERSION="18.04.3 LTS (Bionic Beaver)"

**Problem description**:

Build fail from version 4.0.4
````
> Task :buildSrc:compileJava FAILED
/home/bhargav/bhargav/cratedb-source/crate/buildSrc/src/main/java/io/crate/gradle/TestLogger.java:61: error: cannot find symbol
            for (String output : testOutputs.getOrDefault(test, List.of())) {
                                                                    ^
  symbol:   method of()
  location: interface List
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

````
**Steps to reproduce**:

````
git clone https://github.com/crate/crate
cd crate
git submodule update --init
git checkout 4.0.4
./gradlew clean communityEditionDistTar

````
I tried with both jdk version 8 & 12 respectively

**Comment by bhagujava** [comment]
@kovrus  does openjdk 11 would work here ?

**Comment by kovrus** [comment]
@bhagujava yes, it should.

**Comment by bhagujava** [comment]
@kovrus So from now onward if i have to use community edition with latest release i have to build it from our-self.  am i correct ?

**Comment by bhagujava** [comment]
@kovrus 



i am getting error after build from openjdk12


````
Caused by: org.elasticsearch.transport.RemoteTransportException: [raycrate03][172.28.0.3:4300][internal:cluster/coordination/join/validate]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid qeWuuEksRXa0B1t6nLl7_w than local cluster uuid GXz3Z4tOQqmfpgNwBnOwNA, rejecting
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$3(JoinHelper.java:140) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1314) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2019-09-26T11:59:18,886][INFO ][o.e.c.c.JoinHelper       ] [raycrate03] failed to join {raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200} with JoinRequest{sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, optionalJoin=Optional[Join{term=195, lastAcceptedTerm=193, lastAcceptedVersion=468, sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, targetNode={raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200}}]}
org.elasticsearch.transport.RemoteTransportException: [raycrate02][172.28.0.2:4300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:476) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:306) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1093) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$27(TcpTransport.java:1237) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [raycrate03][172.28.0.3:4300][internal:cluster/coordination/join/validate]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid qeWuuEksRXa0B1t6nLl7_w than local cluster uuid GXz3Z4tOQqmfpgNwBnOwNA, rejecting
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$3(JoinHelper.java:140) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1314) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2019-09-26T11:59:19,885][INFO ][o.e.c.c.JoinHelper       ] [raycrate03] failed to join {raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200} with JoinRequest{sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, optionalJoin=Optional[Join{term=195, lastAcceptedTerm=193, lastAcceptedVersion=468, sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, targetNode={raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200}}]}
org.elasticsearch.transport.RemoteTransportException: [raycrate02][172.28.0.2:4300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:476) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:306) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1093) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$27(TcpTransport.java:1237) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [raycrate03][172.28.0.3:4300][internal:cluster/coordination/join/validate]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid qeWuuEksRXa0B1t6nLl7_w than local cluster uuid GXz3Z4tOQqmfpgNwBnOwNA, rejecting
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$3(JoinHelper.java:140) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1314) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2019-09-26T11:59:20,886][INFO ][o.e.c.c.JoinHelper       ] [raycrate03] failed to join {raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200} with JoinRequest{sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, optionalJoin=Optional[Join{term=195, lastAcceptedTerm=193, lastAcceptedVersion=468, sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, targetNode={raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200}}]}
org.elasticsearch.transport.RemoteTransportException: [raycrate02][172.28.0.2:4300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:476) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:306) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1093) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$27(TcpTransport.java:1237) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [raycrate03][172.28.0.3:4300][internal:cluster/coordination/join/validate]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid qeWuuEksRXa0B1t6nLl7_w than local cluster uuid GXz3Z4tOQqmfpgNwBnOwNA, rejecting
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$3(JoinHelper.java:140) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1314) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2019-09-26T11:59:21,885][INFO ][o.e.c.c.JoinHelper       ] [raycrate03] failed to join {raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200} with JoinRequest{sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, optionalJoin=Optional[Join{term=195, lastAcceptedTerm=193, lastAcceptedVersion=468, sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, targetNode={raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200}}]}
org.elasticsearch.transport.RemoteTransportException: [raycrate02][172.28.0.2:4300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:476) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:306) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1093) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$27(TcpTransport.java:1237) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [raycrate03][172.28.0.3:4300][internal:cluster/coordination/join/validate]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid qeWuuEksRXa0B1t6nLl7_w than local cluster uuid GXz3Z4tOQqmfpgNwBnOwNA, rejecting
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$3(JoinHelper.java:140) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1314) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2019-09-26T11:59:22,888][INFO ][o.e.c.c.JoinHelper       ] [raycrate03] failed to join {raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200} with JoinRequest{sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, optionalJoin=Optional[Join{term=195, lastAcceptedTerm=193, lastAcceptedVersion=468, sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, targetNode={raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200}}]}
org.elasticsearch.transport.RemoteTransportException: [raycrate02][172.28.0.2:4300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:476) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:306) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1093) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$27(TcpTransport.java:1237) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [raycrate03][172.28.0.3:4300][internal:cluster/coordination/join/validate]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid qeWuuEksRXa0B1t6nLl7_w than local cluster uuid GXz3Z4tOQqmfpgNwBnOwNA, rejecting
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$3(JoinHelper.java:140) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1314) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
[2019-09-26T11:59:23,886][INFO ][o.e.c.c.JoinHelper       ] [raycrate03] failed to join {raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200} with JoinRequest{sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, optionalJoin=Optional[Join{term=195, lastAcceptedTerm=193, lastAcceptedVersion=468, sourceNode={raycrate03}{D1Jx5alORWuBRUY0I5-8Rg}{JmcHE9dMRemAaMtN4L794w}{172.28.0.3}{172.28.0.3:4300}{http_address=172.28.0.3:4200}, targetNode={raycrate02}{bM_lVhPcTFWQBprP4bvdiA}{WAOngDvAQG2SLTxbjRCdHA}{172.28.0.2}{172.28.0.2:4300}{http_address=172.28.0.2:4200}}]}
org.elasticsearch.transport.RemoteTransportException: [raycrate02][172.28.0.2:4300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:476) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:306) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1093) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$27(TcpTransport.java:1237) ~[crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [raycrate03][172.28.0.3:4300][internal:cluster/coordination/join/validate]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid qeWuuEksRXa0B1t6nLl7_w than local cluster uuid GXz3Z4tOQqmfpgNwBnOwNA, rejecting
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$3(JoinHelper.java:140) ~[crate-app.jar:4.0.4-2bf405fdba]



````

**Comment by bhagujava** [comment]
build from openjdk12 working
