### ISSUE TITLE
Alter column datatypes

### ISSUE THREAD

**Issue by bhagujava** [crate/crate#9185]
**Use case**:
Alter column datatypes in order to migrate 4.0.x
**Feature description**:

**Comment by seut** [comment]
Can you please add more information why this is needed?

**Comment by bhagujava** [comment]
We are on 3.x and want to shift  on 4.x.

4.x has breaking changes related to datatypes and  we have 5.8 Million  record.

**Comment by seut** [comment]
The old data type names are registered as aliases for backward comparability.

**Comment by bhagujava** [comment]
Right . but how about the future release ?

**Comment by seut** [comment]
We'll probably migrate them on upgrade but yes its a valid point.

**Comment by mfussenegger** [comment]
To clarify here: 

The data types that we accept via CREATE TABLE or ALTER TABLE have been extended in 4.0 to match the SQL Standard types where appropriate. We've added type aliases for all our old type names so that CREATE TABLE and ALTER TABLE statements keep being compatible.

What changed in an incompatible way is that `information_schema` tables use the new type names. So any applications or clients using the type names have to be extended/updates.

But you don't need to do any migration on existing tables. 
You might eventually have to update CREATE TABLE or ALTER TABLE statements to use the new types in case we'd remove the aliases but there are currently no plans to do so.

**Comment by bhagujava** [comment]
Okay.

Need to update  [this](https://crate.io/docs/clients/jdbc/en/2.1/#types) documentation

**Comment by bhagujava** [comment]
@seut 

Is it expected behaviour while updating  version form 3.x to 4.x ?

````

org.elasticsearch.transport.RemoteTransportException: [raycrate01][10.0.1.200:4300][indices:admin/seq_no/global_checkpoint_sync[p]]
Caused by: org.elasticsearch.action.UnavailableShardsException: [raystatistic..partitioned.ray_user_session_history.04732d9m70q32e9i60o30c1g][2] Not enough active copies to meet shard count of [ALL] (have 1, needed 2). Timeout: [1m], request: [GlobalCheckpointSyncAction.Request{shardId=[raystatistic..partitioned.ray_user_session_history.04732d9m70q32e9i60o30c1g][2], timeout=1m, index='raystatistic..partitioned.ray_user_session_history.04732d9m70q32e9i60o30c1g', waitForActiveShards=ALL}]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:99) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:347) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:287) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:948) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:945) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:271) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2230) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:957) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:308) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:283) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:275) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:674) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[2019-10-01T11:50:13,068][INFO ][o.e.i.s.GlobalCheckpointSyncAction] [raycrate01] [raystatistic..partitioned.ray_user_session_history.04732d9m6os3cd1g60o30c1g][2] global checkpoint sync failed
org.elasticsearch.transport.RemoteTransportException: [raycrate01][10.0.1.200:4300][indices:admin/seq_no/global_checkpoint_sync[p]]
Caused by: org.elasticsearch.action.UnavailableShardsException: [raystatistic..partitioned.ray_user_session_history.04732d9m6os3cd1g60o30c1g][2] Not enough active copies to meet shard count of [ALL] (have 1, needed 2). Timeout: [1m], request: [GlobalCheckpointSyncAction.Request{shardId=[raystatistic..partitioned.ray_user_session_history.04732d9m6os3cd1g60o30c1g][2], timeout=1m, index='raystatistic..partitioned.ray_user_session_history.04732d9m6os3cd1g60o30c1g', waitForActiveShards=ALL}]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:99) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:347) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:287) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:948) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:945) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:271) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2230) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:957) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:308) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:283) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:275) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:674) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:694) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [crate-app.jar:4.0.4-2bf405fdba]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[2019-10-01T11:50:13,104][INFO ][o.e.i.s.GlobalCheckpointSyncAction] [raycrate01] [raystatistic..partitioned.ray_speed_test.04732d9m6kp34chk60o30c1g][3] global checkpoint sync failed
org.elasticsearch.transport.RemoteTransportException: [raycrate01][10.0.1.200:4300][indices:admin/seq_no/global_checkpoint_sync[p]]
Caused by: org.elasticsearch.action.UnavailableShardsException: [raystatistic..partitioned.ray_speed_test.04732d9m6kp34chk60o30c1g][3] Not enough active copies to meet shard count of [ALL] (have 1, needed 2). Timeout: [1m], request: [GlobalCheckpointSyncAction.Request{shardId=[raystatistic..partitioned.ray_speed_test.04732d9m6kp34chk60o30c1g][3], timeout=1m, index='raystatistic..partitioned.ray_speed_test.04732d9m6kp34chk60o30c1g', waitForActiveShards=ALL}]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:99) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:347) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:287) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:948) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:945) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:271) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2230) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:957) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:308) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [crate-app.jar:4.0.4-2bf405fdba]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransport


````

**Comment by seut** [comment]
@bhagujava Yes, this is not 4.0.x related but should already behave similar on 3.3. We've already changed the default value for `write.wait_for_active_shards` back to `1` on MASTER/4.1 to avoid such errors if replicas are not yet available.
You can change this setting manually to fix that issues by `ALTER TABLE table_name SET ("write.wait_for_active_shards" = 1)` on each table.
