### ISSUE TITLE
Cant insert geo_shape using jdbc

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate#9561]
**CrateDB version**: 4.0.11

**Problem description**:
I trying to insert geo_shape object using JDBC connection.
I am trying to insert a row as shown in this [test](https://github.com/crate/crate/blob/master/sql/src/test/java/io/crate/integrationtests/GeoShapeIntegrationTest.java), but receive error:
```
org.postgresql.util.PSQLException: ERROR: SQLParseException: Cannot cast r to type integer
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.TypeInfoCache.getPGType(TypeInfoCache.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.setMap(PgPreparedStatement.java:463)
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:948)
```

I found that `TypeInfoCache.getPGType` method called with `hstore` parameter and executes SQL:
```
SELECT pg_type.oid, typname 
FROM pg_catalog.pg_type 
LEFT 
    JOIN (select ns.oid as nspoid, ns.nspname, r.r 
          from pg_namespace as ns 
          join ( select s.r, (current_schemas(false))[s.r] as nspname 
                   from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r 
         using ( nspname ) 
       ) as sp 
    ON sp.nspoid = typnamespace 
 WHERE typname = 'hstore'
 ORDER BY sp.r, pg_type.oid DESC LIMIT 1;
```
which raised error: *ERROR: SQLParseException: Cannot cast r to type integer*

Also, I trying to some different ways (pass object as json, pass coordinates as array, ....), but all of them was unsuccessful with other errors.

**Steps to reproduce**:

1. create test table:
`CREATE TABLE test (a GEO_SHAPE)`
`>> Table TEST created.`

2. execute JAVA code:
```
var prop = new Properties();
prop.put("user", "crate");
try (var conn = DriverManager.getConnection("jdbc:postgresql://YOUR_HOST_NAME:YOUR_PORT/", prop)) {
	try (var call = conn.prepareCall("INSERT INTO test (a) VALUES (?)")) {
		call.setObject(1, Map.of("type", "Polygon", "coordinates", new double[][] { { 1, 1 }, { 1, 2 }, { 2, 2 }, { 2, 1 } }));
		call.execute();
	}
}
```

**Comment by mfussenegger** [comment]
Could you try with the [CrateDB specific JDBC client](https://crate.io/docs/clients/jdbc/en/latest/getting-started.html#set-up-as-a-dependency) ?

The connection string changes to `jdbc:crate://...`. 

We're currently also working on improving the support for the PostgreSQL JDBC driver, but that will be a while longer until everything works fine. See https://github.com/crate/crate-qa/pull/128 and https://github.com/crate/crate/milestone/1 to track the progress

**Comment by shm-dmitry** [comment]
@mfussenegger 
Yes, I tried official crate-jdbc.
And latest repo version 2.6.0
And latest github version 2.6.1 (builded from sources).

```
public class Main {
	public static void main(String[] args) throws SQLException {
		var prop = new Properties();
		prop.put("user", "crate");
		try (var conn = DriverManager.getConnection("jdbc:crate://xxxxx:5432/", prop)) {
			try (var call = conn.prepareCall("INSERT INTO test (a) VALUES (?)")) {
				call.setObject(1, Map.of("type", "Polygon", "coordinates", new double[][] { { 1, 1 }, { 1, 2 }, { 2, 2 }, { 2, 1 } }));
				call.execute();
			}
		}
	}
}
```

```
Exception in thread "main" java.sql.SQLFeatureNotSupportedException: Connection: prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) not supported
	at io.crate.shade.org.postgresql.jdbc.PgConnection.prepareCall(PgConnection.java:1701)
	at io.crate.shade.org.postgresql.jdbc.PgConnection.prepareCall(PgConnection.java:391)
	at test.Main.main(Main.java:12)
```

I can create issue in crate-jdbc project if need.

**Comment by mfussenegger** [comment]
Could you use `prepareStatement` instead of `prepareCall`?

Here is an example from our test suite in which we insert a shape value:

```
        try (Connection conn = DriverManager.getConnection(getConnectionString())) {
            PreparedStatement preparedStatement =
                conn.prepareStatement("insert into test (id, string_field, boolean_field, byte_field, " +
                                      "short_field, integer_field, long_field, float_field, double_field, object_field, " +
                                      "timestamp_field, ip_field, geo_point_field, geo_shape_field) values " +
                                      "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            preparedStatement.setInt(1, 1);
            preparedStatement.setString(2, "Youri");
            preparedStatement.setBoolean(3, true);
            preparedStatement.setByte(4, (byte) 120);
            preparedStatement.setShort(5, (short) 1000);
            preparedStatement.setInt(6, 1200000);
            preparedStatement.setLong(7, 120000000000L);
            preparedStatement.setFloat(8, 1.4f);
            preparedStatement.setDouble(9, 3.456789);
            preparedStatement.setObject(10, objectField);
            preparedStatement.setTimestamp(11, new Timestamp(1000L));
            preparedStatement.setString(12, "127.0.0.1");
            preparedStatement.setArray(13, conn.createArrayOf("double", new Double[]{9.7419021d, 47.4048045d}));
            preparedStatement.setString(14, "POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))");
            preparedStatement.execute();
            conn.createStatement().execute("refresh table test");
        }
```

and the select part:

```
        ResultSet resultSet = CONNECTION.createStatement().executeQuery("select geo_shape_field from test");
        assertThat(resultSet, instanceOf(PgResultSet.class));
        assertThat(resultSet.next(), is(true));
        assertThat((Map) resultSet.getObject("geo_shape_field"), Is.<Map>is(new HashMap<String, Object>(){{
            put("coordinates", Collections.singletonList(
                    Arrays.asList(
                            Arrays.asList(30.0, 10.0),
                            Arrays.asList(40.0, 40.0),
                            Arrays.asList(20.0, 40.0),
                            Arrays.asList(10.0, 20.0),
                            Arrays.asList(30.0, 10.0)
                    )
            ));
            put("type", "Polygon");
        }
        }));
        assertThat(resultSet.getObject("geo_shape_field", PGobject.class).getValue(),
                Matchers.allOf(
                        Matchers.containsString("\"type\":\"Polygon\""),
                        Matchers.containsString("\"coordinates\":[[[30.0,10.0],[40.0,40.0],[20.0,40.0],[10.0,20.0],[30.0,10.0]]]")
                )
        );
```

**Comment by shm-dmitry** [comment]
@mfussenegger 
Yes, `prepareStatement` works fine:

```
public class Main {
	public static void main(String[] args) throws SQLException {
		var prop = new Properties();
		prop.put("user", "crate");
		try (var conn = DriverManager.getConnection("jdbc:crate://crate00:5432/", prop)) {
			try (var call = conn.prepareStatement("INSERT INTO test (a) VALUES (?)")) {
				call.setObject(1, Map.of("type", "Polygon", "coordinates",
						new double[][][] { { { 1, 1 }, { 1, 2 }, { 2, 2 }, { 2, 1 }, { 1, 1 } } }));
				call.execute();
			}
		}
	}
}
```

**Comment by mfussenegger** [comment]
Ok, good to hear that it works.

To make this particular usage work with the PostgreSQL JDBC client we'll at least need https://github.com/crate/crate/issues/9551, maybe more.

**Comment by mfussenegger** [comment]
With CrateDB 4.2 this will also work with the PostgreSQL JDBC client, but it will be necessary to use a JSON string to set the geo_shape instead of `setObject` with a Map.
