### ISSUE TITLE
ArithmeticException

### ISSUE THREAD

**Issue by bputt-e** [crate/crate#9656]
**CrateDB version**: 4.1.1 community edition

**Environment description**:
Centos 7.latest
Openjdk 11

**Problem description**:
I issue a simple query: ```select * from TABLE limit 100;```

I get the following error: ```SQLActionException[ArithmeticException: / by zero]```

**Steps to reproduce**:

I create a partitioned table and the error above occurs no matter if there's data in it or not

**Comment by mfussenegger** [comment]
Could you post the schema of the table?

**Comment by bputt-e** [comment]
Sure, here's our simplified schema (we have ~170 tags)

```
CREATE TABLE thedatas (
    startdate TIMESTAMP,
    startdatehour TIMESTAMP,
    enddate TIMESTAMP,
    createdat TIMESTAMP,
    sysid STRING,
    tags OBJECT(STRICT) AS (
        somestr1 STRING,
        somestr2 STRING,
        somestr3 STRING,
        somelong1 LONG,
        somelong2 LONG,
        sometimestamp1 TIMESTAMP,
        sometimestamp2 TIMESTAMP,
        somearray1 ARRAY(STRING),
        somearray2 ARRAY(STRING),
        somebool1 BOOLEAN,
        somebool2 BOOLEAN
    ),
    user OBJECT(STRICT) AS (
        somestr1 STRING,
        somestr2 STRING,
        somestr3 STRING,
        somestr4 STRING,
        somestr5 STRING,
        somestr6 STRING,
        somestr7 STRING,
        somestr8 STRING,
        somelong1 LONG,
        somelong2 LONG,
        somearray1 ARRAY(STRING),
        somearray2 ARRAY(STRING),
    ),
    uniqueid TEXT,
    partitionkey TIMESTAMP,
    PRIMARY KEY ("uniqueid", "sysid", "partitionkey")
) CLUSTERED INTO 3 SHARDS PARTITIONED BY (partitionkey)
WITH (
    number_of_replicas = 1,
    refresh_interval = 30000,
    column_policy = 'strict'
)
```

**Comment by MattCosturos** [comment]
Having the same issue on a brand new setup. Using the latest docker image pulled today.

`create table devicetypes (
id int primary key,
name text
);

insert into devicetypes (id, name) values(1,'type1');
insert into devicetypes (id, name) values(2,'type2');

select * from devicetypes;
SQLActionException[ArithmeticException: / by zero]
`

**Comment by MattCosturos** [comment]
Top of the stack trace from crate webadmin.
Looks like a stat calculation is failing / generating the /0 error
```
SQLActionException: 500 Internal Server Error 5000 ArithmeticException: / by zero
	at io.crate.statistics.Stats.averageSizePerRowInBytes(Stats.java:92)
	at io.crate.planner.operators.Collect.<init>(Collect.java:131)
	at io.crate.planner.operators.Collect.lambda$create$0(Collect.java:113)
	at io.crate.planner.operators.Limit.lambda$create$0(Limit.java:61)
	at io.crate.planner.operators.FetchOrEval.lambda$create$0(FetchOrEval.java:133)
	at io.crate.planner.operators.LogicalPlanner.normalizeAndPlan(LogicalPlanner.java:216)
	at io.crate.planner.operators.LogicalPlanner$Visitor.visitSelectStatement(LogicalPlanner.java:452)
	at io.crate.planner.operators.LogicalPlanner$Visitor.visitSelectStatement(LogicalPlanner.java:441)
	at io.crate.analyze.relations.AnalyzedRelation.accept(AnalyzedRelation.java:117)
	at io.crate.analyze.AnalyzedStatementVisitor.process(AnalyzedStatementVisitor.java:31)
	at io.crate.planner.operators.LogicalPlanner.plan(LogicalPlanner.java:150)
	at io.crate.planner.Planner.visitSelectStatement(Planner.java:260)
	at io.crate.planner.Planner.visitSelectStatement(Planner.java:144)
	at io.crate.analyze.relations.AnalyzedRelation.accept(AnalyzedRelation.java:117)
	at io.crate.analyze.AnalyzedStatementVisitor.process(AnalyzedStatementVisitor.java:31)
	at io.crate.planner.Planner.plan(Planner.java:234)
	at io.crate.action.sql.Session.singleExec(Session.java:566)
	at io.crate.action.sql.Session.exec(Session.java:465)
	at io.crate.action.sql.Session.sync(Session.java:444)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:272)
```

**Comment by MattCosturos** [comment]
I can confirm this bug does not exist in 4.0.10

**Comment by bputt-e** [comment]
@mfussenegger in your PR you mention: ```when querying an empty table, or a non-empty table with outdated table statistics.```

Do the table stats become updated ever? We've left our db running overnight, it has plenty of records and we still get the same error.

**Comment by mfussenegger** [comment]
> Do the table stats become updated ever? We've left our db running overnight, it has plenty of records and we still get the same error.

They should get updated automatcially. Otherwise you can trigger an update by running `ANALYZE` and then verify that the stats got updated by querying the `pg_stats` table.

**Comment by bputt-e** [comment]
We have ```stats.enabled: false``` in our crate.yml which may explain why the stats didn't get updated

**Comment by bputt-e** [comment]
@mfussenegger I ran the following query and got the following response, not sure if your fix resolves it or not, just mentioning it

```EXPLAIN ANALYZE SELECT * FROM mytable LIMIT 1;```

```SQLActionException[Error in ArithmeticException]```

Trace details in console are sparse as this is all I receive:

```
SQLActionException: 500 Internal Server Error 5000 Error in ArithmeticException
```

**Comment by mfussenegger** [comment]
Oh sorry I should have been more verbose. I was referring to [ANALYZE](https://crate.io/docs/crate/reference/en/latest/sql/statements/analyze.html?highlight=analyze) not `EXPLAIN ANYLZE`.

It really is just

```
ANALYZE;
```

**Comment by bputt-e** [comment]
Thanks! I ran the command and can now query datas
