### ISSUE TITLE
cannot rejoin: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported

### ISSUE THREAD

**Issue by masterkain** [crate/crate#9710]
I deploy cratedb via helm on a kubernetes 1.16 cluster.

Today I guess the autoscaler moved the crate-0 pod to another node (keeping the volume, efs) but when it restarted it throws:

```
[2020-02-27T19:28:09,636[INFO [o.e.e.NodeEnvironment     [crate-0 using [1 data paths, mounts [[/data (fs-8cb83347.efs.eu-west-1.amazonaws.com:/data-crate-0-pvc-d1c8d1cb-437e-11ea-99a3-06583a2d74d6)]], net usable_space [8191.9pb, net total_space [8191.9pb, types [nfs4
[2020-02-27T19:28:09,642[INFO [o.e.e.NodeEnvironment     [crate-0 heap size [1gb, compressed ordinary object pointers [true
[2020-02-27T19:28:10,457[INFO [o.e.n.Node                [crate-0 node name [crate-0, node ID [LZqfmXrzRZ6lP7Bf5-bWzw
[2020-02-27T19:28:10,457[INFO [o.e.n.Node                [crate-0 version[4.1.2, pid[1, build[ceb2149/2020-02-14T14:55:30Z], OS[Linux/4.14.146-119.123.amzn2.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]
[2020-02-27T19:28:11,182[INFO [i.c.plugin                [crate-0 plugins loaded: [enterpriseFunctions, jmx-monitoring, lang-js 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2020-02-27T19:28:14,386[INFO [o.e.p.PluginsService      [crate-0 no modules loaded
[2020-02-27T19:28:14,387[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [crate-azure-discovery
[2020-02-27T19:28:14,388[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [es-repository-hdfs
[2020-02-27T19:28:14,388[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [io.crate.plugin.BlobPlugin
[2020-02-27T19:28:14,388[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [io.crate.plugin.CrateCommonPlugin
[2020-02-27T19:28:14,388[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [io.crate.plugin.HttpTransportPlugin
[2020-02-27T19:28:14,388[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [io.crate.plugin.PluginLoaderPlugin
[2020-02-27T19:28:14,388[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [io.crate.plugin.SrvPlugin
[2020-02-27T19:28:14,388[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [io.crate.udc.plugin.UDCPlugin
[2020-02-27T19:28:14,389[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [org.elasticsearch.analysis.common.CommonAnalysisPlugin
[2020-02-27T19:28:14,389[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin
[2020-02-27T19:28:14,389[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [org.elasticsearch.plugin.analysis.AnalysisPhoneticPlugin
[2020-02-27T19:28:14,389[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [org.elasticsearch.plugin.repository.url.URLRepositoryPlugin
[2020-02-27T19:28:14,389[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [org.elasticsearch.repositories.azure.AzureRepositoryPlugin
[2020-02-27T19:28:14,389[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [org.elasticsearch.repositories.s3.S3RepositoryPlugin
[2020-02-27T19:28:14,390[INFO [o.e.p.PluginsService      [crate-0 loaded plugin [org.elasticsearch.transport.Netty4Plugin
[2020-02-27T19:28:16,780[INFO [o.e.d.DiscoveryModule     [crate-0 using discovery type [zen and seed hosts providers [settings, srv
[2020-02-27T19:28:18,889[INFO [psql                      [crate-0 PSQL SSL support is disabled.
[2020-02-27T19:28:19,300[INFO [i.c.p.PipelineRegistry    [crate-0 HTTP SSL support is disabled.
[2020-02-27T19:28:19,487[INFO [o.e.n.Node                [crate-0 initialized
[2020-02-27T19:28:19,487[INFO [o.e.n.Node                [crate-0 starting ...
[2020-02-27T19:28:19,519[INFO [psql                      [crate-0 publish_address {192.168.164.18:5432}, bound_addresses {0.0.0.0:5432}
[2020-02-27T19:28:19,591[INFO [i.c.p.h.CrateNettyHttpServerTransport [crate-0 publish_address {192.168.164.18:4200}, bound_addresses {0.0.0.0:4200}
[2020-02-27T19:28:19,600[INFO [o.e.t.TransportService    [crate-0 publish_address {192.168.164.18:4300}, bound_addresses {0.0.0.0:4300}
[2020-02-27T19:28:19,607[INFO [o.e.b.BootstrapChecks     [crate-0 bound or publishing to a non-loopback address, enforcing bootstrap checks
[2020-02-27T19:28:19,823[INFO [i.c.d.SrvUnicastHostsProvider [crate-0 Using dynamic nodes [192.168.135.41:4300, 192.168.137.43:4300, 192.168.164.18:4300
[2020-02-27T19:28:20,405[INFO [o.e.c.c.JoinHelper        [crate-0 failed to join {crate-1}{mcVIe8jBRpCW8H7d6zq_3w}{8TC9UMdWQYeh6TgIm9Zr5g}{192.168.137.43}{192.168.137.43:4300}{http_address=192.168.137.43:4200} with JoinRequest{sourceNode={crate-0}{LZqfmXrzRZ6lP7Bf5-bWzw}{Mdscx2b3TeSjsPNchxUiDw}{192.168.164.18}{192.168.164.18:4300}{http_address=192.168.164.18:4200}, optionalJoin=Optional.empty}
org.elasticsearch.transport.RemoteTransportException: [crate-1[192.168.137.43:4300[internal:cluster/coordination/join]
Caused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -137908715520b
    at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:44) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:39) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDecider.canAllocate(DiskThresholdDecider.java:146) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.decider.AllocationDeciders.canAllocate(AllocationDeciders.java:75) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.tryRelocateShard(BalancedShardsAllocator.java:957) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.balanceByWeights(BalancedShardsAllocator.java:497) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.balance(BalancedShardsAllocator.java:305) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator.allocate(BalancedShardsAllocator.java:124) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:403) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:368) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:351) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.coordination.JoinTaskExecutor.execute(JoinTaskExecutor.java:149) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.coordination.JoinHelper$1.execute(JoinHelper.java:116) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:309) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:209) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:141) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[crate-app.jar:4.1.2
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
    at java.lang.Thread.run(Thread.java:835) [?:?]
[2020-02-27T19:28:20,688[INFO [i.c.d.SrvUnicastHostsProvider [crate-0 Using dynamic nodes [192.168.135.41:4300, 192.168.137.43:4300, 192.168.164.18:4300
[2020-02-27T19:28:20,701[INFO [o.e.c.c.JoinHelper        [crate-0 failed to join {crate-1}{mcVIe8jBRpCW8H7d6zq_3w}{8TC9UMdWQYeh6TgIm9Zr5g}{192.168.137.43}{192.168.137.43:4300}{http_address=192.168.137.43:4200} with JoinRequest{sourceNode={crate-0}{LZqfmXrzRZ6lP7Bf5-bWzw}{Mdscx2b3TeSjsPNchxUiDw}{192.168.164.18}{192.168.164.18:4300}{http_address=192.168.164.18:4200}, optionalJoin=Optional.empty}
org.elasticsearch.transport.RemoteTransportException: [crate-1[192.168.137.43:4300[internal:cluster/coordination/join]
Caused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -137908715520b
    at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:44) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:39) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDecider.canAllocate(DiskThresholdDecider.java:146) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.decider.AllocationDeciders.canAllocate(AllocationDeciders.java:75) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.tryRelocateShard(BalancedShardsAllocator.java:957) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.balanceByWeights(BalancedShardsAllocator.java:497) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.balance(BalancedShardsAllocator.java:305) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator.allocate(BalancedShardsAllocator.java:124) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:403) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:368) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:351) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.coordination.JoinTaskExecutor.execute(JoinTaskExecutor.java:149) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.coordination.JoinHelper$1.execute(JoinHelper.java:116) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:309) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:209) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:141) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[crate-app.jar:4.1.2
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
    at java.lang.Thread.run(Thread.java:835) [?:?]
[2020-02-27T19:28:21,684[INFO [i.c.d.SrvUnicastHostsProvider [crate-0 Using dynamic nodes [192.168.135.41:4300, 192.168.137.43:4300, 192.168.164.18:4300
[2020-02-27T19:28:21,694[INFO [o.e.c.c.JoinHelper        [crate-0 failed to join {crate-1}{mcVIe8jBRpCW8H7d6zq_3w}{8TC9UMdWQYeh6TgIm9Zr5g}{192.168.137.43}{192.168.137.43:4300}{http_address=192.168.137.43:4200} with JoinRequest{sourceNode={crate-0}{LZqfmXrzRZ6lP7Bf5-bWzw}{Mdscx2b3TeSjsPNchxUiDw}{192.168.164.18}{192.168.164.18:4300}{http_address=192.168.164.18:4200}, optionalJoin=Optional.empty}
org.elasticsearch.transport.RemoteTransportException: [crate-1[192.168.137.43:4300[internal:cluster/coordination/join]
Caused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -137908715520b
    at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:44) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:39) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDecider.canAllocate(DiskThresholdDecider.java:146) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.decider.AllocationDeciders.canAllocate(AllocationDeciders.java:75) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.tryRelocateShard(BalancedShardsAllocator.java:957) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.balanceByWeights(BalancedShardsAllocator.java:497) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.balance(BalancedShardsAllocator.java:305) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator.allocate(BalancedShardsAllocator.java:124) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:403) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:368) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:351) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.coordination.JoinTaskExecutor.execute(JoinTaskExecutor.java:149) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.coordination.JoinHelper$1.execute(JoinHelper.java:116) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:309) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:209) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:141) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[crate-app.jar:4.1.2
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[crate-app.jar:4.1.2
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[crate-app.jar:4.1.2
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
    at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by mfussenegger** [comment]
Thank you for the report. 

This seems related to https://github.com/elastic/elasticsearch/issues/48380 - we're going to port over the bugfixes.

**Comment by mfussenegger** [comment]
As a workaround you could try to temporarily disable the disk allocation decider (`SET GLOBAL cluster.routing.allocation.disk.threshold_enabled = false`)

**Comment by masterkain** [comment]
thanks @mfussenegger for the workaround, the node is now online, is this happening because EFS?
