### ISSUE TITLE
UNION ALL query not working when using two nested aggregate functions

### ISSUE THREAD

**Issue by robd003** [crate/crate#9743]
**CrateDB version**: 4.1.2

**Environment description**:
 - Docker: 19.03.5, build 633a0ea
 - Problem can be reproduced without docker: 
    - [X] yes
    - [ ] no

**Problem description**:

When trying to use UNION ALL you can't use more than 1 aggregate function in the sub-query. If you do you'll get an error: Function max(real) is not a scalar function.

**Steps to reproduce**:

Explain query: {"UnionExecutionPlan": {"left": {"UnionExecutionPlan": {"left": {"Collect": {"collectPhase": {"COLLECT": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["fey9AzRnSwi9aG6BGcRUDw"], "id": 0, "projections": [{"aggregations": "Aggregation{sum, args=[IC{0, bigint}], filter=true}, Aggregation{sum, args=[IC{1, bigint}], filter=true}", "keys": "IC{2, integer}", "type": "HashAggregation"}, {"aggregations": "Aggregation{sum, args=[IC{1, bigint}], filter=true}, Aggregation{sum, args=[IC{2, bigint}], filter=true}", "keys": "IC{0, integer}", "type": "HashAggregation"}, {"outputs": "IC{0, integer}, to_integer(coalesce(IC{1, bigint}, 0), null), to_integer(coalesce(IC{2, bigint}, 0), null), null, null", "type": "Eval"}], "routing": {"fey9AzRnSwi9aG6BGcRUDw": {"voxsnap.events_2019": [0, 1, 2, 3]}}, "toCollect": "if(op_isnull(Ref{voxsnap.events_2019.library_type, text}), 1, 0), if(op_not(op_isnull(Ref{voxsnap.events_2019.library_type, text})), 1, 0), Ref{voxsnap.events_2019.narration, integer}", "type": "executionPhase", "where": "Ref{voxsnap.events_2019.event_type, text} = play AND Ref{voxsnap.events_2019.customer, text} = handerpants AND Ref{voxsnap.events_2019.event_time, timestamp with time zone} >= 1577836800000 AND Ref{voxsnap.events_2019.event_time, timestamp with time zone} <= 1580428800000"}}, "type": "executionPlan"}}, "mergePhase": {"MERGE": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["fey9AzRnSwi9aG6BGcRUDw"], "id": 2, "type": "executionPhase"}}, "right": {"Collect": {"collectPhase": {"COLLECT": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["fey9AzRnSwi9aG6BGcRUDw"], "id": 1, "projections": [{"aggregations": "Aggregation{count, args=[], filter=true}", "keys": "IC{0, integer}", "type": "HashAggregation"}, {"aggregations": "Aggregation{count, args=[IC{1, bigint}], filter=true}", "keys": "IC{0, integer}", "type": "HashAggregation"}, {"outputs": "IC{0, integer}, null, null, to_integer(coalesce(IC{1, bigint}, 0), null), null", "type": "Eval"}], "routing": {"fey9AzRnSwi9aG6BGcRUDw": {"voxsnap.events_redirector_2019": [0, 1, 2, 3]}}, "toCollect": "Ref{voxsnap.events_redirector_2019.narration, integer}", "type": "executionPhase", "where": "Ref{voxsnap.events_redirector_2019.platform, text} = podcast AND Ref{voxsnap.events_redirector_2019.customer, text} = handerpants AND Ref{voxsnap.events_redirector_2019.event_time, timestamp with time zone} >= 1577836800000 AND Ref{voxsnap.events_redirector_2019.event_time, timestamp with time zone} <= 1580428800000"}}, "type": "executionPlan"}}, "type": "executionPlan"}}, "mergePhase": {"MERGE": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["fey9AzRnSwi9aG6BGcRUDw"], "id": 4, "projections": [{"aggregations": "Aggregation{max, args=[IC{1, integer}], filter=true}, Aggregation{max, args=[IC{2, integer}], filter=true}, Aggregation{max, args=[IC{3, integer}], filter=true}, Aggregation{max, args=[IC{4, bigint}], filter=true}", "keys": "IC{0, integer}", "type": "HashAggregation"}, {"outputs": "IC{0, integer}, coalesce(IC{1, integer}, 0), coalesce(IC{2, integer}, 0), coalesce(IC{3, integer}, 0), coalesce(IC{4, bigint}, 0)", "type": "Eval"}], "type": "executionPhase"}}, "right": {"Collect": {"collectPhase": {"COLLECT": {"distribution": {"distributedByColumn": 0, "type": "BROADCAST"}, "executionNodes": ["fey9AzRnSwi9aG6BGcRUDw"], "id": 3, "projections": [{"aggregations": "Aggregation{sum, args=[IC{0, real}], filter=true}, Aggregation{max, args=[IC{1, real}], filter=true}", "keys": "IC{2, integer}, IC{3, text}", "type": "HashAggregation"}, {"aggregations": "Aggregation{sum, args=[IC{2, real}], filter=true}, Aggregation{max, args=[IC{3, real}], filter=true}", "keys": "IC{0, integer}, IC{1, text}", "type": "HashAggregation"}, {"outputs": "IC{0, integer}, null, null, null, to_bigint(IC{2, real}, null)", "type": "Eval"}], "routing": {"fey9AzRnSwi9aG6BGcRUDw": {"voxsnap.events_timeupdate_2019": [0, 1, 2, 3]}}, "toCollect": "max(Ref{voxsnap.events_timeupdate_2019.audio_time, real}), Ref{voxsnap.events_timeupdate_2019.audio_time, real}, Ref{voxsnap.events_timeupdate_2019.narration, integer}, Ref{voxsnap.events_timeupdate_2019.session_id, text}", "type": "executionPhase", "where": "Ref{voxsnap.events_timeupdate_2019.customer, text} = handerpants AND Ref{voxsnap.events_timeupdate_2019.event_time, timestamp with time zone} >= 1577836800000 AND Ref{voxsnap.events_timeupdate_2019.event_time, timestamp with time zone} <= 1580428800000"}}, "type": "executionPlan"}}, "type": "executionPlan"}}

SQL run: select narration, 
    COALESCE(max(embedded_plays), 0) as embedded_plays, 
    COALESCE(max(library_plays), 0) as library_plays, 
    COALESCE(max(podcast_plays), 0) as podcast_plays, 
    COALESCE(max(listen_time), 0) as listen_time
    from (select narration, 
          COALESCE(sum(case when library_type is null then 1 else 0 end), 0)::integer as embedded_plays,
          COALESCE(sum(case when library_type is not null then 1 else 0 end), 0)::integer as library_plays,
          NULL::integer as podcast_plays,
          NULL::bigint as listen_time
          from voxsnap.events_2019 
          where event_type = 'play'  
          and customer = 'handerpants'
          and event_time >= '2020-01-01' and event_time <= '2020-01-31'
          group by narration
        union all
          select narration,
          NULL::integer as embedded_plays,
          NULL::integer as library_plays,
          COALESCE(count(*), 0)::integer as podcast_plays,
          NULL::bigint as listen_time
          from voxsnap.events_redirector_2019 
          where platform = 'podcast' 
          and customer = 'handerpants'
          and event_time >= '2020-01-01' and event_time <= '2020-01-31'
          group by narration
        union all
          select narration,
          NULL::integer as embedded_plays,
          NULL::integer as library_plays,
          NULL::integer as podcast_plays,
          SUM(MAX(audio_time))::bigint as listen_time
          from voxsnap.events_timeupdate_2019 
          where customer = 'handerpants'
          and event_time >= '2020-01-01' and event_time <= '2020-01-31'
          GROUP BY narration, session_id) as big_query
    group by narration;
SQLActionException[UnhandledServerException: io.crate.exceptions.UnsupportedFeatureException: Function max(real) is not a scalar function.]

SQLActionException: 500 Internal Server Error 5000 UnhandledServerException: io.crate.exceptions.UnsupportedFeatureException: Function max(real) is not a scalar function.
	at io.crate.expression.BaseImplementationSymbolVisitor.visitFunction(BaseImplementationSymbolVisitor.java:68)
	at io.crate.expression.BaseImplementationSymbolVisitor.visitFunction(BaseImplementationSymbolVisitor.java:43)
	at io.crate.expression.symbol.Function.accept(Function.java:141)
	at io.crate.expression.InputFactory$Context.add(InputFactory.java:159)
	at io.crate.expression.InputFactory$Context.add(InputFactory.java:144)
	at io.crate.execution.engine.collect.DocInputFactory.extractImplementations(DocInputFactory.java:74)
	at io.crate.execution.engine.collect.LuceneShardCollectorProvider.getUnorderedIterator(LuceneShardCollectorProvider.java:144)
	at io.crate.execution.engine.collect.ShardCollectorProvider.getIterator(ShardCollectorProvider.java:113)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterators(ShardCollectSource.java:428)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterator(ShardCollectSource.java:298)
	at io.crate.execution.engine.collect.MapSideDataCollectOperation.createIterator(MapSideDataCollectOperation.java:57)
	at io.crate.execution.engine.collect.CollectTask.innerPrepare(CollectTask.java:164)
	at io.crate.execution.jobs.AbstractTask.prepare(AbstractTask.java:64)
	at io.crate.execution.jobs.RootTask.<init>(RootTask.java:162)
	at io.crate.execution.jobs.RootTask$Builder.build(RootTask.java:118)
	at io.crate.execution.jobs.TasksService.createTask(TasksService.java:141)
	at io.crate.execution.engine.JobLauncher.setupTasks(JobLauncher.java:209)
	at io.crate.execution.engine.JobLauncher.execute(JobLauncher.java:154)
	at io.crate.planner.operators.LogicalPlanner.executeNodeOpTree(LogicalPlanner.java:438)
	at io.crate.planner.operators.LogicalPlanner.doExecute(LogicalPlanner.java:410)
	at io.crate.planner.operators.LogicalPlanner.execute(LogicalPlanner.java:389)
	at io.crate.planner.operators.LogicalPlan.executeOrFail(LogicalPlan.java:174)
	at io.crate.planner.Plan.execute(Plan.java:74)
	at io.crate.action.sql.Session.singleExec(Session.java:597)
	at io.crate.action.sql.Session.exec(Session.java:465)
	at io.crate.action.sql.Session.sync(Session.java:444)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:272)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:207)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:120)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:134)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:83)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by robd003** [comment]
It works just fine if I use a single aggregate function, but when trying to nest them it fails.

**Comment by robd003** [comment]
Looks like I just needed to use a sub-query:

select narration, 
COALESCE(max(embedded_plays), 0) as embedded_plays, 
COALESCE(max(library_plays), 0) as library_plays, 
COALESCE(max(podcast_plays), 0) as podcast_plays, 
COALESCE(max(listen_time), 0) as listen_time
from (select narration, 
      COALESCE(sum(case when library_type is null then 1 else 0 end), 0)::integer as embedded_plays,
      COALESCE(sum(case when library_type is not null then 1 else 0 end), 0)::integer as library_plays,
      NULL::integer as podcast_plays,
      NULL::real as listen_time
      from voxsnap.events_2019 
      where event_type = 'play'  
      and customer = 'handerpants'
      and event_time >= '2020-01-01' and event_time <= '2020-01-31'
      group by narration
    union all  
      select narration,
      NULL::integer as embedded_plays,
      NULL::integer as library_plays,
      COALESCE(count(*), 0)::integer as podcast_plays,
      NULL::real as listen_time
      from voxsnap.events_redirector_2019 
      where platform = 'podcast' 
      and customer = 'handerpants'
      and event_time >= '2020-01-01' and event_time <= '2020-01-31'
      group by narration
    union all
      select narration,
      NULL::integer as embedded_plays,
      NULL::integer as library_plays,
      NULL::integer as podcast_plays,
      sum(audio)/60 as listen_time
      from (select narration, max(audio_time) as audio, session_id from voxsnap.events_timeupdate_2019 where (customer = 'handerpants' and event_time >= '2020-01-01' and event_time <= '2020-01-31') GROUP BY narration, session_id) as audio_time group by narration) as big_query
group by narration;
