### ISSUE TITLE
"trunc" scalar function not implemented in 4.1.4 ?

### ISSUE THREAD

**Issue by MikeMaxFR** [crate/crate#9871]
**CrateDB version**: 4.1.4

**Environment description**: Linux

**Problem description**:

the trunc method is not implemented even though it is in the documentation (is the v:latest means nightly 4.2 or latest stable 4.1.4 ?

> SQLActionException[UnsupportedFeatureException: unknown function: trunc(double precision, bigint)]

<details>
<summary>Stack trace:</summary>

```
SQLActionException: 400 Bad Request 4004 UnsupportedFeatureException: unknown function: trunc(double precision, bigint)
	at io.crate.metadata.Functions.raiseUnknownFunction(Functions.java:250)
	at io.crate.metadata.Functions.get(Functions.java:121)
	at io.crate.analyze.expressions.ExpressionAnalyzer.allocateBuiltinOrUdfFunction(ExpressionAnalyzer.java:1063)
	at io.crate.analyze.expressions.ExpressionAnalyzer.allocateBuiltinOrUdfFunction(ExpressionAnalyzer.java:1021)
	at io.crate.analyze.expressions.ExpressionAnalyzer.convertFunctionCall(ExpressionAnalyzer.java:281)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitFunctionCall(ExpressionAnalyzer.java:497)
	at io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitFunctionCall(ExpressionAnalyzer.java:449)
	at io.crate.sql.tree.FunctionCall.accept(FunctionCall.java:74)
	at io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:221)
	at io.crate.analyze.relations.select.SelectAnalysis.toSymbol(SelectAnalysis.java:69)
	at io.crate.analyze.relations.select.SelectAnalyzer$InnerVisitor.visitSingleColumn(SelectAnalyzer.java:61)
	at io.crate.analyze.relations.select.SelectAnalyzer$InnerVisitor.visitSingleColumn(SelectAnalyzer.java:57)
	at io.crate.sql.tree.SingleColumn.accept(SingleColumn.java:80)
	at io.crate.sql.tree.DefaultTraversalVisitor.visitSelect(DefaultTraversalVisitor.java:79)
	at io.crate.sql.tree.Select.accept(Select.java:49)
	at io.crate.analyze.relations.select.SelectAnalyzer.analyzeSelect(SelectAnalyzer.java:52)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:327)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:117)
	at io.crate.sql.tree.QuerySpecification.accept(QuerySpecification.java:109)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:154)
	at io.crate.analyze.relations.RelationAnalyzer.visitQuery(RelationAnalyzer.java:117)
	at io.crate.sql.tree.Query.accept(Query.java:72)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:137)
	at io.crate.analyze.relations.RelationAnalyzer.analyze(RelationAnalyzer.java:149)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:248)
	at io.crate.analyze.Analyzer$AnalyzerDispatcher.visitQuery(Analyzer.java:244)
	at io.crate.sql.tree.Query.accept(Query.java:72)
	at io.crate.analyze.Analyzer.analyzedStatement(Analyzer.java:239)
	at io.crate.analyze.Analyzer.boundAnalyze(Analyzer.java:227)
	at io.crate.action.sql.Session.bind(Session.java:290)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:249)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:207)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:120)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:84)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:134)
	at io.crate.protocols.http.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:83)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

**Steps to reproduce**:

simply launch this request : 

**SELECT trunc(5.5445, 2) as test FROM sys.cluster;**

**Comment by mfussenegger** [comment]
> s the v:latest means nightly 4.2 or latest stable 4.1.4

`latest` in the documentation is for the unreleased version (4.2). `trunc` doesn't exist in 4.1.

With the latest-nightly it works:

```
cr8 run-crate latest-nightly -- @crash --hosts {node.http_url} -c <<EOF "
SELECT trunc(5.545, 2)"
EOF

# @crash
========

CONNECT OK
+------+
| 5.54 |
+------+
| 5.54 |
+------+
SELECT 1 row in set (0.015 sec)
```


@mechanomi I think we should follow up on changing the default of the documentation to point to the latest stable release. This pops up time and again that people want to use unreleased functionality.

**Comment by MikeMaxFR** [comment]
Ok, it makes sense :)


Thanks !
